### ISSUE TITLE
[Bug] asan be core doris::NotInListPredicate<doris::StringValue>::evaluate

### ISSUE THREAD

**Issue by SWJTU-ZhangLei** [apache/doris#10063]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

root@regtest-15-bj:/mnt/hdd01/DORIS_MASTER_ASAN/be/log# /mnt/hdd01/DORIS_MASTER_ASAN/be/lib/palo_be --version
trunk DEBUG (build git://regtest-15-bj/mnt/hdd01/repo_center/doris_master/be/../@73a30935399108a6fc2abf8b5017bd1ff2872dc6)
Built on Fri, 10 Jun 2022 07:22:07 CST by root@regtest-15-bj

### What's Wrong?

(gdb) bt
#0  0x00007f343452ffbb in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f3434515864 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x0000557b91b3fbf2 in google::DumpStackTraceAndExit () at src/utilities.cc:160
#3  0x0000557b9840511d in google::LogMessage::Fail () at src/logging.cc:1650
#4  0x0000557b98407659 in google::LogMessage::SendToLog (this=0x7f340c638720) at src/logging.cc:1607
#5  0x0000557b98404c86 in google::LogMessage::Flush (this=0x7f340c638720) at src/logging.cc:1476
#6  0x0000557b98407cc9 in google::LogMessageFatal::~LogMessageFatal (this=<optimized out>, __in_chrg=<optimized out>) at src/logging.cc:2226
#7  0x0000557b929b1872 in doris::NotInListPredicate<doris::StringValue>::evaluate (this=0x606000699980, column=..., sel=0x7f340c638ac0, size=0x7f340c638be0)
    at /mnt/hdd01/repo_center/doris_master/be/src/olap/in_list_predicate.cpp:191
#8  0x0000557b94d90ad1 in doris::segment_v2::SegmentIterator::_evaluate_short_circuit_predicate (this=0x616000394880, vec_sel_rowid_idx=0x7f340c638ac0, selected_size_ptr=0x7f340c638be0)
    at /mnt/hdd01/repo_center/doris_master/be/src/olap/rowset/segment_v2/segment_iterator.cpp:917
#9  0x0000557b94d9288a in doris::segment_v2::SegmentIterator::next_batch (this=0x616000394880, block=0x6070042b6dc0)
    at /mnt/hdd01/repo_center/doris_master/be/src/olap/rowset/segment_v2/segment_iterator.cpp:1015
#10 0x0000557b92c10af7 in doris::BetaRowsetReader::next_block (this=0x6130007ac480, block=0x6070042b6dc0) at /mnt/hdd01/repo_center/doris_master/be/src/olap/rowset/beta_rowset_reader.cpp:189
#11 0x0000557b940e8767 in doris::vectorized::VCollectIterator::Level0Iterator::next (this=0x6070040151c0, block=0x6070042b6dc0)
    at /mnt/hdd01/repo_center/doris_master/be/src/vec/olap/vcollect_iterator.cpp:233
#12 0x0000557b940eb80a in doris::vectorized::VCollectIterator::Level1Iterator::_normal_next (this=0x60b0000dbc20, block=0x6070042b6dc0)
    at /mnt/hdd01/repo_center/doris_master/be/src/vec/olap/vcollect_iterator.cpp:424
#13 0x0000557b940ebab6 in doris::vectorized::VCollectIterator::Level1Iterator::_normal_next (this=0x60b0000dbc20, block=0x6070042b6dc0)
    at /mnt/hdd01/repo_center/doris_master/be/src/vec/olap/vcollect_iterator.cpp:433
#14 0x0000557b940e9349 in doris::vectorized::VCollectIterator::Level1Iterator::next (this=0x60b0000dbc20, block=0x6070042b6dc0)
    at /mnt/hdd01/repo_center/doris_master/be/src/vec/olap/vcollect_iterator.cpp:294
#15 0x0000557b940e70ff in doris::vectorized::VCollectIterator::next (this=0x61b0002a9e98, block=0x6070042b6dc0) at /mnt/hdd01/repo_center/doris_master/be/src/vec/olap/vcollect_iterator.cpp:173
#16 0x0000557b940f931c in doris::vectorized::BlockReader::_direct_next_block (this=0x61b0002a9a80, block=0x6070042b6dc0, mem_pool=0x0, agg_pool=0x0, eof=0x7f340c640840)
    at /mnt/hdd01/repo_center/doris_master/be/src/vec/olap/block_reader.cpp:162
#17 0x0000557b92687ccb in doris::vectorized::BlockReader::next_block_with_aggregation (this=0x61b0002a9a80, block=0x6070042b6dc0, mem_pool=0x0, agg_pool=0x0, eof=0x7f340c640840)
    at /mnt/hdd01/repo_center/doris_master/be/src/vec/olap/block_reader.h:49
#18 0x0000557b951618f5 in doris::vectorized::VOlapScanner::get_block (this=0x617000347980, state=0x620000397080, block=0x6070042b6dc0, eof=0x7f340c640840)
    at /mnt/hdd01/repo_center/doris_master/be/src/vec/exec/volap_scanner.cpp:56
#19 0x0000557b9512ec93 in doris::vectorized::VOlapScanNode::scanner_thread (this=0x621000e11500, scanner=0x617000347980)
    at /mnt/hdd01/repo_center/doris_master/be/src/vec/exec/volap_scan_node.cpp:219
#20 0x0000557b9514cbad in std::__invoke_impl<void, void (doris::vectorized::VOlapScanNode::*&)(doris::vectorized::VOlapScanner*), doris::vectorized::VOlapScanNode*&, doris::vectorized::VOlapScanner*&> (__f=
    @0x6030019ea150: (void (doris::vectorized::VOlapScanNode::*)(doris::vectorized::VOlapScanNode * const, doris::vectorized::VOlapScanner *)) 0x557b9512d392 <doris::vectorized::VOlapScanNode::scanner_thread(doris::vectorized::VOlapScanner*)>, __t=@0x6030019ea168: 0x621000e11500) at /var/local/ldb_toolchain/include/c++/11/bits/invoke.h:74
#21 0x0000557b9514c765 in std::__invoke<void (doris::vectorized::VOlapScanNode::*&)(doris::vectorized::VOlapScanner*), doris::vectorized::VOlapScanNode*&, doris::vectorized::VOlapScanner*&> (
    __fn=
    @0x6030019ea150: (void (doris::vectorized::VOlapScanNode::*)(doris::vectorized::VOlapScanNode * const, doris::vectorized::VOlapScanner *)) 0x557b9512d392 <doris::vectorized::VOlapScanNode::scanner_thread(doris::vectorized::VOlapScanner*)>) at /var/local/ldb_toolchain/include/c++/11/bits/invoke.h:96
#22 0x0000557b9514c097 in std::_Bind<void (doris::vectorized::VOlapScanNode::*(doris::vectorized::VOlapScanNode*, doris::vectorized::VOlapScanner*))(doris::vectorized::VOlapScanner*)>::__call<void, , 0ul, 1ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul>) (this=0x6030019ea150, __args=...) at /var/local/ldb_toolchain/include/c++/11/functional:420
#23 0x0000557b9514ba5d in std::_Bind<void (doris::vectorized::VOlapScanNode::*(doris::vectorized::VOlapScanNode*, doris::vectorized::VOlapScanner*))(doris::vectorized::VOlapScanner*)>::operator()<, void>() (this=0x6030019ea150) at /var/local/ldb_toolchain/include/c++/11/functional:503
#24 0x0000557b9514ad36 in std::__invoke_impl<void, std::_Bind<void (doris::vectorized::VOlapScanNode::*(doris::vectorized::VOlapScanNode*, doris::vectorized::VOlapScanner*))(doris::vectorized::VOlapScanner*)>&>(std::__invoke_other, std::_Bind<void (doris::vectorized::VOlapScanNode::*(doris::vectorized::VOlapScanNode*, doris::vectorized::VOlapScanner*))(doris::vectorized::VOlapScanner*)>&) (__f=...) at /var/local/ldb_toolchain/include/c++/11/bits/invoke.h:61
#25 0x0000557b95149c14 in std::__invoke_r<void, std::_Bind<void (doris::vectorized::VOlapScanNode::*(doris::vectorized::VOlapScanNode*, doris::vectorized::VOlapScanner*))(doris::vectorized::VOlapScanner*)>&>(std::_Bind<void (doris::vectorized::VOlapScanNode::*(doris::vectorized::VOlapScanNode*, doris::vectorized::VOlapScanner*))(doris::vectorized::VOlapScanner*)>&) (__fn=...)
    at /var/local/ldb_toolchain/include/c++/11/bits/invoke.h:111
#26 0x0000557b95148b4e in std::_Function_handler<void (), std::_Bind<void (doris::vectorized::VOlapScanNode::*(doris::vectorized::VOlapScanNode*, doris::vectorized::VOlapScanner*))(doris::vectorized::VOlapScanner*)> >::_M_invoke(std::_Any_data const&) (__functor=...) at /var/local/ldb_toolchain/include/c++/11/bits/std_function.h:291
#27 0x0000557b92dba6aa in std::function<void ()>::operator()() const (this=0x7f340c644cc8) at /var/local/ldb_toolchain/include/c++/11/bits/std_function.h:560
#28 0x0000557b92db7280 in doris::PriorityWorkStealingThreadPool::work_thread (this=0x614000014440, thread_id=38)
    at /mnt/hdd01/repo_center/doris_master/be/src/util/priority_work_stealing_thread_pool.hpp:133
#29 0x0000557b92ddaa12 in std::__invoke_impl<void, void (doris::PriorityWorkStealingThreadPool::* const&)(int), doris::PriorityWorkStealingThreadPool*&, int&> (__f=
    @0x604000906718: (void (doris::PriorityWorkStealingThreadPool::*)(doris::PriorityWorkStealingThreadPool * const, int)) 0x557b92db6f14 <doris::PriorityWorkStealingThreadPool::work_thread(int)>, __t=@0x604000906730: 0x614000014440) at /var/local/ldb_toolchain/include/c++/11/bits/invoke.h:74
#30 0x0000557b92dda7eb in std::__invoke<void (doris::PriorityWorkStealingThreadPool::* const&)(int), doris::PriorityWorkStealingThreadPool*&, int&> (__fn=
--Type <RET> for more, q to quit, c to continue without paging--
    @0x604000906718: (void (doris::PriorityWorkStealingThreadPool::*)(doris::PriorityWorkStealingThreadPool * const, int)) 0x557b92db6f14 <doris::PriorityWorkStealingThreadPool::work_thread(int)>) at /var/local/ldb_toolchain/include/c++/11/bits/invoke.h:96
#31 0x0000557b92dda71d in std::_Mem_fn_base<void (doris::PriorityWorkStealingThreadPool::*)(int), true>::operator()<doris::PriorityWorkStealingThreadPool*&, int&> (this=0x604000906718)
    at /var/local/ldb_toolchain/include/c++/11/functional:131
#32 0x0000557b92dda606 in std::__invoke_impl<void, std::_Mem_fn<void (doris::PriorityWorkStealingThreadPool::*)(int)>&, doris::PriorityWorkStealingThreadPool*&, int&> (__f=...)
    at /var/local/ldb_toolchain/include/c++/11/bits/invoke.h:61
#33 0x0000557b92dda49f in std::__invoke_r<void, std::_Mem_fn<void (doris::PriorityWorkStealingThreadPool::*)(int)>&, doris::PriorityWorkStealingThreadPool*&, int&> (__fn=...)
    at /var/local/ldb_toolchain/include/c++/11/bits/invoke.h:111
#34 0x0000557b92dda1af in std::_Bind_result<void, std::_Mem_fn<void (doris::PriorityWorkStealingThreadPool::*)(int)> (doris::PriorityWorkStealingThreadPool*, int)>::__call<void, , 0ul, 1ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul>) (this=0x604000906718, __args=...) at /var/local/ldb_toolchain/include/c++/11/functional:570
#35 0x0000557b92dd9f11 in std::_Bind_result<void, std::_Mem_fn<void (doris::PriorityWorkStealingThreadPool::*)(int)> (doris::PriorityWorkStealingThreadPool*, int)>::operator()<>() (
    this=0x604000906718) at /var/local/ldb_toolchain/include/c++/11/functional:629
#36 0x0000557b92dd9df5 in std::__invoke_impl<void, std::_Bind_result<void, std::_Mem_fn<void (doris::PriorityWorkStealingThreadPool::*)(int)> (doris::PriorityWorkStealingThreadPool*, int)>>(std::__invoke_other, std::_Bind_result<void, std::_Mem_fn<void (doris::PriorityWorkStealingThreadPool::*)(int)> (doris::PriorityWorkStealingThreadPool*, int)>&&) (__f=...)
    at /var/local/ldb_toolchain/include/c++/11/bits/invoke.h:61
#37 0x0000557b92dd9d49 in std::__invoke<std::_Bind_result<void, std::_Mem_fn<void (doris::PriorityWorkStealingThreadPool::*)(int)> (doris::PriorityWorkStealingThreadPool*, int)>>(std::_Bind_result<void, std::_Mem_fn<void (doris::PriorityWorkStealingThreadPool::*)(int)> (doris::PriorityWorkStealingThreadPool*, int)>&&) (__fn=...)
    at /var/local/ldb_toolchain/include/c++/11/bits/invoke.h:96
#38 0x0000557b92dd8b00 in std::thread::_Invoker<std::tuple<std::_Bind_result<void, std::_Mem_fn<void (doris::PriorityWorkStealingThreadPool::*)(int)> (doris::PriorityWorkStealingThreadPool*, int)> > >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x604000906718) at /var/local/ldb_toolchain/include/c++/11/bits/std_thread.h:253
#39 0x0000557b92dd5c3e in std::thread::_Invoker<std::tuple<std::_Bind_result<void, std::_Mem_fn<void (doris::PriorityWorkStealingThreadPool::*)(int)> (doris::PriorityWorkStealingThreadPool*, int)> > >::operator()() (this=0x604000906718) at /var/local/ldb_toolchain/include/c++/11/bits/std_thread.h:260
#40 0x0000557b92dd52fc in std::thread::_State_impl<std::thread::_Invoker<std::tuple<std::_Bind_result<void, std::_Mem_fn<void (doris::PriorityWorkStealingThreadPool::*)(int)> (doris::PriorityWorkStealingThreadPool*, int)> > > >::_M_run() (this=0x604000906710) at /var/local/ldb_toolchain/include/c++/11/bits/std_thread.h:211
#41 0x0000557b9a55b180 in execute_native_thread_routine ()
#42 0x00007f34344d6450 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#43 0x00007f3434606d53 in clone () from /lib/x86_64-linux-gnu/libc.so.6

### What You Expected?

work well

### How to Reproduce?

1、run regression test case
select city from test_dup_tab_char_nullable where city not in ('a1','e1')

2、be.conf
mem_limit = 20%
disable_minidump = true
path_gc_check_interval_second = 1
max_garbage_sweep_interval = 180
rowbatch_align_tuple_offset = true

buffer_pool_limit = 2%
chunk_reserved_bytes_limit = 134217728
enable_storage_vectorization = true
enable_low_cardinality_optimize = true
disable_storage_page_cache = true

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by BiteTheDDDDt** [comment]
Is it same problem like https://github.com/apache/incubator-doris/pull/10047 ?

**Comment by SWJTU-ZhangLei** [comment]
> Is it same problem like #10047 ?

i am not sure, i will try to run regression tests again with this patch to confirm.
