### ISSUE TITLE
[Bug] Error occurs when showing query profile

### ISSUE THREAD

**Issue by Gabriel39** [apache/doris#10095]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

trunk

### What's Wrong?

select * from customer limit 100;

show query profile "/56d7cc7abc254ca7-84d884fe4f4d401b";

ERROR 1105 (HY000): errCode = 2, detailMessage = failed to get fragment profile tree. err: errCode = 2, detailMessage = Invalid instance profile, without sender or exec node: Instance 56d7cc7abc254ca7-84d884fe4f4d401d (host=TNetworkAddress(hostname:172.19.0.11, port:9065)):

### What You Expected?

works well

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by qimumu9406** [comment]
Check that the instance exists, if so, can you describe the operation process?

**Comment by zxealous** [comment]
Did you set enable_profile is true?    if don't set it,  the default value of enable_profile is false, `BE` won't report profile to coordinator.

**Comment by freemandealer** [comment]
same issus here.

I was tring the doris query profile facility.

after enable profile using `SET is_report_success=true;`

then execute select statements

`show query profile "/"\G` gives me:
```
*************************** 1. row ***************************
   QueryId: e4a384b03c9c4aaa-ab5fcd6a7299f6db
      User: root
 DefaultDb: default_cluster:testdb
       SQL: select id,actor_login from github_1 limit 10
 QueryType: Query
 StartTime: 2022-08-08 12:28:22
   EndTime: 2022-08-08 12:28:23
 TotalTime: 46ms
QueryState: EOF
```

so I send `show query profile "/e4a384b03c9c4aaa-ab5fcd6a7299f6db"\G`

return error:
```
ERROR 1105 (HY000): errCode = 2, detailMessage = failed to get fragment profile tree. err: errCode = 2, detailMessage = Invalid instance profile, without sender or exec node: Instance e4a384b03c9c4aaa-ab5fcd6a7299f6dc (host=TNetworkAddress(hostname:172.16.70.241, port:9061)):
```

All 4 BE processes are running correctly, without WARNING log.

**Comment by luozenglin** [comment]
BE instance will report the final profile to FE after returning the query data. At this time, Fe may have`unregisterQuery` in `QeProcessorImpl`, resulting in the loss of the instance profile. Fe failed to parse instance profile, resulting in an error in `show query profile`.

**Comment by liugs0213** [comment]
这个bug,我在1.2.2.rc也遇到了
![image](https://user-images.githubusercontent.com/55676558/225631557-cd702be8-6f58-48c2-8d20-61bd0c4f0592.png)

**Comment by yuxuan-luo** [comment]
1.2.3-rc02 也遇到了

**Comment by liwei9902** [comment]
doris-2.0.0-alpha1 也遇到了

**Comment by tenywen** [comment]
doris-2.1.0 也遇到了
 show query profile "/f0edefb4bd0441c5-ad433d88742622a1"\G;
ERROR 1105 (HY000): errCode = 2, detailMessage = failed to get fragment profile tree. err: errCode = 2, detailMessage = Invalid instance profile name: Pipeline :0  (host=TNetworkAddress(hostname:172.16.1.193, port:9060))
