### ISSUE TITLE
[Enhancement] Show create table Comment use single quotes 

### ISSUE THREAD

**Issue by stalary** [apache/doris#10203]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Current show create table use of double quotes, which is not standard mysql syntax, causes some BI platforms to fail to resolve comments, such as Superset.

### Solution

  `name` varchar(100) NULL COMMENT "姓名"  ->   `name` varchar(100) NULL COMMENT '姓名'

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by qimumu9406** [comment]
If it is a 'name varchar(100) NULL COMMENT " 'name' " ' statement, what should I do?

**Comment by stalary** [comment]
Comment uses single quotation marks. The internal single quotation marks need to be escaped.

**Comment by qimumu9406** [comment]
If this issuer is not in a hurry, I want to try it.

**Comment by stalary** [comment]
> If this issuer is not in a hurry, I want to try it.

You can try it, can be compatible with mysql and can get comment normally in superset.

**Comment by qimumu9406** [comment]
thk.

**Comment by stalary** [comment]
> thk.

How is your progress?

**Comment by qimumu9406** [comment]
> 

Sorry, I haven't started yet, if this issuer is urgent, it can be arranged to someone else.

**Comment by stalary** [comment]
> > 
> 
> Sorry, I haven't started yet, if this issuer is urgent, it can be arranged to someone else.

Ok, I will support it.
