### ISSUE TITLE
[UserCase] User list collection

### ISSUE THREAD

**Issue by yangzhg** [apache/doris#10229]
Now more and more users want to have their names appear in the doris user list, if there are people who actually use doris and generate relatively large profits in their own business, and are willing to display the company's logo and name and user cases in On the doris user list, you can leave your company name both in Chinese and English and logo picture in the comments below. I will update the user list regularly.

现在有越来越多的用户希望将他们的名字出现在doris 用户列表里， 如果有真正使用了doris 并且在自己的业务上产生了比较大的收益，并且有意愿将公司的logo、名字以及使用场景展示在doris 用户列表上，可以再在下面评论中 留下你们公司中文和英文名称、logo图片、使用场景， 我会定期更新到用户列表中。

中文名：
英文名：
Logo：
使用场景：

**Comment by whutpencil** [comment]
![公司LOGO-黑字](https://user-images.githubusercontent.com/24907215/174302370-e5af925b-9ca5-4550-be73-ebb1782db9cb.png)
网易游戏

**Comment by hf200012** [comment]
> ![公司LOGO-黑字](https://user-images.githubusercontent.com/24907215/174302370-e5af925b-9ca5-4550-be73-ebb1782db9cb.png) 网易游戏

Very Nice

**Comment by Level1Accelerator** [comment]
![042887ba57b1f949a28bb5bcd162233](https://user-images.githubusercontent.com/14903509/174304189-7e77ac5c-b7a4-4937-a81f-cf552f08c93d.png)
武汉物易云通网络科技有限公司

**Comment by belialxing** [comment]
![38A3515C-88DC-44ED-8263-68CDCAE83577](https://user-images.githubusercontent.com/52272263/174304314-1cf175b5-226c-491a-a164-5e40622e312f.png)
同程数科

**Comment by admh** [comment]
![Footprint Analytics](https://user-images.githubusercontent.com/19163424/174307906-875f38e1-34d5-4797-a808-34ab4f625ae8.png)

**Comment by chovy-3012** [comment]
![Uploading aispeech-logo.png…]()

思必驰

**Comment by hou-rong** [comment]
![图片](https://pic4.zhimg.com/80/v2-e4e52763945c8f1078f6c9f2143ba981_720w.png)
知乎

**Comment by yangzhg** [comment]
the above are added at #10256

**Comment by gadbees** [comment]
![Lifewit-logo-RGB-orange](https://user-images.githubusercontent.com/9403879/174686992-17eceaa4-f1c4-4e3e-b98f-86f0dc3c9afc.png)
公司中文全称:    福建东西乐活科技有限公司
英文名称简称:    lifewit

**Comment by TonyChai24** [comment]
![keep-logo](https://user-images.githubusercontent.com/9876066/174993058-faf42a05-c089-44c8-a0f4-c676762fa12b.png)
Keep

**Comment by TonyChai24** [comment]
![keep-logo](https://user-images.githubusercontent.com/9876066/174993707-c9f9bea1-9b8b-4f68-8cf7-44e77d23065e.jpg)
Keep

**Comment by realdengziqi** [comment]
![尚硅谷logo](https://user-images.githubusercontent.com/42276568/175284500-17355c0e-09a9-48e4-800c-b73dae2910ee.jpg)
公司中文全称: 尚硅谷

**Comment by adonis0147** [comment]
@yangzhg I think this issue can be pinned to the top.

**Comment by Dam1029** [comment]
<img width="906" alt="截屏2022-06-26 上午10 53 37" src="https://user-images.githubusercontent.com/26566636/175797439-b3151f27-6334-4755-b0e8-6149fc562594.png">

**Comment by emerkfu** [comment]
![](https://user-images.githubusercontent.com/59500675/180141347-bad4eff9-16a8-4b29-8ae8-8094f9109282.png)
橙联

**Comment by hf200012** [comment]
@emerkfu You add my WeChat and pull you into the group，WeChat：35926237

**Comment by htyoung** [comment]
![logo](https://user-images.githubusercontent.com/9734567/187390259-09a93d1c-aba1-4510-9a4f-202e76fe21d1.png)
斗鱼
DOUYU.COM

**Comment by Xiaojun-Pan** [comment]
![logo](https://user-images.githubusercontent.com/40374927/195240870-e9d611be-30cd-40a5-87bc-a23f75760f21.png)
无锡宝通科技
http://www.boton-tech.com/

**Comment by WildWolfBang** [comment]
360数科，如果尺寸和背景颜色不合适，可在链接中下载https://www.360shuke.com/logo.html
![360数科logo竖版原色](https://user-images.githubusercontent.com/17874410/197146184-4a975b83-2c88-4d3d-b92c-89fbb5365312.jpg)
![360数科logo的横版](https://user-images.githubusercontent.com/17874410/197146346-adf1f705-7d22-4ee2-b082-348b65940e0e.jpg)

**Comment by cxgamefalcon** [comment]
![物泊科技logo 2](https://user-images.githubusercontent.com/53923597/204975917-46dc01f7-eab8-4235-88b1-9f49b9d8a9ff.svg)
物泊科技

**Comment by ccpypy** [comment]
![image](https://user-images.githubusercontent.com/50856789/206687064-54b22098-5792-4422-b7ae-a60d9466375c.png)
十方融海

**Comment by sinostone** [comment]
![wasulogo](https://github.com/apache/doris/assets/92700245/d5f2eecd-3d21-4683-b99b-140a6f76a71b)
华数

**Comment by shigongxing** [comment]
雨润集团

![1689044360690](https://github.com/apache/doris/assets/19562639/ad85f5fd-8f7d-4853-aef4-644f74349a0a)

**Comment by Viktor-Mr** [comment]
![image](https://github.com/apache/doris/assets/68584434/9b6dc10e-e445-476b-ba67-b3d06d21c75c)
广州趣米网络
inrice

**Comment by wxiao1002** [comment]
![logo](https://github.com/apache/doris/assets/104369225/5f215dc7-3f24-451f-afff-8682a50c840f)
中文名：贵州蛟龙云科技
英文名：jlc

**Comment by fanjia1024** [comment]
联想
![image](https://github.com/apache/doris/assets/33594643/92f38a95-ed5e-4873-8398-9a10ea3629b7)

**Comment by luzhijing** [comment]
This issue was moved to a discussion, welcome to leave your company's info here:
 [https://github.com/apache/doris/discussions/27683](https://github.com/apache/doris/discussions/27683)
