### ISSUE TITLE
[Enhancement] support "if [not] exists" from create and drop sql_block_rule

### ISSUE THREAD

**Issue by morningman** [apache/doris#10307]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

```
create sql_block_rule if not exists xxx;
drop sql_block_rule if exists xxx
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
please assign to me.
