### ISSUE TITLE
[Bug] Failed to obtain fragment data

### ISSUE THREAD

**Issue by aifirstlove163** [apache/doris#10383]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris 1.0

### What's Wrong?

Doris on es,elasticsearch 's version is 8.2. fe get elasticsearch meta data not found.
Exception happens when fetch index meta data from remote es cluster.table id: 12036, err: index not found 

### What You Expected?

Expect to support this version,elastic search is 8.2

### How to Reproduce?

1.create index
PUT test
{
   "settings": {
      "index": {
         "number_of_shards": "3",
         "number_of_replicas": "0"
      }
   },
   "mappings": {
         "properties": {
            "k1": {
               "type": "long"
            },
            "k2": {
               "type": "date"
            },
            "k3": {
               "type": "keyword"
            },
            "k4": {
               "type": "text",
               "analyzer": "standard"
            },
            "k5": {
               "type": "float"
            }
         }
   }
}
2.insert data
POST /_bulk
{"index":{"_index":"test"}}
{ "k1" : 100, "k2": "2020-01-01", "k3": "Trying out Elasticsearch", "k4": "Trying out Elasticsearch", "k5": 10.0}
{"index":{"_index":"test"}}
{ "k1" : 100, "k2": "2020-01-01", "k3": "Trying out Doris", "k4": "Trying out Doris", "k5": 10.0}
{"index":{"_index":"test"}}
{ "k1" : 100, "k2": "2020-01-01", "k3": "Doris On ES", "k4": "Doris On ES", "k5": 10.0}
{"index":{"_index":"test"}}
{ "k1" : 100, "k2": "2020-01-01", "k3": "Doris", "k4": "Doris", "k5": 10.0}
{"index":{"_index":"test"}}
{ "k1" : 100, "k2": "2020-01-01", "k3": "ES", "k4": "ES", "k5": 10.0}
3. create table 
CREATE EXTERNAL TABLE `test` (
  `k1` bigint(20) COMMENT "",
  `k2` datetime COMMENT "",
  `k3` varchar(20) COMMENT "",
  `k4` varchar(100) COMMENT "",
  `k5` float COMMENT ""
) ENGINE=ELASTICSEARCH
PARTITION BY RANGE(`k1`)
PROPERTIES (
"hosts" = "http://10.0.0.31:9200",
"index" = "test"
);

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
https://github.com/apache/doris/pull/10391
I've fixed it.

**Comment by yqzdy1207** [comment]
目前我也遇到了这个问题，Doris 1.0  ES 8.2.3

ERROR 1105 (HY000): errCode = 2, detailMessage = fetch es table [test] metadata failure: index[test] not found
