### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by jieshier** [apache/doris#10400]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.0.5-release-binary

### What's Wrong?

1、执行查询有时会报错如下。
ERROR 1105 (HY000): errCode = 2, detailMessage = Could not allocate aggregate expression input value
ExecNode:Exprs:AGGREGATION_NODE (id=3):5cf2fd57a5a44006-b719b10f473a90d9 could not allocate 16.00 B without exceeding limit.
Error occurred on backend 10.0.12.250 by fragment 5cf2fd57a5a44006-b719b

### What You Expected?

查询不报错！

### How to Reproduce?

--我在github问题中发现一个跟我一样的情况，但是没有相关解答：
https://github.com/apache/doris/issues/6680#issue-997892295

### Anything Else?

无

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xinyiZzz** [comment]
错误原因是超出了query内存限制，doris中一个query默认执行内存限制为2G，
修改session variable `set exec_mem_limit = xxxx;` 提高当前session的query内存限制，
也可以 `set global exec_mem_limit = xxxx;` 修改query默认内存限制，重启mysql client生效。
