### ISSUE TITLE
[Bug] be core，COW<doris::vectorized::IColumn>

### ISSUE THREAD

**Issue by pingchunzhang** [apache/doris#10576]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

9d4a9b95a4d188dbf66a7ecd60de8f3f3960b664

### What's Wrong?

==========================gdb=====================
`(gdb) bt
#0  0x00005591ac39f39e in COW<doris::vectorized::IColumn>::intrusive_ptr<doris::vectorized::IColumn const>::operator*() const & (this=0x38)
    at /home/zcp/repo_center/selectdb_selectdb-1.0/selectdb/be/src/vec/common/cow.h:206
Backtrace stopped: Cannot access memory at address 0x7f57f3b2d628
(gdb) `

=======================be.out======================
`*** Aborted at 1656684765 (unix time) try "date -d @1656684765" if you are using GNU date ***
*** SIGSEGV address not mapped to object (@0x38) received by PID 2282584 (TID 0x7f57f3b3c700) from PID 56; stack trace: ***
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /home/zcp/repo_center/selectdb_selectdb-1.0/selectdb/be/src/common/signal_handler.h:407
 1# 0x00007F589B4AF0C0 in /lib/x86_64-linux-gnu/libc.so.6
 2# COW<doris::vectorized::IColumn>::intrusive_ptr<doris::vectorized::IColumn const>::operator*() const & at /home/zcp/repo_center/selectdb_selectdb-1.0/selectdb/be/src/vec/common/cow.h:206
 3# void doris::vectorized::ProcessHashTableProbe<doris::vectorized::PrimaryTypeHashTableContext<unsigned int>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)8>, false>::build_side_ou
tput_column<true>(std::vector<COW<doris::vectorized::IColumn>::mutable_ptr<doris::vectorized::IColumn>, std::allocator<COW<doris::vectorized::IColumn>::mutable_ptr<doris::vectorized::IColumn> > >&, int, i
nt, std::vector<bool, std::allocator<bool> > const&, int) at /home/zcp/repo_center/selectdb_selectdb-1.0/selectdb/be/src/vec/exec/join/vhash_join_node.cpp:217
 4# doris::vectorized::ProcessHashTableProbe<doris::vectorized::PrimaryTypeHashTableContext<unsigned int>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)8>, false>::do_process_with_ot
her_join_conjunts(doris::vectorized::PrimaryTypeHashTableContext<unsigned int>&, doris::vectorized::PODArray<unsigned char, 4096ul, Allocator<false, false>, 15ul, 16ul> const*, doris::vectorized::MutableB
lock&, doris::vectorized::Block*) at /home/zcp/repo_center/selectdb_selectdb-1.0/selectdb/be/src/vec/exec/join/vhash_join_node.cpp:464
 5# auto doris::vectorized::HashJoinNode::get_next(doris::RuntimeState*, doris::vectorized::Block*, bool*)::{lambda(auto:1&&, auto:2&&, auto:3, auto:4)#2}::operator()<doris::vectorized::PrimaryTypeHashTab
leContext<unsigned int>&, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)8>&, std::integral_constant<bool, true>, std::integral_constant<bool, false> >(doris::vectorized::PrimaryTypeHa
shTableContext<unsigned int>&, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)8>&, std::integral_constant<bool, true>, std::integral_constant<bool, false>) const at /home/zcp/repo_cent
er/selectdb_selectdb-1.0/selectdb/be/src/vec/exec/join/vhash_join_node.cpp:906
 6# void std::__invoke_impl<void, doris::vectorized::HashJoinNode::get_next(doris::RuntimeState*, doris::vectorized::Block*, bool*)::{lambda(auto:1&&, auto:2&&, auto:3, auto:4)#2}, doris::vectorized::Prim
aryTypeHashTableContext<unsigned int>&, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)8>&, std::integral_constant<bool, true>, std::integral_constant<bool, false> >(std::__invoke_othe
r, doris::vectorized::HashJoinNode::get_next(doris::RuntimeState*, doris::vectorized::Block*, bool*)::{lambda(auto:1&&, auto:2&&, auto:3, auto:4)#2}&&, doris::vectorized::PrimaryTypeHashTableContext<unsig
ned int>&, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)8>&, std::integral_constant<bool, true>&&, std::integral_constant<bool, false>&&) at /home/ubuntu/tools/ldb-tools/include/c++/
11/bits/invoke.h:61
 7# std::__invoke_result<doris::vectorized::HashJoinNode::get_next(doris::RuntimeState*, doris::vectorized::Block*, bool*)::{lambda(auto:1&&, auto:2&&, auto:3, auto:4)#2}, doris::vectorized::PrimaryTypeHa
shTableContext<unsigned int>&, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)8>&, std::integral_constant<bool, true>, std::integral_constant<bool, false> >::type std::__invoke<doris::
vectorized::HashJoinNode::get_next(doris::RuntimeState*, doris::vectorized::Block*, bool*)::{lambda(auto:1&&, auto:2&&, auto:3, auto:4)#2}, doris::vectorized::PrimaryTypeHashTableContext<unsigned int>&, s
td::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)8>&, std::integral_constant<bool, true>, std::integral_constant<bool, false> >(doris::vectorized::HashJoinNode::get_next(doris::RuntimeSta
te*, doris::vectorized::Block*, bool*)::{lambda(auto:1&&, auto:2&&, auto:3, auto:4)#2}&&, doris::vectorized::PrimaryTypeHashTableContext<unsigned int>&, std::integral_constant<doris::TJoinOp::type, (doris
::TJoinOp::type)8>&, std::integral_constant<bool, true>&&, std::integral_constant<bool, false>&&) at /home/ubuntu/tools/ldb-tools/include/c++/11/bits/invoke.h:97
 8# std::__detail::__variant::__gen_vtable_impl<std::__detail::__variant::_Multi_array<std::__detail::__variant::__deduce_visit_result<void> (*)(doris::vectorized::HashJoinNode::get_next(doris::RuntimeSta
te*, doris::vectorized::Block*, bool*)::{lambda(auto:1&&, auto:2&&, auto:3, auto:4)#2}&&, std::variant<std::monostate, doris::vectorized::SerializedHashTableContext, doris::vectorized::PrimaryTypeHashTabl
eContext<unsigned char>, doris::vectorized::PrimaryTypeHashTableContext<unsigned short>, doris::vectorized::PrimaryTypeHashTableContext<unsigned int>, doris::vectorized::PrimaryTypeHashTableContext<unsign
ed long>, doris::vectorized::PrimaryTypeHashTableContext<doris::vectorized::UInt128>, doris::vectorized::PrimaryTypeHashTableContext<doris::vectorized::UInt256>, doris::vectorized::FixedKeyHashTableContex
t<unsigned long, true>, doris::vectorized::FixedKeyHashTableContext<unsigned long, false>, doris::vectorized::FixedKeyHashTableContext<doris::vectorized::UInt128, true>, doris::vectorized::FixedKeyHashTab
leContext<doris::vectorized::UInt128, false>, doris::vectorized::FixedKeyHashTableContext<doris::vectorized::UInt256, true>, doris::vectorized::FixedKeyHashTableContext<doris::vectorized::UInt256, false>
>&, std::variant<std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)0>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)2>, std::integral_constant<doris::TJoinOp::type,
(doris::TJoinOp::type)8>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)1>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)4>, std::integral_constant<doris::TJoinO
p::type, (doris::TJoinOp::type)3>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)5>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)6>, std::integral_constant<dori
s::TJoinOp::type, (doris::TJoinOp::type)7>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)9>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)10> >&, std::variant<s
td::integral_constant<bool, false>, std::integral_constant<bool, true> >&&, std::variant<std::integral_constant<bool, false>, std::integral_constant<bool, true> >&&)>, std::integer_sequence<unsigned long,
 4ul, 2ul, 1ul, 0ul> >::__visit_invoke(doris::vectorized::HashJoinNode::get_next(doris::RuntimeState*, doris::vectorized::Block*, bool*)::{lambda(auto:1&&, auto:2&&, auto:3, auto:4)#2}&&, std::variant<std
::monostate, doris::vectorized::SerializedHashTableContext, doris::vectorized::PrimaryTypeHashTableContext<unsigned char>, doris::vectorized::PrimaryTypeHashTableContext<unsigned short>, doris::vectorized
::PrimaryTypeHashTableContext<unsigned int>, doris::vectorized::PrimaryTypeHashTableContext<unsigned long>, doris::vectorized::PrimaryTypeHashTableContext<doris::vectorized::UInt128>, doris::vectorized::P
rimaryTypeHashTableContext<doris::vectorized::UInt256>, doris::vectorized::FixedKeyHashTableContext<unsigned long, true>, doris::vectorized::FixedKeyHashTableContext<unsigned long, false>, doris::vectoriz
ed::FixedKeyHashTableContext<doris::vectorized::UInt128, true>, doris::vectorized::FixedKeyHashTableContext<doris::vectorized::UInt128, false>, doris::vectorized::FixedKeyHashTableContext<doris::vectorize
d::UInt256, true>, doris::vectorized::FixedKeyHashTableContext<doris::vectorized::UInt256, false> >&, std::variant<std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)0>, std::integral_cons
tant<doris::TJoinOp::type, (doris::TJoinOp::type)2>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)8>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)1>, std::inte
gral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)4>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)3>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)5>,
std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)6>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)7>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::
type)9>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)10> >&, std::variant<std::integral_constant<bool, false>, std::integral_constant<bool, true> >&&, std::variant<std::integral_con
stant<bool, false>, std::integral_constant<bool, true> >&&) at /home/ubuntu/tools/ldb-tools/include/c++/11/variant:1015 
9# decltype(auto) std::__do_visit<std::__detail::__variant::__deduce_visit_result<void>, doris::vectorized::HashJoinNode::get_next(doris::RuntimeState*, doris::vectorized::Block*, bool*)::{lambda(auto:1&
&, auto:2&&, auto:3, auto:4)#2}, std::variant<std::monostate, doris::vectorized::SerializedHashTableContext, doris::vectorized::PrimaryTypeHashTableContext<unsigned char>, doris::vectorized::PrimaryTypeHa
shTableContext<unsigned short>, doris::vectorized::PrimaryTypeHashTableContext<unsigned int>, doris::vectorized::PrimaryTypeHashTableContext<unsigned long>, doris::vectorized::PrimaryTypeHashTableContext<
doris::vectorized::UInt128>, doris::vectorized::PrimaryTypeHashTableContext<doris::vectorized::UInt256>, doris::vectorized::FixedKeyHashTableContext<unsigned long, true>, doris::vectorized::FixedKeyHashTa
bleContext<unsigned long, false>, doris::vectorized::FixedKeyHashTableContext<doris::vectorized::UInt128, true>, doris::vectorized::FixedKeyHashTableContext<doris::vectorized::UInt128, false>, doris::vect
orized::FixedKeyHashTableContext<doris::vectorized::UInt256, true>, doris::vectorized::FixedKeyHashTableContext<doris::vectorized::UInt256, false> >&, std::variant<std::integral_constant<doris::TJoinOp::t
ype, (doris::TJoinOp::type)0>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)2>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)8>, std::integral_constant<doris::T
JoinOp::type, (doris::TJoinOp::type)1>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)4>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)3>, std::integral_constant
<doris::TJoinOp::type, (doris::TJoinOp::type)5>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)6>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)7>, std::integral
_constant<doris::TJoinOp::type, (doris::TJoinOp::type)9>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)10> >&, std::variant<std::integral_constant<bool, false>, std::integral_constan
t<bool, true> >, std::variant<std::integral_constant<bool, false>, std::integral_constant<bool, true> > >(doris::vectorized::HashJoinNode::get_next(doris::RuntimeState*, doris::vectorized::Block*, bool*):
:{lambda(auto:1&&, auto:2&&, auto:3, auto:4)#2}&&, std::variant<std::monostate, doris::vectorized::SerializedHashTableContext, doris::vectorized::PrimaryTypeHashTableContext<unsigned char>, doris::vectori
zed::PrimaryTypeHashTableContext<unsigned short>, doris::vectorized::PrimaryTypeHashTableContext<unsigned int>, doris::vectorized::PrimaryTypeHashTableContext<unsigned long>, doris::vectorized::PrimaryTyp
eHashTableContext<doris::vectorized::UInt128>, doris::vectorized::PrimaryTypeHashTableContext<doris::vectorized::UInt256>, doris::vectorized::FixedKeyHashTableContext<unsigned long, true>, doris::vectoriz
ed::FixedKeyHashTableContext<unsigned long, false>, doris::vectorized::FixedKeyHashTableContext<doris::vectorized::UInt128, true>, doris::vectorized::FixedKeyHashTableContext<doris::vectorized::UInt128, f
alse>, doris::vectorized::FixedKeyHashTableContext<doris::vectorized::UInt256, true>, doris::vectorized::FixedKeyHashTableContext<doris::vectorized::UInt256, false> >&, std::variant<std::integral_constant
<doris::TJoinOp::type, (doris::TJoinOp::type)0>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)2>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)8>, std::integral
_constant<doris::TJoinOp::type, (doris::TJoinOp::type)1>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)4>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)3>, std:
:integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)5>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)6>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type
)7>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)9>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)10> >&, std::variant<std::integral_constant<bool, false>, std
::integral_constant<bool, true> >&&, std::variant<std::integral_constant<bool, false>, std::integral_constant<bool, true> >&&) at /home/ubuntu/tools/ldb-tools/include/c++/11/variant:1715
10# decltype(auto) std::visit<doris::vectorized::HashJoinNode::get_next(doris::RuntimeState*, doris::vectorized::Block*, bool*)::{lambda(auto:1&&, auto:2&&, auto:3, auto:4)#2}, std::variant<std::monostate
, doris::vectorized::SerializedHashTableContext, doris::vectorized::PrimaryTypeHashTableContext<unsigned char>, doris::vectorized::PrimaryTypeHashTableContext<unsigned short>, doris::vectorized::PrimaryTy
peHashTableContext<unsigned int>, doris::vectorized::PrimaryTypeHashTableContext<unsigned long>, doris::vectorized::PrimaryTypeHashTableContext<doris::vectorized::UInt128>, doris::vectorized::PrimaryTypeH
ashTableContext<doris::vectorized::UInt256>, doris::vectorized::FixedKeyHashTableContext<unsigned long, true>, doris::vectorized::FixedKeyHashTableContext<unsigned long, false>, doris::vectorized::FixedKe
yHashTableContext<doris::vectorized::UInt128, true>, doris::vectorized::FixedKeyHashTableContext<doris::vectorized::UInt128, false>, doris::vectorized::FixedKeyHashTableContext<doris::vectorized::UInt256,
 true>, doris::vectorized::FixedKeyHashTableContext<doris::vectorized::UInt256, false> >&, std::variant<std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)0>, std::integral_constant<doris:
:TJoinOp::type, (doris::TJoinOp::type)2>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)8>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)1>, std::integral_consta
nt<doris::TJoinOp::type, (doris::TJoinOp::type)4>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)3>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)5>, std::integr
al_constant<doris::TJoinOp::type, (doris::TJoinOp::type)6>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)7>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)9>, st
d::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)10> >&, std::variant<std::integral_constant<bool, false>, std::integral_constant<bool, true> >, std::variant<std::integral_constant<bool, f
alse>, std::integral_constant<bool, true> > >(doris::vectorized::HashJoinNode::get_next(doris::RuntimeState*, doris::vectorized::Block*, bool*)::{lambda(auto:1&&, auto:2&&, auto:3, auto:4)#2}&&, std::vari
ant<std::monostate, doris::vectorized::SerializedHashTableContext, doris::vectorized::PrimaryTypeHashTableContext<unsigned char>, doris::vectorized::PrimaryTypeHashTableContext<unsigned short>, doris::vec
torized::PrimaryTypeHashTableContext<unsigned int>, doris::vectorized::PrimaryTypeHashTableContext<unsigned long>, doris::vectorized::PrimaryTypeHashTableContext<doris::vectorized::UInt128>, doris::vector
ized::PrimaryTypeHashTableContext<doris::vectorized::UInt256>, doris::vectorized::FixedKeyHashTableContext<unsigned long, true>, doris::vectorized::FixedKeyHashTableContext<unsigned long, false>, doris::v
ectorized::FixedKeyHashTableContext<doris::vectorized::UInt128, true>, doris::vectorized::FixedKeyHashTableContext<doris::vectorized::UInt128, false>, doris::vectorized::FixedKeyHashTableContext<doris::ve
ctorized::UInt256, true>, doris::vectorized::FixedKeyHashTableContext<doris::vectorized::UInt256, false> >&, std::variant<std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)0>, std::integr
al_constant<doris::TJoinOp::type, (doris::TJoinOp::type)2>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)8>, std::integral_constant<doris::TJoinOp::type, (doris::TJoinOp::type)1>, st
11# doris::vectorized::HashJoinNode::get_next(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /home/zcp/repo_center/selectdb_selectdb-1.0/selectdb/be/src/vec/exec/join/vhash_join_node.cpp:893
12# doris::vectorized::AggregationNode::get_next(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /home/zcp/repo_center/selectdb_selectdb-1.0/selectdb/be/src/vec/exec/vaggregation_node.cpp:381
13# doris::PlanFragmentExecutor::get_vectorized_internal(doris::vectorized::Block**) at /home/zcp/repo_center/selectdb_selectdb-1.0/selectdb/be/src/runtime/plan_fragment_executor.cpp:328
14# doris::PlanFragmentExecutor::open_vectorized_internal() at /home/zcp/repo_center/selectdb_selectdb-1.0/selectdb/be/src/runtime/plan_fragment_executor.cpp:277
15# doris::PlanFragmentExecutor::open() at /home/zcp/repo_center/selectdb_selectdb-1.0/selectdb/be/src/runtime/plan_fragment_executor.cpp:235
16# doris::FragmentExecState::execute() at /home/zcp/repo_center/selectdb_selectdb-1.0/selectdb/be/src/runtime/fragment_mgr.cpp:242
17# doris::FragmentMgr::_exec_actual(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>) at /home/zcp/repo_center/selectdb_selectdb-1.0/selectdb/be/src/runtime/f
ragment_mgr.cpp:485
18# void std::__invoke_impl<void, void (doris::FragmentMgr::*&)(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>), doris::FragmentMgr*&, std::shared_ptr<doris:
:FragmentExecState>&, std::function<void (doris::PlanFragmentExecutor*)>&>(std::__invoke_memfun_deref, void (doris::FragmentMgr::*&)(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::P
lanFragmentExecutor*)>), doris::FragmentMgr*&, std::shared_ptr<doris::FragmentExecState>&, std::function<void (doris::PlanFragmentExecutor*)>&) in /mnt/ssd01/selectdb-1.0/VEC_UBSAN/be/lib/doris-be
19# std::enable_if<is_invocable_r_v<void, void (doris::FragmentMgr::*&)(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>), doris::FragmentMgr*&, std::shared_pt
r<doris::FragmentExecState>&, std::function<void (doris::PlanFragmentExecutor*)>&>, void>::type std::__invoke_r<void, void (doris::FragmentMgr::*&)(std::shared_ptr<doris::FragmentExecState>, std::function
<void (doris::PlanFragmentExecutor*)>), doris::FragmentMgr*&, std::shared_ptr<doris::FragmentExecState>&, std::function<void (doris::PlanFragmentExecutor*)>&>(void (doris::FragmentMgr::*&)(std::shared_ptr
<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>), doris::FragmentMgr*&, std::shared_ptr<doris::FragmentExecState>&, std::function<void (doris::PlanFragmentExecutor*)>&) in /
mnt/ssd01/selectdb-1.0/VEC_UBSAN/be/lib/doris-be
20# void std::_Bind_result<void, void (doris::FragmentMgr::*(doris::FragmentMgr*, std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>))(std::shared_ptr<doris::Fra
gmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>)>::__call<void, , 0ul, 1ul, 2ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul, 2ul>) in /mnt/ssd01/selectdb-1.0/VEC_UBSAN/be/lib/doris-be
21# void std::_Bind_result<void, void (doris::FragmentMgr::*(doris::FragmentMgr*, std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>))(std::shared_ptr<doris::Fra
gmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>)>::operator()<>() at /home/ubuntu/tools/ldb-tools/include/c++/11/functional:631
22# void std::__invoke_impl<void, std::_Bind_result<void, void (doris::FragmentMgr::*(doris::FragmentMgr*, std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>))(s
td::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>)>&>(std::__invoke_other, std::_Bind_result<void, void (doris::FragmentMgr::*(doris::FragmentMgr*, std::shared_p
tr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>))(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>)>&) in /mnt/ssd01/selectdb-
1.0/VEC_UBSAN/be/lib/doris-be
23# std::enable_if<is_invocable_r_v<void, std::_Bind_result<void, void (doris::FragmentMgr::*(doris::FragmentMgr*, std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecuto
r*)>))(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>)>&>, void>::type std::__invoke_r<void, std::_Bind_result<void, void (doris::FragmentMgr::*(doris::Fragm
entMgr*, std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>))(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>)>&>(s
td::_Bind_result<void, void (doris::FragmentMgr::*(doris::FragmentMgr*, std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>))(std::shared_ptr<doris::FragmentExecS
tate>, std::function<void (doris::PlanFragmentExecutor*)>)>&) in /mnt/ssd01/selectdb-1.0/VEC_UBSAN/be/lib/doris-be
24# std::_Function_handler<void (), std::_Bind_result<void, void (doris::FragmentMgr::*(doris::FragmentMgr*, std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>))
(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>)> >::_M_invoke(std::_Any_data const&) at /home/ubuntu/tools/ldb-tools/include/c++/11/bits/std_function.h:292
25# std::function<void ()>::operator()() const at /home/ubuntu/tools/ldb-tools/include/c++/11/bits/std_function.h:560
26# doris::FunctionRunnable::run() at /home/zcp/repo_center/selectdb_selectdb-1.0/selectdb/be/src/util/threadpool.cpp:45
27# doris::ThreadPool::dispatch_thread() at /home/zcp/repo_center/selectdb_selectdb-1.0/selectdb/be/src/util/threadpool.cpp:548
28# void std::__invoke_impl<void, void (doris::ThreadPool::*&)(), doris::ThreadPool*&>(std::__invoke_memfun_deref, void (doris::ThreadPool::*&)(), doris::ThreadPool*&) at /home/ubuntu/tools/ldb-tools/incl
ude/c++/11/bits/invoke.h:74
29# std::__invoke_result<void (doris::ThreadPool::*&)(), doris::ThreadPool*&>::type std::__invoke<void (doris::ThreadPool::*&)(), doris::ThreadPool*&>(void (doris::ThreadPool::*&)(), doris::ThreadPool*&)
at /home/ubuntu/tools/ldb-tools/include/c++/11/bits/invoke.h:97
30# void std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) at /home/ubuntu/tools/ldb-tools/include/c++/11/functional:422
31# void std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>::operator()<, void>() at /home/ubuntu/tools/ldb-tools/include/c++/11/functional:505
32# void std::__invoke_impl<void, std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>&>(std::__invoke_other, std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>&) at /home/ubuntu/tools
/ldb-tools/include/c++/11/bits/invoke.h:61
33# std::enable_if<is_invocable_r_v<void, std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>&>, void>::type std::__invoke_r<void, std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>&>
(std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>&) at /home/ubuntu/tools/ldb-tools/include/c++/11/bits/invoke.h:117
34# std::_Function_handler<void (), std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()> >::_M_invoke(std::_Any_data const&) at /home/ubuntu/tools/ldb-tools/include/c++/11/bits/std_function.h:292
35# std::function<void ()>::operator()() const at /home/ubuntu/tools/ldb-tools/include/c++/11/bits/std_function.h:560
36# doris::Thread::supervise_thread(void*) at /home/zcp/repo_center/selectdb_selectdb-1.0/selectdb/be/src/util/thread.cpp:409
37# start_thread in /lib/x86_64-linux-gnu/libpthread.so.0
38# __clone in /lib/x86_64-linux-gnu/libc.so.6
 `

### What You Expected?

no coredump

### How to Reproduce?

skip

### Anything Else?

no others

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jacktengg** [comment]
How to reproduce:
Status HashJoinNode::_hash_table_build(RuntimeState* state) 函数中，将BUILD_BLOCK_MAX_SIZE修改为一个很小的值：

        constexpr static auto BUILD_BLOCK_MAX_SIZE = 2; 
复现sql:

MySQL [test]> create table a(a int, b int ) distributed by hash(`a`) buckets 1 properties("replication_num"="1");
Query OK, 0 rows affected (0.01 sec)

MySQL [test]> create table b(a int, b int ) distributed by hash(`a`) buckets 1 properties("replication_num"="1");
Query OK, 0 rows affected (0.00 sec)

MySQL [test]> insert into a values(1,1),(2,2),(3,3);
Query OK, 3 rows affected (0.04 sec)
{'label':'insert_9d64ba3bb7144972-b5e993a4d0a9964c', 'status':'VISIBLE', 'txnId':'39'}

MySQL [test]> insert into b values (2,2), (3,3), (4,4);
Query OK, 3 rows affected (0.03 sec)
{'label':'insert_6c243ff69950450a-9808811fbb831a5f', 'status':'VISIBLE', 'txnId':'40'}

MySQL [test]> select * from a where not exists (select * from b where a.a = b.a and a.b != b.b);
