### ISSUE TITLE
[Bug]  When Window Function  and Lateral View  are used together, empty fields will appear in the result

### ISSUE THREAD

**Issue by zhengshubin** [apache/doris#10587]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.0

### What's Wrong?

When Window Function  and Lateral View  are used together, empty fields will appear in the result.
Query  sql:
 SET SESSION  enable_vectorized_engine = false;
SELECT 
*
FROM(
	SELECT 
		p_partkey,
		p_category,
		sum(p_size) OVER(PARTITION BY p_category  ORDER BY p_size) rn
	FROM part

)t1 LATERAL VIEW explode_split('2022-06-01,2022-06-02',',') tmp as dt;

result:
p_partkey|p_category|rn|dt        
---------+----------+--+----------
   NULL      |    NULL      |  NULL |2022-06-01
   NULL      |    NULL      |  NULL |2022-06-02
   NULL      |    NULL      |  NULL |2022-06-01
         .....
 ---------+----------+--+----------

### What You Expected?

result is correct 

### How to Reproduce?

table ·part · is official demo table

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by BiteTheDDDDt** [comment]
Hi, I can't reproduce this case in SSB-100G, could you please update to 1.1 and try again?

**Comment by zhengshubin** [comment]
> Hi, I can't reproduce this case in SSB-100G, could you please update to 1.1 and try again?
It is normal in 1.1.0-rc05
