### ISSUE TITLE
[Bug] BrokerLoad导入任务出现type:ETL_RUN_FAIL; msg:errCode = 2, detailMessage = Broker list path exception. path=hdfs:xxx

### ISSUE THREAD

**Issue by icedrugs89** [apache/doris#10696]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.0.0

### What's Wrong?

1、创建BrokerLoad任务，使用kerberos认证访问hdfs的hive文件导入数据
2、hive文件路径中分区和下一级目录使用通配符*，访问所有分区所有文件
3、任务提交后隔40多秒出现如下的错误
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/100941547/177957713-acae2d98-ca41-43cf-856b-4b6925b7c1c7.png">

4、查看对应的broker机器的log日志，错误堆栈如下：
![image](https://user-images.githubusercontent.com/100941547/177957406-f06d9c4c-1112-4355-9b14-27efb4481a25.png)

### What You Expected?

BrokerLoad任务提交后，show load 看到具体的任务状态为ETL:100%; LOAD:99%，以及JobDetails结果中的ScannedRows行数一直在增长

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kpfly** [comment]
Good Job，跨地域了么？

icedrugs89 ***@***.***> 于2022年7月8日周五 17:19写道：

**Comment by shixiutao** [comment]
It is recommended to send the complete command for **broker load** and the **hdfs** path. I have encountered similar issues before. At that time, I reported an error due to the inconsistent format extracted from the **partition** and **COLUMNS FROM PATH** of the **hive** table
