### ISSUE TITLE
[Bug] BE coredump when receive singal

### ISSUE THREAD

**Issue by Lchangliang** [apache/doris#10903]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

#8  0x00005585b14d2346 in std::default_delete<doris::ThreadPool>::operator() (this=0x602000041f30, __ptr=0x61e000006080)
    at /var/local/ldb_toolchain/include/c++/11/bits/unique_ptr.h:85
#9  0x00005585b14cb0f9 in std::unique_ptr<doris::ThreadPool, std::default_delete<doris::ThreadPool> >::~unique_ptr (this=0x602000041f30, __in_chrg=<optimized out>)
    at /var/local/ldb_toolchain/include/c++/11/bits/unique_ptr.h:361
#10 0x00005585b14c81d0 in doris::MemTableFlushExecutor::~MemTableFlushExecutor (this=0x602000041f30, __in_chrg=<optimized out>)
    at /home/zcp/repo_center/doris_master/be/src/olap/memtable_flush_executor.h:98
#11 0x00005585b14d2e88 in std::default_delete<doris::MemTableFlushExecutor>::operator() (this=0x61a000001b78, __ptr=0x602000041f30)
    at /var/local/ldb_toolchain/include/c++/11/bits/unique_ptr.h:85
#12 0x00005585b14cc1cf in std::unique_ptr<doris::MemTableFlushExecutor, std::default_delete<doris::MemTableFlushExecutor> >::~unique_ptr (this=0x61a000001b78, 
    __in_chrg=<optimized out>) at /var/local/ldb_toolchain/include/c++/11/bits/unique_ptr.h:361
#13 0x00005585b149df9d in doris::StorageEngine::~StorageEngine (this=0x61a000001880, __in_chrg=<optimized out>)
--Type <RET> for more, q to quit, c to continue without paging--c
    at /home/zcp/repo_center/doris_master/be/src/olap/storage_engine.cpp:172
#14 0x00005585b0a845cc in main (argc=1, argv=0x7ffce07c4678) at /home/zcp/repo_center/doris_master/be/src/service/doris_main.cpp:499

### What You Expected?

grace exit

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SWJTU-ZhangLei** [comment]
I guess the reason is the order of desconstruction.  try like this,  
    doris::ExecEnv::destroy(exec_env);
    delete engine;
    engine = nullptr;
    return 0;

In ExecEnv  ThreadPoolToken will  desconstruction; and in engine ThreadPool will desconstruction.
