### ISSUE TITLE
[Bug] cannot access the hive external table stored with s3 as the backend

### ISSUE THREAD

**Issue by ReganHoo** [apache/doris#11024]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.0-rc05

### What's Wrong?

When I access the hive external table stored with s3 as the backend, the `be` reported the following error. In addition, the `fe` has obtained the file list of the corresponding table at this time.
![1658286154695](https://user-images.githubusercontent.com/36258078/179887128-914a48a0-7b64-41b0-b400-c17e21b9db96.jpg)

### What You Expected?

Able to smoothly access hive external tables stored with s3 as the backend

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by morningman** [comment]
Could you provide your `create table` stmt?

**Comment by ReganHoo** [comment]
CREATE TABLE `account_udid` (
  `game_cd` int NOT NULL COMMENT "",
  `account_id` char(256) NOT NULL COMMENT "",
  `udid` char(256) NOT NULL COMMENT "
) ENGINE=HIVE
COMMENT "HIVE"
PROPERTIES (
'hive.metastore.uris' = 'thrift://x.x.x.x:9083',
'database' = 'ods',
'table' = 'account_udid',
'AWS_ACCESS_KEY'='xxxxxxxx',
'AWS_SECRET_KEY'='xxxxxxxx',
'AWS_ENDPOINT'='s3.us-west-2.amazonaws.com',
'AWS_REGION'='us-west-2'
);

**Comment by SbloodyS** [comment]
I also encountered this issue. Did you fix it? @ReganHoo

**Comment by ReganHoo** [comment]
>

**Comment by ReganHoo** [comment]
> I also encountered this issue. Did you fix it? @ReganHoo

Update your doris version to 1.1.2 to solve this problem
