### ISSUE TITLE
[Bug] External table should not have primary key in doris.

### ISSUE THREAD

**Issue by siriume** [apache/doris#11023]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

Error when creating mysql external table, external table should not have primary key in doris.
DDL sql like this:
```
CREATE EXTERNAL TABLE `tb_xxx` (
  `id` bigint NOT NULL,
  `name` varchar(255) NOT NULL,
  `status` tinyint NOT NULL DEFAULT '1',
  `remark` string,
  `create_uid` int(10) DEFAULT NULL COMMENT,
  `modify_uid` int(10) DEFAULT NULL COMMENT,
  `ctime` int(10) NOT NULL,
  `mtime` int(10) NOT NULL
) ENGINE=ODBC COMMENT 'tb_xxx odbc external table'
PROPERTIES (
"odbc_catalog_resource" = "mysql_xx_resource",
"database" = "xxxx",
"table" = "tb_xxx"
);  -- `id`
```

Execution failed: Error Failed to execute sql: java.sql.SQLException: (conn=6) errCode = 2, detailMessage = String Type should not be used in key column[remark].

### What You Expected?

If you replace the text type with the string type, it should succeed when creating the external table.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
Please assign to me. @morningman
