### ISSUE TITLE
[DOC] README.md at least 2 url is not working

### ISSUE THREAD

**Issue by shenxingwuying** [apache/doris#11087]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

Compile and install
See [Compilation](https://doris.apache.org/docs/install/source-install/compilation-with-ldb-toolchain.html)

Getting start
See [Basic Usage](https://doris.apache.org/docs/data-table/basic-usage.html)

The 2 url is not working. eg:
![image](https://user-images.githubusercontent.com/6360122/180216838-e6d27ec7-f1b9-4bee-bf06-268f851019a9.png)

### What You Expected?

Fix it.

### Anything Else?

1

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by shenxingwuying** [comment]
If you support the correct url, I can fix it as my first commit.

**Comment by dataalive** [comment]
> If you support the correct url, I can fix it as my first commit.

correct url should be : 
https://doris.apache.org/docs/install/source-install/compilation-with-ldb-toolchain 
https://doris.apache.org/docs/data-table/basic-usage

**Comment by shenxingwuying** [comment]
> > If you support the correct url, I can fix it as my first commit.
> 
> correct url should be : https://doris.apache.org/docs/install/source-install/compilation-with-ldb-toolchain https://doris.apache.org/docs/data-table/basic-usage

Get.
