### ISSUE TITLE
[Bug] query odbc table error when set enable_vectorized_engine to true

### ISSUE THREAD

**Issue by shutao917** [apache/doris#11127]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris 1.1.0

### What's Wrong?

SET GLOBAL enable_vectorized_engine=TRUE;
SELECT * FROM yz_datawarehouse_pg.dim_accounting_period

错误代码： 2000
Unknown MySQL error

### What You Expected?

right

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kpfly** [comment]
@yiguolei

**Comment by JNSimba** [comment]
What is the schema of the table? Are there more detailed errors?

**Comment by yiguolei** [comment]
Could you please provide some error log in BE?

**Comment by shutao917** [comment]
> Could you please provide some error log in BE?

there is not log in be and fe。the doris cluster is upgrade from 1.0 to 1.1
table schema like this(the table is create when doris version is 1.0)：
CREATE EXTERNAL TABLE `x1` (
  `id` BIGINT(20) NULL ,
  `tenant_id` BIGINT(20) NULL ,
  `dt_yearmonth_str` TEXT NULL 
) ENGINE=ODBC
COMMENT "ODBC"
PROPERTIES (
"odbc_catalog_resource" = "xxxxx",
"database" = "aaaa",
"table" = "aaaaa.dim_accounting_period"
);


when i want to  create a new table like below will get a error(the doris version is upgrade to 1.1):
errCode = 2, detailMessage = String Type should not be used in key column[dt_yearmonth_str].

so i change the sql to:
CREATE EXTERNAL TABLE `x2` (
  `id` BIGINT(20) NULL ,
  `tenant_id` BIGINT(20) NULL ,
  `dt_yearmonth_str` VARCHAR(10) NULL 
) ENGINE=ODBC
COMMENT "ODBC"
PROPERTIES (
"odbc_catalog_resource" = "xxxxx",
"database" = "aaaa",
"table" = "aaaaa.dim_accounting_period"
);

the table is create successful and select * from x2 is ok.
we had many odbc tables,so am i need to upgrade all table define?

**Comment by stalary** [comment]
@shutao917 https://github.com/apache/doris/pull/11096 has been fixed, please wait for 1.1.1 release.
