### ISSUE TITLE
[Bug] fe-core: Compilation failure

### ISSUE THREAD

**Issue by siriume** [apache/doris#11224]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master    8a6c9d8   (#11207)

### What's Wrong?

fe-core compile faild

### What You Expected?

compile succeed

### How to Reproduce?

Fix the error by commenting this line of code
doris/fe/fe-core/src/test/java/org/apache/doris/utframe/TestWithFeService.java:111
//Catalog.getCurrentCatalog().clear();

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by BiteTheDDDDt** [comment]
fixed on #11215
