### ISSUE TITLE
[Bug] Rows transformed by collect_list in subquery cannot be used

### ISSUE THREAD

**Issue by siriume** [apache/doris#11238]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master-8a6c9d8

### What's Wrong?

SQL:
```
select plat_id,company_id, email 
from (
    select plat_id,
    company_id,
    collect_list(user_email) email
    from tb_company
    group by plat_id, company_id)
company
```
error:
```
Execution failed: Error Failed to execute sql: java.sql.SQLException: (conn=95) errCode = 2, detailMessage = Unsupported type 'ARRAY<NOT_NULL(CHAR(-1))>' in '`email`'.
```

### What You Expected?

execute succeed

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yiguolei** [comment]
@cambyzju  Could you please have a look at it？

**Comment by cambyzju** [comment]
@siriume please give me your create table SQL, and some test data.

After fix it, I will recheck your case.

**Comment by cambyzju** [comment]
Maybe you do not open array flag? 
How to Open Array Flag:
`set enable_array_type=true;`
