### ISSUE TITLE
https://doris.incubator.apache.org/docs/get-starting/    Help docs describes the error

### ISSUE THREAD

**Issue by Echo18322276280** [apache/doris#11249]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

docs   version 1.1 

### What's Wrong?

https://doris.incubator.apache.org/docs/sql-manual/sql-reference/Cluster-Management-Statements/ALTER-SYSTEM-DROP-FOLLOWER；
https://doris.incubator.apache.org/docs/sql-manual/sql-reference/Cluster-Management-Statements/ALTER-SYSTEM-DROP-OBSERVER；
There is an error in the description of the linked page，And the error doesn't stop here，Please check the documentation in this directory about Cluster management！

### What You Expected?

Check for corrections ASAP 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
I did not find this problem in the 1.1 document on the official website.

**Comment by Echo18322276280** [comment]
I found that the official website should have updated the document last night, and that error has disappeared.

**Comment by jackwener** [comment]
Solved, close it.
Thanks for your feedback
