### ISSUE TITLE
[Bug] lost Index info during TabletSchema::build_current_tablet_schema

### ISSUE THREAD

**Issue by compasses** [apache/doris#11288]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

CREATE TABLE `lint` (
  `lo_orderkey` bigint(20) NULL,
  `lo_orderpriority` varchar(16) NULL,
  INDEX idx_ngrambf (`lo_orderpriority`) USING NGRAM_BF (3,256) COMMENT 'username ngram_bf index'
) ENGINE=OLAP
DUPLICATE KEY(`lo_orderkey`)
COMMENT 'OLAP'
DISTRIBUTED BY HASH(`lo_orderkey`) BUCKETS 1
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"bloom_filter_columns" = "lo_orderkey",
"in_memory" = "false",
"storage_format" = "V2"
);

add index for two column lo_orderkey-> bloom filter, lo_orderpriority -> ngram bloom filter (new index you can ignore this)

in TabletSchema::build_current_tablet_schema:
ori_tablet_schema _cols[0]'s _is_bf_column = true , after became false;
ori_tablet_schema _cols[1]'s ngram info lost too.. 

### What You Expected?

should have same schema with ori_tablet_schema

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Lchangliang** [comment]
assign me
