### ISSUE TITLE
[Bug] Broker Load cannot correctly import hive data when column name start with number 

### ISSUE THREAD

**Issue by Wujiao233** [apache/doris#11465]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.0-rc05

### What's Wrong?

hive table is like
```sql
create table tmp.t_doris_import_test as 
select 'a' as id, 1 as `41_col`
union all 
select 'b' as id, 2 as `41_col`
union all 
select 'c' as id, 3 as `41_col`
```
which has a column name start with number

and doris table is 
```sql
CREATE TABLE tmp.t_doris_import_test
(
    `id` varchar(20)
    ,`_41_col` bigint 
)
DUPLICATE KEY(`id`)
DISTRIBUTED BY RANDOM
```
because doris cannot use column name start with number so I add a underline before number

then use broker load to load data from hive to doris
```sql
LOAD LABEL sync_t_doris_import_test_1
(
    DATA INFILE("hdfs://path/to/warehouse/tmp.db/t_doris_import_test/*")
    INTO TABLE t_doris_import_test
    FORMAT AS "orc"
    (`id`,`41_col`)
)
WITH BROKER "brokers"
    (
    "username" = "xxx",
    "password" = "xxx"
    )
PROPERTIES
(
    "timeout"="3600"
);
```

which finish successfully.. However when I query this table on doris 
```sql
select * from tmp.t_doris_import_test
```

it return 

| id   | _41_col |
| --- | --- |
| a    |    NULL |
| b    |    NULL |
| c    |    NULL |

### What You Expected?

the result should be like 

| id   | _41_col |
| --- | --- |
| a    |    1 |
| b    |    2 |
| c    |    3 |

or maybe I use the wrong load configuration...

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by freemandealer** [comment]
just gussing... maybe  both tables should have the same name?

**Comment by freemandealer** [comment]
or, you can use 'SET' to do the colume mapping.
FYI:
https://cloud.baidu.com/doc/DORIS/s/5kmealoa8
https://developer.aliyun.com/article/920250

**Comment by Wujiao233** [comment]
after use 'SET' it works fine now 
```sql
LOAD LABEL sync_t_doris_import_test_1
(
    DATA INFILE("hdfs://path/to/warehouse/tmp.db/t_doris_import_test/*")
    INTO TABLE t_doris_import_test
    FORMAT AS "orc"
    (`id`,`41_col`)
    SET (`_41_col` = `41_col`)
)
WITH BROKER "brokers"
    (
    "username" = "xxx",
    "password" = "xxx"
    )
PROPERTIES
(
    "timeout"="3600"
);
```

I assume the default column mapping is by it's index.. and thanks for your help
