### ISSUE TITLE
[Bug] The nvl function reports an error after the vectorization engine is enabled.

### ISSUE THREAD

**Issue by siriume** [apache/doris#11495]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris dev1.1.2 branch ee83ab9

### What's Wrong?

SQL: `select nvl(null,0);`
with error
```
[HY000][1105] errCode = 2, detailMessage = No matching function with signature: nvl(unknown type: NULL_TYPE, tinyint(4)).
```

### What You Expected?

SQL execute succeed.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by morningman** [comment]
the nvl is the oracle function name. You can use `ifnull` function in Doris.
And nvl will be as a alias of `ifnull` in next release version(1.2)
