### ISSUE TITLE
[Bug]  I want to create a new table from the query results of a table

### ISSUE THREAD

**Issue by longzmkm** [apache/doris#11591]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1

### What's Wrong?

 create  table
    `information_schema`.`first_model`
  as (

with source_data as (

    select * from information_schema.tables

)
select
*
from source_data);

Error info:
Query 1 ERROR: errCode = 2, detailMessage = Unknown table 'source_data' in default_cluster:information_schema

### What You Expected?

I want to create a new table from the query results of a table

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
`with as` needs to be wrapped by `select * from () as XXX`

**Comment by qinchaofeng** [comment]
@longzmkm just like [stalary](https://github.com/stalary) said :

```
create table
information_schema.first_model
as 
select * from (

with source_data as (

select * from information_schema.tables
)
select
*
from source_data) as aa;
```
