### ISSUE TITLE
[Bug] Returning incorrect amount of rows when enable vectorization in some where conditions with varchar data type

### ISSUE THREAD

**Issue by lide-reed** [apache/doris#11644]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris 1.1.1 rc03

### What's Wrong?

MySQL [testdb]> select count(*) from  lide_test where create_time>='2022-05-22 11:56:00' and create_time<='2022-05-22 11:58:00';
+----------+
| count(*) |
+----------+
|      105 |
+----------+
1 row in set (0.06 sec)

MySQL [testdb]> set enable_vectorized_engine=true;
Query OK, 0 rows affected (0.00 sec)

MySQL [testdb]> select count(*) from  lide_test where create_time>='2022-05-22 11:56:00' and create_time<='2022-05-22 11:58:00';
+----------+
| count(*) |
+----------+
|      104 |
+----------+
1 row in set (0.07 sec)

### What You Expected?

The same result between enable or disable vectorization

### How to Reproduce?

1. create table
CREATE TABLE `lide_test` (
  `uid` varchar(500) NULL COMMENT "",
  `dt` date NULL COMMENT "导入时间",
  `create_time` varchar(1050) NULL COMMENT ""
) ENGINE=OLAP
UNIQUE KEY(`uid`, `dt`)
COMMENT "OLAP"
PARTITION BY RANGE(`dt`)
(PARTITION P19700101 VALUES [('1970-01-01'), ('2022-08-08')),
PARTITION P20220808 VALUES [('2022-08-08'), ('2022-08-09')),
PARTITION P20220809 VALUES [('2022-08-09'), ('2022-08-10')),
PARTITION P20220810 VALUES [('2022-08-10'), ('2022-08-11')),
PARTITION P20220811 VALUES [('2022-08-11'), ('2022-08-12')),
PARTITION P20220812 VALUES [('2022-08-12'), ('2022-08-13')),
PARTITION P20220813 VALUES [('2022-08-13'), ('2022-08-14')))
DISTRIBUTED BY HASH(`uid`, `dt`) BUCKETS 8
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"in_memory" = "false",
"storage_format" = "V2"
);

2. import sample data
download from https://derenli-bj-1301087413.cos.ap-beijing.myqcloud.com/tmp/data.tgz

4. query

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dataroaring** [comment]
03E5AD557AE13CE18A2A3BB836DA6793        2022-05-22      2022-05-22 11:57:54

**Comment by dataroaring** [comment]
select * from lide_test where create_time>='2022-05-22 11:57:54' and create_time<='2022-05-22 11:57:55';
