### ISSUE TITLE
1.1版本的文档中有ntile函数，但实际不支持

### ISSUE THREAD

**Issue by alangui** [apache/doris#11676]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.0-rc05

### What's Wrong?

No matching function with signature: ntile(tinyint(4))

### What You Expected?

支持ntile

### How to Reproduce?

1.1.0-rc05版本中使用ntile函数

### Anything Else?

无

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by BiteTheDDDDt** [comment]
这个函数在1.1的向量化引擎中还未被支持，在1.2中会加入这个功能
