### ISSUE TITLE
[Bug] 数据列内容不一致

### ISSUE THREAD

**Issue by icedrugs89** [apache/doris#11888]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.1-rc03-2dbd70b

### What's Wrong?

dwd_trade_draw_pdi表更新模型，主键字段为loan_req_no，数据量9亿行
1、执行如下sql，返回5条数据(loan_no字段实际为空的，出现很多都为固定的一个值346217251348331732993)：
select * from fin_dw.dwd_trade_draw_pdi a where date(a.time_loan) >='2022-01-01' and a.loan_state = 'ARJ' and a.loan_no >'0' and a.loan_no not in('NULL','null','') limit 5;
返回数据为如下：
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/100941547/185314482-c7b1f5d3-63b2-47eb-977e-739a4cf6b17d.png">
2、使用第一条数据的loan_req_no=LP6229905816126898176进行查询,返回数据中loan_no字段为空
select loan_req_no,loan_no  from fin_dw.dwd_trade_draw_pdi a where loan_req_no='LP6229905816126898176';
<img width="961" alt="image" src="https://user-images.githubusercontent.com/100941547/185575783-4c83198e-dd50-4b98-b998-af9ecd216891.png">
3、使用loan_no被替换的值346228486043417579522条件查询，整张表只有一行匹配的值
select * from fin_dw.dwd_trade_draw_pdi a where  loan_no='346228486043417579522'
<img width="957" alt="image" src="https://user-images.githubusercontent.com/100941547/185575160-79dcdba3-aaa8-4721-a613-206c66f0cae5.png">
4、hive使用第一条数据的loan_req_no=LP6229905816126898176进行查询,返回数据中loan_no字段为空，其他字段值相同(与第二步一致)
select * from fin_dw.dwd_trade_draw_pdi a where  loan_req_no='LP6229905816126898176'

### What You Expected?

第一步中返回的100条数据中loan_req_no=LP6218452717482803201的应该与做为主键查询返回单行数据保持一致，loan_no真实数据为空，而不是被替换的值

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by BiteTheDDDDt** [comment]
Hi, Do you have any minimal case can reproduce this problems?

**Comment by icedrugs89** [comment]
Not now, reproduced in simulation，But copy the problem's table named dwd_trade_draw_pdi_test001 and reimport data using broker load, then execute step 1 and step 2, get the same error!

**Comment by icedrugs89** [comment]
与社区的技术人员沟通后，采用如下的步骤验证：
1.be.conf增加enable_storage_vectorization = false重启
2.执行select * from fin_dw.dwd_trade_draw_pdi a where date(a.time_loan) >='2022-01-01' and a.loan_state = 'ARJ' and a.loan_no >'0' and a.loan_no not in('NULL','null','') limit 5;
返回结果数据为空，符合预期，向量化存储对某些类型的值方面可能存在一些问题，关闭后恢复

**Comment by icedrugs89** [comment]
be.conf修改以下2个配置也可以临时解决，低基数优化存在一些bug，临时关闭：
enable_low_cardinality_optimize=false，
enable_storage_vectorization=true
线上验证没问题，1.2版本已经修复这个低基数优化的bug

**Comment by dataalive** [comment]
有临时解决方案及后续版本已经fix，该issue先关闭。
