### ISSUE TITLE
[Bug] Failed to execute CREATE TABLE LIKE or  CREATE TABLE AS SELECT  When the SQL statement contains DEFAULT CURRENT_TIMESTAMP

### ISSUE THREAD

**Issue by aopangzi** [apache/doris#11905]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

Execution failed: Error Failed to execute sql: java.sql.SQLException: (conn=112) errCode = 2, detailMessage = Failed to execute CREATE TABLE LIKE dwd_itsm_jt_base. Reason: errCode = 2, detailMessage = date literal [CURRENT_TIMESTAMP] is invalid: errCode = 2, detailMessage = Invalid date value: CURRENT_TIMESTAMP

### What You Expected?

execute successfully

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
Let me have a look, this may need support, can you post your sql?

**Comment by aopangzi** [comment]
create table db_test.ods_daping_cmdb_jt_zstd_bak like db_test.ods_daping_cmdb_jt_zstd    or  create table ods_daping_cmdb_jt_zstd2 as select * from ods_daping_cmdb_jt_zstd

**Comment by stalary** [comment]
> create table db_test.ods_daping_cmdb_jt_zstd_bak like db_test.ods_daping_cmdb_jt_zstd or create table ods_daping_cmdb_jt_zstd2 as select * from ods_daping_cmdb_jt_zstd

Please also provide table ddl, thanks~

**Comment by aopangzi** [comment]
mysql> create table db_test.ods_daping_cmdb_jt_zstd_bak like db_test.ods_daping_cmdb_jt_zstd;
ERROR 1105 (HY000): errCode = 2, detailMessage = Failed to execute CREATE TABLE LIKE ods_daping_cmdb_jt_zstd. Reason: errCode = 2, detailMessage = date literal [CURRENT_TIMESTAMP] is invalid: errCode = 2, detailMessage = Invalid date value: CURRENT_TIMESTAMP
mysql> desc ods_daping_cmdb_jt_zstd;
+-----------------------+---------------+------+-------+-------------------+-------+
| Field                 | Type          | Null | Key   | Default           | Extra |
+-----------------------+---------------+------+-------+-------------------+-------+
| TIMEKEY               | DATE          | Yes  | true  | NULL              |       |
| CATEGORY              | VARCHAR(32)   | Yes  | true  | NULL              |       |
| DISPLAY_NAME          | VARCHAR(32)   | Yes  | true  | NULL              |       |
| DEVICE                | VARCHAR(32)   | Yes  | true  | NULL              |       |
| BELONG_TO             | VARCHAR(32)   | Yes  | true  | NULL              |       |
| belong_to_id_db       | VARCHAR(64)   | Yes  | false | NULL              | NONE  |
| belong_to_id_api      | VARCHAR(64)   | Yes  | false | NULL              | NONE  |
| LOCATION              | VARCHAR(32)   | Yes  | false | NULL              | NONE  |
| dt                    | DATETIME      | Yes  | false | CURRENT_TIMESTAMP | NONE  |

**Comment by aopangzi** [comment]
CREATE TABLE `ods_daping_cmdb_jt_zstd` (
  `TIMEKEY` date NULL,
  `CATEGORY` varchar(32) NULL,
  `DISPLAY_NAME` varchar(32) NULL,
  `DEVICE` varchar(32) NULL,
  `BELONG_TO` varchar(32) NULL,
  `belong_to_id_db` varchar(64) NULL,
  `belong_to_id_api` varchar(64) NULL,
  `LOCATION` varchar(32) NULL,
  `dt` datetime NULL DEFAULT "CURRENT_TIMESTAMP",
  `location_id_db` varchar(64) NULL,
  `location_id_api` varchar(64) NULL,
  `DEVICESTATUS` varchar(32) NULL,
  `devicestatus_id_db` varchar(64) NULL,
  `devicestatus_id_api` varchar(64) NULL,
  `BK_HOST_NAME` varchar(128) NULL,
  `BK_HOST_ID` varchar(32) NULL,
  `BK_INST_NAME` varchar(128) NULL,
  `ASSET_CODE` varchar(32) NULL,
  `host_type` varchar(64) NULL,
  `relat_py_ip` varchar(64) NULL,
  `cpu_num` varchar(64) NULL,
  `memory_capacity` varchar(64) NULL,
  `disk_capacity` varchar(64) NULL,
  `enable_date` varchar(64) NULL,
  `bk_host_innerip` varchar(64) NULL,
  `use_classifica` varchar(85) NULL,
  `use_classifica_id_db` varchar(85) NULL,
  `use_classifica_id_api` varchar(85) NULL,
  `bk_os_type` varchar(85) NULL,
  `bk_os_type_id_api` varchar(85) NULL,
  `bk_os_type_id_db` varchar(85) NULL,
  `sys_type` varchar(85) NULL,
  `sys_type_id_api` varchar(85) NULL,
  `sys_type_id_db` varchar(85) NULL,
  `bk_inst_id` varchar(32) NULL,
  `task_id` varchar(64) NULL,
  `policy_name` varchar(255) NULL,
  `system_name` varchar(255) NULL,
  `manageip` varchar(255) NULL,
  `policy_use` varchar(255) NULL,
  `address_translation` varchar(1000) NULL,
  `port_desc` varchar(512) NULL,
  `merge_policy` varchar(255) NULL,
  `remark` varchar(255) NULL,
  `source_port` varchar(255) NULL,
  `protocol_type` varchar(255) NULL,
  `destination_port` varchar(2000) NULL,
  `source_domain` varchar(255) NULL,
  `destination_domain` varchar(255) NULL,
  `rule_action` varchar(255) NULL,
  `policy_deadline` varchar(255) NULL,
  `policy_desc` varchar(255) NULL,
  `source_ipv4` varchar(3000) NULL,
  `destination_ipv4` varchar(3000) NULL,
  `policy_status` varchar(255) NULL,
  `maintenance_post` varchar(255) NULL,
  `domain` varchar(255) NULL
) ENGINE=OLAP
DUPLICATE KEY(`TIMEKEY`, `CATEGORY`, `DISPLAY_NAME`, `DEVICE`, `BELONG_TO`)
COMMENT 'OLAP'
DISTRIBUTED BY HASH(`TIMEKEY`) BUCKETS 5
PROPERTIES (
"replication_allocation" = "tag.location.default: 2",
"in_memory" = "false",
"storage_format" = "V2",
"compression" = "ZSTD"
) |

**Comment by stalary** [comment]
Thanks, today I will take a look at the problem.
