### ISSUE TITLE
[Enhancement] replace `assertTrue(X.equals(X))` with `assertEquals`

### ISSUE THREAD

**Issue by jackwener** [apache/doris#11916]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

```java
Assert.assertTrue(column1.equals(column1));
Assert.assertFalse(column2.equals(column2));
->
Assert.assertEquals(column1, column1);
Assert.assertNotEquals(column2, column2);
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by balan2307** [comment]
I am interested in solving this ,can you please assign me?

**Comment by s11ngh** [comment]
Hi, could you assign this issue? Would love working on it

**Comment by sristis0202** [comment]
I am interested, please add!

**Comment by jackwener** [comment]
Hi, if you are interesting, you can new a PR and link this issue.

**Comment by eshikarya** [comment]
Hi @jackwener! I'm a beginner in open source, I want to work on this issue if it's unassigned can you please guide me on how I can get started?

**Comment by AnvarAslam** [comment]
i am very happy to solve these issue can i take it and solve these issue & u can help me to guide me on these?

**Comment by Prakhar047** [comment]
its my very first contribution to open source, can you assign this problem to me?

**Comment by jackwener** [comment]
Hi, everyone, if you are interesting, you can new a PR and link this issue.
And @ me, I will review it.

**Comment by etcZYP** [comment]
@jackwener plz review my PR, thx

**Comment by jackwener** [comment]
BTW, I suggest to use `intellij IDEA` open project. And IDEA will suggest it and auto fix it.

**Comment by priyasharma1** [comment]
Hi @jackwener , I am also facing a few failed tests, can you please provide direction on how to resolve these?

**Comment by TrueDevCoder** [comment]
Hi, I would love to try out this task, can you assign it to me ?
