### ISSUE TITLE
[Bug] doris的group_concat函数不支持distinct

### ISSUE THREAD

**Issue by weAreFriendYo** [apache/doris#11932]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1

### What's Wrong?

当使用group_concat(distinct  colunmName) 时 ，提示group_concat does not support DISTINCT ,官方文档却说支持

### What You Expected?

当使用group_concat(distinct  colunmName) 时 ，提示group_concat does not support DISTINCT ,官方文档却说支持

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
Wait for 1.1.2 publish, you can use it.
