### ISSUE TITLE
[Bug] 嵌套查询使用 LATERAL VIEW 生成的属性做为条件判断不生效

### ISSUE THREAD

**Issue by MRYOG** [apache/doris#11986]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.2-rc02

### What's Wrong?

在使用  LATERAL VIEW 相关方法时候，外层嵌套的查询，要是使用  LATERAL VIEW  生成的属性做为条件判断，是不生效的。其他属性作为条件判断是可以的
![image](https://user-images.githubusercontent.com/10381662/186060159-1f2e5303-ad3c-4138-bdbb-e2ca583ded1f.png)

### What You Expected?

Fix it

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by spihiker** [comment]
My doris version:1.1.1
I have the same problem.
