### ISSUE TITLE
[Bug] Delete 语句Where 条件不能跟加 1=1

### ISSUE THREAD

**Issue by MRYOG** [apache/doris#11987]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.2-rc02

### What's Wrong?

delete from table where 1=1 报错 ： Left expr of binary predicate should be column name

![image](https://user-images.githubusercontent.com/10381662/186060628-0b037bd6-04cc-4bbd-9203-1abed744eb67.png)

### What You Expected?

拼接语句 1=1 还是比较常见，Doris delete 不能添加是有特殊考虑吗？还是可以修复？

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
Currently, DELETE only allow key columns.

**Comment by MRYOG** [comment]
Understand, thank you
