### ISSUE TITLE
[Bug] can't create table when column name with dot(.)

### ISSUE THREAD

**Issue by zingdle** [apache/doris#11993]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.1

### What's Wrong?

```sql
CREATE DATABASE FOO;

CREATE TABLE `FOO`.`tbl`
(
    `ID`    BIGINT NOT NULL,
    `COL.0` BIGINT NOT NULL,
    `COL.1` BIGINT NOT NULL
) UNIQUE KEY(`ID`)
DISTRIBUTED BY HASH(`ID`) BUCKETS 10
PROPERTIES("replication_num" = "1");
```

I got:
```
ERROR 1166 (42000): errCode = 2, detailMessage = Incorrect column name 'COL.0'
```

### What You Expected?

`FOO`.`tbl` should be ok.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Henry2SS** [comment]
It is not allowed to use `.` in column name.
The column regex is `^[_a-zA-Z@][a-zA-Z0-9_]{0,63}$`

**Comment by zingdle** [comment]
@Henry2SS seems that it's ok to have dot in column name.

http://sqlfiddle.com/#!9/66fccf7/1/0

**Comment by morningman** [comment]
> [Enhancement](Error Msg) show details of COLUMN and TABLE name regex #11999
MySQL support it.
But IMO, it may be conflict with the nested column type which Doris will be supported in future.
For example, a STRUCT type column `k1`, we can get it's member `k1.field1`, but it is hard to explain this: `k1.0.field1`.
