### ISSUE TITLE
[Bug] with as 复杂使用时，出现null值错误

### ISSUE THREAD

**Issue by MRYOG** [apache/doris#11994]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.2-rc2

### What's Wrong?

with test_customer as(
select c_customer_sk,c_customer_id,c_current_cdemo_sk
    from tpc_db.customer as q
    where c_customer_sk
            in (
	        select c_customer_sk
      		from tpc_db.customer
      		where c_salutation='test'
      		group by 1 having COUNT(DISTINCT c_salutation) >4)
    )
    select * from test_customer limit 10

条件中包含复杂查询时，出现报错
![image](https://user-images.githubusercontent.com/10381662/186104216-f8f60b1a-4e16-4070-953c-55226ebae219.png)

### What You Expected?

Fix

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by luozenglin** [comment]
Can you provide the steps to reproduce this issue？

**Comment by MRYOG** [comment]
you can relpace any yours table and column  execute it . it will throw this exception
