### ISSUE TITLE
[Bug] FE的JDBC有问题

### ISSUE THREAD

**Issue by doglex** [apache/doris#12063]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

apache-doris-1.1.1-bin-x86.tar

### What's Wrong?

playgroud界面show databases， 报 mariadb错误

### What You Expected?

可以显示 information_schema

### Anything Else?

用自己的jdbc才行 
cp  mysql-connector-java-5.1.47.jar mariadb-java-client-3.0.4.jar

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hf200012** [comment]
必须是内置的，两个驱动类的路径，名称都不一样，肯定不能这样用
![KqY6aeirZ6](https://user-images.githubusercontent.com/820301/187104167-d477544c-e036-496b-aa8a-ed7c69d7cdb5.jpg)

**Comment by doglex** [comment]
> 必须是内置的，两个驱动类的路径，名称都不一样，肯定不能这样用 ![KqY6aeirZ6](https://user-images.githubusercontent.com/820301/187104167-d477544c-e036-496b-aa8a-ed7c69d7cdb5.jpg)

对的。
我发现问题不在jdbc的jar包上，而是，
需要先点击Playgroud的左侧的一个数据库才能查询，
若没有选中数据库，mariadb就会报错
