### ISSUE TITLE
[Feature] Mysql subtable with binlog model merge one table

### ISSUE THREAD

**Issue by GDragon97** [apache/doris#12110]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

I want to megre Mysql subtable into one table and can update by unique key 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
You can use Agg key and replace_if_not_null implement multitable merge.
