### ISSUE TITLE
[Bug] create table failed when string type has a default value which length greater than 1

### ISSUE THREAD

**Issue by dujl** [apache/doris#12145]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-master after doris 1.1.2

### What's Wrong?

create table failed when string type has a default value which length greater than 1

```

CREATE TABLE `tb6` (
  `id` int(11) NULL DEFAULT "10",
  `name` varchar(32) NULL DEFAULT "a varchar 32",
  `c_text` text NULL DEFAULT "a text",
  `c_str` string  NULL DEFAULT "a string"
) ENGINE=OLAP
UNIQUE KEY(`id`)
COMMENT 'OLAP'
DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES (
"replication_allocation" = "tag.location.default: 3",
"in_memory" = "false",
"storage_format" = "V2",
"disable_auto_compaction" = "false"
); 
```

### What You Expected?

create table successful

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
https://github.com/apache/doris/pull/12187
