### ISSUE TITLE
[Enhancement] Optimize cache reader use pre-created buffer

### ISSUE THREAD

**Issue by zxealous** [apache/doris#12164]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Now, cacher reader creates a buffer for receiving data each time while download the cache, the download task is serial, no need to create a new buffer every time.

### Solution

Create a shared buffer in advance.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Toms1999** [comment]
let me seesee
