### ISSUE TITLE
doris审计日志BUG -截取原生sql

### ISSUE THREAD

**Issue by biandou1313** [apache/doris#12381]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris1.1.1

### What's Wrong?

1、 审计日志表字段存储原始sql 
stmt string comment "The original statement, trimed if longer than 2G "

2、插件里面配置max_stmt_length=700000 （比默认大）

3、产生现象： 数据库中存储创建表得sql 都被截取了
![1662450957(1)](https://user-images.githubusercontent.com/34857750/188578967-47ca0f2b-26e0-4efc-bf6f-dcc8e04b6b82.png)

### What You Expected?

不要截取原生sql  

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by biandou1313** [comment]
我需要完整原生sql

**Comment by biandou1313** [comment]
大佬 还在看这个问题么



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Paddy ***@***.***&gt;; 
发送时间: 2022年9月7日(星期三) 上午7:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/doris] doris审计日志BUG -截取原生sql (Issue #12381)





 
Assigned #12381 to @biandou1313.

**Comment by dataalive** [comment]
我也研究下这个问题。

**Comment by hf200012** [comment]
https://github.com/apache/doris/pull/12589

**Comment by dataalive** [comment]
has been fixed by https://github.com/apache/doris/pull/12627

**Comment by biandou1313** [comment]
我验证一下
