### ISSUE TITLE
[Bug] flink-doris-connector failed

### ISSUE THREAD

**Issue by BigdataGit** [apache/doris#12582]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

<img width="815" alt="image" src="https://user-images.githubusercontent.com/27194698/190051540-6742b513-a23b-4d80-b4c7-71d7e4c95bc2.png">

### What's Wrong?

> 

The access to doris sink http is unavailable
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/27194698/190050798-bc0a8987-fcd4-4e20-93c1-558d322e92d2.png">

After looking at the source code, the API of the HTTP query table structure and the URL in the exception information are not quite the same. I don't understand what's going on here

<img width="889" alt="image" src="https://user-images.githubusercontent.com/27194698/190046354-e58d01ef-7a82-4f68-b447-5e8321ebd271.png">

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/27194698/190046414-fa6d69b9-4bfa-4d6b-b12e-87f7c302a5d3.png">

### What You Expected?

Connector compiled by myself

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JNSimba** [comment]
The request for the schema interface failed, you can try to use curl to request locally to see if it is normal

**Comment by BigdataGit** [comment]
> The request for the schema interface failed, you can try to use curl to request locally to see if it is normal

The request is normal, and the console page can also be opened, but there is a problem. The address requested by the flash connector is different

**Comment by BigdataGit** [comment]
> 

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/27194698/190053066-dc6bdad8-70cd-4a23-b60c-ac8228ed4038.png">

**Comment by JNSimba** [comment]
this api ： https://doris.apache.org/zh-CN/docs/admin-manual/http-actions/fe/table-schema-action
