### ISSUE TITLE
[Bug] ArrayFileColumnIterator::next_batch DCHECK(num_read == num_items) failed

### ISSUE THREAD

**Issue by ByteYue** [apache/doris#12642]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Master ASAN
4 BE

### What's Wrong?

When querying statement below in Doris, BE crashed.
`select      /*+ SET_VAR(query_timeout = 600) */ ref_21.`k3` as c0,    version() as c1,    ref_21.`k1` as c2 from  regression_test_load_insert.tbl_test_array_string_insert as ref_21 where true`
It seems the `DCHECK(num_read == num_items)` in ArrayFileColumnIterator::next_batch is the trigger.

### What You Expected?

Return valid rows instead coredump.

### How to Reproduce?

Compile be with asan, then type statement below to doris.
`select      /*+ SET_VAR(query_timeout = 600) */ ref_21.`k3` as c0,    version() as c1,    ref_21.`k1` as c2 from  regression_test_load_insert.tbl_test_array_string_insert as ref_21 where true`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by cambyzju** [comment]
1. recently we have a non-backward compatibility upgrade https://github.com/apache/doris/pull/12293, we need to clear table with array-column after upgrade;
2. could you give more infos about the table schema and test data?

**Comment by ByteYue** [comment]
Sorry for late response, the table `regression_test_load_insert.tbl_test_array_string_insert` is generated by the regression test `regression-test/suites/load/insert/test_array_string_insert.groovy`.
> we need to clear table with array-column after upgrade
By following the above instruction, the problem is solved and rows are returned as expected. Thanks a lot!
