### ISSUE TITLE
【Bug】doris writer write failed on json format

### ISSUE THREAD

**Issue by Wilson-BT** [apache/doris#12718]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris: 1.1.2
DataxWriter: 0.0.1-SNAPSHOT

### What's Wrong?

1. When we use json format and batch write to doris, the order of column key on http header is different with json-data.
2. The method ```Key.getFormat``` not match【DOC】,we should make compatible between loadProps and out-format.

### What You Expected?

fix bug

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JNSimba** [comment]
key.format default value is csv, what mean not match 【DOC】?

**Comment by Wilson-BT** [comment]
> key.format default value is csv, what mean not match 【DOC】?


The code is inconsistent with the official documentation, The old and new versions of the code are not compatible
