### ISSUE TITLE
[Enhancement] Support  insert select from temp table  

### ISSUE THREAD

**Issue by Wilson-BT** [apache/doris#12810]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Support insert to table by ``` with a as () insert into b select * from a ``` this sql. 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
You can rewrite it to `insert into b select * from (with a as () select * from a) as ret`
