### ISSUE TITLE
[Bug] slack link is no longer active

### ISSUE THREAD

**Issue by ruleeeer** [apache/doris#12836]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

all

### What's Wrong?

![image](https://user-images.githubusercontent.com/70385062/191512608-1318cfd7-9471-4853-ba56-9c6c6448a325.png)

When I click on the Slack link, it shows

![image](https://user-images.githubusercontent.com/70385062/191513003-fde37058-f92e-43af-ad3b-1607dac3a20a.png)

### What You Expected?

You can join the slack normally

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LemonLiTree** [comment]
you can try it：https://join.slack.com/t/apachedoriscommunity/shared_invite/zt-1co4h0c90-Kfu5MUgaTi4n~lAwNXfbuQ
And if you want（reply me or follow the wechat official account on the official website）, you can join the WeChat group of the open source user community。
