### ISSUE TITLE
[Enhancement] SelectRollupTest UT is unstable

### ISSUE THREAD

**Issue by jackwener** [apache/doris#12964]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

```
org.apache.doris.common.DdlException: errCode = 2, detailMessage = Table[t]'s state is not NORMAL. Do not allow doing ALTER ops
  at org.apache.doris.nereids.rules.mv.SelectRollupTest.runBeforeAll(SelectRollupTest.java:52)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dinggege1024** [comment]
@jackwener  Hi jack, i would like to help this

**Comment by dinggege1024** [comment]
#13030 Hi @jackwener , plz review this pr~
