### ISSUE TITLE
[Bug](aarch64) Failed to start BE due to errors caused by AddressSanitizer

### ISSUE THREAD

**Issue by adonis0147** [apache/doris#13026]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris Version: master
Build Type: ASAN
OS: Ubuntu 22.04.1 LTS (aarch64)

### What's Wrong?

```shell
==45593==ERROR: AddressSanitizer failed to allocate 0x0 (0) bytes of ReadFileToBuffer (error code: 22)
ERROR: Failed to mmap
```

### What You Expected?

Start BE successfully.

### How to Reproduce?

```shell
BUILD_TYPE=ASAN BUILD_META_TOOL=OFF ./build.sh --be --clean
cd output/be/bin
./start_be.sh
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hello-stephen** [comment]
Hi, friend
I also encounter the mmap problem when trying to run be ut with ` ./run-be-ut.sh -j10` on the aarch64 machine.
```

...
[1204/1204] Linking CXX executable test/doris_be_test
******************************
   Running Backend Unit Test  
******************************
==3190562==ERROR: AddressSanitizer failed to allocate 0x0 (0) bytes of ReadFileToBuffer (error code: 22)
ERROR: Failed to mmap
=== Finished. Gtest output: /root/doris/be/ut_build_ASAN/gtest_output
```
Would you please take a look?

**Comment by adonis0147** [comment]
Hi @hello-stephen , I couldn't reproduce this issue on my machine. Would you like to provide more information?
