### ISSUE TITLE
[Feature] Batch create partitions (supports date and number types)

### ISSUE THREAD

**Issue by azaleaFang** [apache/doris#13123]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Batch partition creation is supported during and after table creation. Start and end of batch partition can be specified by START and END, and partition increment value can be specified by EVERY clause. The batch partition contains the value of START, but not the value of END. The naming rules for partitions are the same as those for dynamic partitions.

### Use case

When the time or number span is large, it is troublesome to manually set each partition.
![1](https://user-images.githubusercontent.com/28645124/193980293-ec977d64-09a9-45af-a274-b56c1dd48175.png)
![2](https://user-images.githubusercontent.com/28645124/193980300-6a961056-3251-493a-867a-dc0161ea8d34.png)
![3](https://user-images.githubusercontent.com/28645124/193980317-77569cfb-2749-41e4-9e46-301d12dd96fc.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
Can you decribe your demand？I think dynamic partition can satisfy most scenarios.

**Comment by thj999** [comment]
> Can you decribe your demand？I think dynamic partition can satisfy most scenarios.
Historical data from 2019 to now is initialized

**Comment by azaleaFang** [comment]
see the detail describtion below:
https://docs.starrocks.io/zh-cn/latest/table_design/Data_distribution#%E6%89%B9%E9%87%8F%E5%88%9B%E5%BB%BA%E5%88%86%E5%8C%BA

**Comment by azaleaFang** [comment]
> > Can you decribe your demand？I think dynamic partition can satisfy most scenarios.
> > Historical data from 2019 to now is initialized
see the detail describtion below:
https://docs.starrocks.io/zh-cn/latest/table_design/Data_distribution#%E6%89%B9%E9%87%8F%E5%88%9B%E5%BB%BA%E5%88%86%E5%8C%BA

**Comment by azaleaFang** [comment]
> Can you decribe your demand？I think dynamic partition can satisfy most scenarios.

see the detail describtion below:
https://docs.starrocks.io/zh-cn/latest/table_design/Data_distribution#%E6%89%B9%E9%87%8F%E5%88%9B%E5%BB%BA%E5%88%86%E5%8C%BA
