### ISSUE TITLE
[Bug] SM4 encryption function encryption result error

### ISSUE THREAD

**Issue by FreeOnePlus** [apache/doris#13221]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.1

### What's Wrong?

In the sample results of Doris, the SM4 encryption function returns the encryption content as' aDjwRflBrDjhBZIOFNw3Tg==', but the encryption results of the encryption program written in Java and the test website are both' LjZFimmUHZO4TghQCZ8z4w=='

The test website is: http://lzltool.com/SM4

The test is as shown in the figure

![7Na3wptqOH](https://user-images.githubusercontent.com/54164178/194751005-466e04e0-36ee-459c-9f85-094a73e22229.png)

![c00e2b3077b6248283e3110f03196fb](https://user-images.githubusercontent.com/54164178/194751071-9d4768ed-6bdc-4599-ad11-a518fbf80ab2.jpg)

### What You Expected?

![f1df003fa1f3c3dcf431102d0ffab97](https://user-images.githubusercontent.com/54164178/194751042-5d47a34b-aa5a-4147-94bb-b3c81681ce73.jpg)
![c00e2b3077b6248283e3110f03196fb](https://user-images.githubusercontent.com/54164178/194751047-4f56af6e-aa10-4a85-b293-a535c423d3dd.jpg)
![3d5b4c143d3a31a70302dd34ec19957](https://user-images.githubusercontent.com/54164178/194751052-bdee2572-9740-4dfa-98dc-ae58e5cec1b2.jpg)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by biohazard4321** [comment]
Use unhex to wrap the key like 
       select to_base64(sm4_encrypt('text', unhex('F3229A0B371ED2D9441B830D21A390C3')));
then you will get the right result.

**Comment by FreeOnePlus** [comment]
> Use unhex to wrap the key like select to_base64(sm4_encrypt('text', unhex('F3229A0B371ED2D9441B830D21A390C3'))); then you will get the right result.

get√

**Comment by FreeOnePlus** [comment]
<img width="877" alt="image" src="https://user-images.githubusercontent.com/54164178/195271065-50588ec6-fec8-4b59-8328-7630d87d12cb.png">
