### ISSUE TITLE
[Bug] SQL查询 IF子句不支持表达式

### ISSUE THREAD

**Issue by vvii** [apache/doris#13232]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.2-rc05-a8323dae4

### What's Wrong?

提交查询
`select if(dayofweek(CURDATE()) = 1, 7, dayofweek(CURDATE())-1)`
报错
`ERROR 1105 (HY000): RpcException, msg: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason`
观察到BE节点挂掉，be.out 文件输出
`*** Aborted at 1665370577 (unix time) try "date -d @1665370577" if you are using GNU date ***
*** SIGSEGV address not mapped to object (@0x0) received by PID 3262778 (TID 0x7f3374980700) from PID 0; stack trace: ***
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /mnt/disk2/apache-doris/be/src/common/signal_handler.h:420
 1# 0x00007F33B544EF00 in /lib64/libc.so.6
 2# void doris::vectorized::MutableBlock::merge<doris::vectorized::Block&>(doris::vectorized::Block&) at /mnt/disk2/apache-doris/be/src/vec/core/block.h:379
 3# doris::vectorized::VUnionNode::get_next_const(doris::RuntimeState*, doris::vectorized::Block*) at /mnt/disk2/apache-doris/be/src/vec/exec/vunion_node.cpp:193
 4# doris::vectorized::VUnionNode::get_next(doris::RuntimeState*, doris::vectorized::Block*, bool*) in /usr/local/services/doris/be/lib/doris_be
 5# doris::PlanFragmentExecutor::get_vectorized_internal(doris::vectorized::Block**) at /mnt/disk2/apache-doris/be/src/runtime/plan_fragment_executor.cpp:352
 6# doris::PlanFragmentExecutor::open_vectorized_internal() at /mnt/disk2/apache-doris/be/src/runtime/plan_fragment_executor.cpp:301
 7# doris::PlanFragmentExecutor::open() in /usr/local/services/doris/be/lib/doris_be
 8# doris::FragmentExecState::execute() at /mnt/disk2/apache-doris/be/src/runtime/fragment_mgr.cpp:246
 9# doris::FragmentMgr::_exec_actual(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>) at /mnt/disk2/apache-doris/be/src/runtime/fragment_mgr.cpp:478
10# void std::__invoke_impl<void, void (doris::FragmentMgr::*&)(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>), doris::FragmentMgr*&, std::shared_ptr<doris::FragmentExecState>&, std::function<void (doris::PlanFragmentExecutor*)>&>(std::__invoke_memfun_deref, void (doris::FragmentMgr::*&)(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>), doris::FragmentMgr*&, std::shared_ptr<doris::FragmentExecState>&, std::function<void (doris::PlanFragmentExecutor*)>&) at /mnt/disk2/ygl/installs/ldbtools/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:74
11# doris::ThreadPool::dispatch_thread() at /mnt/disk2/apache-doris/be/src/util/threadpool.cpp:578
12# doris::Thread::supervise_thread(void*) at /mnt/disk2/apache-doris/be/src/util/thread.cpp:407
13# start_thread in /lib64/libpthread.so.0
14# __clone in /lib64/libc.so.6`

### What You Expected?

if函数的参数应当支持表达式

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by BiteTheDDDDt** [comment]
经过测试，在目前的master没有这个问题

**Comment by vvii** [comment]
1.1.
