### ISSUE TITLE
[Bug] CAST does not support HLL and BITMAP data types

### ISSUE THREAD

**Issue by hf200012** [apache/doris#13288]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.2

### What's Wrong?

```
create table `select_varchar`  PROPERTIES("replication_num" = "1")  as select 123,"1999-10-10",'aaa',123,123,"1970                   -01-01 00:00:00","1970-01-01 00:00:00","1970-01-01 00:00:00",123,123,123,hll_hash(""),bitmap_from_string("");
```
Error:
```
ERROR 1105 (HY000): Unexpected exception: errCode = 2, detailMessage = Failed to execute CTAS Reason: errCode = 2, detailMessage = Aggregate type `_col11` hll NONE NULL COMMENT "" is not compatible with primitive type hll
```

### What You Expected?

OK

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
hll and bitmap need aggrgate，but CTAS not get the key column, so it will be error.
