### ISSUE TITLE
openEuler 22.03-LTS  'doris_be' failed to start (exit status 127) -- '/var/apache-doris/be/bin/start_be.sh': /var/apache-doris/be/lib/doris_be: symbol lookup error: /var/apache-doris/be/lib/doris_be: undefined symbol: _dl_sym, version GLIBC_PRIVATE

### ISSUE THREAD

**Issue by huangkaiyan10** [apache/doris#13309]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris 1.1.1

### What's Wrong?

openEuler 22.03-LTS  server os 。
 'doris_be' failed to start (exit status 127) -- '/var/apache-doris/be/bin/start_be.sh': /var/apache-doris/be/lib/doris_be: symbol lookup error: /var/apache-doris/be/lib/doris_be: undefined symbol: _dl_sym, version GLIBC_PRIVATE

### What You Expected?

doris_be can start success at oepnEuler 22.03-LTS server os.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dataalive** [comment]
这个用最新的1.1.3编译或者发布后的arm包应该可以。

**Comment by huangkaiyan10** [comment]
doris 1.1.3 test ok
