### ISSUE TITLE
[Doc] 1.1 版本 不支持 Java UDF 函数

### ISSUE THREAD

**Issue by Chris-Arith** [apache/doris#13369]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

v1.1.2

### What's Wrong?

官方文档中介绍了 Java UDF 函数，但是 1.1.2 版本不支持 Java UDF 函数

### What You Expected?

修改官方文档，指定支持版本

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LemonLiTree** [comment]
https://github.com/apache/doris-website/pull/144

**Comment by Wilson-BT** [comment]
> [apache/doris-website#144](https://github.com/apache/doris-website/pull/144) 已删除，会在1.2版本支持
what time will the version of 1.2 be pushed?

**Comment by LemonLiTree** [comment]
> > [apache/doris-website#144](https://github.com/apache/doris-website/pull/144) 已删除，会在1.2版本支持
> > what time will the version of 1.2 be pushed?

Within one month
