### ISSUE TITLE
[Bug] 无法正确识表别名

### ISSUE THREAD

**Issue by zenyanggongmian1995** [apache/doris#13431]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.2.rc02

### What's Wrong?

无法正确识别表别名。

当我使用lateral view 侧视图时， 包含在侧视图内部的SQL语句，其中的表别名可以任意，SQL会正常跑，没有正确识别。

### What You Expected?

使别名可以正确识别

### How to Reproduce?

        SELECT *
	        FROM (
	            SELECT 
	                concat_ws('$', '1', xxapasdap_d.uv / 10000) AS uv,  
	                concat_ws('$', '2', asdasapp_d.pv / 10000) AS pv,  
	                concat_ws('$', '3', asdasdconapp_d.duration / 36000000) AS duration,
	                concat_ws('$', '24', arweepp_d.pv / app_d.uv) AS pv_capita, 
	                concat_ws( '$', '25',app_d.duration / (app_d.uv * 3600)) AS duration_capita 
	            FROM (SELECT * FROM  test.test  WHERE  day_id = 20221016 AND uv IS NOT NULL) app_d
	            ORDER BY app_d.standard_app_id        ) a lateral VIEW explode_split ( CONCAT_WS( ',', uv, pv, duration, pv_capita, duration_capita ), ',' ) tmp1 AS key_value

可以看见 我上面内层所有字段前的表别名都是随机写的，但是该SQL仍然可以运行，且结果是正确的。

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dataalive** [comment]
this issue has been fixed by https://github.com/apache/doris/pull/13600
