### ISSUE TITLE
7.5 检查导入数据 执行下面的 SQL 语句检查导入的数据量上 上面的数据量是一致。文案错误

### ISSUE THREAD

**Issue by LuiciferYi** [apache/doris#13461]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

官网文档

### What's Wrong?

7.5 检查导入数据 执行下面的 SQL 语句检查导入的数据量上 上面的数据量是一致。文案错误

### What You Expected?

7.5 检查导入数据 执行下面的 SQL 语句检查导入的数据与上面的数据量是一致。

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dataalive** [comment]
方便的话可以提交个PR来修复，我看你选择了愿意提交PR~

**Comment by LemonLiTree** [comment]
https://github.com/apache/doris-website/pull/147
