### ISSUE TITLE
[Bug] Inconsistent behavior for string comparison in FE and BE

### ISSUE THREAD

**Issue by Gabriel39** [apache/doris#13573]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

In FE, when constant folding rule is applied, '汇总' is always less than '2022-01-01'.
![image](https://user-images.githubusercontent.com/37700562/197327290-0dafab90-054f-45ca-8ef9-4ac572641be1.png)

But when I send a sorting sql which runs a sorting in BE, the result is contrary.
![image](https://user-images.githubusercontent.com/37700562/197327389-08d37ab2-745d-4c60-9b2e-73ed9113cd16.png)

### What You Expected?

FE should keep the same logic as BE.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by nextdreamblue** [comment]
be中，字符串的比较是基于utf8的编码，按字节比较，字节是基于uint8
fe中，java基于signed byte
导致be中fe中，编码值对应的数字值不同导致排序不同
