### ISSUE TITLE
[Bug] CREATE STORAGE POLICY 提示语法错误

### ISSUE THREAD

**Issue by rc452860** [apache/doris#13570]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.2

### What's Wrong?

执行语句
```
CREATE STORAGE POLICY testPolicy
PROPERTIES(
  "storage_resource" = "s3",
  "cooldown_ttl" = "1d"
);
```
报错
```
Execution failed: Error Failed to execute sql: org.apache.doris.common.AnalysisException: errCode = 2, detailMessage = Syntax error in line 1: CREATE STORAGE POLICY testPolicy ^ Encountered: STORAGE Expected
```

### What You Expected?

按照文档所述应当正常执行。
https://doris.apache.org/zh-CN/docs/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-POLICY#example

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
Support it after 1.2 version

**Comment by dataalive** [comment]
the document has been wrongly put in version 1.1 , we will fix it . the feature is supported after version 1.2 like @stalary has said
