### ISSUE TITLE
[Bug] [Bug] Sql Exec Failed Raise IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Wilson-BT** [apache/doris#13640]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.3

### What's Wrong?

when i exec sql like this，IndexOutOfBoundsException will be raised. we don`t know why.
```
with b as (
select store_no,order_unit_no,item_no,max(item_name) as item_naa
		from retail_gms_ods.inventory
		group by store_no,order_unit_no,item_no
		order by store_no,order_unit_no,item_no
		limit 100
)
SELECT
	a.store_no,
	a.order_unit_no,
	a.item_code,
	a.item_name,
	a.item_no,
	a.color_no,
	a.sku_no,
	a.size_kind,
	a.balance_qty 
FROM
	retail_gms_ods.inventory a
	INNER JOIN 
	b 
	ON a.store_no = b.store_no 
	AND a.order_unit_no = b.order_unit_no 
	AND a.item_no = b.item_no
```
but we can explain it success.

### What You Expected?

Sql exec can be more robust.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dataalive** [comment]
this bug has been fixed by https://github.com/apache/doris/pull/13300 and pull the latest code of branch 1.1-lts to fix
