### ISSUE TITLE
[Feature]   SUBSTRING_INDEX() 不支持且无替换方案

### ISSUE THREAD

**Issue by stitch-k** [apache/doris#13666]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

  SUBSTRING_INDEX() 不支持且无替换方案

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dataalive** [comment]
https://doris.apache.org/docs/dev/sql-manual/sql-functions/string-functions/split_part is close to your needs.

**Comment by LOVEGISER** [comment]
1. use split("hello world", " ");  return:["hello", "world"]
2.use array_slice(["hello", "world"], 1, 1)

**Comment by wwek** [comment]
> 

这个只支持正取，不支持倒取

也就是MySQL中 SUBSTRING_INDEX() 除了支持用正数 正取， 还支持用负数 倒取
实现一个等效函数

**Comment by LOVEGISER** [comment]
你的需求是不是返回一个数据就行，但是要支持正取和倒取？

**Comment by LOVEGISER** [comment]
也就是split_part支持倒取就满足需求了？

**Comment by wwek** [comment]
> 也就是split_part支持倒取就满足需求了？

split_part 如果支持了用负数就行倒取字段是可以满足我的需求的。相关issue已提
https://github.com/apache/doris/issues/13712

**Comment by wwek** [comment]
SUBSTRING_INDEX() 是另外一个需求了，这个后面也可以支持下。
和MySQL中的等效实现，这样让用户平滑迁移
