### ISSUE TITLE
[Bug]  SQL : create table as select ,include decimal type throw SQLException

### ISSUE THREAD

**Issue by MRYOG** [apache/doris#13703]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.3-rc02

### What's Wrong?

table test_a column include type decimal , execute sql : create table as select * from test_a throw SQLException
Error Message:
Execution failed: Error Failed to execute sql: java.sql.SQLException: (conn=9720) errCode = 2, detailMessage = Unsupported type 'DECIMAL(26,9)' in create table as select statement

### What You Expected?

Fix

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LemonLiTree** [comment]
I tested OK!
`mysql> CREATE TABLE test_20221027(
    ->   `key2` BIGINT NULL COMMENT "key2",
    ->   `value1` decimal(26,9)  NULL COMMENT "value1"
    -> ) ENGINE = OLAP
    -> DUPLICATE KEY(`key2`)
    -> DISTRIBUTED BY HASH(`key2`) BUCKETS 1
    -> PROPERTIES (    
    ->     "replication_num"="1",
    ->     "storage_format" = "v2");
Query OK, 0 rows affected (0.01 sec)

mysql> insert into test_20221027(key2,value1) values (1,123456789.1234);
Query OK, 1 row affected (0.03 sec)
{'label':'insert_d26ecf9b25c74ab8-98d31c7576cab960', 'status':'VISIBLE', 'txnId':'30609'}

mysql> create table test_20221027_1 
    -> PROPERTIES (    
    ->     "replication_num"="1",
    ->     "storage_format" = "v2") 
    -> as select * from test_20221027;
Query OK, 1 row affected (0.05 sec)
{'label':'insert_3799c8e0e6aa4461-ba1c0f5e297923bc', 'status':'VISIBLE', 'txnId':'30612'}

mysql> select * from test_20221027_1;
+------+----------------+
| key2 | value1         |
+------+----------------+
|    1 | 123456789.1234 |
+------+----------------+
1 row in set (0.01 sec)`

**Comment by MRYOG** [comment]
I check my test environment version is 1.1.2-rc2 , upgrade 1.1.3-rc02 is ok
