### ISSUE TITLE
[Feature] split_part函数支持用负数倒取字段

### ISSUE THREAD

**Issue by wwek** [apache/doris#13712]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

VARCHAR split party (VARCHAR content, VARCHAR delimiter, INT field)
当前第三个参数 不支持使用负数倒取第几个字段，需要支持

https://doris.apache.org/docs/dev/sql-manual/sql-functions/string-functions/split_part?_highlight=split_part

### Use case

期望
select split_part("hello world", " ", -1);
输出： world

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Yulei-Yang** [comment]
try this https://github.com/apache/doris/pull/13914

**Comment by wwek** [comment]
> try this #13914

tks
