### ISSUE TITLE
[Bug] BE node dead , core dump message find error path

### ISSUE THREAD

**Issue by MRYOG** [apache/doris#13814]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.3-rc02

### What's Wrong?

Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/opt/soft/doris-palo/be/lib/doris_be'.
Program terminated with signal 6, Aborted.
#0  0x00002aadd0415387 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-325.el7_9.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-51.el7_9.x86_64 libcom_err-1.42.9-19.el7.x86_64 libgcc-4.8.5-44.el7.x86_64 libselinux-2.5-15.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64 libtool-ltdl-2.4.2-22.el7_3.x86_64 mysql-connector-odbc-8.0.27-1.el6.x86_64 openssl-libs-1.0.2k-24.el7_9.x86_64 pcre-8.32-17.el7.x86_64 unixODBC-2.3.1-14.el7.x86_64 zlib-1.2.7-19.el7_9.x86_64
(gdb)
(gdb) bt
#0  0x00002aadd0415387 in raise () from /lib64/libc.so.6
#1  0x00002aadd0416a78 in abort () from /lib64/libc.so.6
#2  0x0000557b09f72870 in ?? ()
#3  0x0000557b0c32962d in google::LogMessage::Fail() ()
#4  0x0000557b0c32bb69 in google::LogMessage::SendToLog() ()
#5  0x0000557b0c329196 in google::LogMessage::Flush() ()
#6  0x0000557b0c32c1d9 in google::LogMessageFatal::~LogMessageFatal() ()
#7  0x0000557b0adaa7a2 in doris::OlapScanNode::transfer_thread(doris::RuntimeState*)
    () at /mnt/disk2/ygl/installs/ldbtools/include/c++/11/ext/new_allocator.h:89
#8  0x0000557b0e4112c0 in execute_native_thread_routine ()
#9  0x00002aadd07b4ea5 in start_thread () from /lib64/libpthread.so.0
#10 0x00002aadd04ddb0d in clone () from /lib64/libc.so.6
(gdb) f2
Undefined command: "f2".  Try "help".
(gdb) f 2
#2  0x0000557b09f72870 in ?? ()
    at /mnt/disk2/apache-doris/thirdparty/installed/include/boost/exception/exception.hpp:232
232	/mnt/disk2/apache-doris/thirdparty/installed/include/boost/exception/exception.hpp: 没有那个文件或目录.
(gdb) f 0
#0  0x00002aadd0415387 in raise () from /lib64/libc.so.6
(gdb) f 1
#1  0x00002aadd0416a78 in abort () from /lib64/libc.so.6
(gdb) f 3
#3  0x0000557b0c32962d in google::LogMessage::Fail() ()
(gdb) f 4
#4  0x0000557b0c32bb69 in google::LogMessage::SendToLog() ()
(gdb) f 5
#5  0x0000557b0c329196 in google::LogMessage::Flush() ()
(gdb) f 6
#6  0x0000557b0c32c1d9 in google::LogMessageFatal::~LogMessageFatal() ()
(gdb) f 7
#7  0x0000557b0adaa7a2 in doris::OlapScanNode::transfer_thread(doris::RuntimeState*)
    () at /mnt/disk2/ygl/installs/ldbtools/include/c++/11/ext/new_allocator.h:89
89	/mnt/disk2/ygl/installs/ldbtools/include/c++/11/ext/new_allocator.h: 没有那个文件或目录.
(gdb) f 8
#8  0x0000557b0e4112c0 in execute_native_thread_routine ()
(gdb) f 9
#9  0x00002aadd07b4ea5 in start_thread () from /lib64/libpthread.so.0
(gdb) f 10
#10 0x00002aadd04ddb0d in clone () from /lib64/libc.so.6

![image](https://user-images.githubusercontent.com/10381662/198953241-3b8b7bf9-06fc-4935-a91a-b93f99224b08.png)

### What You Expected?

want know why check this path: /mnt/disk2/apache-doris/thirdparty/installed/include/boost/exception/exception.hpp:232 , and how to fix it

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by MRYOG** [comment]
> Is there `Failed to assign scanner task to thread pool` in your be.INFO?

Yes, the last log is 
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/10381662/199033507-fbd7d02f-c778-4c5a-83bc-7e04ade63cb1.png">

**Comment by zenyanggongmian1995** [comment]
same questiion: Failed to assign scanner task to thread pool   how to fix it?

**Comment by dataalive** [comment]
https://github.com/apache/doris/pull/14409
