### ISSUE TITLE
[Enhancement] `forEach()` replace `stream().forEach()`

### ISSUE THREAD

**Issue by jackwener** [apache/doris#13889]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Please use `IDEA`, it will hint we use `forEach()`  replace `stream().forEach()` 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Pace2Car** [comment]
I will work on it, please assignee it to me.
