### ISSUE TITLE
[Bug] ARRAY<T> does not work

### ISSUE THREAD

**Issue by Raven888888** [apache/doris#13952]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris 1.1.3 (1 BE + 1 FE)
Mysql mariadb-client 10.6

### What's Wrong?

I am following this [guide](https://doris.apache.org/docs/sql-manual/sql-reference/Data-Types/ARRAY/), but unable to create a table with ARRAY type.

Checked that `enable_array_type` is already `true`.
![image](https://user-images.githubusercontent.com/58241952/199705365-4767c7c3-71ff-402f-83b0-7597af379de2.png)

Hit unsupported data type when creating the table.
![image](https://user-images.githubusercontent.com/58241952/199705830-e21e58c8-be6e-4635-a954-b572b4113884.png)

### What You Expected?

Able to create the table with ARRAY column, just like the guide.

### How to Reproduce?

Follow the setup and guide.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zy-kkk** [comment]
Hello, the array type was not supported in version 1.1.x. It will be supported in the upcoming 1.2 release

**Comment by Raven888888** [comment]
Got it, thanks! @zy-kkk
