### ISSUE TITLE
[Bug] bitmap_subset_in_range function when there is only one data in the bitmap, the function get the sub-bitmap is null, not itself.

### ISSUE THREAD

**Issue by siriume** [apache/doris#13964]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master-f49a0da

### What's Wrong?

run sql like this:
```sql
select bitmap_to_string(bitmap_subset_in_range(bitmap_from_string('20221103'), 0, 20221104)) date_list_bitmap;
```
result is 0;

### What You Expected?

result is 20221103;

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhangstar333** [comment]
fixed:https://github.com/apache/doris/pull/13978
