### ISSUE TITLE
[Bug] sub_bitmap/bitmap_subset_limit return null when the bitmap count is 1

### ISSUE THREAD

**Issue by zh0122** [apache/doris#13968]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.2

### What's Wrong?

sub_bitmap/bitmap_subset_limit return null when the bitmap count is 1

```sql
# Expect: 1,2,3 Result: 1,2,3
select bitmap_to_string(sub_bitmap(bitmap_from_string('1,2,3,4,5'), 0, 3)) value;  

# Expect：1， Result： null
select bitmap_to_string(sub_bitmap(bitmap_from_string('1'), 0, 3)) value;  
```

### What You Expected?

Return the correct sub bitmap when the coutn of src bitmap is 1.

### How to Reproduce?

```sql
# Expect: 1,2,3 Result: 1,2,3
select bitmap_to_string(sub_bitmap(bitmap_from_string('1,2,3,4,5'), 0, 3)) value;  

# Expect：1， Result： null
select bitmap_to_string(sub_bitmap(bitmap_from_string('1'), 0, 3)) value;  
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhangstar333** [comment]
fixed:https://github.com/apache/doris/pull/13978
