### ISSUE TITLE
WIDTH_BUCKET function support

### ISSUE THREAD

**Issue by vkingnew** [apache/doris#13981]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

> function **width_bucket** had supported by oracle and postgresql,hive,sparksql,impala,snowflake and  databricks.
please add the same name function and have the same feature.
please refer to:
https://www.postgresql.org/docs/15/functions-math.html
https://docs.snowflake.com/en/sql-reference/functions/width_bucket.html

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Yukang-Lian** [comment]
Yeah, thanks for your advice. We will support it in the future. I think maybe in one month or two.
