### ISSUE TITLE
[Feature] group_uniq_array function

### ISSUE THREAD

**Issue by Yukang-Lian** [apache/doris#13982]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

**syntax**: groupUniqArray(x) or groupUniqArray(max_size)(x)

**function**: Creates an array from different argument values.

```sql
SELECT *
FROM arrays_test
┌─s───────┬─arr─────┐
│ alex    │ [1,2]   │
│ hello   │ [1,2]   │
│ World   │ [3,4,5] │
│ Goodbye │ []      │
└─────────┴─────────┘

SELECT groupUniqArray(arr) from arrays_test
┌─groupUniqArray(arr)─┐
│ [[],[1,2],[3,4,5]]  │
└─────────────────────┘

```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TangSiyang2001** [comment]
Apply for a try.

**Comment by TangSiyang2001** [comment]
When doing this job,I found that this function is quite similar with `collect_set`, except for the 'max_size ' limit.The sibling function `group_array` seems also in this situation.Shall we upgrade the `collect_set` and `collect_list`  to support the same semantics of the above two,or just simply create new functions as `group_uniq_array`  and  `group_array` ?
