### ISSUE TITLE
以小时自动创建分区，分区创建的时间越来越迟，最后可能第一个按小时的分区不会创建导致数据丢失

### ISSUE THREAD

**Issue by sky1229329146** [apache/doris#13999]
1.以小时自动创建分区，第一个分区和第二个分区的创建时间并不是严格的相差1小时，而是比1小时多几秒
2.一天有24小时，则最后一个分区的创建时间就会延迟数十秒才创建
3.到第二天系统再自动创建分区时，第一个分区就明显比第一次创建延迟了很久才创建

放图报错，暂时无法放图
6号创建的分区比3号创建的分区完了30多秒

**Comment by nextdreamblue** [comment]
目前动态分区的后台调度周期是由 fe的 dynamic_partition_check_interval_seconds 参数来控制的，每sleep这么多秒就会进入下一次判断，而每次执行添加新partition，删除过期partition的耗时，就导致下次任务的调度会有顺延才会再执行

其实延伸一下，这个地方会存在一个调度不及时的问题。当前dynamic_partition_check_interval_seconds参数默值是600秒，10分钟才调度一次动态分区的检查和添加（如果需要），如果一个fe调度任务在每小时的09、19、29、39、49、59分去执行，这就存在一种情况：当到了需要添加新分区的整小时时，比如按hour的0分时，按天的0点0分时，新分区的添加是会延迟9分钟才执行的，这就有可能导致这段没有及时添加新分区的时间里，新数据的插入因为没有对应的分区，而会丢失的，但是这种插入是不会报错的。

**Comment by sky1229329146** [comment]
好的，谢谢解答疑惑
