### ISSUE TITLE
[Bug] grouping sets + case when or coalesce get wrong result 

### ISSUE THREAD

**Issue by htyoung** [apache/doris#14043]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

version：1.1.3-rc02

### What's Wrong?

Test SQL: 
select 
	coalesce(col1,"all") as `col1` 
	,count(*) as `cnt`
from (
	select null as col1
	union all
	select "a" as col1
) t
group by
	grouping sets
	(
		(col1)
		,()
	)
;

### What You Expected?

The expected result is:

col1  cnt
all     2
all     1
a       1

but the actual result is :
col1  cnt
NULL     2
all     1
a       1

<img width="470" alt="image" src="https://user-images.githubusercontent.com/9734567/200319817-402a8e46-f3e5-480f-a84c-3bdf336fea10.png">

so, I test the similar sql with hive, mysql(8.0+ and 5.7+) also get the expected result.
<img width="949" alt="image" src="https://user-images.githubusercontent.com/9734567/200318848-4cd3f10e-fbba-47ce-92bf-925b5c4c2732.png">
<img width="402" alt="image" src="https://user-images.githubusercontent.com/9734567/200319156-df0e4dec-ce61-48f7-a48f-9cfeed6c9fa5.png">
![image](https://user-images.githubusercontent.com/9734567/200319236-051a80b9-d498-4890-b731-385ee45a9159.png)

### How to Reproduce?

just run the test sql directly

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yiguolei** [comment]
It will be fixed in 1.2 and 1.1.5
