### ISSUE TITLE
[Bug]  After the ctas statement is executed the query has no result

### ISSUE THREAD

**Issue by smallhibiscus** [apache/doris#14237]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.4

### What's Wrong?

execute the following sql statement:

`
  create table tmp_2 as  select 1 as uid,from_unixtime(1668156059,"%Y-%m-%d") as dt; `
`
  select * from tmp_2;
`

the result is empty.
set insert strict mode, insert data will report an error.

but after converting dt using cast, the result is normal.
example:

`create table tmp_2 as  select 1 as uid,cast(from_unixtime(1668156059,"%Y-%m-%d") as text) as dt; `

### What You Expected?

The automatic type can be judged without conversion.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by nextdreamblue** [comment]
maybe fix on https://github.com/apache/doris/pull/13906
or https://github.com/apache/doris/pull/14090

**Comment by smallhibiscus** [comment]
> 

thx，https://github.com/apache/doris/pull/13906 has fixed ，can u pick it to 1.1-lts ?

**Comment by nextdreamblue** [comment]
> > 
> 
> thx，#13906 has fixed ，can u pick it to 1.1-lts ?

done
