### ISSUE TITLE
[Bug] intersect_count function bug

### ISSUE THREAD

**Issue by ZuseRebirth** [apache/doris#14256]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.2-rc05-a8323dae4

### What's Wrong?

return the wrong result of the query which use the function 【intersect_count】
![image](https://user-images.githubusercontent.com/96508101/201624720-ca7d5599-6814-456a-990e-042e0854f4d6.png)
![image](https://user-images.githubusercontent.com/96508101/201624901-0c660aa0-8db5-4027-ae55-22e477ad2ea2.png)
as you can see,the hdid_dict_value='6674758' on '2022-11-06' and '2022-11-07' has the record, so the result has be 1,not 0

### What You Expected?

function 【intersect_count】return the right result

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hf200012** [comment]
https://github.com/apache/doris/pull/12980

**Comment by ZuseRebirth** [comment]
doris update to 1.1.4 ,it has been fixed
