### ISSUE TITLE
[Feature] add index pattern (doris on es)

### ISSUE THREAD

**Issue by Zijun-Git** [apache/doris#14310]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Doris On ES 创建外表配置中，index字段支持索引pattern发现，类似于kibana配置索引的pattern。
例如在es中并不是固定索引，通常为按天划分，比如test-2022/11/16、test-2022/11/17，如果index配置参数支持test-*，可以自动发现所有索引

### Use case

test-*
test-2022/11/16、test-2022/11/17、test-2022/11/18

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
Currently, it can be implemented through the alias, does it meet your needs?

**Comment by Zijun-Git** [comment]
但是别名是指向已存在的单个或者多个索引，更像是一个索引集，如果未创建的索引，如何自动发现呢？例如test-2022/11/16手动设置别名，但是test-2022/11/17还未创建这种是不是就需要再重新更新别名？因此我觉得类似于kibana这种索引pattern能够去自动发现索引，并且无缝连接查询是不是更好呢？比如设置patter test-*，那么后续test-yyyy/MM/dd的所有索引都能够自动发现，这样是不是更合适？

**Comment by stalary** [comment]
> 但是别名是指向已存在的单个或者多个索引，更像是一个索引集，如果未创建的索引，如何自动发现呢？例如test-2022/11/16手动设置别名，但是test-2022/11/17还未创建这种是不是就需要再重新更新别名？因此我觉得类似于kibana这种索引pattern能够去自动发现索引，并且无缝连接查询是不是更好呢？比如设置patter test-*，那么后续test-yyyy/MM/dd的所有索引都能够自动发现，这样是不是更合适？

This meet a question, How do we resolve the problem of match index mapping inconsistencies?

**Comment by Zijun-Git** [comment]
目前看起来只能通过alias的方式去解决。另外请问对于es的其他类型的字段（比如boolean类型）是否有计划去增加在doris的映射

**Comment by stalary** [comment]
> 目前看起来只能通过alias的方式去解决。另外请问对于es的其他类型的字段（比如boolean类型）是否有计划去增加在doris的映射

Currently support type 'https://doris.apache.org/zh-CN/docs/dev/ecosystem/external-table/multi-catalog#elasticsearch',
only array not support~
