### ISSUE TITLE
[Bug] Agg Regression Test failed in muti distinct

### ISSUE THREAD

**Issue by HappenLee** [apache/doris#14571]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

```
select count(distinct c_date) from datetype

8
```

```
select count(distinct c_bigint), count(distinct c_date) from datetype

9 9
```

### What You Expected?

```
select count(distinct c_bigint), count(distinct c_date) from datetype

9 8
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by littleforce163** [comment]
Is it still a problem? It is serious that with wrong result.
