### ISSUE TITLE
[Bug] 'SHOW ROLES' statement does not display resource privilege granted to roles in master branch

### ISSUE THREAD

**Issue by xutaoustc** [apache/doris#14812]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

1. GRANT USAGE_PRIV ON RESOURCE * TO ROLE 'my_role';
    GRANT USAGE_PRIV ON RESOURCE 'spark_resource' TO ROLE 'my_role';
2. SHOW ROLES
It does not display spark_resource in the output

### What You Expected?

There should be Usage_priv in GlobalPrivs column, and spark_resource: Usage_priv in ResourcePrivs column.

### How to Reproduce?

1. GRANT USAGE_PRIV ON RESOURCE * TO ROLE 'my_role';
    GRANT USAGE_PRIV ON RESOURCE 'spark_resource' TO ROLE 'my_role';
2. SHOW ROLES

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yuanyuan8983** [comment]
Hello, you can add my WeChat. Let's take a look at this problem. My WeChat is cyllyy810222.
