### ISSUE TITLE
[Bug] [daily] decimal \ right semi join \right anti join cases bug

### ISSUE THREAD

**Issue by LizZhang315** [apache/doris#14810]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-0.0.0-trunk-36737fe

### What's Wrong?

case 1：
SQL: select 1, 2  union select 1.01, 2.0 union (select 0.0001, 0.0000001) order by 1, 2

Bug: Doris result is different from mysql result.

mysql result:
+--------+-----------+
| 1      | 2         |
+--------+-----------+
| 0.0001 | 0.0000001 |
| 1.0000 | 2.0000000 |
| 1.0100 | 2.0000000 |
+--------+-----------+

doris result:
+------+-----------+
| 1    | 2         |
+------+-----------+
|    0 | 0.0000001 |
|    1 | 2.0000000 |
|    1 | 2.0000000 |
+------+-----------+

case 2:
SQL1:  select b.k1, b.k2, b.k3, b.k4, b.k5 from baseall a right anti join test b on a.k1 = b.k1 or a.k2 = b.k2 where b.k2 > 0 and b.k3 != 0 and b.k6 > "000" order by 1, 2, 3, 4, 5 limit 65535;
SQL2: select b.k1, b.k2, b.k3, b.k4, b.k5 from baseall a right semi join test b on a.k1 = b.k1 or a.k2 = b.k2 where b.k2 > 0 and b.k3 != 0 and b.k6 > "000" order by 1, 2, 3, 4, 5 limit 65535;

Bug: The results of each SQL query are different.

table test row count 60015, table schema :
+-------+--------------+------+-------+---------+-------+
| Field | Type         | Null | Key   | Default | Extra |
+-------+--------------+------+-------+---------+-------+
| k1    | TINYINT      | Yes  | true  | NULL    |       |
| k2    | SMALLINT     | Yes  | true  | NULL    |       |
| k3    | INT          | Yes  | true  | NULL    |       |
| k4    | BIGINT       | Yes  | true  | NULL    |       |
| k5    | DECIMAL(9,3) | Yes  | true  | NULL    |       |
| k6    | CHAR(5)      | Yes  | true  | NULL    |       |
| k10   | DATE         | Yes  | true  | NULL    |       |
| k11   | DATETIME     | Yes  | true  | NULL    |       |
| k7    | VARCHAR(20)  | Yes  | true  | NULL    |       |
| k8    | DOUBLE       | Yes  | false | NULL    | MAX   |
| k9    | FLOAT        | Yes  | false | NULL    | SUM   |
+-------+--------------+------+-------+---------+-------+

table baseall row count 15, table schema:
+-------+--------------+------+-----+---------+-------+
| Field | Type         | Null | Key | Default | Extra |
+-------+--------------+------+-----+---------+-------+
| k1    | tinyint(4)   | YES  |     | NULL    |       |
| k2    | smallint(6)  | YES  |     | NULL    |       |
| k3    | int(11)      | YES  |     | NULL    |       |
| k4    | bigint(20)   | YES  |     | NULL    |       |
| k5    | decimal(9,3) | YES  |     | NULL    |       |
| k6    | char(5)      | YES  |     | NULL    |       |
| k10   | date         | YES  |     | NULL    |       |
| k11   | datetime     | YES  |     | NULL    |       |
| k7    | varchar(20)  | YES  |     | NULL    |       |
| k8    | double       | YES  |     | NULL    |       |
| k9    | float        | YES  |     | NULL    |       |
+-------+--------------+------+-----+---------+-------+

case 3:
SQL： select count(*) from ( select a.k1 as a1, a.k2 as a2, a.k3 as a3, b.k1 as b1, b.k2 as b2, b.k3 as b3 from test a left outer join baseall b on a.k1 < b.k1 or a.k2 > b.k2 where a.k2 >0 and b.k3!=0 and a.k6>"000") t;

Bug: The query result is different in enable_vectorized mode and disable_vectorized mode.

### What You Expected?
In case 1, doris result is same with mysql result.
In case 2, the results of each SQL query are the same.
In case 3, the result of enable_vectorized mode and disable_vectorized mode are the same.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhangy5** [comment]
In enable_vectorized mode, case 3 result is ok now.
