### ISSUE TITLE
kafka data load :the length of input is too long than schema

### ISSUE THREAD

**Issue by zhouhoo** [apache/doris#14936]
when I use kafka routine load to load data into doris , I got the error:
`Reason: the length of input is too long than schema. column_name: test_id; input str: [{"test_id":"1"] schema length: 4; actual length: 14; . src line [];`
the table in doris is as bellow:
`CREATE TABLE `gxy_test` (
  `test_id` char(4) NOT NULL COMMENT "唯一主键",
  `create_time` datetime NULL COMMENT "创建时间",
  `name` char(50) NULL COMMENT "名字",
  `desc` varchar(150) NULL COMMENT "描述",
  `is_deleted` tinyint NULL COMMENT "是否删除",
  `update_time` datetime NULL COMMENT "更新时间"
) ENGINE=OLAP
UNIQUE KEY(`test_id`, `create_time`)
COMMENT "测试"
PARTITION BY RANGE(`create_time`)()
DISTRIBUTED BY HASH(`test_id`) BUCKETS 20
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "MONTH",
"dynamic_partition.time_zone" = "Asia/Shanghai",
"dynamic_partition.start" = "-60",
"dynamic_partition.end" = "2",
"dynamic_partition.prefix" = "p",
"dynamic_partition.replication_allocation" = "tag.location.default: 1",
"dynamic_partition.buckets" = "12",
"dynamic_partition.create_history_partition" = "true",
"dynamic_partition.history_partition_num" = "12",
"dynamic_partition.hot_partition_num" = "1",
"dynamic_partition.reserved_history_periods" = "NULL",
"dynamic_partition.start_day_of_month" = "1",
"in_memory" = "false",
"storage_format" = "V2"
);`

the data in kafka is as bellow:
`{"test_id":"1"$$"name":"小李"$$"desc":"这是名字"$$"create_time":"2022-11-02 09:00:09"$$"is_deleted":"1"$$"update_time":"2022-11-02 09:00:09"}`

so the lenght char '1' is 1 not 14 ! why doris give wrong lenght? 

my doris version is 1.1.1 and kafka version is 2.13-3.3.1

**Comment by yuanyuan8983** [comment]
Hello, this problem is caused by the fact that the length of your data type is less than the length of the imported data. You can increase the data type of the corresponding field and then import it. You can add my WeChat account: cyllyy810222
