### ISSUE TITLE
[Bug] [daily]pymysql execute lost connection when sql failed

### ISSUE THREAD

**Issue by zhangy5** [apache/doris#14937]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

![image](https://user-images.githubusercontent.com/10826066/206408797-01c385b2-1420-4d7e-ba0a-74cb9c328f98.png)

### What You Expected?

![image](https://user-images.githubusercontent.com/10826066/206408952-3a5a25a0-e063-4d14-9ab9-f2fe4085c6e8.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dinggege1024** [comment]
LGTM
