### ISSUE TITLE
[Doc] optimize the BE config document 

### ISSUE THREAD

**Issue by LemonLiTree** [apache/doris#14943]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

I find that there are too many BE configuration items and it is difficult to find them. I think we should optimize the structure of the configuration item document

### Solution

I summarized several categories of configuration items and sorted all configuration items neatly
1、Service
2、Query
3、Compaction
4、Load
5、Thread
6、Memory
7、Storage
8、Log
9、Else

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by freemandealer** [comment]
maybe 'Misc' instead of 'Else' ?
