### ISSUE TITLE
[Feature] flinksql增量读取doris

### ISSUE THREAD

**Issue by ynzzxc** [apache/doris#14968]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

近实时场景，不想维护hudi，业务数据同步到doris，flinksql读取doris历史及增量数据，写入Doris或mysql

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
What is your design proposal?
