### ISSUE TITLE
[Feature] Support function `roundBankers`

### ISSUE THREAD

**Issue by Gabriel39** [apache/doris#14970]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

ClickHouse supports function `roundBankers` but Doris doesn't support now

If you are interested in it, you could leave a comment for me.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by maochongxin** [comment]
Can I try it?

**Comment by Gabriel39** [comment]
> Can I try it?

Sure. And feel free to discuss with me if you have any problems

**Comment by maochongxin** [comment]
> > Can I try it?
> 
> Sure. And feel free to discuss with me if you have any problems

Thanks, please assign to me

**Comment by Gabriel39** [comment]
> > > Can I try it?
> > 
> > 
> > Sure. And feel free to discuss with me if you have any problems
> 
> Thanks, please assign to me

Done. Look forward to your PR :)
