### ISSUE TITLE
[Bug] BE 1.2.0 unable to start due to "Failed to initialize JNI: Failed to find the library libjvm.so"

### ISSUE THREAD

**Issue by gojumprope** [apache/doris#15039]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

apache doris be version 1.2.0

java version
openjdk version "1.8.0_352"
OpenJDK Runtime Environment (build 1.8.0_352-8u352-ga-1~20.04-b08)
OpenJDK 64-Bit Server VM (build 25.352-b08, mixed mode)

### What's Wrong?

unable to start be server

ubuntu@dorisbe2:~/doris/apache-doris-be-1.2.0-bin-x86_64$ sudo bin/start_be.sh
WARNING: Logging before InitGoogleLogging() is written to STDERR
W1213 10:45:01.800364 67632 doris_main.cpp:382] Failed to initialize JNI: Failed to find the library libjvm.so.

### What You Expected?

able to start backend server

### How to Reproduce?

download be 1.2.0 in ubuntu server
https://www.apache.org/dyn/mirrors/mirrors.cgi?action=download&filename=doris/1.2/1.2.0-rc04/apache-doris-be-1.2.0-bin-x86_64.tar.xz

put java udf jar file in doris/be/lib

sudo be/bin/start_be.sh

WARNING: Logging before InitGoogleLogging() is written to STDERR
W1213 10:48:04.386593 69801 doris_main.cpp:382] Failed to initialize JNI: Failed to find the library libjvm.so.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Wilson-BT** [comment]
you should add ```export JAVA_HOME = xxx``` Path to start_be.sh.

**Comment by Data-bytes305** [comment]
@Wilson-BT 
Already added the JAVA variable as you suggested，problem still not resolved
os: Ubuntu20.04
doris: doris -1.2
java: java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode).

**Comment by Wilson-BT** [comment]
> @Wilson-BT Already added the JAVA variable as you suggested，problem still not resolved os: Ubuntu20.04 doris: doris -1.2 java: java version "1.8.0_201" Java(TM) SE Runtime Environment (build 1.8.0_201-b09) Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode).

but，i have the same problem，and had solved by it.

**Comment by Wilson-BT** [comment]
Answer had been given you from this pr .https://github.com/apache/doris/pull/15045

**Comment by gojumprope** [comment]
> 

thank you. the problem is solved
