### ISSUE TITLE
doris表新增字段后一直不显示新增的字段.

### ISSUE THREAD

**Issue by caomingjie-code** [apache/doris#15122]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

5.1.0

### What's Wrong?

doris表新增字段后一直不显示新增的字段.
![图片](https://user-images.githubusercontent.com/63859342/208004866-496016d3-b33a-47a4-95c0-f7cf8f57e7a0.png)

### What You Expected?

可以新增字段。现在新增字段如下：
1064 - errCode = 2, detailMessage = Table[ad_emi_game_data]'s state is not NORMAL. Do not allow doing ALTER ops

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
Alter table is a async operation.
