### ISSUE TITLE
stream load写入默认值问题

### ISSUE THREAD

**Issue by yunfeng79** [apache/doris#15279]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris 1.2版本
表中两个字段
op_tag1` tinyint(4) REPLACE_IF_NOT_NULL NULL DEFAULT "1" COMMENT "删除标记（1:INSERT,UPDATE 2:DELETE）"
`create_time1` datetime MIN NULL DEFAULT CURRENT_TIMESTAMP COMMENT "创建时间"。
通过stream load导入
![image](https://user-images.githubusercontent.com/21050635/209079193-c27e90bf-2cf2-4a8c-b21c-9f54ade7818a.png)

正常应该是写入默认值

### What's Wrong?

![image](https://user-images.githubusercontent.com/21050635/209079266-1f08b6dd-ea37-41e3-a6c7-b4713781a8b4.png)

### What You Expected?

![image](https://user-images.githubusercontent.com/21050635/209079294-1c3afe4c-dc3e-4bc9-978b-b82cf19a59f9.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
You use `REPLACE_IF_NOT_NULL`, you can try to use `REPLACE`.
