### ISSUE TITLE
[stream laod result stattus is success,but when I query data immediately,sometimes not find]

### ISSUE THREAD

**Issue by huanccwang** [apache/doris#15371]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.4

### What's Wrong?

stream laod result stattus is success,but when I query data immediately,sometimes not find

### What You Expected?

please tell me this is doris bug or my code bug?Anybody had met this question? 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
This is a problem if your read and write connections are not on the same fe node.
