### ISSUE TITLE
[Bug] when where clause column type is bigint , value equal faild

### ISSUE THREAD

**Issue by MRYOG** [apache/doris#15472]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.5-rc02

### What's Wrong?

TABLE ：
CREATE TABLE `test_bigint` (
  `day_id` int(11) NOT NULL COMMENT "分区字段,如:20211001",
  `device_id` varchar(255) NULL COMMENT "ID",
  `analysys_id` bigint(20) NULL COMMENT "ID"
) ENGINE = OLAP DUPLICATE KEY(`day_id`, `device_id`) 
COMMENT "OLAP" DISTRIBUTED BY HASH(`day_id`) BUCKETS 1 PROPERTIES (
  "replication_allocation" = "tag.location.default: 1",
  "in_memory" = "false",
  "storage_format" = "V2"
);
SQL : 
![image](https://user-images.githubusercontent.com/10381662/209916345-e3fd8f6c-d00e-4eca-85bb-beb8553b3a68.png)
![image](https://user-images.githubusercontent.com/10381662/209916364-6aeffa16-524d-41a3-97ed-4380d98d9b04.png)
![image](https://user-images.githubusercontent.com/10381662/209916391-8b4859f7-377e-4222-a1d4-6b30f93e0854.png)

### What You Expected?

Fix it

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yuxuan-luo** [comment]
<img width="853" alt="image" src="https://user-images.githubusercontent.com/119841515/209919717-023ca7b2-5eed-4972-b4de-128afb300ce6.png">
我这边发现并无异常

**Comment by MRYOG** [comment]
sorry , the bug is doris web only show 28462147635660600 , realy value is 2846214763566060097

**Comment by MRYOG** [comment]
![image](https://user-images.githubusercontent.com/10381662/209930429-da764161-e6e4-4563-8807-d2f11300b311.png)

**Comment by MRYOG** [comment]
same problem : https://github.com/apache/doris/issues/10313
