### ISSUE TITLE
[Bug] mapping not found for the ES Cluster

### ISSUE THREAD

**Issue by df007df** [apache/doris#15485]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris: doris-1.2.0-rc04

es: 8.3.3

### What's Wrong?

配置ES链接后，查询失败。错误内容

创建语句
```

CREATE EXTERNAL TABLE `es_index_products_v4` (
  
	`_id` varchar COMMENT "_id",
  `id` bigint(20) COMMENT "id",
	`code` varchar(20) COMMENT "code",
	
	`source` varchar(20) COMMENT "source",
	`platform` varchar(20) COMMENT "platform",
	
	`status` varchar(20) COMMENT "status",
	
  `gmtCreate` datetime COMMENT "gmtCreate",
	`gmtModified` datetime COMMENT "gmtModified"
	
)
ENGINE=ELASTICSEARCH 
PROPERTIES (
"hosts" = "https://xxx:x9200",
"index" = "products_v4_1",
"user" = "xxxxx",
"password" = "xxxxxxxxxx",
"enable_docvalue_scan" = "true",
"http_ssl_enabled" = "true",
"nodes_discovery" = "false"
);

```

be 的日志内容

![image](https://user-images.githubusercontent.com/2849902/209953313-ac35e8f1-25a1-4f8f-b948-03648a204104.png)

使用此地址是可以获取到JSON内容的；
![image](https://user-images.githubusercontent.com/2849902/209953922-413bfa11-0a96-427c-8334-0cc19fdb5152.png)

实际请求的内容
![image](https://user-images.githubusercontent.com/2849902/209953983-16048845-dd39-425b-b43e-a86342b8d1b1.png)

### What You Expected?

调研中，希望尽快好。
doris 1.1.0 版本是可以的

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
Please provide products_v4_1/_mapping full info.

**Comment by 804e** [comment]
doris不支持获取元数据字段_id吗？
建表语句
```
CREATE EXTERNAL TABLE `table_1` (
  `_id` varchar,
  `subjectId` text NULL
) ENGINE=ELASTICSEARCH
PROPERTIES (
"hosts" = "http://elasticsearch:9200",
"user" = "elastic",
"password" = "123456",
"index" = "table_1",
"enable_docvalue_scan" = "true",
"max_docvalue_fields" = "20",
"enable_keyword_sniff" = "true",
"nodes_discovery" = "false",
"http_ssl_enabled" = "false"
);
```
日志报错
```
2023-01-05 17:00:09,511 WARN (es repository|12) [EsTable.syncTableMetaData():308] Exception happens when fetch index [table_1] meta data from remote es cluster.table id: 11005, err: 
org.apache.doris.external.elasticsearch.DorisEsException: index[table_1] type[{"table_1":{"mappings":{"properties":{"subjectId":{"type":"keyword"}}}}}] mapping not found column_id for the ES Cluster
```
但是文档说是支持获取_id的，是不是哪里有误？
https://doris.apache.org/zh-CN/docs/dev/ecosystem/external-table/doris-on-es#%E8%8E%B7%E5%8F%96es%E5%85%83%E6%95%B0%E6%8D%AE%E5%AD%97%E6%AE%B5_id

**Comment by stalary** [comment]
> doris不支持获取元数据字段_id吗？ 建表语句
> 
> ```
> CREATE EXTERNAL TABLE `table_1` (
>   `_id` varchar,
>   `subjectId` text NULL
> ) ENGINE=ELASTICSEARCH
> PROPERTIES (
> "hosts" = "http://elasticsearch:9200",
> "user" = "elastic",
> "password" = "123456",
> "index" = "table_1",
> "enable_docvalue_scan" = "true",
> "max_docvalue_fields" = "20",
> "enable_keyword_sniff" = "true",
> "nodes_discovery" = "false",
> "http_ssl_enabled" = "false"
> );
> ```
> 
> 日志报错
> 
> ```
> 2023-01-05 17:00:09,511 WARN (es repository|12) [EsTable.syncTableMetaData():308] Exception happens when fetch index [table_1] meta data from remote es cluster.table id: 11005, err: 
> org.apache.doris.external.elasticsearch.DorisEsException: index[table_1] type[{"table_1":{"mappings":{"properties":{"subjectId":{"type":"keyword"}}}}}] mapping not found column_id for the ES Cluster
> ```
> 
> 但是文档说是支持获取_id的，是不是哪里有误？ https://doris.apache.org/zh-CN/docs/dev/ecosystem/external-table/doris-on-es#%E8%8E%B7%E5%8F%96es%E5%85%83%E6%95%B0%E6%8D%AE%E5%AD%97%E6%AE%B5_id

I'll take a look at it for you when I'm idle.

**Comment by stalary** [comment]
> doris不支持获取元数据字段_id吗？ 建表语句
> 
> ```
> CREATE EXTERNAL TABLE `table_1` (
>   `_id` varchar,
>   `subjectId` text NULL
> ) ENGINE=ELASTICSEARCH
> PROPERTIES (
> "hosts" = "http://elasticsearch:9200",
> "user" = "elastic",
> "password" = "123456",
> "index" = "table_1",
> "enable_docvalue_scan" = "true",
> "max_docvalue_fields" = "20",
> "enable_keyword_sniff" = "true",
> "nodes_discovery" = "false",
> "http_ssl_enabled" = "false"
> );
> ```
> 
> 日志报错
> 
> ```
> 2023-01-05 17:00:09,511 WARN (es repository|12) [EsTable.syncTableMetaData():308] Exception happens when fetch index [table_1] meta data from remote es cluster.table id: 11005, err: 
> org.apache.doris.external.elasticsearch.DorisEsException: index[table_1] type[{"table_1":{"mappings":{"properties":{"subjectId":{"type":"keyword"}}}}}] mapping not found column_id for the ES Cluster
> ```
> 
> 但是文档说是支持获取_id的，是不是哪里有误？ https://doris.apache.org/zh-CN/docs/dev/ecosystem/external-table/doris-on-es#%E8%8E%B7%E5%8F%96es%E5%85%83%E6%95%B0%E6%8D%AE%E5%AD%97%E6%AE%B5_id

I have fixed it.

**Comment by df007df** [comment]
> > doris不支持获取元数据字段_id吗？ 建表语句
> > ```
> > CREATE EXTERNAL TABLE `table_1` (
> >   `_id` varchar,
> >   `subjectId` text NULL
> > ) ENGINE=ELASTICSEARCH
> > PROPERTIES (
> > "hosts" = "http://elasticsearch:9200",
> > "user" = "elastic",
> > "password" = "123456",
> > "index" = "table_1",
> > "enable_docvalue_scan" = "true",
> > "max_docvalue_fields" = "20",
> > "enable_keyword_sniff" = "true",
> > "nodes_discovery" = "false",
> > "http_ssl_enabled" = "false"
> > );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 日志报错
> > ```
> > 2023-01-05 17:00:09,511 WARN (es repository|12) [EsTable.syncTableMetaData():308] Exception happens when fetch index [table_1] meta data from remote es cluster.table id: 11005, err: 
> > org.apache.doris.external.elasticsearch.DorisEsException: index[table_1] type[{"table_1":{"mappings":{"properties":{"subjectId":{"type":"keyword"}}}}}] mapping not found column_id for the ES Cluster
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 但是文档说是支持获取_id的，是不是哪里有误？ https://doris.apache.org/zh-CN/docs/dev/ecosystem/external-table/doris-on-es#%E8%8E%B7%E5%8F%96es%E5%85%83%E6%95%B0%E6%8D%AE%E5%AD%97%E6%AE%B5_id
> 
> I have fixed it.

This is not the same problem as mine, I have found the problem code.
