### ISSUE TITLE
[Bug] flink-doris-connector-1.15-1.2.1导入数据，be内存泄露

### ISSUE THREAD

**Issue by songtao-git** [apache/doris#15499]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.0

### What's Wrong?

使用flink-doris-connector-1.15-1.2.1的方式来导入全量数据，be的内存一直上涨，直到限制后任务失败，重启后恢复，好不容易使用savepoint+重启策略把全量数据导完之后，增量较少的情况下，be的内存仍然一直上涨，时间一久系统的内存都使用完了😂

### What You Expected?

be的内存能够回收，在增量数据不大的情况下，内存不要一直上涨知道吃掉所有内存

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FreeOnePlus** [comment]
可以加个微信来跟踪一下你这个问题，fl_manyi
