### ISSUE TITLE
[Bug]执行CLEAN LABEL报错 Encountered: CLEAN

### ISSUE THREAD

**Issue by magicxf** [apache/doris#15602]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

V1.1.1

### What's Wrong?

执行CLEAN LABEL FROM test_db;或者CLEAN LABEL labelxxxx FROM test_db;
都报错：
ERROR 1105 (HY000): errCode = 2, detailMessage = Syntax error in line 1:
clean label from test_db_pre
^
Encountered: CLEAN
Expected

### What You Expected?

CLEAN LABEL成功不报错

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by luozenglin** [comment]
This feature was not supported until v1.2
