### ISSUE TITLE
[Bug] doris创建sql server外部表，查询结果有乱码

### ISSUE THREAD

**Issue by magicxf** [apache/doris#15609]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

V1.1.1

### What's Wrong?

在BE上按照[Apache Doris 通过ODBC连接SQL Server](https://zhuanlan.zhihu.com/p/479117071)完成配置，并连接成功。
环境：
CentOS Linux release 7.9.2009 (Core)
unixODBC：2.3.11
freetds：1.2.21

freetds.conf配置如下：
![Snipaste_2023-01-04_16-14-57](https://user-images.githubusercontent.com/28557507/210511912-18c6b01f-c943-43f7-8540-60810812051d.png)
tsql可连接成功：
![Snipaste_2023-01-04_16-18-58](https://user-images.githubusercontent.com/28557507/210512486-8cbef6a0-79e1-46f1-b892-5a8d88ae1645.png)
odbcinst.ini配置如下:
![Snipaste_2023-01-04_16-43-43](https://user-images.githubusercontent.com/28557507/210516642-8ba0f1df-dfe6-4b46-9ee0-e2936e1ebdea.png)
odbc.ini配置如下：
![Snipaste_2023-01-04_16-44-32](https://user-images.githubusercontent.com/28557507/210516787-667ed20e-b8e4-4b23-b7fa-6395cd4413b2.png)
isql可连接成功：
![Snipaste_2023-01-04_16-46-26](https://user-images.githubusercontent.com/28557507/210517099-dc1c6ffe-0176-4f29-a27c-76bd2d6dea3c.png)

sql server表结构如下：
![Snipaste_2023-01-04_17-10-18](https://user-images.githubusercontent.com/28557507/210521330-0fe31bc9-ae84-4e6a-8c9f-c604bd2509d5.png)
数据如下：
![Snipaste_2023-01-04_16-53-17](https://user-images.githubusercontent.com/28557507/210518347-59540051-0f6f-43da-914b-347b576d9a68.png)

创建sql server外部资源以及外部表：
![Snipaste_2023-01-04_16-49-08](https://user-images.githubusercontent.com/28557507/210517800-52c71952-7d62-4689-8296-f93f684d2408.png)
但是在FE上使用mysql-client连接BE进行查询，出现乱码，使用dorisFE后台查询也是如此：
![Snipaste_2023-01-04_16-52-02](https://user-images.githubusercontent.com/28557507/210518196-705cb28c-6aee-4fda-ad8f-7772997e0b19.png)

在FE上执行INSERT语句，插入外部表数据，成功，可以在sql server中看到新增记录，而且没有乱码。
![Snipaste_2023-01-04_17-08-07](https://user-images.githubusercontent.com/28557507/210520967-5b3e25c9-30fe-4cac-94f4-b67834bc38d0.png)

### What You Expected?

doris创建的外部表没有乱码

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by nextdreamblue** [comment]
"ClientCharset" = "UTF-8"
不要把这个信息放入resource中，而是和建表语句放一起

) ENGINE = ODBC
 COMMENT "COMMON_InvoiceType"
PROPERTIES ("odbc_catalog_resource" = "sqlserver_odbc_xxx",
 "database" = "ddd",
 "table" = "bbbb",
"ClientCharset" = "UTF-8"
);

**Comment by magicxf** [comment]
> "ClientCharset" = "UTF-8" 不要把这个信息放入resource中，而是和建表语句放一起
> 
> ) ENGINE = ODBC COMMENT "COMMON_InvoiceType" PROPERTIES ("odbc_catalog_resource" = "sqlserver_odbc_xxx", "database" = "ddd", "table" = "bbbb", "ClientCharset" = "UTF-8" );

我试过这个方式，然后使用SHOW CREATE TABLE ext_PortraitConfigTag;
结果发现PROPERTIES中没有"ClientCharset" = "UTF-8"这一项，说明建表语句不支持该属性。
相反的SHOW RESOURCES中就有该属性。

**Comment by magicxf** [comment]
直接把doris升级到V1.2，然后用jdbc 外部表就解决了。
相关资源如下，后来人少走弯路：
1、官方教程：https://doris.apache.org/zh-CN/docs/dev/ecosystem/external-table/jdbc-of-doris/#qa
2、TLS版本不匹配报错解决：
https://my-blue.gitee.io/2022/07/06/%E9%A1%B9%E7%9B%AE%E4%B8%AD%E8%BF%9E%E6%8E%A5SQLServer%E5%87%BA%E7%8E%B0%E7%9A%84%E9%97%AE%E9%A2%98
https://www.pudn.com/news/623ec167f9448f597f2923bb.html
