### ISSUE TITLE
[Bug] [daily] be core when execute split_part query

### ISSUE THREAD

**Issue by zhangy5** [apache/doris#15678]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master doris-0.0.0-trunk-95f2f43

### What's Wrong?
jenkins failed case: https://ci-builds.apache.org/job/Doris/job/doris_daily_enable_vectorized/167/testReport/(root)/test_query_string_function/test_query_split_part/

![image](https://user-images.githubusercontent.com/10826066/210951262-d4163caa-57e6-4f74-a8eb-69fee0a4266c.png)
![image](https://user-images.githubusercontent.com/10826066/210951307-14150156-c615-4210-8e0c-b48eb8682e50.png)

### What You Expected?

query ok

### How to Reproduce?

select split_part(k8, '1', 1), k8, split_part(concat(k8, '12'), '1', 1) from baseall order by k8 limit 2;

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LizZhang315** [comment]
Still query error
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/24400239/211233170-adc022c8-cc95-4a58-b87c-ef92ebb6805d.png">
