### ISSUE TITLE
ADD EXCLUDE FUNCTION

### ISSUE THREAD

**Issue by kk467415728** [apache/doris#15773]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

我们通过使用Tableau和Superset这类BI工具来对接Doris，我们大部分的需求都需要用到 EXCLUDE 函数，所以想请教一下是否可以实现这个函数，谢谢。
需求大致如下： 例：input、fail为度量值，error_code为筛选列
在聚合度量input时需要排除掉error_code的过滤值，在聚合度量fail时需要 error_code的过滤生效，且sum(input)和sum(fail)需要一起展示。

### Use case

SELECT COL1, EXCLUDE(ERROR_CODE : SUM(INPUT)) AS INPUT_EXCLUDE,SUM(FAIL)  FROM TABLE 
WHERE ERROR_CODE = 'error1' 
GROUP BY COL1;

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
这个应该是bi内部处理吧，其他olap有支持的吗

**Comment by kk467415728** [comment]
是的，我们之前是通过BI工具Tableau提供的 EXCLUDE 函数对度量做一个处理，但是目前由于Tableau用不了了，发现在对接Superset的时候不支持这个功能，所以才想问一下有没有什么解决办法。那我们就只好去找一款其他的BI工具来处理了。

**Comment by stalary** [comment]
这个不属于Doris的问题，你可以用其他BI或者二次开发Superset

**Comment by kk467415728** [comment]
好的，谢谢~
