### ISSUE TITLE
[Bug] ALTER TABLE tablename MODIFY COLUMN 对于 array 数组报错

### ISSUE THREAD

**Issue by enterwhat** [apache/doris#15799]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-1.2.1-rc01-Unknown

### What's Wrong?

ALTER TABLE tablename MODIFY COLUMN cpu_processName ARRAY<varchar(100)> NULL COMMENT "cpu进程名数组"
> 1105 - errCode = 2, detailMessage = Can not change ARRAY to ARRAY
> 时间: 0.147s

原有：cpu_processName ARRAY<varchar(40)> NULL COMMENT "cpu进程名数组"
期望改为：cpu_processName ARRAY<varchar(100)> NULL COMMENT "cpu进程名数组"

### What You Expected?

成功执行

### How to Reproduce?

执行类似改表语句

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
Currently, we do not support schema change between complex types with subtypes.

**Comment by xy720** [comment]
No, complex types are not supported in schema change now.
Because we haven't finished this part yet.
So we have temporarily banned users from doing schema change.
