### ISSUE TITLE
[Enhancement] make max running txn per db more flexible

### ISSUE THREAD

**Issue by Henry2SS** [apache/doris#15869]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Now, we have a fe config `max_running_txn_num_per_db`. It limits every database's transaction number.

But in JD, we have a problem. Some users have broker load with large amount of data. Their task will affect other users load task. We need a limit that can be flexibly changed.

### Solution

Add transaction quota of every database.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yjyJames** [comment]
It confused me too. Transactions may reach the limit while canal sync job is running (with 200 tables in sync).
