### ISSUE TITLE
[Bug] 单引号转义自身的问题

### ISSUE THREAD

**Issue by kilodleif** [apache/doris#15900]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.4

### What's Wrong?

字符串中存在连续的单引号时，不管单引号是否已使用反斜杠转义，两个相邻的单引号都会转义成一个。而MySQL中，已经使用反斜杠转义的单引号不会再次转义自身。
![image](https://user-images.githubusercontent.com/18283234/212256770-6ed8c0df-43e3-47cd-9f5b-13710975b288.png)
![image](https://user-images.githubusercontent.com/18283234/212256959-32d8626b-77ed-4605-8d41-849177280eab.png)

### What You Expected?

已经使用反斜杠转义的单引号不会再次转义自身

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by morrySnow** [comment]
nestest master could get right result
