### ISSUE TITLE
[Feature] Support array functions for nested type datev2/datetimev2

### ISSUE THREAD

**Issue by Gabriel39** [apache/doris#15952]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Yukang-Lian** [comment]
I will work on it!
