### ISSUE TITLE
[Bug]  if 函数后计算结果发生错误

### ISSUE THREAD

**Issue by ChubChen** [apache/doris#15986]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.1 

### What's Wrong?

![image](https://user-images.githubusercontent.com/9711512/212694642-a8d55d9d-5610-4d11-bf58-d23bae003f3e.png)
相同的两个计算公式，如果没有出现在if 函数的时候计算结果是正确的。 但是代入到if 函数中结算出来结果出错。

### What You Expected?

预期结果应该和未使用if语句前公式的到结果一致。

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yuanyuan8983** [comment]
Hello, I didn't find any problems in the test just now. Let's test this problem together. Please add my WeChat: cyllyy810222

**Comment by yuxuan-luo** [comment]
复现方法：
建表语句及数据导入：
CREATE TABLE `doris_test_sink` (
  `id` int(11) NULL,
  `s_count` int(11) NULL,
  `fee` DECIMALV3(15,4) NULL,
  `skuname` varchar(40) NULL,
  `skudesc` varchar(200) NULL
) ENGINE=OLAP
DUPLICATE KEY(`id`)
COMMENT 'OLAP'
DISTRIBUTED BY HASH(`id`) BUCKETS 1
PROPERTIES (
"replication_allocation" = "tag.location.default: 3",
"in_memory" = "false",
"storage_format" = "V2",
"disable_auto_compaction" = "false"
);

curl -u admin -H "label:load_local_file_test" -H "column_separator:," -T /root/test.csv http://10.0.0.xx:8040/api/xiaomi/doris_test_sink/_stream_load

csv:
10001,12,13.3, test1,this is atest
10002,100,15.3,test2,this is atest
10003,102,16.3,test3,this is atest
10004,120,17.3,test4,this is atest
10005,23,10.3, test5,this is atest
10006,24,112.3,test6,this is atest
10007,26,13.3, test7,this is atest
10008,29,145.3,test8,this is atest
10009,30,16.3, test9,this is atest
100010,32,18.3,test10,this is atest
100011,52,18.3,test11,this is atest
100012,62,10.3,test12,this is atest

-- 查询 sql
select *,if(1 = 2, 
	1.0*s_count - fee,
	fee) as bug ,round(fee - s_count,6) as fe from doris_test_sink;

**Comment by lide-reed** [comment]
@yuxuan-luo try to make a patch to fix this bug
