### ISSUE TITLE
[Bug] [daily]  be core when query after create mv and delete

### ISSUE THREAD

**Issue by zhangy5** [apache/doris#16004]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master
doris-0.0.0-trunk-b469efd

### What's Wrong?

jenkins failed case:
https://ci-builds.apache.org/job/Doris/job/doris_daily_enable_vectorized/179/testReport/(root)/test_sys_delete_on_duplicate_value/test_delete_on_duplicate_value_limit_rollup/
be.out info can see:
https://ci-builds.apache.org/job/Doris/job/doris_daily_enable_vectorized/179/testReport/(root)/test_sys_check_core/test_check_be_core/

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/10826066/212826582-ce1439ff-50df-414d-b239-126b3078b470.png">

### What You Expected?

query ok

### How to Reproduce?

1. create table
2. load data
3. create mv
4. delete
5. create another mv
6. query

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by BiteTheDDDDt** [comment]
This bug will be fixed in https://github.com/apache/doris/pull/15837
