### ISSUE TITLE
[Enhancement] Support BE http service with brpc.

### ISSUE THREAD

**Issue by TangSiyang2001** [apache/doris#16087]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Doris BE uses `libevent` to support http service currently, which is planned to be replaced by `brpc` step by step in the future.

### Solution

Doris BE has `webserver_port` for http service and `brpc_port` for internal service. The brpc-based http service will share the `brpc_port` with internal service, and `webserver_port` will be kept for libevent-based http service at the current stage.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dataroaring** [comment]
Great issue. This would simplify http related code.
