### ISSUE TITLE
[Bug] peakMemoryBytes is missing in audit log and mem_limit does not work

### ISSUE THREAD

**Issue by kylinmac** [apache/doris#16228]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.5-rc02

### What's Wrong?

When set enable_vectorized_engine = true, peakMemoryBytes is missing in audit log. 

The image can be found in https://github.com/apache/doris/pull/14750

i try to add line 
`
        _sender->update_max_peak_memory_bytes();
`
in be/src/vec/sink/result_sink.cpp  , but it does not work  , the value of peakMemoryBytes is still 0.

### What You Expected?

When set enable_vectorized_engine = true, print the right value of peakMemoryBytes in  audit log.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kylinmac** [comment]
![image](https://user-images.githubusercontent.com/74998015/215404810-d231642f-1081-4718-bdda-892f91e86e55.png)
The exec_mem_limit even does not work in  enable_vectorized_engine=false

**Comment by xinyiZzz** [comment]
1.1.5的话，向量化默认关闭了 exec_mem_limit 的限制，要在be.conf开启两个参数
enable_proc_meminfo_cancel_query
enable_mem_tracker_cancel_query
![image](https://user-images.githubusercontent.com/13197424/215452875-ed45c099-7a63-4fe1-9c77-a0e21946b86a.png)
原因是向量化的内存控制，比非向量化更严格，所以个别用户升级后大量查询报exceed limit，所以默认给关掉了

**Comment by xinyiZzz** [comment]
至于audit log没有peakMemoryBytes，也是1.1.5还没支持，1.2已经加上了
