### ISSUE TITLE
[Enhancement]  insert into timeout easily

### ISSUE THREAD

**Issue by freemandealer** [apache/doris#16301]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

现在因为 query_timeout 默认值比较小，用户不注意就会 INSERT INTO 超时。我们可以针对 INSERT INTO 单独做超时处理。

### Solution

InsertStmt.java 替换 getQueryTimeoutS

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TangSiyang2001** [comment]
I'm willing to submit a PR !
