### ISSUE TITLE
[Enhancement] Support microseconds in function `unix_timestamp`

### ISSUE THREAD

**Issue by Gabriel39** [apache/doris#16560]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Now Doris already supports DATETIMEV2 which could have precision up to microseconds. But function `unix_timestamp` still can not process those microseconds. So we need this feature for users who need timestamp with microseconds.

In Doris:

1. `CREATE TABLE `datetime_table` (`date` datetime(3) NOT NULL COMMENT '数据灌入日期时间'     ) distributed by hash(`date`) buckets 1      properties("replication_num"="1");`
2. `insert into `datetime_table` values ("2022-01-01 10:10:10.111");`
3. `select unix_timestamp(`date`) from datetime_table;`

![image](https://user-images.githubusercontent.com/37700562/217757927-4cdfccf5-9717-4ea3-b7af-ad861ab374aa.png)

In MySQL:

1. `CREATE TABLE `datetime_table` (`date` datetime(3) NOT NULL COMMENT '数据灌入日期时间'     );`
2. `insert into `datetime_table` values ("2022-01-01 10:10:10.111");`
3. `select unix_timestamp(`date`) from datetime_table;`

![image](https://user-images.githubusercontent.com/37700562/217757954-3cda554d-d009-4fde-aaea-f185cc4a317b.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by isHuangXin** [comment]
Plz, assign it to me.

**Comment by BBB-source** [comment]
I will work on it.

**Comment by liangjiawei1110** [comment]
I'd like to try it.

**Comment by Gabriel39** [comment]
> I'd like to try it.

Great! I will re-assign this issue to you

**Comment by hongkun-Shao** [comment]
May I ask if anyone else is dealing with this issue? If not, could you assign it to me to try? However, since I am new to the community, I cannot guarantee that I can complete it, but I will do my best. @Gabriel39

**Comment by zclllyybb** [comment]
Sorry but this issue is duplicated by https://github.com/apache/doris/issues/24382. will close this. @liangjiawei1110 @hongkun-Shao
