### ISSUE TITLE
[Bug] [daily] BE core when execute insert streaming with win function

### ISSUE THREAD

**Issue by LizZhang315** [apache/doris#16658]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-0.0.0-trunk-1de4e31

### What's Wrong?

jenkins failed case:https://ci-builds.apache.org/job/Doris/job/doris_daily_enable_vectorized/lastBuild/testReport/junit/(root)/test_stream_insert/test_insert_win/
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/24400239/218387566-cb6e2a8e-44cd-4b6c-a6c1-813dd56acd72.png">
BE core file:
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/24400239/218387620-7f7e3de1-e4d6-49a4-aa13-94b9d03a2f62.png">

### What You Expected?

SQL execute success

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by eldenmoon** [comment]
https://github.com/apache/doris/pull/16816/files This PR may help solve this problem
