### ISSUE TITLE
Error [1105] [HY000]: Range partition with batch partition: Failed to create table using datetime partition column

### ISSUE THREAD

**Issue by liuchunhua** [apache/doris#16684]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.1

### What's Wrong?

``` SQL
create table internal.demo.test(
id int,
gmt_create datetime
) ENGINE=OLAP
UNIQUE KEY( id, gmt_create)
PARTITION BY RANGE(`gmt_create`)(
FROM ("2023-01-01 00:00:00") TO ("2024-01-01 00:00:00") INTERVAL 1 DAY
)
DISTRIBUTED BY HASH(id) BUCKETS 5
```
Error:
> [1105] [HY000]: errCode = 2, detailMessage = Invalid range value format： errCode = 2, detailMessage = date literal [2023-01-01] is invalid: errCode = 2, detailMessage = Invalid datetime value: 2023-01-01

``` SQL
create table internal.demo.test(
id int,
gmt_create datetime
) ENGINE=OLAP
UNIQUE KEY( id, gmt_create)
PARTITION BY RANGE(`gmt_create`)(
FROM ("2023-01-01") TO ("2024-01-01") INTERVAL 1 DAY
)
DISTRIBUTED BY HASH(id) BUCKETS 5;
```

Error:
> [1105] [HY000]: errCode = 2, detailMessage = Invalid range value format： errCode = 2, detailMessage = date literal [2023-01-01] is invalid: errCode = 2, detailMessage = Invalid datetime value: 2023-01-01

### What You Expected?

How to create partition table like this?

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lsy3993** [comment]
@catpineapple The issue has been assigned to you in our jira
