### ISSUE TITLE
[Bug] create table could create column with type 'ALL'

### ISSUE THREAD

**Issue by morrySnow** [apache/doris#16741]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

```sql
create table test (c1 all) distributed by hash(c1) properties('replication_num'='1');
```

```
+-------+------+------+------+---------+-------+
| Field | Type | Null | Key  | Default | Extra |
+-------+------+------+------+---------+-------+
| c1    | ALL  | Yes  | true | NULL    |       |
+-------+------+------+------+---------+-------+
```

and then, query it will throw exception
```
ERROR 1105 (HY000): errCode = 2, detailMessage = Unexpected exception: Index -1 out of bounds for length 33
```

### What You Expected?

cannot create table with a ALL type column

### How to Reproduce?

```sql
create table test (c1 all) distributed by hash(c1) properties('replication_num'='1');
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TangSiyang2001** [comment]
I'll try to fix it.

**Comment by TangSiyang2001** [comment]
Job done, PTAL.
