### ISSUE TITLE
[Bug]round函数四舍五入不正确

### ISSUE THREAD

**Issue by vojin53** [apache/doris#16804]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-1.2.2-rc01

### What's Wrong?

执行sql如下：
select round(2.5);
返回结果期望是3，返回却是2。
![image](https://user-images.githubusercontent.com/83171599/219223147-1c96c4ec-a3f9-4d5f-9eaf-43869d91ded9.png)

该错误在1.1.5版本是不存在的。

### What You Expected?

round函数计算能正确执行

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vojin53** [comment]
在1.15版本中，改bug不存在，返回结果是3
![image](https://user-images.githubusercontent.com/83171599/219223618-0639d050-6810-4ce1-a25b-17dbb0933a7a.png)

**Comment by Gabriel39** [comment]
现在默认使用行为是把2.5看作是double类型然后计算round结果，但是double是不保证精度的所以结果会有问题。如果想得到精确值的话你可以使用DECIMALV3
