### ISSUE TITLE
[Bug] 窗口函数last_value窗口不生效 

### ISSUE THREAD

**Issue by vojin53** [apache/doris#16845]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-1.2.2

### What's Wrong?

表数据如下
![image](https://user-images.githubusercontent.com/83171599/219383106-b025ea2a-e153-4a59-acc4-87b4e34e1db5.png)

------------------------------------------------------------------
执行sql为
select 
    u_id,
    u_city,
    u_salary,
    last_value(u_salary) over (partition by u_city order by u_id rows between unbounded preceding and 1 preceding) last_value_test
from example_window_tb;

------------------------------------------------------------------
此SQL使用SPARK的返回结果为
![image](https://user-images.githubusercontent.com/83171599/219383370-a6750b75-0aa4-42c2-a90d-54191c723337.png)
以上是我期望的结果，根据u_city 分区，在两个分区内分别计算last_value。

------------------------------------------------------------------
而在Doris中的返回结果为：
![image](https://user-images.githubusercontent.com/83171599/219383673-77d9237f-70b3-4817-bb32-0dc5accc579e.png)
partition by u_city 没有生效，sz分区的第一行不是null，而是gz分区的最后一行。

### What You Expected?

![image](https://user-images.githubusercontent.com/83171599/219384008-6ae9c9cf-5cfd-412c-addc-eea2f75be6f0.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhangstar333** [comment]
https://github.com/apache/doris/pull/17084
