### ISSUE TITLE
[Bug] Doris1.2.2  jdbc Catalog connects to sqlserve unable to query

### ISSUE THREAD

**Issue by dlimeng** [apache/doris#16873]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris : 1.2.2
sqlserver : 2005

### What's Wrong?

This jdbc Catalog connects to sqlserve 
SQLServerException: The holdability value 1,000 is not valid.
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/16789827/219587423-39ba0abd-572c-4dec-8cab-2f5544af9022.png">

### What You Expected?

Fix the problem

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gojumprope** [comment]
same issue here

**Comment by zhangstar333** [comment]
https://github.com/apache/doris/pull/16929

**Comment by dlimeng** [comment]
> #16929

Thanks
