### ISSUE TITLE
[Bug] SPLIT_BY_STRING函数执行报错；

### ISSUE THREAD

**Issue by RavenZdh** [apache/doris#16947]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris-1.2.1

### What's Wrong?

开启向量化模式的前提下，执行官网中的SPLIT_BY_STRING函数案例报错：SQL 错误 [1105] [HY000]: errCode = 2, detailMessage = No matching function with signature: split_by_string(varchar(-1), varchar(-1)).

![1676888208585](https://user-images.githubusercontent.com/49672022/220077536-dafc5b3a-b412-4ebb-b76c-95a3878a414e.png)
![1676888219069](https://user-images.githubusercontent.com/49672022/220077554-3aed642a-5cc1-4468-9407-be3e06d361d4.png)

### What You Expected?

略

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by nextdreamblue** [comment]
https://github.com/apache/doris/pull/15677
