### ISSUE TITLE
[Bug] Stream load Failed

### ISSUE THREAD

**Issue by sileiH** [apache/doris#16981]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris1.2.2

### What's Wrong?

1. 有一份数据000.csv，数据一共8W多条， 然后再用stream load 会报错，字段数不对
![image](https://user-images.githubusercontent.com/34700762/220276575-09379553-9fd7-40ab-9d46-9e6712b36eaf.png)

![image](https://user-images.githubusercontent.com/34700762/220276232-664d1303-d721-4bb8-9579-1706eaa65142.png)

3. 然后我取报错的那行数据最近的cat 000.csv| grep -100 'XXX' > 111.csv （这边grep XXX 为报错的那一行）,用111.csv执行导入成功。
4. 然后我取报错的那行数据最近的cat 000.csv| grep -40000 'XXX' > 222.csv, 用222.csv执行导入成功
5. 然后我取报错的那行数据最近的cat 000.csv| grep -100000 'XXX' >> 222.csv, （全量数据，但有数据重复）, 用222.csv执行导入成功。

### What You Expected?

能够解决这个stream load的问题

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhannngchen** [comment]
@sileiH can you provide the table's schema?

**Comment by sileiH** [comment]
create table test (
	`col1` char(48) not null,
	`col2` char(12) not null,
	`col3` char(48) not null,
	`col4` int(11) not null,
	`col5` char(30) not null,
	`col6` varchar(360) not null,
	`col7` char(45) not null,
	`col8` int(11) not null,
	`col9` int(11) not null,
	`col10` char(3) not null,
	`col11` decimal(16, 2) not null,
	`col12` decimal(16, 2) not null,
	`col13` int(11) not null,
	`col14` char(48) not null
) engine=olap
unique key(`col1`)
comment 'OLAP'
distributed by hash(`col1`) buckets 10
properties(
"replication_allocation" = "tag.location.default: 1",
"in_memory" = "false",
"storage_format" = "V2",
"disable_auto_compaction" = "false"
)
