### ISSUE TITLE
[feature](cooldown) Forbid storage policy for MoW tables

### ISSUE THREAD

**Issue by platoneko** [apache/doris#17065]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Cooldown may cause serious performance degradation on MoW tables, temporarily disable storage policy for MoW tables.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 1330571** [comment]
I would like to pick this issue

**Comment by platoneko** [comment]
Related modules: `ModifyTablePropertiesClause`, `InternalCatalog.createOlapTable`.

**Comment by dataroaring** [comment]
We can create a mow unique table using property "enable_unique_key_merge_on_write" = "true".  https://doris.apache.org/docs/dev/data-table/data-model?_highlight=merge#merge-on-write-of-unique-model 

We can set cooldown property according to https://doris.apache.org/docs/dev/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-POLICY?_highlight=cooldown#example.

This issue want to disable cooldown on merge on write unique key.
