### ISSUE TITLE
[Enhancement] iceberg依赖hive版本冲突

### ISSUE THREAD

**Issue by wangmiao1002** [apache/doris#17080]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

基于Hive2.1.1的 Metastore创建的iceberg 的Catalog，查询表时出现
ERROR 1105 (HY000): errCode = 2, detailMessage = Unexpected exception: failed to get table doristest in db fun_wm from hms client. reason: org.apache.thrift.TApplicationException: Invalid method name: 'get_table_req'
基于上述同样配置 创建hive的catalog 则可以查询，是否iceberg连接hive Matestore可以和hive的catalog逻辑保持一致

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by morningman** [comment]
please paste your `create catalog` statement, and what is your Doris version?

**Comment by wangmiao1002** [comment]
doris 版本：1.2.2

> 
![image](https://user-images.githubusercontent.com/38424929/221086320-3bc9ea2f-8639-4ec0-a432-7888cf870d7b.png)

**Comment by morningman** [comment]
you can specify the hive version in your `create catalog` stmt:

"hive.version" = "2.1.1"

See https://doris.apache.org/zh-CN/docs/dev/lakehouse/multi-catalog/hive#hive-%E7%89%88%E6%9C%AC

**Comment by wangmiao1002** [comment]
Successfully set the hive version to query the execution. Thank you for your reply
