### ISSUE TITLE
[Enhancement] Support altering the property "light_schema_change" for the tables which created before 1.2

### ISSUE THREAD

**Issue by Lchangliang** [apache/doris#17094]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

There is similar issue [related-issue](https://github.com/apache/doris/issues/15601) but it's closed. 
For the tables which created before 1.2, when the BE upgrade to  1.2, the user cann't alter the property "light_schema_change". 

### Solution

The different whether light_schema_change or not is that the column ids are set in FE or BE. Before 1.2, the column ids are set in BE. If light_schema_change = true, the column ids are set in FE. So when we want to alter a non-light-schema-change table to support light-schema-change, we need to get the column ids from BE and rewrite the FE table meta. The feature is important very much because when a table altered to light-schema-change and it will not support to rollback. It mean that we need plenty of patience to test and familiar with FE/BE metadata code.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Yukang-Lian** [comment]
will work on it.

**Comment by TangSiyang2001** [comment]
@Yukang-Lian has heavy tasks currently and passes this task to me. I'll try to work on it.
