### ISSUE TITLE
[Feature] add some new json function

### ISSUE THREAD

**Issue by nextdreamblue** [apache/doris#17216]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

`json_contains` : [https://dev.mysql.com/doc/refman/5.7/en/json-search-functions.html#function_json-contains](https://dev.mysql.com/doc/refman/5.7/en/json-search-functions.html#function_json-contains)

`json_extract` : support return array, like : [https://dev.mysql.com/doc/refman/5.7/en/json-search-functions.html#function_json-extract](https://dev.mysql.com/doc/refman/5.7/en/json-search-functions.html#function_json-extract)

`json_unqoute` : [https://dev.mysql.com/doc/refman/5.7/en/json-modification-functions.html#function_json-unquote](https://dev.mysql.com/doc/refman/5.7/en/json-modification-functions.html#function_json-unquote)

`json_valid` : [https://dev.mysql.com/doc/refman/5.7/en/json-attribute-functions.html#function_json-valid](https://dev.mysql.com/doc/refman/5.7/en/json-attribute-functions.html#function_json-valid)

`-> operator` : [https://dev.mysql.com/doc/refman/5.7/en/json-search-functions.html#operator_json-column-path](https://dev.mysql.com/doc/refman/5.7/en/json-search-functions.html#operator_json-column-path)

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by nextdreamblue** [comment]
@Yukang-Lian 
can you add these functions issues: 
`json_contains`
`json_extract` : support return array
`json_unqoute`
`-> operator`

to #17176 for firset good issue

**Comment by Yukang-Lian** [comment]
> @Yukang-Lian can you add these functions issues: `json_contains` `json_extract` : support return array `json_unqoute` `-> operator`
> 
> to #17176 for firset good issue

Yeah!

**Comment by nextdreamblue** [comment]
> > @Yukang-Lian can you add these functions issues: `json_contains` `json_extract` : support return array `json_unqoute` `-> operator`
> > to #17176 for firset good issue
> 
> Yeah!

thanks bro

**Comment by Perryen** [comment]
Hi, can I get one of these tasks? Maybe the first:json_contains，I need to learn something  to resolve this for some time，thanks for your help~~
