### ISSUE TITLE
[Bug] missing from GROUP BY

### ISSUE THREAD

**Issue by sangetang** [apache/doris#17214]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.2

### What's Wrong?

select 
    t.`compareDay`, 
    sum(shopOpenCnt)
from ( 
    SELECT  
        date_format(DATE(TIMESTAMPADD(DAY,-8,CURDATE())),'%m/%d') AS `compareDay` ,
        0 AS shopOpenCnt
    ) t 
group by t.`compareDay` 

select t.`compareDay`, sum(shopOpenCnt) from ( SELECT date_format(DATE(TIMESTAMPADD(DAY,-8,CURDATE())),'%m/%d') AS `compareDay` , 0 AS shopOpenCnt ) t group by t.`compareDay`]; SQL state [HY000]; error code [1105]; errCode = 2, detailMessage = select list expression not produced by aggregation output (missing from GROUP BY clause?): `t`.`compareDay`; nested exception is java.sql.SQLException: errCode = 2, detailMessage = select list expression not produced by aggregation output (missing from GROUP BY clause?): `t`.`compareDay`

### What You Expected?

no error

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zy-kkk** [comment]
Hello, I think this PR #16854  can solve your problem. It has been merge into branch-1.2-lts, and we will release version 1.2.3 as soon as possible

**Comment by sangetang** [comment]
邮件已收到，谢谢！祝你生活愉快！

**Comment by sangetang** [comment]
> Hello, I think this PR #16854 can solve your problem. It has been merge into branch-1.2-lts, and we will release version 1.2.3 as soon as possible

**Comment by sangetang** [comment]
> Hello, I think this PR #16854 can solve your problem. It has been merge into branch-1.2-lts, and we will release version 1.2.3 as soon as possible

I`ll try it. 3ks
