### ISSUE TITLE
[Enhancement] (fe exception) write a java annotation to catch throwable from a method and print log

### ISSUE THREAD

**Issue by yiguolei** [apache/doris#17238]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

There are some method in doris that may throw exception but doris does not deal with it. For exmple, FrontendServiceImpl the method getTableNames throws exception, but not print it. If BE call this method and failed, we do not know what happened.  And it is very ugly to add try catch in every method. Maybe we could add a java annotation like  @LOG_EXCEPITON

    @LOG_EXCEPTION
    @Override
    public TGetTablesResult getTableNames(TGetTablesParams params) throws TException {
        LOG.debug("get table name request: {}", params);
        TGetTablesResult result = new TGetTablesResult();
        List<String> tablesResult = Lists.newArrayList();

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by NetShrimp06** [comment]
i can help with this

**Comment by yiguolei** [comment]
@NetShrimp06 Hi, any progress on this issue?
