### ISSUE TITLE
[Bug] Broker load decimal value wrong

### ISSUE THREAD

**Issue by sangetang** [apache/doris#17277]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.2

### What's Wrong?

Table:
Create Table: CREATE TABLE..
(
...
`shop_address_lon` decimal(10, 6) NULL COMMENT '门店地址经度',
...
)

Hive data:
shop_address_lon
--
117.390818
125.926015
116.306408
112.381638
116.168892
116.350425
118.111734
118.139702
116.427341
112.927493
110.342861
112.880605
118.188491
117.389622
118.188520
126.252262
126.254401
117.390893
116.480970
117.394867
125.078311
118.186204
110.778412
116.210653
117.390428
102.371515
117.276387
117.389622
116.310525
117.511841
116.310905
112.901858
113.258976
117.390893
112.880605
117.388131
102.102428
118.188491
118.133584
116.481209
113.304986
117.390548
110.734182
117.390297
118.188491
126.243529
117.190182
110.306666
112.552221
105.588470
118.188491
116.321792
116.411923
116.424833
117.259716
109.649664
117.390198
117.391052
116.417830
116.410131
116.313698
117.391052
117.391400
116.231525
116.235764
117.389123
116.471753
113.386775
110.781470
107.963299
117.193545
110.692000
115.974609
117.389906
117.390153
116.386376
116.420182
117.390207
114.142016
118.188491
115.973648
118.188491
116.406557
113.392517
117.390245
125.677949
116.336116
118.187555
116.308251
117.389622
116.431719
110.785141
116.481310
117.390893
126.252262
117.162616
117.276387
117.390286
116.383640
116.888202

Be error:

Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1173908.18, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1259260.15, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1163064.08, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1123816.38, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1161688.92, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1163504.25, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1181117.34, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1181397.02, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1164273.41, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1129274.93, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1103428.61, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1128806.05, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1181884.91, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1173896.22, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1181885.2, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1262522.62, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1262544.01, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1173908.93, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1164809.7, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1173948.67, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1250783.11, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1181862.04, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1107784.12, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1162106.53, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1173904.28, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1023715.15, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1172763.87, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1173896.22, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1163105.25, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1175118.41, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1163109.05, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1129018.58, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1132589.76, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1173908.93, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1128806.05, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1173881.31, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1021024.28, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1181884.91, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1181335.84, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1164812.09, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1133049.86, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1173905.48, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1107341.82, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1173902.97, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1181884.91, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1262435.29, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1171901.82, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1103066.66, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1125522.21, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1055884.7, precision=10, scale=6; . src line []; 
Reason: column_name[shop_address_lon], decimal value is not valid for definition, value=1181884.91, precision=10, scale=6; . src line [];

Value changed!!

### What You Expected?

load success

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by limeiyang** [comment]
same question ！resolved ？

**Comment by sangetang** [comment]
邮件已收到，谢谢！祝你生活愉快！
