### ISSUE TITLE
[Enhancement] better merge single_replica_load_rpc_service into brpc_service

### ISSUE THREAD

**Issue by freemandealer** [apache/doris#17333]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

better merge single_replica_load_rpc_service into brpc_service

refer to these to see what is `single replica load`: 
[single replica load design](https://cwiki.apache.org/confluence/display/DORIS/DSIP-015:+Support+single+replica+load+for+load)
[single replica implement]( https://github.com/apache/doris/commit/f730a048b1e3baf3d78b27292698eecbae3fcef7)

The code would be much clarified if there is only one rpc service. The reason why the original code uses two services is that rpc will time out under heavy workloads if use just one.

However, according to the design of brpc thread model, even if running in separated service thread pools, the underlying pthreads/cpu cores are shared by the two services. I think the reason why the two services solution works is only because it claims more worker pthreads, which can also be achieved by simply setting bigger  `--bthread_concurrency`  gflag config.

So two services achieve nothing but messyness. We should merge them into one and identify&fix the root cause of the timeout problem.

### Solution

step1. merge single_replica_load_rpc_service into brpc_service

step2. test the system with heavy load jobs to try to reproduce the rpc timeout problem

step3. make assumptions & proving

> some of my guesses:
>
> ```c++
> void PInternalServiceImpl::request_slave_tablet_pull_rowset(...) {
>     ...
>     worker_pool.offer([=]() {
>        ...     
>     }
>     ...
> }
> ```
>
> if the worker pool is full (possible under heavy loads), the pthread will wait under std::condition_variable. If most of the pthreads in the pool are blocked, there would be few pthread to deal with rpc request and then timeout happens.
>
> If it is true, we need to use bthread's condition variable instead of std::condition_variable. The former one will only yeild the underlying pthread to other rpc jobs, rather than blocking it.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TangSiyang2001** [comment]
Let me have a try.

**Comment by TangSiyang2001** [comment]
My assumption about RPC timeout:

Actually, tasks are offered to work pool with the `try_offer` API now:
```cpp
virtual bool try_offer(WorkFunction func) {
        PriorityThreadPool::Task task = {0, func, 0};
        return _work_queue.try_put(task);
}
```
rather than the `offer` API:
```cpp
virtual bool offer(WorkFunction func) {
        PriorityThreadPool::Task task = {0, func, 0};
        return _work_queue.blocking_put(task);
}
```
In currrent code, once the request is processed by the corresponding bthread, it will be offered to the worker pool immediately and processed in the async way.

Therefore, RPC timeout under heavy loads may actually result from:
    1. (minor) Too few pthreads for bthread workers to manage the requests.
    2. (major) The ratio of `brpc_heavy_work_pool_threads/brpc_heavy_work_pool_max_queue_size` may be inproper under the corresponding case, so tasks in blocking queue are blocked too long to be processed by the busy worker threads.

**Comment by freemandealer** [comment]
> Using bthread's condition variable instead of std::condition_variable may not work under the current case, because bthreads for brpc requests are not working upon the work_pool of ourselves.

There are some misunderstandings. My logic is as follows:

- Merge two services into one
- If there are any problems, replace with bthread mutex to verify my assumption written above.

So using bthread mutex was just a verification method originally. Chenlinzhong’s modification of the RPC handling framework last month has confirmed my assumption and fixed it with another elegant method. With his fix, there is no need to use bthread mutex anymore (but not completely useless, see below).

Now let’s stop discussing historical issues and discuss the next steps based on the current situation.

Because of chenlinzhong's brilliant solution, our service merging task has become easier ever than before: just do the merge and ... done, right?

Even if RPC processing and business processing are separated, if all underlying pthreads are occupied, blocking problems still happens. In the end, we still need to avoid blocking pthreads as much as possible. Getting rid of std::mutex is still an important way to do so.

No worry. If we find any problems during subsequent stress testing, we can analyze them case by case.

**Comment by TangSiyang2001** [comment]
>> BTW, even if RPC processing and business processing are separated, if all underlying pthreads are occupied, blocking problems still happens. In the end, we still need to avoid blocking pthreads as much as possible. Getting rid of std::mutex is still an important way to do so.

@freemandealer  Thank u very much! So the RPC hang problem has been stagely solved by the async service now.
