### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by 905614251** [apache/doris#17354]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.2

### What's Wrong?

1.2.2： 使用S3Load/BrokerLoad  parquet  ErrorMsg ：type:ETL_QUALITY_UNSATISFIED; msg:quality not good enough to cancel
在1.2.1版本中正常

### What You Expected?

Success

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yuanyuan8983** [comment]
It seems to be caused by the unqualified data quality，you can add me on WeChat and we can test it together：cyllyy810222
