### ISSUE TITLE
[Feature] (array function) support array_popfront function

### ISSUE THREAD

**Issue by bobhan1** [apache/doris#17361]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Yukang-Lian** [comment]
Please set `Yes I am willing to submit a PR!` to true.

**Comment by bobhan1** [comment]
@Yukang-Lian , I want to know how much memory is enough for compiling the BE. The docs says that 4~8G will be enough. I allocate 8G for the virtual machine. If I use `-j2` or more threads to compile the BE, `cc1plus` will be terminated due to OOM when  compiling `aggregate_function_XXX.cpp` . So I use `-j1` to reduce the memory demand. However, when compiling `aggregate_function_min_maxby.cpp`, it soon consumed all the memory and after a long time `cc1plus` was terminated due to OOM. I wonder if it's casued by the memory leak of `cc1plus` or somthing else. Thank you.

**Comment by Yukang-Lian** [comment]
you can add my wechat `abmdocrt_lyk`.

**Comment by bobhan1** [comment]
> you can add my wechat `abmdocrt_lyk`.

OK
