### ISSUE TITLE
[Feature] (array_function) support array_flatten function

### ISSUE THREAD

**Issue by bobhan1** [apache/doris#17433]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by bobhan1** [comment]
Do we need to do type conversion or promotion if the type of the values in innermost arrays are different with each other?

**Comment by eldenmoon** [comment]
@bobhan1  you could reference to function `array()`, it has a promotion rule, you could try it to test.

**Comment by bobhan1** [comment]
> @bobhan1 you could reference to function `array()`, it has a promotion rule, you could try it to test.

It seems that it doesn't support nested array now? I add some nested array test for `array()` in `test_array_functions_by_literal.groovy` and it fails.
```
qt_sql "select array([])"
qt_sql "select array([1, 2], [3], [4, 5])"
```

**Comment by eldenmoon** [comment]
> > @bobhan1 you could reference to function `array()`, it has a promotion rule, you could try it to test.
> 
> It seems that it doesn't support nested array now? I add some nested array test for `array()` in `test_array_functions_by_literal.groovy` and it fails.
> 
> ```
> qt_sql "select array([])"
> qt_sql "select array([1, 2], [3], [4, 5])"
> ```

Yes we do not support nested array for now, i'll disscuss this feature soon.But before the nested array compleletd, could you please pick anthoer array function?

**Comment by bobhan1** [comment]
> > > @bobhan1 you could reference to function `array()`, it has a promotion rule, you could try it to test.
> > 
> > 
> > It seems that it doesn't support nested array now? I add some nested array test for `array()` in `test_array_functions_by_literal.groovy` and it fails.
> > ```
> > qt_sql "select array([])"
> > qt_sql "select array([1, 2], [3], [4, 5])"
> > ```
> 
> Yes we do not support nested array for now, i'll disscuss this feature soon.But before the nested array compleletd, could you please pick anthoer array function?

OK, I'll try another one. Please remove me out from the table in doris future
