### ISSUE TITLE
[Feature] (array function) support array_enumerate_uniq function

### ISSUE THREAD

**Issue by bobhan1** [apache/doris#17448]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by bobhan1** [comment]
@eldenmoon  `gensrc/script/doris_builtins_functions.py`中有没有办法表示任意长度的入参？因为`array_enumerate_uniq()`函数的参数个数是可以是任意的。还是说现阶段我们只能手动枚举不同参数个数(一定范围内)的函数签名？

**Comment by eldenmoon** [comment]
@bobhan1 参考下`array()`函数， 参数个数可以是任意的
