### ISSUE TITLE
[Enhancement](webui) query profile ui page is too wide when the sql is very long

### ISSUE THREAD

**Issue by yiguolei** [apache/doris#17589]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

![image](https://user-images.githubusercontent.com/9208457/223884082-e3d055c7-e7c6-40f9-b494-5d5c566f8a33.png)

The sql statement column in profile page, try to display the total sql in the page, but f the sql is very very long the page is not very well. I think maybe we could limit the width of the page and only display part of the long sql. For example display it in a multi line text field.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by PasunuriSrinidhi** [comment]
To address the issue of the query profile UI page being too wide when the SQL is very long, I want to implement the following enhancements:

1. Text wrapping

2. Collapsible sections

3. Horizontal scrolling

4. Responsive design
          
I want to work on this issue. can you please assign this issue to me?
