### ISSUE TITLE
[Enhancement] refactor `Nereids Unit Test` by match-pattern

### ISSUE THREAD

**Issue by jackwener** [apache/doris#17625]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Currently, EliminateFilterTest directly check PlanTree by checking Memo.

Use MemoPatternMatchSupported to match result.

A example is  `ExtractFilterFromCrossJoinTest`

- [ ] MergeFiltersTest
- [ ] EliminateLimitTest 
- [ ] EliminateFilterTest
- [ ] SplitLimitTest
- [ ] FindHashConditionForJoinTest

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jackwener** [comment]
> Thanks @jackwener for creating this, I would like to try `EliminateLimitTest` and `EliminateFilterTest`.

Thanks @reswqa , assigned to you

**Comment by reswqa** [comment]
Since no one else claimed remaining tasks, I'm willing to continue to close this issue completely.
BTW, I have refactored all unit tests under `org.apache.doris.nereids.rules` by match-pattern, not only the remaining parts in the list.
