### ISSUE TITLE
[Enhancement](clear profile) add clear profile support in FE 

### ISSUE THREAD

**Issue by yiguolei** [apache/doris#17650]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

If set enable_profile=true, there will be many many profiles. Until FE restart.
Could add a SQL: CLEAR QUERY PROFILE; 

Then will clear all the profiles on this FE.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by nextdreamblue** [comment]
let me add this feature
