### ISSUE TITLE
[Bug] Logical bug about `where true not in (columns)`

### ISSUE THREAD

**Issue by ChaseHuangxu** [apache/doris#17697]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Apache Doris 1.2.2 Release

### What's Wrong?

I'm trying to add Apache Doris support to SQLancer, this may be a logic bug found by @[SQLancer](https://github.com/sqlancer/sqlancer).

You can reproduce this error from the following steps.

1. `CREATE TABLE t3(c0 BOOLEAN NOT NULL DEFAULT 'false') DISTRIBUTED BY RANDOM BUCKETS 5 PROPERTIES ("replication_num" = "1");`
2.  `insert into t3 values (true),(true),(true);`

<img width="918" alt="image" src="https://user-images.githubusercontent.com/91189188/224504762-ef42efdc-2e62-4707-90d9-785217340077.png">

3. SELECT ALL DATAS;
<img width="193" alt="image" src="https://user-images.githubusercontent.com/91189188/224504897-915d5403-aa2a-460e-9897-35a08d30b4b5.png">

4. `select (true NOT IN (t3.c0)) from t3;`  The SQL result is below, that is to say, when the data in column c0 is all true, **`true NOT IN (t3.c0)` returns all false**
<img width="346" alt="image" src="https://user-images.githubusercontent.com/91189188/224505173-e6079225-4cd5-45e2-8b29-c0965775713e.png">

5. `SELECT t3.c0 FROM t3 WHERE (true NOT IN (t3.c0));` The SQL result is below, From the results we can see **that `true NOT IN (t3.c0)` returns all true**
<img width="402" alt="image" src="https://user-images.githubusercontent.com/91189188/224505111-62119e49-dd04-4351-865c-5cb0ee238f6b.png">

### What You Expected?

The return result of  step 5. `SELECT t3.c0 FROM t3 WHERE (true NOT IN (t3.c0));` should be empty.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ChaseHuangxu** [comment]
Hey, I found another similar question.

**Comment by BiteTheDDDDt** [comment]
fixed on https://github.com/apache/doris/pull/19471
