### ISSUE TITLE
[Bug] sequence列删除成功之后，无法新增一模一样的数据

### ISSUE THREAD

**Issue by dearMOMO** [apache/doris#17739]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.2 

### What's Wrong?

你好 
这边发现一个问题(不确定是不是BUG)。使用的是主键模型【当存在sequence列时，将与导入数据key 相同的数据全部删除】；删除数据时按照sequence列进行删除。删除成功之后，我想恢复这条数据，于是我又重新同步了一条相同的一份数据，这条数据无法新增成功，streamload返回成功；可是当我把sequence列字段的值设置的比原先大的时候，又可以新增数据；

这个是分两次执行的事务的， 删除了一条数据，然后又新增了一条一模一样的数据，结果看不到

### What You Expected?

被删除的数据，我新增相同的数据，依然可以查询出来

### How to Reproduce?

**1.项目运行地址**

https://gitee.com/momoriven/ApacheDoris.git

**2.创建数据库**
CREATE DATABASE example_db;

**3.执行建表语句**

> CREATE TABLE IF NOT EXISTS example_db.unique_detail (
>     `user_id` VARCHAR(30) NOT NULL COMMENT "用户id",
>     `register_time` DATE COMMENT "用户注册时间",
>     `username` VARCHAR(50)  COMMENT "用户昵称",
>     `city` VARCHAR(20) COMMENT "用户所在城市",
>     `age` SMALLINT COMMENT "用户年龄",
>     `sex` TINYINT COMMENT "用户性别",
>     `phone` LARGEINT COMMENT "用户电话",
>     `address` VARCHAR(500) COMMENT "用户地址"
> 
>     )
>     ENGINE = olap UNIQUE KEY ( `user_id`,`register_time` )
>     COMMENT  "This is my first DORIS table"
>     PARTITION BY RANGE(register_time)
>     --批量建分区
> (
>    FROM ("2021-01-01") TO ("2030-12-31") INTERVAL 1 MONTH
> )
>     DISTRIBUTED BY HASH ( `user_id` ) BUCKETS 32
>     PROPERTIES
> (
>     "function_column.sequence_col" = 'age',
>     "replication_num" = "1", --副本数。默认副本数为3。如果 BE 节点数量小于3，则需指定副本数小于等于 BE 节点数量。
>     "enable_unique_key_merge_on_write" = "true",
>     "in_memory" = "false"
> );
> 
>
> 

**4修改doris的ip**

![image](https://user-images.githubusercontent.com/34231503/224631696-288f38b6-18e2-44d8-9aff-c783fa5f1d17.png)

**5.同步数据**

![image](https://user-images.githubusercontent.com/34231503/224631897-93b21a69-10b8-42e6-8dcc-e4a4a39383b2.png)

数据新增成功

![image](https://user-images.githubusercontent.com/34231503/224632050-50aab07d-8f1e-41a2-af84-819f54e59209.png)

**6.删除数据**

![image](https://user-images.githubusercontent.com/34231503/224632413-f0d8f86d-e397-498b-ab41-0a444b927a19.png)

删除数据成功

![image](https://user-images.githubusercontent.com/34231503/224632923-f5bae94a-4676-4cd2-bb25-547e8e7bc46a.png)

**6.新增刚刚被删除一条一摸一样的数据**

![image](https://user-images.githubusercontent.com/34231503/224633930-eec9c87f-72ac-4111-b714-f011b6581336.png)

streamload执行成功

![1678692169444](https://user-images.githubusercontent.com/34231503/224633799-84bb4941-75dc-46a6-96b4-1df37dfb347f.jpg)

可是数据并没有进入数据库
![image](https://user-images.githubusercontent.com/34231503/224634477-ed7863d5-c151-4a8c-b5de-1c725e8bf479.png)

![image](https://user-images.githubusercontent.com/34231503/224634615-e7bd0025-088b-4bc7-9bf1-d53b6a602377.png)

![image](https://user-images.githubusercontent.com/34231503/224634701-23d14bb6-8ad4-476f-bd97-73d0c16c8d11.png)

### 接下来是很诡异的操作一幕
**7.删除数据库，重新建库和建表**
参考第2、3点步骤

**8.同步数据**
![image](https://user-images.githubusercontent.com/34231503/224642661-0d53e061-bdac-4e63-9d7a-a0d8cf855277.png)

### **9.删除数据**
需要注意的是，将137行的代码  int age = 30;   改为int age = 28;  【原来是30，现在改为和原始数据一样的数字，  28】
![微信图片_20230313161341](https://user-images.githubusercontent.com/34231503/224643942-ed9b300e-8e14-4243-9829-3d99545722a9.png)

数据是可以删除成功的

**10.现在同步数据**
![image](https://user-images.githubusercontent.com/34231503/224644476-164971f2-86ef-4700-938c-c9204e470a62.png)

数据可以同步成功
![image](https://user-images.githubusercontent.com/34231503/224644682-317f6d2e-3636-4c6d-93b2-07466a4ea16d.png)

### **11、本人结论**
如果 sequence_col 的值和原值一样，删除之后是可以新增成功的，并且可以查询到数据；
如果 sequence_col 的值大于原值，删除之后是可以新增成功的，但是无法查询到数据；

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhannngchen** [comment]
discussed with @dearMOMO , the behavior is expected
sequence column provides a way to get consistent result even the data is loaded out of order
for more detail, see the document: https://doris.apache.org/zh-CN/docs/dev/data-operate/update-delete/batch-delete-manual
