### ISSUE TITLE
Doris1.2.2 通过HMS 访问 Iceberg异常[Bug] 

### ISSUE THREAD

**Issue by liugs0213** [apache/doris#17746]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-1.2.2-rc01-a3521b3

### What's Wrong?

1.Iceberg底层存储使用S3

通过Iceberg Catalog连接HMS, Doris读取的数据为NULL,hive读取数据正常
![image](https://user-images.githubusercontent.com/55676558/224663006-0f23ab38-c3c7-41d9-9489-779922f33440.png)

### What You Expected?

希望能通过Doris读取和HMS相同的数据

### How to Reproduce?

通过spark连接HMS 创建表并且插入n条数据，然后使用hive读正常，使用doris读却未null

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by morningman** [comment]
What is your hive version?
And what is the file format?

**Comment by liugs0213** [comment]
> What is your hive version? And what is the file format?

hive version: 3.1.2
![image](https://user-images.githubusercontent.com/55676558/224715967-88a88e1e-2b4c-4d9c-a4d6-a0ccbacfafba.png)
fileformat: parquet

**Comment by morningman** [comment]
This may because the file column name not matched with name in table.
You can try following step to check:

1. use table value function `hdfs()`: https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-functions/table-functions/hdfs
To read the parquet file directly.

You can also use `describe function hdfs(xx)` to check the column name in parquet file, to see if they are same.

**Comment by liugs0213** [comment]
> 



> This may because the file column name not matched with name in table. You can try following step to check:
> 
> 1. use table value function `hdfs()`: https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-functions/table-functions/hdfs
>    To read the parquet file directly.
> 
> You can also use `describe function hdfs(xx)` to check the column name in parquet file, to see if they are same.

1.function hdfs() s3 not supported:
![image](https://user-images.githubusercontent.com/55676558/224911250-e7d8af43-7a93-4922-81d6-e27b69651656.png)
2.Using spark to read and view metadata columns is the same:
![image](https://user-images.githubusercontent.com/55676558/224911463-9c35fe27-e2ba-41dd-869b-4a75dfe5769f.png)
![image](https://user-images.githubusercontent.com/55676558/224911574-2b1ff163-6bf6-49cc-bbae-d8d49621834e.png)

**Comment by liugs0213** [comment]
> This may because the file column name not matched with name in table. You can try following step to check:
> 
> 1. use table value function `hdfs()`: https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-functions/table-functions/hdfs
>    To read the parquet file directly.
> 
> You can also use `describe function hdfs(xx)` to check the column name in parquet file, to see if they are same.

function s3() is ok:
![image](https://user-images.githubusercontent.com/55676558/224912662-aa24b3cb-867f-472d-bf4c-b910568fbfe0.png)

**Comment by morningman** [comment]
It is strange.
This is my wechat: morningman-cmy, you can contact me in private.

**Comment by liugs0213** [comment]
> It is strange. This is my wechat: morningman-cmy, you can contact me in private.

在大佬的建议下，升级到最新版本解决
