### ISSUE TITLE
[Bug] 1.2 +version,No matching function with signature: collect_list(varchar(11), tinyint(4))

### ISSUE THREAD

**Issue by caoliang-web** [apache/doris#17761]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-1.2.1-rc01-Unknown

### What's Wrong?

CREATE TABLE test.`test_insert` (
   `id` varchar(11) NULL COMMENT '唯一标识',
   `name` varchar(10) NULL COMMENT '采集时间',
   `age` int(11) NULL
) ENGINE=OLAP
DUPLICATE KEY(`id`)
COMMENT 'test'
DISTRIBUTED BY HASH(`id`) BUCKETS 10
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"in_memory" = "false",
"storage_format" = "V2",
"light_schema_change" = "true",
"disable_auto_compaction" = "false"
);

insert into test.`test_insert` values (1,'a',40),(2,'b',50),(3,'c',60);
insert into test.`test_insert` values (1,'a',40),(2,'b',50),(3,'c',60);

mysql> select collect_list(id,2) from test_insert;
ERROR 1105 (HY000): errCode = 2, detailMessage = No matching function with signature: collect_list(varchar(11), tinyint(4)).

### What You Expected?

Support collect_list(id,2) syntax

### Anything Else?

collect_set() same question

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LemonLiTree** [comment]
fixed
