### ISSUE TITLE
[Bug] 相同的join查询，当join的键(字段名)大写和小写的时候，系统匹配的join方式不同

### ISSUE THREAD

**Issue by Bingchen1512** [apache/doris#17876]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

**doris 1.2.2**

### What's Wrong?

**相同的join查询，当join的键(字段名)大写和小写的时候，系统匹配的join方式不同。**

建表语句中`CGENERALHID `和`CGENERALHID`使用的大写。

```mysql
# 使用字段名大写join关联
explain select TAUDITTIME,NNUM
from
ods_ic_saleout_h salehead
LEFT JOIN ods_ic_saleout_b salebody ON salehead.CGENERALHID = salebody.CGENERALHID
limit 100;
```
  2:VHASH JOIN
  |  join op: LEFT OUTER JOIN(BUCKET_SHUFFLE)[Tables are not in the same group]
  |  is mark: false
  |  equal join conjunct: `salehead`.`CGENERALHID` = `salebody`.`CGENERALHID`
"  |  cardinality=142,073"
  |  vec output tuple id: 2
  |  vIntermediate tuple ids: 3 4 
  |  output slot ids: 7 10 
  |  hash output slot ids: 2 3 
  |  limit: 100

```mysql
# 使用字段名小写join关联
explain select TAUDITTIME,NNUM
from
ods_ic_saleout_h salehead
LEFT JOIN ods_ic_saleout_b salebody ON salehead.cgeneralhid = salebody.cgeneralhid
limit 100;
```
  2:VHASH JOIN
  |  join op: LEFT OUTER JOIN(BROADCAST)[Tables are not in the same group]
  |  is mark: false
  |  equal join conjunct: `salehead`.`cgeneralhid` = `salebody`.`cgeneralhid`
"  |  cardinality=142,073"
  |  vec output tuple id: 2
  |  vIntermediate tuple ids: 3 4 
  |  output slot ids: 7 10 
  |  hash output slot ids: 2 3 
  |  limit: 100

### What You Expected?

doris忽略字段名大小写。但该查询中，字段名大小写影响join方式。
字段名大小写join关联，是否会影响join方式。

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by GoGoWen** [comment]
seems an issue. i will take it.

**Comment by Bingchen1512** [comment]
Hello, can you add this bug fix in the next minor version update, such as 1.2.4, thank you.
