### ISSUE TITLE
[Bug] Failed to deserialize parquet page header

### ISSUE THREAD

**Issue by Chris-Arith** [apache/doris#17950]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.1

### What's Wrong?

When we use broker load to load data into Doirs, sometimes, it will show an error message like `ErrorMsg=type:LOAD_RUN_FAIL; msg:errCode = 2, detailMessage = Failed to deserialize parquet page header` and stop the load process.
But these data can be read in Hue correctly.
Then we load data partition by partition, and locate the partition that causes this problem.
However, these data has nothing special with others. And we download this file and open with `ParquetViewer` , it also can be viewed.

### What You Expected?

I think this problem should not happen, and at leaset, it should tell us which file has this problem.

### How to Reproduce?

can't be reproduced 100%

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Chris-Arith** [comment]
> Doris 1.2.3 has been released today. You can try it with Doris 1.2.3, which fixes the problem of reading parquet files.

thanks a lot. Can you give us a brief overview of the cause of why this problem happened and does this problem occur occasionally？

**Comment by will0815** [comment]
sql : select count(1) from hive.dws.tb1;
error :
Read parquet file /user/hive/warehouse/dws.db/tb1/000066_0 failed, reason = [IO_ERROR]Failed to deserialize parquet page header. offset: 23203354, header size: 42328, end offset: 23245682, real header size: 42328

doris: doris-2.0.0-rc04
hive CATALOG : 'type'='hms',  'hive.version' = '2.1.1',

**Comment by panthony** [comment]
Tested various parquet files with doris 2.0 and gets the same deserialize parquet page header errors.

I also had a "can't read enough booleans in rle decoder 0" occasionally.

I can read those parquets just fine with any other tools (parquet cli, clickhouse, spark, custom java code, python, ..)

I'm testing the parquet like this:

```sql
SELECT
  ...
FROM s3(
 ...
)
```

**Comment by xingyingone** [comment]
we  met this bug in doris 2.0.3
