### ISSUE TITLE
配置be的enable_quick_compaction参数不成功

### ISSUE THREAD

**Issue by sky1229329146** [apache/doris#18050]
尝试了2种方法
1.在linux上直接使用命令
curl -X POST http://{central02}:{8049}/api/update_config?{enable_quick_compaction}={true}&persist=true;
报错：
"msg": "set enable_quick_compaction=true failed, reason: Not supported: 'enable_quick_compaction' is not support to modify"

2.修改be的配置文件
enable_quick_compaction: true

查看配置参数还是没变
enable_quick_compaction=0

**Comment by GoGoWen** [comment]
doris版本是多少？

**Comment by sky1229329146** [comment]
doris-1.1.1

**Comment by GoGoWen** [comment]
修改配置文件enable_quick_compaction=true， 重启BE， 如果还不生效就升级到1.1.5，

**Comment by sky1229329146** [comment]
可以了
