### ISSUE TITLE
[Enhancement] open only needed partitions when sink

### ISSUE THREAD

**Issue by freemandealer** [apache/doris#18092]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

For example, when loading the latest 1 partition of total 10 partitions, all other 9 partitions will also be opened and generate empty size rowsets after loading.

### Solution

The current logic is to simply open them all because we cannot predict where each row of data is sink to. We need a `lazy open mechanism` here to open only needed partitions.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AdarshRawat1** [comment]
@freemandealer yes I'll work on this enhancement. Please, guide me .

**Comment by freemandealer** [comment]
@AdarshRawat1 Sure. Before we actually start anything, let's do some preparations:

First of all, you need to set up a dev&test environment. Check the links below:
[compile](https://doris.apache.org/docs/dev/install/source-install/compilation-with-ldb-toolchain)
[deploy](https://doris.apache.org/docs/dev/install/install-deploy)

For what we are enhancing is the Load process, we first need to know how to load as a user. Check the user manual:
[streamload manual](https://doris.apache.org/docs/dev/data-operate/import/import-way/stream-load-manual/)

Finally, familiarize yourself with the code base concerning Load (especially the Sink operation): 
```
vtablet_sink.{h,cpp}
internal_service.{h,cpp}
load_channel_mgr.{h,cpp}
load_channel.{h,cpp}
tablets_channal.{h,cpp}
...
```

After finishing these preparations, we can further discuss the proposal of how to implement the lazy-open mechanism for Sink.

BTW, Do you have Skype or Lark or any other IM that can share screen?

**Comment by AdarshRawat1** [comment]
I will commence the necessary arrangements.
Yes, I have Skype.

**Comment by freemandealer** [comment]
> I will commence the necessary arrangements and get familiar with code base. Yes, I have Skype.

Hi @AdarshRawat1 , how is everything going with the tasks? Do not hesitate to contact us if you met any problems. My Skype ID is

![image](https://user-images.githubusercontent.com/6492193/230556305-8e97d6ad-1950-4ac1-9904-6a7d5190bdc1.png)

**Comment by AdarshRawat1** [comment]
Hi @freemandealer, I had exams recently and was unable to work on the tasks. However, I plan to work on this issue on the upcoming Sunday. If I encounter any problems, I will be sure to contact you. Thank you for your understanding.

**Comment by freemandealer** [comment]
> Hi @freemandealer, I had exams recently and was unable to work on the tasks. However, I plan to work on this issue on the upcoming Sunday. If I encounter any problems, I will be sure to contact you. Thank you for your understanding.

@AdarshRawat1 Sure. Take your time.

I'll list my proposal briefly below so you can have a reference:

Since the problem is opening tablets from all partitions no matter whether the data is actually sent to the partition or not, we plan to open the tablets from the partition only when there is data coming for it.

Original flow:
```
// Before sending data throught SinkNode
PInternalServiceImpl::tablet_writer_open
-> LoadChannel::open
  -> TabletsChannel::open
      -> _open_all_writers(request)
           -> for all tablets open DeltaWriter

// then send data
tablet_writer_add_block
-> LoadChannelMgr
  -> LoadChannel
      -> TabletsChannel::add_batch
          -> DeltaWriter write data
```

New flow:
```
// Before sending data throught SinkNode
PInternalServiceImpl::tablet_writer_open
-> LoadChannel::open
  -> TabletsChannel::open
      ->  no more open writers

// then send data
tablet_writer_add_block
-> LoadChannelMgr
  -> LoadChannel
      -> TabletsChannel::add_batch
         -> if specific DeltaWriter is not opened, open it in place before write
```

**Comment by AdarshRawat1** [comment]
Thank you @freemandealer

**Comment by freemandealer** [comment]
@AdarshRawat1 I am sorry but had to ask about your progress. Our community users are experiencing many problems related to #18092,so fixing this issue has become more urgent than before.

If you have already started coding, we can discuss how to make the process faster.

If you have not fully started the project yet, no need to feel pressured about it. I can do it myself. Apache Doris still needs your help in other issues. Feel free to check other issues in [Good First Issues]( https://github.com/apache/doris/issues/17176).

**Comment by AdarshRawat1** [comment]
@freemandealer, I am currently working on resolving the issue. Let us continue our discussion on Skype to further address the matter.

**Comment by freemandealer** [comment]
@Yukang-Lian I am doing the task myself since it has higher priority than the time it is created. So no need to add it to the GoodFirstIssues pool. Thanks.
