### ISSUE TITLE
jdbc catalog链接oracle外部数据源，拉取元数据遇到含有非法字符的表名报错问题

### ISSUE THREAD

**Issue by Allen-zy** [apache/doris#18195]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris version : 1.2.3
one follower two observer

### What's Wrong?

创建了oracel 的jdbc catalog,doris拉取oracle库的元数据信息，遇到含有类似‘/’转义字符的表名，导致拉取元数据信息失败，线程一直被占用，使用canal等外部实时同步工具需要访问doris的information_schema或者再mysql客户端执行相关查询语句时，会堵塞报错，另外除去information_schema库以外其他库表的查询也会带有警告，且查询速度较慢。
查询警告如下 RpcException, msg: org.apache.doris.rpcRpcException: (xxx.xxx.xx.x)[THRIFT RPC ERRORJfailed to cal frontend service
fe报警日志如下：
2023-03-28 13:01:40,235 WARN (thrift-server-pool-5|516) [TableIf.getBaseSchemaOrEmpty():84] failed to get base schema for table SYSNTYJOpFHSJRB2RQ2A6/R0MVw==
com.google.common.util.concurrent.UncheckedExecutionException: org.apache.doris.external.jdbc.JdbcClientException: failed to get table name list from jdbc for table SYSNTYJOpFHSJRB2RQ2A6/R0MVw==:java.sql.SQLDataException: ORA-01424: missing or illegal character following the escape character

### What You Expected?

希望oracle jdbc catalog能够过滤含有非法字符的表，或者访问指定用户表

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by morningman** [comment]
Please provide table schema in oracle
