### ISSUE TITLE
[Enhancement] Support type conversion between float text and int

### ISSUE THREAD

**Issue by ChaseHuangxu** [apache/doris#18227]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Doris can support type conversion for float text to float, and float to int, but cannot support type conversion for float text to int.
See below, 
![image](https://user-images.githubusercontent.com/91189188/228531306-e64ff8c1-c87b-4b69-8ac6-a34b7539539f.png)

And in mysql, float text can be converted to signed integer.
<img width="542" alt="image" src="https://user-images.githubusercontent.com/91189188/228531608-4c95ee7e-911d-48f0-b307-4874ed641fd9.png">

So I think the float text conversion to int should be supported in Doris.

### Solution

support cast('float text' as int)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dataroaring** [comment]
It works on nerieds.
