### ISSUE TITLE
[Feature] support array_last function, get the last element of the array

### ISSUE THREAD

**Issue by herry2038** [apache/doris#18266]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Support arrayLast(func, arr1) High-order function, which 
Returns the last element in the arr1 array for which func(arr1[i]...) returns something other than 0.
You must pass a lambda function to it as the first argument, and it can’t be omitted.
The lambda function must have UInt8 output type.

### Use case

select  arrayLast((a)->(a > 3), [0,1,2,3,4,5,6,7,8,9,1])  as last_element

with result:
9

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dataroaring** [comment]
@herry2038 You'd better link an similar pr, then developers can learn from it.

**Comment by zhangstar333** [comment]
@slience-club you could see here first, and this implement maybe have a  help  for you
