### ISSUE TITLE
[Bug] SQL function: datediff, return error

### ISSUE THREAD

**Issue by hahafly** [apache/doris#18303]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

v1.1.1

### What's Wrong?

when run query below:
select datediff('2023-03-27', '2023-03-26');
return 0

### What You Expected?

return 1, '2023-03-27' - '2023-03-26' supposed to be 1

### Anything Else?

select datediff('2023-12-31', '2023-01-01');
return 364, correct, so I don't now what's wrong with select datediff('2023-03-27', '2023-03-26');

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liujiwen-up** [comment]
upgrade can solve
