### ISSUE TITLE
[Bug] array_map function should be compared offset rows one by one

### ISSUE THREAD

**Issue by zhangstar333** [apache/doris#18348]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

array_map function it's needs the input array column have same offset, 
so should be compared offset rows one by one

### What You Expected?

running ok

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhangstar333** [comment]
@herry2038 hi, when you resolve the problem, and link this issue in your PR

**Comment by herry2038** [comment]
> @herry2038 hi, when you resolve the problem, and link this issue in your PR

ok
