### ISSUE TITLE
[Feature] java udf/udaf support columns as function parameters like builtin function PERCENTILE

### ISSUE THREAD

**Issue by czzmmc** [apache/doris#18343]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Sometimes we want to make a function with extra parameters during running time. In order not to create multiple functions which it's really tedious, we usually make a general function with an extra parameter. When we use it, we could pass different value to do different work. 

### Use case

For example, think about we create a java udaf to copy the function of builtin function PERCENTILE. We do need this new feature to finish the job.

### Related issues

None

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhangstar333** [comment]
could you be more detailed or give a simple demo?   thanks!

**Comment by czzmmc** [comment]
Of course. Image we have a table named t_salary  for employees' salary management. And we only have two members. Like blow.
t_salary
```
Alice 100
Bob   200
``` 
And now we have a Java UDF "cal_bonus" to calculate bonus for them. Here comes our way. The manager wanna set a number depending on how they behave during last year. So for this particular example, the manager would give Alice 300, and Bob 200. 
Now, our Java UDAF cal_bonus must take two parameters a rule and a salary column. Like cal_bonus(rule, salary).
SQL: select name, cal_bonus('{"Alice": 300, "Bob":200}', salary) from t_salary;
RESP: 
```
name   cal_bonus
Alice  400
Bob    400
``` 
The next year, we could continue to use this Java UDAF with different rule, when we hire more employees.

**Comment by zhangstar333** [comment]
I'm so sorry,  I can't understand the example 😂,
seems you wants an init state, like '{"Alice": 300, "Bob":200}' ?
and then add the data from table 100,200
get the RESP
