### ISSUE TITLE
[Bug] doris-be install and startup happen error

### ISSUE THREAD

**Issue by tiandong19860806** [apache/doris#18402]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-be 1.2.2

### What's Wrong?

当我按照安装文档，执行doris-be组件的安装，启动成功后一段时间后报错如下：

/bin/limit3 命令找不到

### What You Expected?

请告知，启动脚本 doris-be-startup.sh中命令 /bin/limit3，
具体来自哪个软件安装包，请提供对应官方下载地址。

### How to Reproduce?

N/A

### Anything Else?

N/A

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JackDrogon** [comment]
start_be中已经检测了limit3是否存在了，能给出具体的报错日志吗

**Comment by tiandong19860806** [comment]
Hi @JackDrogon ,

系统中没有这个命令“/bin/limit3”, 这个是doris-be模块启动脚本使用的，见文件start_be.sh第246行，和

# 180行
if [[ ! -f '/bin/limit3' ]]; then
    LIMIT=''
else
    LIMIT="/bin/limit3 -c 0 -n 65536"
fi

# 246行
if [[ "${RUN_DAEMON}" -eq 1 ]]; then
    nohup ${LIMIT:+${LIMIT}} "${DORIS_HOME}/lib/doris_be" "$@" >>"${LOG_DIR}/be.out" 2>&1 </dev/null &
else
    export DORIS_LOG_TO_STDERR=1
    ${LIMIT:+${LIMIT}} "${DORIS_HOME}/lib/doris_be" "$@" 2>&1 </dev/null
fi

# 报错信息，如下：
[root@CNT7XDRS01 /]# journalctl -u doris -n 10
-- Logs begin at Tue 2023-04-11 22:07:36 CST, end at Tue 2023-04-11 22:53:50 CST. --
Apr 11 22:53:50 CNT7XDRS01 start_be.sh[5291]: 11# doris::LibJVMLoader::instance() at /root/doris/be/src/util/libjvm_loader.cpp:54
Apr 11 22:53:50 CNT7XDRS01 start_be.sh[5291]: 12# doris::JniUtil::Init() at /root/doris/be/src/util/jni-util.cpp:217
Apr 11 22:53:50 CNT7XDRS01 start_be.sh[5291]: 13# main at /root/doris/be/src/service/doris_main.cpp:380
Apr 11 22:53:50 CNT7XDRS01 start_be.sh[5291]: 14# __libc_start_main in /lib64/libc.so.6
Apr 11 22:53:50 CNT7XDRS01 start_be.sh[5291]: 15# _start in /home/app/doris/lib/doris_be
Apr 11 22:53:50 CNT7XDRS01 start_be.sh[5291]: /home/app/doris/bin/start_be.sh: line 246:  5718 Aborted                 ${LIMIT:+${LIMIT}} "${DORIS_HOME}/lib/doris_be" "$@" 2>&1 < /dev/null
Apr 11 22:53:50 CNT7XDRS01 systemd[1]: doris.service: main process exited, code=exited, status=134/n/a
Apr 11 22:53:50 CNT7XDRS01 systemd[1]: Failed to start doris service.
Apr 11 22:53:50 CNT7XDRS01 systemd[1]: Unit doris.service entered failed state.
Apr 11 22:53:50 CNT7XDRS01 systemd[1]: doris.service failed.
[root@CNT7XDRS01 /]# 
[root@CNT7XDRS01 /]#

**Comment by tiandong19860806** [comment]
而且， 我尝试用安装yum install -y util-linux，安装完之后，也没有命令：/bin/limit3。

**Comment by JackDrogon** [comment]
@tiandong19860806 你的问题不是limit3的问题，它使用了-f检测了命令，如果没有就直接LIMIT=""了

**Comment by JackDrogon** [comment]
看一些be.out中的输出吧

**Comment by tiandong19860806** [comment]
@JackDrogon ， 谢谢你的提醒，我换个思路试一下。

**Comment by tiandong19860806** [comment]
jdk版本导致，从jdk-12换成jdk-8，就可以了。
