### ISSUE TITLE
[Bug] rlike error

### ISSUE THREAD

**Issue by stalary** [apache/doris#18449]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.3

### What's Wrong?

select * from dwd.dwd_test where origin_financing_amount rlike '近|级|数|超' limit 10;
-- [RUNTIME_ERROR]hs_compile regex pattern error:Unsupported architecture

### What You Expected?

run success, it can work in 1.1.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by milton4code** [comment]
1.2.3这个版本bug一堆,难道是实习生提交的pr?

**Comment by morningman** [comment]
> 1.2.3这个版本bug一堆,难道是实习生提交的pr?

I can' t find any of your contribution to Doris, so stop complaint and show me your useful suggestion!

**Comment by stalary** [comment]
https://github.com/apache/doris/pull/18468
