### ISSUE TITLE
[Enhancement] (compaction) stop tablet compaction when table truncated

### ISSUE THREAD

**Issue by yixiutt** [apache/doris#18446]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

When truncate table, tablet in be will still do compaction as current tablet in be has no information about table status in fe.
So, we have to build a relation in be tablet and fe table truncate status.

### Solution

add a tablet status and make fe and be related when truncate table

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TangSiyang2001** [comment]
May I have a try if the task is not in mergency?

**Comment by gitccl** [comment]
> May I have a try if the task is not in mergency?

Hi, I'm sorry that I picked up this task in #17176. Could you give me this task if you haven't started it yet?

**Comment by TangSiyang2001** [comment]
> Hi, I'm sorry that I picked up this task in #17176. Could you give me this task if you haven't started it yet?
OK, I haven't started yet.
