### ISSUE TITLE
[Bug] The query result is not stable, sometimes is empty

### ISSUE THREAD

**Issue by lide-reed** [apache/doris#18466]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-1.2.3-rc02-d69c2ce

### What's Wrong?

MySQL [testdb]> SELECT * FROM t1 WHERE c1=(SELECT max(c1) FROM t1);
Empty set (0.02 sec)

MySQL [testdb]> SELECT * FROM t1 WHERE c1=(SELECT max(c1) FROM t1);
+---------------------+----------+
| c1                  | c2       |
+---------------------+----------+
| 2023-04-06 00:00:00 | zhangsan |
+---------------------+----------+
1 row in set (0.02 sec)

### What You Expected?

MySQL [testdb]> SELECT * FROM t1 WHERE c1=(SELECT max(c1) FROM t1);
+---------------------+----------+
| c1                  | c2       |
+---------------------+----------+
| 2023-04-06 00:00:00 | zhangsan |
+---------------------+----------+
1 row in set (0.02 sec)

### How to Reproduce?

CREATE TABLE t1
(
c1 datetime,
c2 string
)
UNIQUE KEY(c1)
DISTRIBUTED BY HASH(c1) BUCKETS 2;

insert into t1 values('2023-04-06 00:00:00', 'zhangsan');
insert into t1 values('2023-04-05 00:00:00', 'lisi');

SELECT * FROM t1 WHERE c1=(SELECT max(c1) FROM t1);

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lide-reed** [comment]
[profile_wrong.txt](https://github.com/apache/doris/files/11177763/profile_wrong.txt)
[profile_right.txt](https://github.com/apache/doris/files/11177764/profile_right.txt)

**Comment by jacktengg** [comment]
@lide-reed Hi, I used the same version and 1fe 3be and cannot reproduce this problem, is there any special vars of config in your env?

**Comment by zzzzzzzs** [comment]
> @lide-reed Hi, I'm investigating this issue, I used the same version and 1fe 3be and cannot reproduce this problem, is there any special vars or config in your env?

I can reproduce this problem.You need to execute the query statement multiple times.
