### ISSUE TITLE
[Bug]  Jdbc connector _register_func_id meet error and error is NoSuchMethodError: convert Date To Long

### ISSUE THREAD

**Issue by inventertom** [apache/doris#18489]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris 1.2.3
mssel-jdbc-11.2.3.jre8.jar
mssel-jdbc-12.2.0.jre8.jar
mssel-jdbc-8.4.1.jre8.jar

### What's Wrong?

利用外表 查询sqlserver 数据 报，Execution failed: Error Failed to execute sql: java.sql.SQLException: (conn=839) errCode = 2, detailMessage = Jdbc connector _register_func_id meet error and error is NoSuchMethodError: convertDateToLong

### What You Expected?

支持 converDateToLong

### How to Reproduce?

sqlserver schema 
CREATE TABLE [dbo].[rt_prdSNTraceDetail](
	[ProcessTraceID] [dbo].[dm_SystemID] NOT NULL,
	[PrdID] [dbo].[dm_SystemID] NOT NULL,
	[ParentPrdID] [dbo].[dm_SystemID] NULL,
	[inDTime] [datetime] NOT NULL,
	[AssemblyType] [varchar](12) NOT NULL
 CONSTRAINT [PK_rt_prdSNTraceDetail] PRIMARY KEY CLUSTERED 
(
	[ProcessTraceID] ASC,
	[PrdID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)

Doris schema
CREATE EXTERNAL RESOURCE sqlserver_resource1
properties (
    "type"="jdbc",
    "user"="DaasUser",
    "password"="Kaifa#daasuser",
    "jdbc_url"="jdbc:sqlserver://xxxxxx:xxxx;databaseName=KFDB_Mes_CSBU2",
    "driver_url"="http://xxxxxxx.xxxxx/mssql-jdbc-12.2.0.jre8.jar",
    "driver_class"="com.microsoft.sqlserver.jdbc.SQLServerDriver"
);

CREATE EXTERNAL TABLE sqlserver_db.external_test1(
       ProcessTraceID STRING NOT NULL,
       PrdID STRING NOT NULL ,
       ParentPrdID STRING NULL ,
       inDTime datetimev2 not NULL,
       AssemblyType Varchar(12) NOT NULL
) ENGINE=JDBC
COMMENT 'JDBC'
PROPERTIES (
"resource" = "sqlserver_resource1",
"table" = "rt_PrdSNTraceDetail",
"table_type"="sqlserver"
);

select * from external_test1 limit 10;

Execution failed: Error Failed to execute sql: java.sql.SQLException: (conn=839) errCode = 2, detailMessage = Jdbc connector _register_func_id meet error and error is NoSuchMethodError: convertDateToLong

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhangstar333** [comment]
seems your current code of BE is Not consistent with java-udf-jar-with-dependencies.jar under your doris home path be/lib/

**Comment by inventertom** [comment]
> seems your current code of BE is Not consistent with java-udf-jar-with-dependencies.jar under your doris home path be/lib/
The java-udf-jar-with-denpendencies.jar updated to version 1.2.3 ，but still reports the same error, Are there other reasons for this problem?

**Comment by zhangstar333** [comment]
> 
I feel a little strange.
It‘s sure that we deleted convertDateToLong  function on the master.
but you meet this error on doris 1.2.3
I don't know the java-udf-jar-with-denpendencies.jar comes from ?

**Comment by inventertom** [comment]
java-udf-jar-with-denpendencies.jar updated to version 1.2.3，
Download from the official website，
now , Three attempts to execute will succeed once，report the same error,
![E81E3A2A](https://user-images.githubusercontent.com/35754039/231094326-490a46e3-ec19-4414-b9dd-742405316439.PNG)

**Comment by zhangstar333** [comment]
could leave some information about how to contact you?

**Comment by inventertom** [comment]
We upgraded our doris version from 1.2.1 to 1.2.3, 
and we reinstalled Doris to verify that it was an issue caused by doris upgrades across more than 2 versions,
 Thanks for the advice
