### ISSUE TITLE
[Enhancement] add auto increment id support

### ISSUE THREAD

**Issue by dataroaring** [apache/doris#18501]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

https://github.com/apache/doris/issues/15927 requests auto increment id for more real-time bitmap usage.

### Solution

Step1: Add syntax support compatible with mysql. https://dev.mysql.com/doc/refman/8.0/en/example-auto-increment.html

` CREATE TABLE animals (
     id MEDIUMINT NOT NULL AUTO_INCREMENT,
     name CHAR(30) NOT NULL,
 );
`

tasks:
- [ ]  add syntax support in fe/fe-core/src/main/cup/sql_parser.cup
- [ ]  add property for auto-increment column in analysis/ColumnDef.java, especially toColumn.
- [ ]  add auto increment support in catalog/Column.java
DDLs creating table is handled in InternalCatalog::createOlapTable

Step2: Support auto increment column for Duplicated Table
  We can assign range for auto increment column via 2 methods. Option 1,  Currently, Doris finishes a transaction via two phase commit protocol. When a transaction(load, insert into) commits, FE assigns a version for the transaction and publishes it to BEs. FE can also assigns a range for auto increment column for a transaction and BE record it in the meta, then BE can generate values for the column when the column is read.  Option 2, Allocating a range from FE when BE handles data, e.g. for nulls in vtablet_sink and not specified values in delta_writer.cpp.  Considering auto increment column for unique tables, we choose opt 2.

tasks:

- [ ] implement AutoIncrementGenerator in FE.
- [ ] add AutoIncrementGenerator as a member in OlapTable.
- [ ] add get_auto_increment_range in FrontendService.
- [ ] collect auto increment cols from VTabletSink::_schema, we need to add auto increment cols into it even if the auto increment cols is not written.
- [ ] fill values for auto increment cols  in VtabletSlink::send.

Step3: Support auto increment column for Unique Table
  Currently, Doris support two Unique Model, MOR(merge on read) and MOW(merge on write). We can assign a range for auto increment column like the duplicated table. However, it is much more complicated for unique tables, e.g. a row has already existed in a unique table, then a updating happens e.g. write a new row with the same key, then we should assure that the auto increment id keeps unchanged. Actually, columns except keys and auto increment id are updated, so a partial column updating happens. Partial updating on MOW is being reviewed https://github.com/apache/doris/pull/17542.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by cnissnzg** [comment]
I am willing to submit a PR for this issue

**Comment by bobhan1** [comment]
I think we should put the process of filling values for auto increment cols in XXXScaner instead of in `VOlapTable::sink()`, bacause `VOlapTable` lacks some neccessary information here. 
For example, if the user add parameter `-H columns: c1, c2=some_func(c1)` in a stream load task, where `c1` is an auto increment column. We can only calculate the values of `c2` in `VFileScanner::_fill_missing_columns()` becasue `VExprContex` for column transformation is only stored in `VFileScanner` and `VOlapTable` doesn't have the information about this. 
So for load task, the process of generating and filling auto increment values should be in `XXXScanner::_get_block_impl()`.
