### ISSUE TITLE
[Bug] After inserting about 1 million pieces of data, be nodes are down.

### ISSUE THREAD

**Issue by jiayuqiu** [apache/doris#18509]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-1.2.2-rc01-Unknown

### What's Wrong?

After inserting about 1 million pieces of data, be nodes are down.

### What You Expected?

I want to fix my issue.

### Anything Else?

The following is my be log

W0408 16:55:42.616163 728822 mem_tracker_limiter.cpp:226] process full gc
Process Memory Summary:
    OS physical memory 15.64 GB. Process memory usage 14.84 GB, limit 12.51 GB, soft limit 11.26 GB. Sys available memory 0, low water mark 1.56 GB, warning water mark 3.13 GB. Refresh interval memory growth 0 B
Memory Tracker Summary:
    Type=experimental, Used=0(0 B), Peak=0(0 B)
    Type=clone, Used=0(0 B), Peak=0(0 B)
    Type=schema_change, Used=0(0 B), Peak=0(0 B)
    Type=compaction, Used=0(0 B), Peak=0(0 B)
    Type=load, Used=17.38 GB(18656366923 B), Peak=18.13 GB(19471640468 B)
    Type=query, Used=0(0 B), Peak=0(0 B)
    Type=global, Used=-47.41 GB(-50906733492 B), Peak=182.96 MB(191846687 B)
    Type=tc/jemalloc_cache, Used=1.99 GB(2140411248 B), Peak=-1.00 B(-1 B)
    Type=process, Used=-28.04 GB(-30109955321 B), Peak=-1.00 B(-1 B)
    MemTrackerLimiter Label=Orphan, Type=global, Limit=-1.00 B(-1 B), Used=-47.41 GB(-50906733492 B), Peak=294.70 MB(309015126 B)
    MemTrackerLimiter Label=DataPageCache, Type=global, Limit=-1.00 B(-1 B), Used=0(0 B), Peak=0(0 B)
    MemTrackerLimiter Label=IndexPageCache, Type=global, Limit=-1.00 B(-1 B), Used=0(0 B), Peak=0(0 B)
    MemTrackerLimiter Label=SegmentCache, Type=global, Limit=-1.00 B(-1 B), Used=0(0 B), Peak=0(0 B)
    MemTrackerLimiter Label=DiskIO, Type=global, Limit=12.51 GB(13436757606 B), Used=0(0 B), Peak=0(0 B)
    MemTrackerLimiter Label=ChunkAllocator, Type=global, Limit=-1.00 B(-1 B), Used=0(0 B), Peak=0(0 B)
    MemTrackerLimiter Label=LastestSuccessChannelCache, Type=global, Limit=-1.00 B(-1 B), Used=0(0 B), Peak=0(0 B)
    MemTrackerLimiter Label=LoadChannelMgr, Type=load, Limit=-1.00 B(-1 B), Used=0(0 B), Peak=0(0 B)
W0408 16:56:01.377184 729564 global.cpp:242] GlobalUpdate is too busy!
W0408 16:56:02.499681 729563 server.cpp:339] UpdateDerivedVars is too busy!
W0408 16:56:26.899755 729563 server.cpp:339] UpdateDerivedVars is too busy!

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jiayuqiu** [comment]
In log file, `Type=global`, Memory usage is less than 0.

**Comment by yuanyuan8983** [comment]
Let's take a look at this issue together. You can add me on WeChat: cylly810222

**Comment by jiayuqiu** [comment]
> Let's take a look at this issue together. You can add me on WeChat: cylly810222

I can't find you by cylly810222, please add me on WeChat: qiumacs0212

**Comment by jiayuqiu** [comment]
> Let's take a look at this issue together. You can add me on WeChat: cylly810222

I can not find you by cylly810222, please add my on WeChat: qiumacs0212
