### ISSUE TITLE
[Bug] be crashes with doris::OlapMeta::put

### ISSUE THREAD

**Issue by dingzebin** [apache/doris#18516]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

0.15.0

### What's Wrong?

be down, and i get the following log from be.out.

*** Aborted at 1681092305 (unix time) try "date -d @1681092305" if you are using GNU date ***
PC: @          0x13bcf22 doris::OlapMeta::put()
*** SIGSEGV (@0x0) received by PID 16818 (TID 0x7faafad4b700) from PID 0; stack trace: ***
    @          0x214c712 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fab56734630 (unknown)
    @          0x13bcf22 doris::OlapMeta::put()
    @          0x1361205 doris::TabletMetaManager::save()
    @          0x1359a0f doris::TabletMeta::_save_meta()
    @          0x1359ebe doris::TabletMeta::save_meta()
    @          0x133011b doris::Tablet::save_meta()
    @          0x13a8275 doris::Compaction::modify_rowsets()
    @          0x13ab031 doris::Compaction::do_compaction_impl()
    @          0x13ac5d5 doris::Compaction::do_compaction()
    @          0x13ad67a doris::CumulativeCompaction::execute_compact_impl()
    @          0x13a84a3 doris::Compaction::execute_compact()
    @          0x132e728 doris::Tablet::execute_compaction()
    @          0x12ff3ba _ZNSt17_Function_handlerIFvvEZN5doris13StorageEngine35_compaction_tasks_producer_callbackEvEUlvE0_E9_M_invokeERKSt9_Any_data
    @          0x16918f3 doris::ThreadPool::dispatch_thread()
    @          0x168ba3c doris::Thread::supervise_thread()
    @     0x7fab5672cea5 start_thread
    @     0x7fab56153b0d __clone
    @                0x0 (unknown)

### What You Expected?

I want to fix my issue.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yuanyuan8983** [comment]
It seems that it is caused by a problem with the interaction. Version 0.15.0 is a bit old. Can you consider upgrading to a newer version? Let's take a look together. My WeChat account is: cylly810222

**Comment by dingzebin** [comment]
> It seems that it is caused by a problem with the interaction. Version 0.15.0 is a bit old. Can you consider upgrading to a newer version? Let's take a look together. My WeChat account is: cylly810222

If I upgrade to anewer version, do I also need to upgrade the flink and jdbc drivers that are being used? Also, this WeChat account cannot be found by users in the search results.

**Comment by dingzebin** [comment]
> > It seems that it is caused by a problem with the interaction. Version 0.15.0 is a bit old. Can you consider upgrading to a newer version? Let's take a look together. My WeChat account is: cylly810222
> 
> If I upgrade to anewer version, do I also need to upgrade the flink and jdbc drivers that are being used? Also, this WeChat account cannot be found by users in the search results.

I have already seen the corresponding upgrade version on the official website. I will try to upgrade it first.

**Comment by yuanyuan8983** [comment]
Sorry, there is a problem with WeChat. This is correct: cyllyy810222
