### ISSUE TITLE
[Bug] org.apache.thrift.TApplicationException: Invalid method name: 'get_table_req'

### ISSUE THREAD

**Issue by milton4code** [apache/doris#18618]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris 版本1.2.3-rc2
使用方式: 通过Multi-Catalog 创建hive ,语句如下

``CREATE CATALOG vee_hive PROPERTIES (
    'type'='hms',
    'hive.metastore.uris' = 'thrift://xx1:9083',
    'hadoop.username' = 'hive',
    'dfs.nameservices'='nameservice1',
    'dfs.ha.namenodes.nameservice1'='namenode40,namenode89',
    'dfs.namenode.rpc-address.nameservice1.namenode40'='xx1:8020',
    'dfs.namenode.rpc-address.nameservice1.namenode89'='xx2:8020',
    'dfs.client.failover.proxy.provider.nameservice1'='org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider'
);
``
使用
show CATALOGS;
switch vee_hive;
SHOW tables ;
三个命令都正常,
选取一个表测试查询语句
``
select * from  xxdb.dwd_d_daily_data limit 10;
``
报错

.

### What's Wrong?

[HY000][1105] errCode = 2, detailMessage = Unexpected exception: failed to get table dwd_d_daily_data in db starmdmdb from hms client. reason: org.apache.thrift.TApplicationException: Invalid method name: 'get_table_req'

### What You Expected?

公司集群用的是cdh6.2.1,hive版本为2.1.0

### Anything Else?

在此之前尝试过创建hive外表方式,
建表时报错
[HY000][1105] Unexpected exception: failed to check if table dwd_d_daily_data in xxxdb exists. reason: org.apache.thrift.TApplicationException: Invalid method name: 'get_table_req'
可以确认hive的各项参数都是正确的,hive表中dwd_d_daily_data 肯定是存在的.

注意到外表后面的说明,hive外部表只支持 2.3.7、3.1.2.
由于是刚入手doris,不太了解外表hive和Catalog 两种方式有何不同.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
Catalog will only be supported in the future. You can try to connect hive using catalog in the new version.

**Comment by gree2** [comment]
根据官方手册，指定 Hive 版本即可。

CREATE CATALOG hive PROPERTIES (
    'type'='hms',
    'hive.metastore.uris' = 'thrift://172.0.0.1:9083',
    'hive.version' = '2.1.1'
);

[指定使用 Hive 版本为 2.1.1 即可以查询 CDH 6.2.1 中对应的 Hive](https://zhuanlan.zhihu.com/p/636316507)
