### ISSUE TITLE
[Enhancement] duplicate table without key

### ISSUE THREAD

**Issue by dataroaring** [apache/doris#18621]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Doris skips data by short index, it is resource consuming to sorting data. Sometimes users do not need short index at all, so we can cancel enfore sort property on duplicate table.

### Solution

- ddl which creates a table without key
- load
- compaction
- query

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by waywtdcc** [comment]
Does this mean that duplicate tables can be created in the following way?

CREATE TABLE cc_test.cc32 (
id int NULL, 
name varchar(200) default 'cc'
)
DUPLICATE 
DISTRIBUTED BY HASH(`id`) BUCKETS 10

**Comment by nextdreamblue** [comment]
before this issue, user can define default DUP_KEYS and some head columns for keys.
after this issue, if user create table without set key type and key columns, will create a DUP_KEYS olap table without key columns.
```
CREATE TABLE `test` (
  `user_id` bigint(20) NULL,
  `is_delete` tinyint(4) NULL,
  `client_version_int` int(11) NULL
) ENGINE=OLAP
COMMENT 'OLAP'
DISTRIBUTED BY HASH(`user_id`) BUCKETS 4
PROPERTIES (
"replication_allocation" = "tag.location.default: 1"
);
```
after this issue, user will get a duplicate table without key columns

**Comment by herry2038** [comment]
check todo list
- [ ] 检查Scannode查询路径；确定无需变更；
- [ ] 检查block reader查询路径；确定无需变更；
