### ISSUE TITLE
[Bug] explode_split unable to split NULL value, return empty result

### ISSUE THREAD

**Issue by gojumprope** [apache/doris#18727]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.3

### What's Wrong?

explode_split unable to split NULL value, return empty result

### What You Expected?

should return rows with null result 

### How to Reproduce?

select k1, e1 from 
(
	SELECT 2 k1, NULL k2
) a
lateral view explode_split(k2, ',') tmp1 as e1 

result: 
![image](https://user-images.githubusercontent.com/38604290/232378859-b16aae24-763b-4e26-8f86-87a695c96dba.png)

expected: 
![image](https://user-images.githubusercontent.com/38604290/232397691-96efb9af-05db-4195-979c-5739ba1869cf.png)

### Anything Else?

documentation shows working but not working in reality
![image](https://user-images.githubusercontent.com/38604290/232378978-c0952e2f-95e2-4575-af1e-9f81898bca03.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by HappenLee** [comment]
use `explode_split_outer `

**Comment by absoluteharam** [comment]
Please update the documentation as well on the explode_split_outer. Thanks!
