### ISSUE TITLE
[Bug] explode_split use chinese char accur error data

### ISSUE THREAD

**Issue by stalary** [apache/doris#18823]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.3

### What's Wrong?

explode_split(investors, '，')
investors=a，b
result ��a ��b

### What You Expected?

no ��

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by BiteTheDDDDt** [comment]
https://github.com/apache/doris/pull/18824/files
