### ISSUE TITLE
[Bug] MySQL load failed

### ISSUE THREAD

**Issue by actcwlf** [apache/doris#18859]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

docker image:
apache/doris:1.2.2-fe-x86_64
apache/doris:1.2.2-be-x86_64

### What's Wrong?

when importing data from csv file, encountered a syntax error
```
MySQL [test_db]> LOAD DATA LOCAL INFILE 'sample.csv' INTO TABLE example_table  FIELDS TERMINATED BY '，' LINES TERMINATED BY '\n' IGNORE 1 LINES;
ERROR 1105 (HY000): errCode = 2, detailMessage = Syntax error in line 1:
LOAD DATA LOCAL INFILE 'sample...
     ^
Encountered: DATA
Expected
```
### What You Expected?

Data imported successfully.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liujiwen-up** [comment]
![image](https://user-images.githubusercontent.com/61498169/233526554-89ead612-9f58-4c3f-bf9c-d94d43f8bd1f.png)
1.2.2 is not supported yet, only the master branch supports it

**Comment by actcwlf** [comment]
感谢回复，请问目前主分支对应的是哪个版本号，是1.2.4吗？

**Comment by LemonLiTree** [comment]
> 感谢回复，请问目前主分支对应的是哪个版本号，是1.2.4吗？

mysql load is expected to be supported in version 2.0

**Comment by actcwlf** [comment]
Thanks~
