### ISSUE TITLE
[Bug]  use show create table xxxx, then give me a error distribution_desc 

### ISSUE THREAD

**Issue by quicklyfast** [apache/doris#18881]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

version doris-1.2.2-rc01(AVX2) RELEASE (build file://be0ca7388ef3@Unknown)
Built on Fri, 10 Feb 2023 16:46:09 UTC by be0ca7388ef3

### What's Wrong?

I created a table `test` with `DISTRIBUTED BY RANDOM BUCKETS 10`, and then executed `show create table test`. The returned DDL statement could not be executed, and upon investigation, it was found that there was round brackets after `RANDOM`.

1. create table `test`
```sql
CREATE TABLE `test` (
  `id` int(11) NULL,
  `col1` text NULL,
  `col2` text NULL
) ENGINE=OLAP
DUPLICATE KEY(`id`)
distributed by random buckets 10
PROPERTIES (
"replication_num" = "1"
);
```
2. show create table test
```
CREATE TABLE `test` (
  `id` int(11) NULL,
  `col1` text NULL,
  `col2` text NULL
) ENGINE=OLAP
DUPLICATE KEY(`id`)
COMMENT 'OLAP'
DISTRIBUTED BY RANDOM() BUCKETS 10
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"in_memory" = "false",
"storage_format" = "V2",
"disable_auto_compaction" = "false"
);
```

### What You Expected?

```
CREATE TABLE `test` (
  `id` int(11) NULL,
  `col1` text NULL,
  `col2` text NULL
) ENGINE=OLAP
DUPLICATE KEY(`id`)
COMMENT 'OLAP'
DISTRIBUTED BY RANDOM BUCKETS 10
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"in_memory" = "false",
"storage_format" = "V2",
"disable_auto_compaction" = "false"
);
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by nextdreamblue** [comment]
let me fix it
