### ISSUE TITLE
[Feature] Support batch operation for Java UDAF to get better performance

### ISSUE THREAD

**Issue by czzmmc** [apache/doris#18904]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Java UDAF can do a lot of things. Unlike Java UDF, we always want a stateful computation. Now we could do it by the new Java UDAF function, but usually get a really BAD performance. That is because we can only get a row once a time through add API. If we could fetch rows in batch, we may use  the concurrency to get faster.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhangstar333** [comment]
now, doris java udaf implement is batch call, like:
for(int i=0;i<batch;++i){
     invoke.add()
}
so user only implement the basic add function.
Recently, performance improvements have been made to Java udf and udaf.

**Comment by czzmmc** [comment]
> now, doris java udaf implement is batch call, like: for(int i=0;i<batch;++i){ invoke.add() } so user only implement the basic add function. Recently, performance improvements have been made to Java udf and udaf.

2.0 or 1.2.x ? Could u please mention the PR for me?

**Comment by zhangstar333** [comment]
maybe in 2.0: https://github.com/apache/doris/pull/21388 https://github.com/apache/doris/pull/21713
