### ISSUE TITLE
[Bug] 指定sequence_col的类型为时间的默认值是CURRENT_TIMESTAMP，insert 失败

### ISSUE THREAD

**Issue by liaoxin01** [apache/doris#18911]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2/master

### What's Wrong?

sequence列使用CURRENT_TIMESTAMP在fe没做处理，导致insert失败。
CREATE TABLE `order_info` (
`project_id` BIGINT NOT NULL ,
`consume_date` DATETIMEV2 NOT NULL,
`order_id` BIGINT NOT NULL ,
`combo_extend` JSONB DEFAULT NULL,
`age` INT ,
`name` varchar(20),
`write_time` DATETIME DEFAULT CURRENT_TIMESTAMP
) UNIQUE KEY(`project_id`, `consume_date`,`order_id`)
DISTRIBUTED BY HASH(`project_id`) BUCKETS 1
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"enable_unique_key_merge_on_write" = "true",
"function_column.sequence_col" = 'write_time'
);

INSERT INTO
test.order_info_4 (
order_id,
project_id,
consume_date,
age,
name
)
VALUES
(
1231234356,
370040365,
'2023-01-12',
NULL,
NULL
);
![image](https://user-images.githubusercontent.com/19986811/233619606-6e1f17c3-fa12-4ccc-97a8-7a9f0b5b919c.png)

### What You Expected?

intert成功

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lvshaokang** [comment]
I will take this task，please assign me，thk！
