### ISSUE TITLE
[Enhancement] reduce load time on unique and aggregate table

### ISSUE THREAD

**Issue by hust-hhb** [apache/doris#18917]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

In my test on tpch lineitem data, loading table whith three replica takes three times longer than single replica table,  and the cause is when inserting memtable , the compare method of skiplist takes up too much time, in my test it will  takes up approximately 50% of the time.

### Solution

Here is a way to reduce load time, memtable store row in vector and sort it on async flush stage, in my test dup key can reduce 50% load time.
Now i'm working on dup key, and the test show that it can reduce 50% time.
https://github.com/apache/doris/pull/18686

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TangSiyang2001** [comment]
May I try it if it is not in mergency? Wanna get familiar with code in this area, lol.

**Comment by Centurybbx** [comment]
Hi, I'm new to doris, but i'd like to try to work on this issue, can you assign it to me?
