### ISSUE TITLE
[Bug]  Kafka 通过 Routine Load 方式写 Doris Bug

### ISSUE THREAD

**Issue by BleethNie** [apache/doris#19174]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-1.2.4-rc01

### What's Wrong?

```
CREATE ROUTINE LOAD rc.abc_record_job ON abc_record
COLUMNS( a_name,s_name,type,xtime, xutime,d_info,time=from_unixtime(xtime, 'yyyy-MM-dd HH:mm:ss'),utime=from_unixtime(xutime, 'yyyy-MM-dd HH:mm:ss'))
PROPERTIES
(
 "max_batch_interval" = "20",
 "max_batch_rows" = "200000",
 "max_batch_size" = "104857600",
 "desired_concurrent_number" = "1",
 "strict_mode" = "false",
 "format" = "json",
 "jsonpaths" = "[\"$.a_name\",\"$.s_name\",\"$.type\",\"$.time\",\"$.utime\",\"$.d_info\"]"
)
FROM KAFKA
(
 "kafka_broker_list" = "192.168.1.2:9092",
 "property.group.id" = "abc", 
 "kafka_topic" = "abc_topic"
);
```
上面为设置routine load job 的脚本，kafka中对应的分区数为6个，但是在将kafka数据写入doris中时，数据未完全写入，只有部分kafka分区的数据成功写入doris中，运行后的doris routine load 任务如下：
```
CREATE ROUTINE LOAD abc_record_job ON abc_record
WITH APPEND
COLUMNS( a_name,s_name,type,xtime, xutime,d_info,time=from_unixtime(xtime, 'yyyy-MM-dd HH:mm:ss'),utime=from_unixtime(xutime, 'yyyy-MM-dd HH:mm:ss'))
PROPERTIES
(
"desired_concurrent_number" = "1",
"max_error_number" = "0",
"max_batch_interval" = "5",
"max_batch_rows" = "200000",
"max_batch_size" = "104857600",
"format" = "json",
 "jsonpaths" = "[\"$.a_name\",\"$.s_name\",\"$.type\",\"$.time\",\"$.utime\",\"$.d_info\"]"
"strip_outer_array" = "false",
"num_as_string" = "false",
"fuzzy_parse" = "false",
"strict_mode" = "false",
"timezone" = "Asia/Shanghai",
"exec_mem_limit" = "2147483648"
)
FROM KAFKA
(
 "kafka_broker_list" = "192.168.1.2:9092",
 "property.group.id" = "abc", 
 "kafka_topic" = "abc_topic"
 "property.kafka_default_offsets" = "OFFSET_END",
"kafka_partitions" = "0, 1, 2, 3, 4, 5",
"kafka_offsets" = "10, OFFSET_END, OFFSET_END, OFFSET_END, OFFSET_END, OFFSET_END"
);

```

可以看到routine load 中部分分区中的kafka_offsets还是为OFFSET_END,部分数据无法送从kafka写入doris,如果将kafka_offsets中OFFSET_END标识修改为0，则kafka所有分区数据都可以写入到doris中，修改方式如下：
```
ALTER ROUTINE LOAD FOR rc.abc_record_job
 FROM KAFKA
(
"kafka_partitions" = "0, 1, 2, 3, 4, 5",
"kafka_offsets" = "10, 0, 0, 0, 0, 0"
);

```

### What You Expected?

kafka所有分区数据都可以正常写入doris

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caoliang-web** [comment]
OFFSET_END：系统会自动查找topic对应的所有分区并从 OFFSET_END 开始消费，如果你的kafka没有生产消息进来，那么你的routine load 任务消费也就只有0分区，kafka offset 10 开始消费

**Comment by BleethNie** [comment]
> OFFSET_END：系统会自动查找topic对应的所有分区并从 OFFSET_END 开始消费，如果你的kafka没有生产消息进来，那么你的routine load 任务消费也就只有0分区，kafka offset 10 开始消费

我使用的kafka是 aliyun 的kafka集群，从管理平台可以看到，kafka的其它分区都是有数据的（当然我也验证了不是kafka问题，我通过代码方式消费这些分区的数据，所有分区都可以正常消费），并不是只有0号分区有数据，但是只有0号分区数据被消费了，其它分区都是无法消费的，但是将其它分区OFFSET_END修改为0后，则所有分区都可以正常消费

**Comment by cst4049** [comment]
遇到了同样的问题， 是怎么解决的呢？

**Comment by liugddx** [comment]
I would like to ask if this problem still exists?
