### ISSUE TITLE
[Bug] doris 外部数据源 链接presto 类型映射不支持varch

### ISSUE THREAD

**Issue by xincrazy** [apache/doris#19197]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-1.2.4-1

### What's Wrong?

doris-1.2.4-1 新功能增加链接presto外部数据源测试

trino版本 trino-412，对接数据源是mysql，然后库tpch表customer，在doris上查询 varchar字段出现UNSUPPORTED_TYPE

<img width="1208" alt="image" src="https://user-images.githubusercontent.com/14065414/235085030-1009801c-b6ea-4257-9a2f-d8ec160363d5.png">

### What You Expected?

希望改掉这个bug

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zy-kkk** [comment]
Hello, this bug occurred because our original trino only tested hive sources, not mysql. I have fixed it and it will be released in version 1.2.5
