### ISSUE TITLE
[Bug]  array_map function error

### ISSUE THREAD

**Issue by 16601746291** [apache/doris#19224]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris1.2.3

### What's Wrong?

mysql> set enable_vectorized_engine = true;
Query OK, 0 rows affected (0.00 sec)

mysql> select array(1,2,3);
+----------------+
| array(1, 2, 3) |
+----------------+
| [1, 2, 3]      |
+----------------+
1 row in set (0.00 sec)

mysql> select array_map(x -> x+1 ,array(1,2,3));
ERROR 1105 (HY000): errCode = 2, detailMessage = Syntax error in line 1:
select array_map(x -> x+1 ,array(1,2,3))
                    ^
Encountered: >
Expected: IDENTIFIER

mysql> 

What happened?  when i execute array_map function ,report error info:
Encountered: >
Expected: IDENTIFIER
lambda is right, so why happen this?

### What You Expected?

use array_map function run some logic

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhangstar333** [comment]
doris1.2.3 not has this function yet.

**Comment by 16601746291** [comment]
Is loose documentation ？The document says since 1.2.2

![image](https://user-images.githubusercontent.com/49640575/236098306-1fe22acc-a04e-4e2f-b16c-528ba5569627.png)

**Comment by LemonLiTree** [comment]
Documentation tag is wrong, I will fix it soon

**Comment by 16601746291** [comment]
Now  i updagrade doris version to 1.2.4.1, but same like this: 

![image](https://user-images.githubusercontent.com/49640575/236259769-132109b8-b885-4382-8711-ee5f92086462.png)
