### ISSUE TITLE
[Bug] S3 Load fail when the path include special characters

### ISSUE THREAD

**Issue by myfjdthink** [apache/doris#19275]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.1 and 1.2.4 both

### What's Wrong?

I tried to import data to Doris using S3 LOAD, which failed when the file path“DATA INFILE” contained special characters like "tag_bucket=6"

Load Command
```SQL
LOAD LABEL address_tag_test_1683192596_3
(
    DATA INFILE("s3://xxxpath/01.orc")
    INTO TABLE `dest_table`
FORMAT AS "ORC"              
)
WITH S3
(
    "AWS_ACCESS_KEY" = "xxx",
    "AWS_SECRET_KEY" = "xxx",
    "AWS_ENDPOINT" = "https://storage.googleapis.com",
    "AWS_REGION" = "us-east4"
)
PROPERTIES
(
    "send_batch_parallelism" = "1"
);
```

An example of a failed import

Note: Iceberg will generates a table with a partition with *tag_bucket=6* in the file path
```SQL
DATA INFILE("s3://warehouse/test.db/table_name/data/tag_bucket=6/01.orc")
```
Failure Information:
> type:LOAD_RUN_FAIL; msg:errCode = 2, detailMessage = failed to init reader for file s3://warehouse/test.db/table_name/data/tag_bucket=6/01.orc, err: Error: [:No response body.] at 10.2.0.2

Example of successful import
```SQL
DATA INFILE("s3://warehouse/test.db/table_name/data/01.orc")
```

### What You Expected?

Doris S3 Load can correctly recognize special s3 file paths

### How to Reproduce?

Just use the practices mentioned above

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Yulei-Yang** [comment]
I will look into this issue

**Comment by GoGoWen** [comment]
please refer to https://github.com/apache/doris/pull/16625,

**Comment by dataroaring** [comment]
@GoGoWen @myfjdthink Do your prs fix the issue?

**Comment by morningman** [comment]
This #16625 may fix this, I can review it.
