### ISSUE TITLE
[Enhancement] allocate blocks in scanner_context on demand and free them timely

### ISSUE THREAD

**Issue by dataroaring** [apache/doris#19283]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Currently, _free_blocks is filled in prepare phase in advance, it allocates blocks computed from a config. It consumes a lot memory and is not used for small load.

### Solution

- [ ] allocate block on demand and limit it as current.
- [ ] free them timely, e.g. close

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gitccl** [comment]
I'd like to do this task.
