### ISSUE TITLE
[Bug] group_concat function - Return Incorrect

### ISSUE THREAD

**Issue by 16601746291** [apache/doris#19296]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris VERSION 1.2.4.1

### What's Wrong?

Incorrect results when using the same column in ascending and desc order by，some testing data screenshot like below :
 
![image](https://user-images.githubusercontent.com/49640575/236371120-b3aebaa6-bb30-4476-8602-943762a4818c.png)

![image](https://user-images.githubusercontent.com/49640575/236370572-51e9a85f-430a-470c-bfa3-e53ec6e0f88c.png)

### What You Expected?

should be like above screenshot: The result of the second and third sql 
 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
@BiteTheDDDDt CC
