### ISSUE TITLE
[Bug] WINDOW FUNCTION LAST_VALUE ERROR

### ISSUE THREAD

**Issue by 16601746291** [apache/doris#19292]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris 1.2.4.1

### What's Wrong?

When i testing last_value function , the test table like below:

mysql> desc test.group_concat_test;
+-----------------+-------------+------+-------+---------+---------+
| Field           | Type        | Null | Key   | Default | Extra   |
+-----------------+-------------+------+-------+---------+---------+
| user_id         | LARGEINT    | No   | true  | NULL    |         |
| username        | VARCHAR(50) | No   | true  | NULL    |         |
| city            | VARCHAR(20) | Yes  | false | NULL    | REPLACE |
| age             | SMALLINT    | Yes  | false | NULL    | REPLACE |
| register_source | VARCHAR(20) | Yes  | false | NULL    | REPLACE |
| register_time   | DATETIME    | Yes  | false | NULL    | REPLACE |
+-----------------+-------------+------+-------+---------+---------+
6 rows in set (0.00 sec)

mysql> select user_id
    ->     ,username
    ->     ,city
    ->     ,age
    ->     ,register_source
    ->     ,register_time
    ->     ,FIRST_VALUE(username) over(partition by city order by register_time) as FIRST_VALUE
    ->     ,LAST_VALUE(username) over(partition by city order by register_time) as LAST_VALUE
    -> from test.group_concat_test;
+---------+----------+------+------+-----------------+---------------------+-------------+------------+
| user_id | username | city | age  | register_source | register_time       | FIRST_VALUE | LAST_VALUE |
+---------+----------+------+------+-----------------+---------------------+-------------+------------+
| 523456  | Jason    | BJ   |   32 | BOOKING         | 2023-05-05 10:03:41 | Jason       | Jason      |
| 123456  | sherry   | CS   |   31 | Wechat          | 2023-04-01 10:03:41 | sherry      | sherry     |
| 120456  | Rose     | CS   |   19 | Web             | 2023-04-13 10:03:41 | sherry      | Rose       |
| 13456   | Jack     | HZ   |   29 | Wechat          | 2023-04-01 10:03:41 | Jack        | Jack       |
| 123     | Billy    | HZ   |   23 | Wechat          | 2023-05-05 10:03:41 | Jack        | Billy      |
| 93456   | Yuki     | SH   |   31 | CTRIP           | 2023-02-10 10:03:41 | Yuki        | Yuki       |
| 2234256 | John     | SH   |   21 | Wechat          | 2023-04-23 10:03:41 | Yuki        | John       |
| 234     | James    | SH   |   20 | LOLO            | 2023-05-05 10:03:41 | Yuki        | James      |
+---------+----------+------+------+-----------------+---------------------+-------------+------------+
8 rows in set (0.00 sec)

the document description
LAST_VALUE() returns the last value in the window range. Opposite of FIRST_VALUE() .
But above return result LAST_VALUE()  is wrong.

### What You Expected?

The LAST_VALUE()  returns correct, same as document description
LAST_VALUE() returns the last value in the window range. Opposite of FIRST_VALUE() .

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 16601746291** [comment]
screenshot like this:
![image](https://user-images.githubusercontent.com/49640575/236367805-c68d11c8-fdeb-45a5-a922-ff9c0249052e.png)

**Comment by LemonLiTree** [comment]
https://github.com/apache/doris/discussions/15385
use RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING and try again

**Comment by 16601746291** [comment]
> #15385 use RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING and try again

It correct，Thanks very much ！
![image](https://user-images.githubusercontent.com/49640575/236609116-1bf1e0de-5a0e-4675-8038-2a48db67f688.png)
