### ISSUE TITLE
[Bug] The query data is null, but Flink Spark and Trino are correct

### ISSUE THREAD

**Issue by chengyi3192** [apache/doris#19340]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris: 1.2.4-1
hive: 3.1.2
flink: 1.13.1
iceberg: 1.1.0

### What's Wrong?

The query data is null, but Flink, Spark, and Trino are correct。And the data written by trino can be correctly detected in Doris。 Here, 2 is written through trino
![image](https://user-images.githubusercontent.com/52986451/236614319-5220da3f-d959-438a-a57a-49e446c6b917.png)

### What You Expected?

data is not null

### How to Reproduce?

1.  在default\_database通过hive创建iceberg表test\_cy1\
    ```sql
    CREATE TABLE test\_cy1 ( id bigint) STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler';
    ```

    ![](http://img.ichengyi.top/20230508103456.png)
2.  插入数据

    1.  通过hive插入数据

        ```sql
        insert into test\_cy1 values(1);
        ```

        ![](http://img.ichengyi.top/20230508103522.png)
    2.  通过flink sql-client插入数据

        ```sql
        \## 创建catalog语句
        CREATE CATALOG hive\_catalog WITH (
        'type'='iceberg',
        'catalog-type'='hive',
        'uri'='thrift://hadoop102:9083',
        'clients'='5',
        'property-version'='1',
        'warehouse'='hdfs\://hadoop102:8020/warehouse/iceberg-hive'
        );

        \## 插入语句
        insert into test\_cy1 values(2);
        ```

        ![](http://img.ichengyi.top/20230508104423.png)
        
    3.  通过trino插入数据
        trino iceberg catalog
        ```java
        connector.name=iceberg
        hive.metastore.uri=thrift://192.168.2.130:9083
        iceberg.file-format=PARQUET
        iceberg.compression-codec=NONE
        ```
        trino命令行启动
        ```
        ./trino-cli --server 192.168.2.130:8083 --catalog iceberg
        ```
        trino 插入语句
        ```sql
        insert into test_cy1 values(3);
        ```
        ![](http://img.ichengyi.top/20230508105919.png)
        ![](http://img.ichengyi.top/20230508105951.png)
        
3. doris查询数据
    使用hive和iceberg插入的数据为null, 使用trino插入的3可以正常显示
    ![](http://img.ichengyi.top/20230508110752.png)

    使用hdfs函数查询
    ![](http://img.ichengyi.top/20230508111531.png)
    
4. test_cy1 hdfs文件
    链接：https://pan.baidu.com/s/1CYoNdOhahxzFPB56SL62Rw 
    提取码：bz6c

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LemonLiTree** [comment]
Can you go into more detail? How is the data of test_cy written?

**Comment by chengyi3192** [comment]
> Can you go into more detail? How is the data of test_cy written?
first row by flink: insert into test_cy values(1);
second row by trino: insert into test_cy values(2);
third row by flink: nsert into test_cy values(3);

**Comment by chengyi3192** [comment]
#16602
