### ISSUE TITLE
[Bug] doris-1.2.4.1 is much slower than doris-1.2.1

### ISSUE THREAD

**Issue by zengxiangqi1031** [apache/doris#19364]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris 1.2.4.1

### What's Wrong?

when i run ssb test, doris 1.2.4.1 is much slower than doris 1.2.1 ;  my machine is 32 core and 128GB RAM , all the parameters are the same.
![image](https://user-images.githubusercontent.com/11873336/236717707-cacbdad7-c6b7-4085-880e-8b20897c3dad.png)
![image](https://user-images.githubusercontent.com/11873336/236717723-63412092-75d7-48f7-aa27-4e42ae8ca605.png)

### What You Expected?

new version should be faster than old version

### How to Reproduce?

just run ssb test with different doris version

### Anything Else?

no

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zy-kkk** [comment]
你可以在1.2.4在be.conf设置disable_storage_page_cache=false,然后重启be重新测试
我们从1.2.2版本开始默认打开了此选项
![image](https://user-images.githubusercontent.com/70795751/237032152-9e3f6ccb-122b-4093-a6f6-c4fde1a23035.png)
