### ISSUE TITLE
[Bug] When user change the properties of the catalog, doris doesn't do the checks

### ISSUE THREAD

**Issue by q763562998** [apache/doris#19379]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Apache Doris 1.2.2 RELEASE

### What's Wrong?

When I create a catalog, **doris will check my properties**, for example, the hive type will check whether the properties of dfs.ha.namenodes exist.However, when I want to modify the catalog's properties, and the properties of this dfs.ha.namenodes does not exist, **doris does not do the check**.
**The first picture** below is that I created a normal catalog, and then deliberately modified the parameters, so that `'dfs.ha.namenodes.HANN' = ''`, doris do not checks the properties.
**The second picture** below is that I created an abnormal catalog, so that` 'dfs.ha.namenodes.HANN' = ''`, but doris checks the properties
![error2](https://user-images.githubusercontent.com/49312826/236749204-385ccd96-0422-4103-86d6-840e19c30b55.png)

![error1](https://user-images.githubusercontent.com/49312826/236749186-9575085d-bc19-4bcc-867b-5329a04b4813.png)

### What You Expected?

I think doris should also make a properties check when **modifying** properties as it did when **creating** them

### How to Reproduce?

Create a catalog first,the sql is
``` sql
CREATE CATALOG hive1 PROPERTIES (
    'type'='hms',
    'hive.metastore.uris' = 'thrift://127.0.0.1:7004',
    'dfs.nameservices'='HANN',
    'dfs.ha.namenodes.HANN'='nn1,nn2',
    'dfs.namenode.rpc-address.HANN.nn1'='nn1_host:rpc_port',
    'dfs.namenode.rpc-address.HANN.nn2'='nn2_host:rpc_port',
    'dfs.client.failover.proxy.provider.HANN'='org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider'
);
```
and update it 
``` sql
ALTER CATALOG hive1 SET PROPERTIES  (
    'type'='hms',
    'hive.metastore.uris' = 'thrift://127.0.0.1:7004',
    'dfs.nameservices'='HANN',
    'dfs.ha.namenodes.HANN'='',
    'dfs.client.failover.proxy.provider.HANN'='org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider'
);
```
------
and create a catalog again
``` sql
CREATE CATALOG hive2 PROPERTIES (
    'type'='hms',
    'hive.metastore.uris' = 'thrift://127.0.0.1:7004',
    'dfs.nameservices'='HANN',
    'dfs.ha.namenodes.HANN'='',
    'dfs.client.failover.proxy.provider.HANN'='org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider'
);
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xxiao2018** [comment]
Hi @q763562998 , this is indeed a problem. We SHOULD check properties both on creating and modifying
