### ISSUE TITLE
[Bug] Cannot create table with 'DATE' type

### ISSUE THREAD

**Issue by Centurybbx** [apache/doris#19388]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master branch: until e5a6b00

### What's Wrong?

- Error occurs when using the example provided by the official doc to create table.

<img width="879" alt="image" src="https://user-images.githubusercontent.com/55011513/236769889-6e384bce-2c1c-4641-bedd-955e76cfebf3.png">
<img width="720" alt="image" src="https://user-images.githubusercontent.com/55011513/236770615-65d3e368-f45e-4a84-a17e-8662165435f5.png">

- After searching the [official doc](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-reference/Data-Types/DATE/), doris recommends using 'DATEV2' after version 1.2.
- So is that suitable to change this in the offcicial doc?

### What You Expected?

Fix this little bug.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LemonLiTree** [comment]
Would you like to modify the document？

**Comment by Centurybbx** [comment]
Sure! I will fix that later!

> Would you like to modify the document？

**Comment by nextdreamblue** [comment]
after some times, it can use datev2, datetimev2, and decimalv3 instead of datav1, datetimev1, and decimalv2 automatically, will be better

**Comment by Centurybbx** [comment]
> after some times, it can use datev2, datetimev2, and decimalv3 instead of datav1, datetimev1, and decimalv2 automatically, will be better

Gotcha! Appreciate it!
