### ISSUE TITLE
[Bug] Can't  restore snapshot backup from doris-1.1.5  in doris-1.2.4

### ISSUE THREAD

**Issue by kylinmac** [apache/doris#19391]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-1.2.4-rc01

### What's Wrong?

backup in 1.1.5 
```
BACKUP SNAPSHOT db.label 
TO repo
ON (
table
);
```
create table first and restore in 1.2.4 
```
CREATE TABLE table(
 ... 
)...

RESTORE SNAPSHOT db.label
FROM repo
PROPERTIES
(
"backup_timestamp"="time"
)
```
show restore can see the error msg : [COMMON_ERROR, msg: Table table already exist but with different schema] ,
because of the new column __DORIS_VERSION_COL__ in 1.2.4

it will success when table dosen't exist in db  before restore 

### What You Expected?

restore to the created table in 1.2.4 from 1.1.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by nextdreamblue** [comment]
set enable_hidden_version_column_by_default = false in fe.conf and restart fe and recreate table, then will not column `DORIS_VERSION_COL`, and then retry restore

**Comment by kylinmac** [comment]
thx
