### ISSUE TITLE
[Enhancement] 希望doris支持多个GROUP_CONCAT函数distinct使用

### ISSUE THREAD

**Issue by didasai** [apache/doris#19478]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

sql案例:
```sql
select GROUP_CONCAT(DISTINCT a,'')
,GROUP_CONCAT(DISTINCT b,'')
from (
	select '1' a
	,'1' b
	union all
	select '1' a
	,'1' b
	union all
	select '2' a
	,'2' b
) r
```
执行结果:
```
1105 - errCode = 2, detailMessage = group_concat can't support multi distinct.
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LemonLiTree** [comment]
try:
`select GROUP_CONCAT(DISTINCT a)
,GROUP_CONCAT(DISTINCT b)
from (
  select '1' a
  ,'1' b
  union all
  select '1' a
  ,'1' b
  union all
  select '2' a
  ,'2' b
) r;
`

**Comment by didasai** [comment]
> try:
> 
> ```sql
> select GROUP_CONCAT(DISTINCT a)
> ,GROUP_CONCAT(DISTINCT b)
> from (
>   select '1' a
>   ,'1' b
>   union all
>   select '1' a
>   ,'1' b
>   union all
>   select '2' a
>   ,'2' b
> ) r;
> ```

你说的不是解决方案啊

**Comment by stalary** [comment]
group_concat supports multiple, although custom delimiters are not supported. Your second field is regarded as a delimiter.
