### ISSUE TITLE
[Feature] support compress file for tvf hdfs() and s3()

### ISSUE THREAD

**Issue by morningman** [apache/doris#19477]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Related discussion: https://github.com/apache/doris/discussions/18140

We can support it by add a new properties for tvf , like :

```
select * from hdfs("uri" = "xxx", ..., "compress_type" = "lz4", ...)
```

User can:
1. Specify compression explicitly by setting `"compression" = "xxx"`.
2. Doris can infer the compression type by the suffix of file name, eg, file1.gz

Currently, we only support reading compress file in csv format, and on BE side, we already support.
All need to do is to analyze the "compress_type" on FE side and pass it to BE.

Related class:
```
PropertyAnalyzer.analyzeCompressionType()
```
You can also refer to this PR: https://github.com/apache/doris/pull/19387/files

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by reswqa** [comment]
Thanks for creating this! I'd like to pick up this~
