### ISSUE TITLE
[Enhancement] Show remote data usage via `SHOW DATA`

### ISSUE THREAD

**Issue by platoneko** [apache/doris#19533]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

After using hot and cold separation, `SHOW DATA` only shows local data usage of the table, but no remote cold data usage info. Expect to show both local and remote data usage via `SHOW DATA`.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by platoneko** [comment]
Should add a "RemoteSize" Column for SHOW_TABLE_DATA_META_DATA and SHOW_INDEX_DATA_META_DATA in `ShowDataStmt`.
May implement `OlapTable.getRemoteDataSize`, similar to the implementation of `OlapTable.getDataSize`.
Note that, Replicas may share the same remote data, consider to use `remoteDataSize` of CooldownReplica as Tablet's remote data size.

**Comment by liangjiawei1110** [comment]
hello, I want to try it
