### ISSUE TITLE
[Enhancement] refactor TaskWorkerPool

### ISSUE THREAD

**Issue by dataroaring** [apache/doris#19575]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Currently, doris put a lot tasks in TaskWorkerPool and init an instance for every kind task. We should refactor TaskWorkerPool to be more object oriented.

### Solution

- [ ] TaskWorkerPool base class.
- [ ] XXTaskWorkerPool for every kind, e.g. ReportTaskWorkerPool, PushTaskWorkerPool
- [ ] Init Corresponding WorkerPool for every kind.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dataroaring** [comment]
mentor: dataroaring, please add my wechat xiaoqiangnk.

**Comment by bobhan1** [comment]
I'd like to take the task
