### ISSUE TITLE
[Bug] ERROR occur in nested subqueries with same column name and union

### ISSUE THREAD

**Issue by ChaseHuangxu** [apache/doris#19611]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Apache Doris 1.2.2 RELEASE

### What's Wrong?

I'm trying to add Apache Doris support to SQLancer, this may be a logic bug found by @[SQLancer](https://github.com/sqlancer/sqlancer).

As shown below: 
    t0 and t1 are two tables, they both have only the column c0,
    An error occurred while executing the SQL statement `select * from (select * from t0, t1 where t1.c0 != 0 union select * from to, t1 where t1.c0 = 0) tmp;`
![image](https://github.com/apache/doris/assets/91189188/94f77e79-8d38-4e99-8fbc-f16e2d2e466f)

### What You Expected?

The SQL `select * from (select * from t0, t1 where t1.c0 != 0 union select * from to, t1 where t1.c0 = 0) tmp;` should execute normal and return correct results.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by morrySnow** [comment]
do not use 1.2.x to test nereids

**Comment by LiBinfeng-01** [comment]
the expectation result of mysql 8 and oracle 21c is also complaining of this grammar, so I suggest to write more specific in sql like :select * from (select t0.c0 from t0, t1 where t1.c0 != 0 union select t1.c0 from t0, t1 where t1.c0 = 0) tmp;

**Comment by LiBinfeng-01** [comment]
![be40c7f6-0f1a-4fb5-ade7-9a1f9058b10c](https://github.com/apache/doris/assets/46676950/4c98a276-18de-4462-8ebf-b9135ca17090)

**Comment by LiBinfeng-01** [comment]
![e02679ef-c7bd-48dc-96b8-8da42e93589c](https://github.com/apache/doris/assets/46676950/49264393-9782-4117-a38f-0da0c58abbe1)

**Comment by LiBinfeng-01** [comment]
![image](https://github.com/apache/doris/assets/46676950/6e6cda02-cb8a-42a4-b62b-3e364ddbeeee)
