### ISSUE TITLE
[Enhancement] result of IF is not expected 

### ISSUE THREAD

**Issue by dataroaring** [apache/doris#19623]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

doris

`select IF(0,"ERROR","this"),IF(1,"is","ERROR");
[null] [null] `

mysql
`select IF(0,"ERROR","this"),IF(1,"is","ERROR");   
this  is
`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by bobhan1** [comment]
I'd like to take the task
