### ISSUE TITLE
[Bug] insert into values does not work as insert into select

### ISSUE THREAD

**Issue by dataroaring** [apache/doris#19664]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

CREATE TABLE `tbl1` (
`k1` int(11) NULL,
`k2` int(11) NULL
) ENGINE=OLAP
DUPLICATE KEY(`k1`, `k2`)
COMMENT 'OLAP'
DISTRIBUTED BY HASH(`k1`) BUCKETS 1
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"storage_format" = "V2",
"light_schema_change" = "true",
"disable_auto_compaction" = "false"
);

insert into tbl1 values("acb" , 2);
data in tbl1 is  0，2

However,

CREATE TABLE `tbl4` (
`k1` varchar(3) NULL
) ENGINE=OLAP
DUPLICATE KEY(`k1`)
COMMENT 'OLAP'
DISTRIBUTED BY HASH(`k1`) BUCKETS 1
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"storage_format" = "V2",
"light_schema_change" = "true",
"disable_auto_compaction" = "false"
);

insert into tbl4 values("abc");

insert into tbl1 select k1, k1 from tbl4;

data in tbl1 is null.

### What's Wrong?

insert into values does not work as insert into select.

### What You Expected?

they work as same.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LucasHeng** [comment]
I'd like to try it.

**Comment by pegasas** [comment]
start docker on local, version 2.0.0_alpha-be-x86_64. 
![image](https://github.com/apache/doris/assets/13224827/8a5b7435-b42b-4164-bf6a-138faa1b9f96)
it seems tb1 ddl has some problem? 
syncing with @dataroaring offline.

**Comment by pegasas** [comment]
sync with @dataroaring offline, this issue should fixed on current master. skipped.
