### ISSUE TITLE
[Bug] Can't create Presto Catalog

### ISSUE THREAD

**Issue by jollygrass** [apache/doris#19726]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.4.1

### What's Wrong?

CREATE CATALOG presto PROPERTIES (
    "type"="jdbc",
    "user"="test",
    "password"="",
    "jdbc_url" = "jdbc:presto://192.168.231.248:7520/hive/test",
    "driver_url" = "presto-jdbc-0.218.jar",
    "driver_class" = "com.facebook.presto.jdbc.PrestoDriver"
);

[1105] [HY000]: errCode = 2, detailMessage = Unsupported jdbc database type, please check jdbcUrl: jdbc:presto://192.168.231.248:7520/hive/test

### What You Expected?

Can create Presto Catalog

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zy-kkk** [comment]
Hi, in Doris version 1.2.4.1 ，we support to use trino jdbc driver connect to trino/presto cluster, not support use presto jdbc dirver.we will support it in 1.2.5,please see #19307
