### ISSUE TITLE
[Feature] support real default value for json stream load

### ISSUE THREAD

**Issue by eldenmoon** [apache/doris#19741]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

```
#表结构
 CREATE TABLE `ods_t_test` (
 `id` bigint(30) NOT NULL,
 `order_code` varchar(30) DEFAULT NULL COMMENT '',
 `create_time` datetimev2(3) DEFAULT CURRENT_TIMESTAMP
) ENGINE=OLAP
UNIQUE KEY(`id`, `order_code`)
DISTRIBUTED BY HASH(`order_code`) BUCKETS 1
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"in_memory" = "false",
"storage_format" = "V2"
);


##数据格式
{"id":"23","order_code":"23123"}


##导入
导入
curl --location-trusted -u root -T test.json -H "label:1245" -H "format:json" http://10.16.10.14:8234/api/test/ods_t_test/_stream_load
```

描述 ： create_time没有设置正确的default值，正常应该是当前时间 ，insert 是没有问题的.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Arthur-Sun** [comment]
Hello, I'm new to here and this is my first time to work on open source project. Could I have a try?

**Comment by DarvenDuan** [comment]
same issue in https://github.com/apache/doris/pull/20078
