### ISSUE TITLE
[Bug] Query TVF failed

### ISSUE THREAD

**Issue by wangbo** [apache/doris#19784]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

commit ce12cf404c3af67253115dd065aab1b30ec64cd8 (doris-master/master)
Author: Kang <kxiao.tiger@gmail.com>
Date:   Wed May 17 17:18:07 2023 +0800

    [bugfix](inverted index) Fix mv inheriting unexpectedly inverted index of base table (#197

### What's Wrong?

```
sql [(none)]>select * from resource_groups();
ERROR 1105 (HY000): errCode = 2, detailMessage = [CANCELLED][THRIFT_RPC_ERROR]failed to call frontend service, reason: Internal error processing fetchSchemaTableData
```

### What You Expected?

query succes

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yongjinhou** [comment]
Bug fixing
