### ISSUE TITLE
[Enhancement] optimize sorting in memtable 

### ISSUE THREAD

**Issue by dataroaring** [apache/doris#19997]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Doris batch data in memtable and sort it before flushing and doris uses std::sort.  There are other sorting available. e.g. https://github.com/google/highway/tree/master/hwy/contrib/sort and https://github.com/orlp/pdqsort. We should evaluate them and use the better one.

### Solution

- [ ] add qpdsort to doris and evaluate it
- [ ] add sort in hwy to doris  and evaluate it.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zncleon** [comment]
I'd like to try it

**Comment by dataroaring** [comment]
The issue is free now.

**Comment by liangjiawei1110** [comment]
I'd like to try it.

**Comment by pengpengSir** [comment]
Since two months have passed, can I take this issue instead? @dataroaring

**Comment by my-vegetable-has-exploded** [comment]
I'd like to have a try.

**Comment by my-vegetable-has-exploded** [comment]
It seems that #20392 have replace std::sort with pdqsort.
