### ISSUE TITLE
[Enhancement] support a agg function like groupUniqArray in clickhouse

### ISSUE THREAD

**Issue by dataroaring** [apache/doris#20129]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

as above in title.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dataroaring** [comment]
ready with collect_set.

**Comment by TangSiyang2001** [comment]
We currently have `collect_set`, whose alias is `group_uniq_array`, creates an array containing distinct elements from expr, with the optional max_size parameter limits the size of the resulting array to max_size elements, with arbitrary order. [see](https://doris.apache.org/docs/dev/sql-manual/sql-functions/aggregate-functions/collect_set/)

This agg works in the same way as `groupUniqArray` in `ClickHouse`.
