### ISSUE TITLE
[Bug] 某个 Tablet 的副本全部损坏后，无法修复

### ISSUE THREAD

**Issue by tim-chow** [apache/doris#20208]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.4.1-1

### What's Wrong?

单个某个 Tablet 的全部副本都损坏后。我执行如下操作：
1. 登陆到每台 BE
2. 停止 BE 进程
3. 将 Tablet 从 ${storage_root_path}/data 删除
4. 使用 meta_tool 清除 Tablet Header，meta_tool --operation=delete_meta ...
5. 通过 MySQL 客户端登陆 FE Query Port（9030）
6. 执行 admin set frontend config ("recover_with_empty_tablet" = "true");
7. FE Master 日志显示，已经用空 Tablet 覆盖损坏的 Tablet
8. 但是执行 SHOW PROC '/cluster_balance/history_tablets'\G，发现副本修复时，报错：ErrMsg: unable to find source replica

### What You Expected?

希望：Tablet 数据可以丢失，用空 Tablet 替换，保证写入和查询不报错。

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gnehil** [comment]
You can add me on WeChat：gnehil489, let's take a look at this problem together

**Comment by tim-chow** [comment]
> gnehil489

thank you so much!
