### ISSUE TITLE
[Feature]  metabase driver

### ISSUE THREAD

**Issue by Avey777** [apache/doris#20263]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

It would be helpful to have a Metabase plugin that facilitates the use of Doris as a data source.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zy-kkk** [comment]
Doris is compatible with MySQL protocol. You can connect to Doris using mysql driver
