### ISSUE TITLE
[Enhancement] optimize behavior of default_storage_medium 

### ISSUE THREAD

**Issue by dataroaring** [apache/doris#20345]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

When there is not storage_medium attr in a create table stmt, then the table is created on the medium of type specified by  default_storage_medium in fe.conf.  However, when all disks in a cluster are of type SSD and default_storage_medium is HDD, then a create table stmt without storage_medium fails.

https://doris.apache.org/docs/dev/admin-manual/config/fe-config#storage

### Solution

We change behavior of default_storage_medium to preferred option instead of specified option. That is, if default_storage_medium is HDD and there is no space on HDD, then doris would create a table on SSDs when there is no storage_medium specified in the create stmt.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Centurybbx** [comment]
I‘d like to work on this!
