### ISSUE TITLE
[Bug] regexp function can not work correctly with Chinese characters

### ISSUE THREAD

**Issue by fracly** [apache/doris#20416]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.2

### What's Wrong?

regexp function can not work correctly with Chinese characters
for example, this sql "select '皖12345' REGEXP '^[皖][0-9]{5}$'"  return 1 in mysql but return 0 in doris

### What You Expected?

regexp can work just as mysql correctly

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caoliang-web** [comment]
1.2.4.1 is no problem, you can upgrade to see

**Comment by fracly** [comment]
fixed in 1.2.4, look good for me
