### ISSUE TITLE
[Feature]  Exchanges the names of two tables or view atomically.

### ISSUE THREAD

**Issue by catpineapple** [apache/doris#20442]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

This method can realize the RENAME of the temporary table  under the atomic operation.

### Use case

for  :  a _1 to a_2

```
a_1 rename a_temp
a_2 rename a_1
a_temp rename a_1
```
it`s  not atomical

but :

```
exchange tables name_1 and name_2;
```
it will be atomical

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tech-Circle-48** [comment]
这个isuue我接了

**Comment by catpineapple** [comment]
this feature  already exists ： alter table ... replace ...
