### ISSUE TITLE
[Feature] support upload cooldown data into HDFS

### ISSUE THREAD

**Issue by ByteYue** [apache/doris#20490]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Currently, Doris only supports uploading cool data into S3 object storage, there would be a lot of users who might want to store their cold data into HDFS.
To implement such functionality, we might need to add HDFS resource inside one rowset(currently there is already S3 resource), and such resource could lead to corresponding FileSystem implementation, the rowset would write its self data into such fs.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LHG41278** [comment]
I want to take this issue, thanks.

**Comment by my-vegetable-has-exploded** [comment]
It seems that #22048 should close this issue?

**Comment by ByteYue** [comment]
> It seems that #22048 should close this issue?

Yes, this issue is already finished
