### ISSUE TITLE
[Enhancement] A more friendly hint for creating table failed when BE shutdown

### ISSUE THREAD

**Issue by yujun777** [apache/doris#20533]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

When BE shutdown,  create table will fail. But it still hint "Failed to create partition[xxx]. Timeout".

If the BE isn't alive,   the more friendly hint may need to tell user that the BE's not available.

What's more,  there's another option:   if some BEs failed,  but the majority of them success,  can we treat the create as successful ?

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by didiaode18** [comment]
I am willing to submit a PR! @dataroaring

**Comment by yujun777** [comment]
Relate code:   

datasource/InternalCatalog.java     createPartitionWithIndices

![image](https://github.com/apache/doris/assets/8347843/51860dae-c4db-4f1b-9e14-74e7ba4e073c)

**Comment by didiaode18** [comment]
I‘d like to work on this!
