### ISSUE TITLE
[Enhancement] let regression case fail fast when job is cancelled

### ISSUE THREAD

**Issue by freemandealer** [apache/doris#20578]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Your can always see such code in doris regression-test/suites:

```    
while (max_try_secs--) {
        String res = getJobState(tbName1)
        if (res == "FINISHED") {
            sleep(3000)
            break
        } else {
            Thread.sleep(1000)
            if (max_try_secs < 1) {
                println "test timeout," + "state:" + res
                assertEquals("FINISHED", res)
            }
        }
   }
```

That is: we quit ONLY if  'FINISHED', otherwise we wait until timeout.
It slows down the regression test because job status could also be other certain and unchanging status such as 'CANCELLED' which is meaningless to wait for.

So we need to wait only for those changing status.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ArmandoZ** [comment]
I‘d like to work on this. Thanks.
