### ISSUE TITLE
[Enhancement] Add IP address process function for SQL like ClickHouse

### ISSUE THREAD

**Issue by wangchong2023** [apache/doris#20584]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

ClickHouse support some [IP address process function](https://clickhouse.com/docs/zh/sql-reference/functions/ip-address-functions) for SQL. These are very useful for some network service cases.
Hope to add these function ASAP.Thanks.

### Solution

Add IP address process function for SQL like ClickHouse

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Yulei-Yang** [comment]
I will take this, pls assign to me

**Comment by superdiaodiao** [comment]
I added another ip function and the PR is https://github.com/apache/doris/pull/25510. @TangSiyang2001
