### ISSUE TITLE
[Enhancement] set back all session variables to default value

### ISSUE THREAD

**Issue by morrySnow** [apache/doris#20643]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

we will set some global variables for test or sometimes
after test, we want to recovery all variables to default value
but it is not easy to do this, because we should check all variables manually

### Solution

provide new statement
```
UNSET [SESSION] VARIABLE ${variable_name};
UNSET [SESSION] VARIABLE ALL;
```
to set variable to default value.

forthemore, we could reorder weather a variable is default value. If it does,
we could update it to new default value when the default value changed.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LHG41278** [comment]
I want to take this issue, thanks.

**Comment by pegasas** [comment]
@TangSiyang2001 @LHG41278 hello, I am new here for some helps, could I have a try?

**Comment by TangSiyang2001** [comment]
> @TangSiyang2001 @LHG41278 hello, I am new here for some helps, could I have a try?

Welcome! However, @LHG41278 is still working on it. You could pick other free issues. If you use WeChat, you could add me: TangSiyang2001.
