### ISSUE TITLE
[Bug] aws-sdk compile error makes build doris from scratch failed

### ISSUE THREAD

**Issue by zhiqiang-hhhh** [apache/doris#20665]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris master, commit id 44e20d9087980a7beee8b20d2ccdea6c096909df

### What's Wrong?

when building doris through build.sh, meet cmake error like:

```cmake
CMake Error at CMakeLists.txt:185 (include):
  include could not find requested file:

    AwsFindPackage


CMake Error at CMakeLists.txt:197 (add_subdirectory):
  add_subdirectory given source "crt/aws-crt-cpp" which is not an existing
  directory.
...

CMake Error at aws-cpp-sdk-core/CMakeLists.txt:516 (aws_use_package):
  Unknown CMake command "aws_use_package".
```

### What You Expected?

should build succeed

### How to Reproduce?

Just download doris to a new Linux environment, and run build.sh, this error should be reproduced. 

A more direct way:
1. rm -rf thirdparty/src/aws-sdk-cpp-1.9.272/
2. cd thirdyparty
3. sh build-thirdparty.sh -j 99 --continue aws_sdk

### Anything Else?

The reason is that prefetch_crt_dependency.sh of aws-skd tar.gz file will download outdated deps of aws-skd, which make cmake file not work. 

See details: https://github.com/aws/aws-sdk-cpp/issues/1648

Possible solution:
1. do not clone .tar.gz of aws-sdk, use git clone git clone --recurse-submodules --branch 1.9.272 instead
2. upgrade aws-sdk from 1.9.x to 1.10.x, which fixed compile problem in https://github.com/aws/aws-sdk-cpp/issues/1888

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhiqiang-hhhh** [comment]
I have tried to reproduce the compile error, but failed. 

Closed.

**Comment by hzjhjjyy** [comment]
I also encountered this problem when building, and finally running the prefetch_crt_dependency.sh script manually after the aws-sdk-cpp was unpacked during the build, and then solved the problem.

**Comment by HackToday** [comment]
This can happens with curl download with certificates issue
