### ISSUE TITLE
[Enhancement] default value for bigint should not has to be quoted

### ISSUE THREAD

**Issue by dataroaring** [apache/doris#20670]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

CREATE TABLE t (topic BIGINT DEFAULT 0) does not work. CREATE TABLE t (topic BIGINT DEFAULT "0") works. 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by nanfeng1999** [comment]
I will resolve it

**Comment by guochao521** [comment]
@dataroaring  Hello, I want to resolve it.

**Comment by tudouzhao** [comment]
if this issue is not solved, I would like to try solving it in one week.

**Comment by tudouzhao** [comment]
Actually, this error happends due to java_cup.runtime.lr_parser.
so, we need to push java_cup to update their services.

**Comment by waywtdcc** [comment]
i want to resolve this issue in  this week @tudouzhao

**Comment by tudouzhao** [comment]
may we need to pay attention to this enhancement issue, but that issue is not merged.
