### ISSUE TITLE
[Bug] Wrong query result

### ISSUE THREAD

**Issue by Larborator** [apache/doris#20725]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.4.1-rc01

### What's Wrong?

仅改变查询条件中的时间分区mt，得到不同的结果。示例和表结构如下：

其中Query SQL1的结果是正确的，Query SQL2的结果少了如下6条：
2023-04-01
2023-04-01
2023-05-01
2023-05-01
2023-05-01
2023-05-01

Query SQL1:
```sql
SELECT
    mt
FROM
    test_table
WHERE
    mt >= STR_TO_DATE('20230401', '%Y%m%d')
    AND
    mt <= STR_TO_DATE('20230501', '%Y%m%d')
    AND
    zone_new = '-1'
    AND
    second_dept = '-1'
    AND
    project = '-1'
    AND
    tag_id = -1
    AND
    room_id = -1
    AND
    is_new = -1
    AND
    pk_parent_type = '-1'
    AND
    pk_type = '-1'
    AND
    raffle_type = '-1'
    AND
    user_type = '-1'
    AND
    anchor_type = '-1'
    AND
    hd_type = '-1'
    AND
    host_type = '-1'
    AND
    template_type = '-1'
ORDER BY mt
;
```

Result 1:
![image](https://github.com/apache/doris/assets/19779893/fbe78409-1b83-4508-94b1-e1c770913f90)

Query SQL2:
```sql
SELECT
    mt
FROM
    test_table
WHERE
    mt >= STR_TO_DATE('20230301', '%Y%m%d')
    AND
    mt <= STR_TO_DATE('20230501', '%Y%m%d')
    AND
    zone_new = '-1'
    AND
    second_dept = '-1'
    AND
    project = '-1'
    AND
    tag_id = -1
    AND
    room_id = -1
    AND
    is_new = -1
    AND
    pk_parent_type = '-1'
    AND
    pk_type = '-1'
    AND
    raffle_type = '-1'
    AND
    user_type = '-1'
    AND
    anchor_type = '-1'
    AND
    hd_type = '-1'
    AND
    host_type = '-1'
    AND
    template_type = '-1'
ORDER BY mt
;
```

Result 2:
![image](https://github.com/apache/doris/assets/19779893/9befa4ca-58cd-4884-b865-ae73add5713b)

Table DDL:
```sql
CREATE TABLE `test_table` (
  `mt` date NULL COMMENT '',
  `room_id` bigint(20) NULL COMMENT '',
  `tag_id` bigint(20) NULL COMMENT '',
  `zone_new` varchar(255) NULL COMMENT '',
  `pk_parent_type` varchar(255) NULL COMMENT '',
  `pk_type` varchar(255) NULL COMMENT '',
  `raffle_type` varchar(255) NULL COMMENT '',
  `user_type` varchar(255) NULL COMMENT '',
  `anchor_type` varchar(255) NULL COMMENT '',
  `hd_parent_type` varchar(255) NULL COMMENT '',
  `hd_type` varchar(255) NULL COMMENT '',
  `is_new` bigint(20) NULL COMMENT '',
  `template_type` varchar(255) NULL COMMENT '',
  `host_type` varchar(255) NULL COMMENT '',
  `second_dept` varchar(255) NULL COMMENT '',
  `project` varchar(255) NULL COMMENT '',
) ENGINE=OLAP
UNIQUE KEY(`mt`, `room_id`, `tag_id`, `zone_new`, `pk_parent_type`, `pk_type`, `raffle_type`, `user_type`, `anchor_type`, `hd_parent_type`, `hd_type`, `is_new`, `template_type`, `host_type`, `second_dept`, `project`)
COMMENT ''
PARTITION BY RANGE(`mt`)()
DISTRIBUTED BY HASH(`mt`, `room_id`) BUCKETS 8
PROPERTIES (
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "MONTH",
"dynamic_partition.time_zone" = "Asia/Shanghai",
"dynamic_partition.start" = "-12",
"dynamic_partition.end" = "1",
"dynamic_partition.prefix" = "p",
"dynamic_partition.replication_allocation" = "tag.location.default: 3",
"dynamic_partition.buckets" = "8",
"dynamic_partition.create_history_partition" = "true",
"dynamic_partition.history_partition_num" = "400",
"dynamic_partition.storage_medium" = "HDD",
"dynamic_partition.start_day_of_month" = "1",
"in_memory" = "false",
"storage_format" = "V2",
"disable_auto_compaction" = "false"
);
```

### What You Expected?

当使用Query SQL2时，正确结果应该如下：

mt
2023-03-01
2023-03-01
2023-03-01
2023-03-01
2023-04-01
2023-04-01
2023-04-01
2023-04-01
2023-05-01
2023-05-01
2023-05-01
2023-05-01

### How to Reproduce?

已经用这个表的数据集在不同集群下复现了此问题，但是原表数据量较大，暂时不知道如何用小量数据复现

### Anything Else?

I found that when I change the zone new = '-1' in the SQL filter condition to zone_new = -1, I can get the correct result(the Doris table column type and the data type of the original storage are both string). This looks like a bug in the SQL filter condition.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by melody3240** [comment]
i guess replica data inconsistency

**Comment by jacktengg** [comment]
> > i guess replica data inconsistency
> 
> hi, I considered this issue before. But when I create a new table and reload data by ETL, this problem still exists.
> 
> And I found that when I change the zone new = '-1' in the SQL filter condition to zone_new = -1, I can get the correct result(the Doris table column type and the data type of the original storage are both string). This looks like a bug in the SQL filter condition.

Hi, can you provide the plan and profile of the changed query when `zone_new = -1`?

**Comment by Larborator** [comment]
> > > i guess replica data inconsistency
> > 
> > 
> > hi, I considered this issue before. But when I create a new table and reload data by ETL, this problem still exists.
> > And I found that when I change the zone new = '-1' in the SQL filter condition to zone_new = -1, I can get the correct result(the Doris table column type and the data type of the original storage are both string). This looks like a bug in the SQL filter condition.
> 
> Hi, can you provide the plan and profile of the changed query when `zone_new = -1`?

yes, all here

[3月-5月profile.txt](https://github.com/apache/doris/files/11765788/3.-5.profile.txt)
[3月-5月profile-隐式转换.txt](https://github.com/apache/doris/files/11765789/3.-5.profile-.txt)
[4月-5月profile.txt](https://github.com/apache/doris/files/11765790/4.-5.profile.txt)

**Comment by xiaoyaoziyang07** [comment]
and I have the same problem
run the same sql twice return different result；the first return one row, the second return none row;

**Comment by Larborator** [comment]
> and I have the same problem run the same sql twice return different result；the first return one row, the second return none row;
> 
> the follow is query profile [FIRST.txt](https://github.com/apache/doris/files/11767821/FIRST.txt) [SECOND.txt](https://github.com/apache/doris/files/11767824/SECOND.txt)

There may be some bugs in BE's low cardinality optimizing when the fieldType is STRING. You can try adding ```enable_low_cardinality_optimize = false``` to BE's conf file and restart BE.

**Comment by jacktengg** [comment]
@xiaoyaoziyang07 @Larborator you can update to [1.2.5-rc01](https://github.com/apache/doris/releases/tag/1.2.5-rc01), which shoud have fixed this issue.

**Comment by Larborator** [comment]
> 

👌👌👌

**Comment by Larborator** [comment]
> @xiaoyaoziyang07 @Larborator you can update to [1.2.5-rc01](https://github.com/apache/doris/releases/tag/1.2.5-rc01), which shoud have fixed this issue.

👌👌👌

**Comment by dujl** [comment]
have u fix the issue? and do u know which pr resolve this issue?

**Comment by Larborator** [comment]
> have u fix the issue? and do u know which pr resolve this issue?

This issue has been fixed in versions 1.2.5-rc01 and later. Try search 'low cardinality' could see the pr.

**Comment by dujl** [comment]
https://github.com/apache/doris/pull/19221/files

**Comment by xiaoyaoziyang07** [comment]
I resolve this problem by this way


enable_low_cardinality_optimize = false
