### ISSUE TITLE
[Enhancement] Doris-1.2.1-rc01 compile error through docker

### ISSUE THREAD

**Issue by bin41215** [apache/doris#20805]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Doris-1.2.1-rc01 The image used for compiling through docker recommends apache/doris:build-env-for-1.2 for the official website; but the compilation reports an error [https://doris.apache.org/zh-CN/docs/1.2/install/source-install/compilation-general](url)
![image](https://github.com/apache/doris/assets/74609438/5ce38fd5-a442-4623-8b92-359001244c68)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by bin41215** [comment]
solved

**Comment by czzmmc** [comment]
@bin41215 Hi, I meet the same problem. How did u fix it ?

**Comment by bin41215** [comment]
> @bin41215 Hi, I meet the same problem. How did u fix it ?

you can do this:
1. remove /var/local/thirdparty/installed 
2. in doris/thirdparty   build_thirdparty.sh
3. move the files compiled in the second step to /var/local/thirdparty/installed 
4. compile doris   （build.sh）
