### ISSUE TITLE
[Bug] failed to create float type column with default value

### ISSUE THREAD

**Issue by TangSiyang2001** [apache/doris#20868]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

all

### What's Wrong?

as title, float type column always encounters error "Default value will lose precision"

### What You Expected?

created normally.

### How to Reproduce?

create a table with column like:
```sql
`k1` float default "3.14"
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yiguolei** [comment]
Maybe we could not do that, because float is not accurate, and if we save the default value, then we could not select it using where clause.
