### ISSUE TITLE
1.2.4.3编译失败[Bug] 

### ISSUE THREAD

**Issue by jewin** [apache/doris#20879]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.4.3

### What's Wrong?

[  5%] Building C object src/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/eventfd.c.o
/home/erator/doris-1.2.4.3/be/src/glibc-compatibility/musl/eventfd.c:6:5: error: conflicting types for 'eventfd'; have 'int(unsigned int,  int)'
    6 | int eventfd(unsigned int count, int flags)
      |     ^~~~~~~
In file included from /home/erator/doris-1.2.4.3/be/src/glibc-compatibility/musl/eventfd.c:1:
/usr/include/sys/eventfd.h:34:12: note: previous declaration of 'eventfd' with type 'int(int,  int)'
   34 | extern int eventfd (int __count, int __flags) __THROW;
      |            ^~~~~~~
make[2]: *** [src/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/eventfd.c.o] Error 1
make[1]: *** [src/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  5%] Building CXX object src/env/CMakeFiles/Env.dir/env_posix.cpp.o
[  5%] Building CXX object src/common/CMakeFiles/Common.dir/resource_tls.cpp.o
[  5%] Building CXX object src/env/CMakeFiles/Env.dir/env_util.cpp.o

### What You Expected?

成功构建

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by waywtdcc** [comment]
你好，我也遇到这个问题，请问怎么处理呢? @jewin
