### ISSUE TITLE
[Bug] 文档错误 

### ISSUE THREAD

**Issue by jiugem** [apache/doris#20917]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

最新版本

### What's Wrong?

![image](https://github.com/apache/doris/assets/26454147/7dc09742-2920-450f-ab51-2aa6d85a20b4)

apache doris 文档学习路径，sequence列指向错误；

join优化、物化视图 指向内容找不到。

### What You Expected?

期待Doris发展的更好。

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hechao-ustc** [comment]
你可以提一个文档修复的PR，然后就成为apache doris contribute了。

**Comment by xinxingi** [comment]
> 你可以提一个文档修复的PR，然后就成为apache doris contribute了。

Submitted pr waiting to be merged. https://github.com/apache/doris-website/pull/247
