### ISSUE TITLE
[Bug] check uri error in hive catalog

### ISSUE THREAD

**Issue by CookingBoy** [apache/doris#20948]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

release-1.2.4.1

### What's Wrong?

Backgroud: Hive supports setting separate paths for partitions

Bug：if the location of Hive tables is hdfs, and the setting of location for some partitions is s3 in the same table, this is an error like 'connect to hdfs failed, error: InvalidParameter: Invalid input: uri is not a valid URI type. ' when you try to read the data of these special partition. And vice versa, but the difference is that the error is like 's3 uri is invalid: hdfs://ns1/xxxx'.

### What You Expected?

read data normally from the special partitions whose location is on s3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by morningman** [comment]
So what you mean is that for hive table, some of its partitions are stored on HDFS, and some of them are stored on S3?

**Comment by CookingBoy** [comment]
> So what you mean is that for hive table, some of its partitions are stored on HDFS, and some of them are stored on S3?

Example：

Hive table creation statement：
![image](https://github.com/apache/doris/assets/16102114/18e7f00b-d225-491c-8c12-e6e6c62303b1)

one partition location settings in same table:
![image](https://github.com/apache/doris/assets/16102114/8bf987ab-f8f6-4999-8e37-407865d341b1)

**Comment by morningman** [comment]
This is my wechat: morningman-cmy, could we talk on wechat for details?

**Comment by CookingBoy** [comment]
> This is my wechat: morningman-cmy, could we talk on wechat for details?

I have communicated with 曹亮@selectdb on wechat，and he confirmed the issue
