### ISSUE TITLE
[Bug] 不支持中文列名

### ISSUE THREAD

**Issue by cst4049** [apache/doris#21057]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0版本
    CREATE TABLE IF NOT EXISTS udpmodel_00000 (
            `_time` DATETIMEV2 NOT NULL COMMENT '日志发生时间',
`_uuid` VARCHAR(64) NOT NULL COMMENT '数据源IP',
`类型` VARCHAR(256) COMMENT '',
`数据` VARCHAR(256) COMMENT ''
        ) ENGINE=OLAP
        DUPLICATE KEY(`_time`)
        DISTRIBUTED BY HASH(_uuid) BUCKETS AUTO
        PROPERTIES (
            "replication_allocation" = "tag.location.default: 1",
            "estimate_partition_size" = "10G"
        )

### What's Wrong?

Execution failed: Error Failed to execute sql: java.sql.SQLSyntaxErrorException: (conn=22772) errCode = 2, detailMessage = Incorrect column name '类型'. Column regex is '^[_a-zA-Z@0-9][.a-zA-Z0-9_+-/><?@#$%^&*]{0,255}$'

### What You Expected?

为什么无法不支持中文列名呢

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hechao-ustc** [comment]
set enable_unicode_name_support=true;
将enable_unicode_name_support设置为true即可支持中文列名。

**Comment by zhangyi007** [comment]
哈喽，列名支持中文解决了吗？enable_unicode_name_support是在哪里设置

**Comment by zhangyi007** [comment]
解决了，感谢；set  enable_unicode_name_support=true; 可能没有生效，要查询确保生效了，SHOW VARIABLES where Variable_name like '%enable_unicode%'

**Comment by cjj2010** [comment]
> 解决了，感谢；set enable_unicode_name_support=true; 可能没有生效，要查询确保生效了，SHOW VARIABLES where Variable_name like '%enable_unicode%'



If global support for Chinese is required, it needs to be set up “ set global denable_unicode_name_support=true”
