### ISSUE TITLE
[Bug] Audit Log stmt not completed

### ISSUE THREAD

**Issue by Chris-Arith** [apache/doris#21128]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.5-rc01

### What's Wrong?

The `stmt` field in table `doris_audit_log_tbl__` is always missing part of the sql statement and the sql is only at size of 2kb.

### What You Expected?

The `stmt` should record full of a sql, that can help us find problems in business.

### Anything Else?

Nil

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by qerewa** [comment]
You can edit the plugin.conf in auditloader,the parameter 'max_stmt_length' controls the max stmt length to be loaded in audit table, default is 4096.

**Comment by Chris-Arith** [comment]
> You can edit the plugin.conf in auditloader,the parameter 'max_stmt_length' controls the max stmt length to be loaded in audit table, default is 4096.

Thanks a lot, it works!
It needs to change the plugin.conf first and then reinstall the plugin.
