### ISSUE TITLE
[Bug] es catalog array type query be down

### ISSUE THREAD

**Issue by caoliang-web** [apache/doris#21135]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.4.1

### What's Wrong?

start time: Wed Jun 14 15:00:16 CST 2023
*** Query id: 73544d52656844f6-a4518fd71c9029e7 ***
*** Aborted at 1686883439 (unix time) try "date -d @1686883439" if you are using GNU date ***
*** Current BE git commitID: 37ecc56bb3 ***
*** SIGSEGV address not mapped to object (@0xa000000000e) received by PID 342573 (TID 0x7f1a429e4700) from PID 14; stack trace: ***
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /mnt/datadisk0/yy/git/doris-1.2.4.1/be/src/common/signal_handler.h:420
 1# os::Linux::chained_handler(int, siginfo*, void*) in /mnt/disk1/caoliang/jdk1.8.0_331/jre/lib/amd64/server/libjvm.so
 2# JVM_handle_linux_signal in /mnt/disk1/caoliang/jdk1.8.0_331/jre/lib/amd64/server/libjvm.so
 3# signalHandler(int, siginfo*, void*) in /mnt/disk1/caoliang/jdk1.8.0_331/jre/lib/amd64/server/libjvm.so
 4# 0x00007F1B7EC71B80 in /lib64/libc.so.6
 5# doris::ScrollParser::fill_columns(doris::TupleDescriptor const*, std::vector<COW<doris::vectorized::IColumn>::mutable_ptr<doris::vectorized::IColumn>, std::allocator<COW<doris::vectorized::IColumn>::mutable_ptr<doris::vectorized::IColumn> > >&, doris::MemPool*, bool*, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&) at /mnt/datadisk0/yy/git/enterprise-core-1.2/be/src/exec/es/es_scroll_parser.cpp:584
 6# doris::vectorized::NewEsScanner::_get_next(std::vector<COW<doris::vectorized::IColumn>::mutable_ptr<doris::vectorized::IColumn>, std::allocator<COW<doris::vectorized::IColumn>::mutable_ptr<doris::vectorized::IColumn> > >&) at /mnt/datadisk0/yy/git/enterprise-core-1.2/be/src/vec/exec/scan/new_es_scanner.cpp:178
 7# doris::vectorized::NewEsScanner::_get_block_impl(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /mnt/datadisk0/yy/git/enterprise-core-1.2/be/src/vec/exec/scan/new_es_scanner.cpp:132
 8# doris::vectorized::VScanner::get_block(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /mnt/datadisk0/yy/git/enterprise-core-1.2/be/src/vec/exec/scan/vscanner.cpp:57
 9# doris::vectorized::ScannerScheduler::_scanner_scan(doris::vectorized::ScannerScheduler*, doris::vectorized::ScannerContext*, doris::vectorized::VScanner*) at /mnt/datadisk0/yy/git/doris-1.2.4.1/be/src/vec/exec/scan/scanner_scheduler.cpp:247
10# doris::ThreadPool::dispatch_thread() at /mnt/datadisk0/yy/git/doris-1.2.4.1/be/src/util/threadpool.cpp:543
11# doris::Thread::supervise_thread(void*) at /mnt/datadisk0/yy/git/doris-1.2.4.1/be/src/util/thread.cpp:455
12# start_thread in /lib64/libpthread.so.0
13# clone in /lib64/libc.so.6

### What You Expected?

array type normal query

### How to Reproduce?

curl -XPUT 'http://localhost:9200/my_index' -H 'Content-Type: application/json' -d'
{
    "mappings" : {
      "_meta" : {
        "doris" : {
          "array_fields" : [
            "expense"
          ]
        }
      },
      "properties" : {
        "amount" : {
          "type" : "double"
        },
        "car_batch" : {
          "type" : "keyword"
        },
        "expense" : {
          "type" : "keyword",
          "null_value" : "_NULL_VALUE_"
        },
        "id" : {
          "type" : "long"
        }
      }
    }

    }'

  curl -XPOST 'http://localhost:9200/my_index/_doc' -H 'Content-Type: application/json' -d'
    {

          "id" : 1,
          "amount" : 100,
          "car_batch" : "batch_01",
          "expense" : [
            "0_0",
            "1_0",
            "2_0",
            "3_0",
            "4_0",
            "5_0"
          ]
        }'

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caoliang-web** [comment]
[https://github.com/apache/doris/issues/20838](url)

**Comment by caoliang-web** [comment]
#20838

**Comment by qidaye** [comment]
fixed in #22046
