### ISSUE TITLE
[Bug] 外部表连接mysql数据库，json类型不兼容

### ISSUE THREAD

**Issue by didasai** [apache/doris#21246]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.4

### What's Wrong?

json格式数据变成16进制字符串了

mysql:
```sql
CREATE TABLE `test_json_table` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `jsonval` json DEFAULT NULL COMMENT '值',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8
```
data:
![image](https://github.com/apache/doris/assets/42800986/811ec680-f5f8-4e59-a78b-d7dce5c626f3)

doris:
```sql
CREATE EXTERNAL TABLE `test_json_table` (
  `id` int(11) NOT NULL COMMENT '自增id',
  `jsonval` varchar(65533) NULL COMMENT '值'
) ENGINE=ODBC
COMMENT 'MYSQL'
PROPERTIES (
"host" = "xxx",
"port" = "xxx",
"user" = "xxx",
"password" = "xxx",
"driver" = "MySQL ODBC 5.7 Unicode Driver",
"odbc_type" = "mysql",
"charest" = "utf8",
"database" = "xxx",
"table" = "xxx"
);
```
data:
![image](https://github.com/apache/doris/assets/42800986/64f3cbcd-e300-4905-bbb9-a6e54aea5c1b)

### What You Expected?

能正常显示json

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zy-kkk** [comment]
Please use the JDBC Catalog feature, ODBC is no longer maintained
