### ISSUE TITLE
[Bug] create storage policy with use_path_style=true success, but the backend failed when try to put object to minio.

### ISSUE THREAD

**Issue by gohalo** [apache/doris#21258]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

create a s3 resouce for minio with use_path_style property, such as the following sql.

```
CREATE RESOURCE "foobar"
PROPERTIES
(
    "type" = "s3",
    "s3.endpoint" = "127.0.0.1:9000",
    ... ...
    "use_path_style" = "true"
);
```

the sql execute success, but the backend failed when try to cooldown some tablets.

### What You Expected?

frontend and backend should be consistent.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
Can you config s3.region?

**Comment by gohalo** [comment]
no

**Comment by stalary** [comment]
> no

try use `us-east-1`

**Comment by gohalo** [comment]
fixed by https://github.com/apache/doris/pull/22249
