### ISSUE TITLE
[Enhancement] Improve Json function for doris

### ISSUE THREAD

**Issue by amorynan** [apache/doris#21268]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Now We have some _JSONB functions_ and  _JSON functions_ are not implement , specific semantics for each function below here can reference mysql

**NOTE** : _JSONB Functions_ , which has same function name with _JSON functions_ but with different implement which can be find in `be/src/vec/functions/function_jsonb.cpp ` . eg. json_parse alias jsonb_parse

### about json_path define:
https://modern-sql.com/blog/2017-06/whats-new-in-sql-2016#json-path

#### we have some JSONB functions which are not implement but JSON has already implement. below here
- [ ]  json_contains  @weijiew 
- [ ]  json_contains_path @weijiew 
- [ ]  json_quote json_unquote 
- [ ]  json_valid @hammerZh-Z 
- [ ]  json_array @yifei02 
- [ ]  json_object

#### below here we have both JSONB and JSON functions not implement .

- [ ]  ->>  ([->>](https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#operator_json-inline-path))
- [ ] JSON_DEPTH ([JSON_DEPTH()](https://dev.mysql.com/doc/refman/8.0/en/json-attribute-functions.html#function_json-depth)) @niebayes 
- [ ] JSON_LENGTH ([JSON_LENGTH()](https://dev.mysql.com/doc/refman/8.0/en/json-attribute-functions.html#function_json-length)) @Xuxiaotuan 
- [ ] JSON_KEYS ([JSON_KEYS()](https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#function_json-keys)) @caicancai 
- [ ] JSON_SEARCH ([JSON_SEARCH()](https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#function_json-search)) 
- [ ] MERGE_OF ([MEMBER OF()](https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#operator_member-of))

- [ ] JSON_INSERT ([JSON_INSERT()](https://dev.mysql.com/doc/refman/8.0/en/json-modification-functions.html#function_json-insert)).  @JasonWen1 
- [ ] JSON_REPLACE ([JSON_REPLACE()](https://dev.mysql.com/doc/refman/8.0/en/json-modification-functions.html#function_json-replace)) @cjj2010 
- [ ] JSON_SET ([JSON_SET()](https://dev.mysql.com/doc/refman/8.0/en/json-modification-functions.html#function_json-set))

- [ ] JSON_OVERLAPS ([JSON_OVERLAPS()](https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#function_json-overlaps))
- [ ] JSON_MERGE_PATCH ([JSON_MERGE_PATCH()](https://dev.mysql.com/doc/refman/8.0/en/json-modification-functions.html#function_json-merge-patch))
- [ ] JSON_MERGE_PRESERVE ([JSON_MERGE_PRESERVE()](https://dev.mysql.com/doc/refman/8.0/en/json-modification-functions.html#function_json-merge-preserve)) @taptao 
- [ ] JSON_REMOVE ([JSON_REMOVE()](https://dev.mysql.com/doc/refman/8.0/en/json-modification-functions.html#function_json-remove))
- [ ] JSON_TABLE ([JSON_TABLE()](https://dev.mysql.com/doc/refman/8.0/en/json-table-functions.html#function_json-table)) @lovlyhao 
- [ ] JSON_STORAGE_SIZE ([JSON_STORAGE_SIZE()](https://dev.mysql.com/doc/refman/8.0/en/json-utility-functions.html#function_json-storage-size))
- [ ] JSON_STORAGE_FREE ([JSON_STORAGE_FREE()](https://dev.mysql.com/doc/refman/8.0/en/json-utility-functions.html#function_json-storage-free))

U can pick this according comment below:
"I pick "-> ->> " " and this task could assign to u for one week, if no pr or progress during one week I would re-assign others

### Solution

U can pick this according comment below:
"I pick "-> ->> " " and this task could assign to u for one week, if no pr or progress during one week I would re-assign others 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by weijiew** [comment]
I will do it.

**Comment by amorynan** [comment]
> I will do it.

U should choose one or more task , like "I pick "-> ->> " " or "I pick "jsonb: json_contains " "

**Comment by yifei02** [comment]
I will do it

**Comment by weijiew** [comment]
I pick "jsonb: json_contains " and "json_contains_path".

**Comment by weijiew** [comment]
> I pick "jsonb: json_contains " and "json_contains_path".

ok , I pick "jsonb: json_contains " and "json_contains_path".

**Comment by yifei02** [comment]
I pick "jsonb: json_contains " and "json_contains_path".

**Comment by niebayes** [comment]
I pick "json: json_depth"

**Comment by Xuxiaotuan** [comment]
I pick "json: JSON_LENGTH"

**Comment by caicancai** [comment]
i pick "JSON_INSERT"

**Comment by caicancai** [comment]
i pick "json:JSON_INSERT"

**Comment by cjj2010** [comment]
i pick "json:JSON_REPLACE"

**Comment by yifei02** [comment]
I pick json_array

**Comment by niebayes** [comment]
I pick json_search

**Comment by JasonWen1** [comment]
I pick json_insert

**Comment by lovlyhao** [comment]
I pick JSON_TABLE.

**Comment by taptao** [comment]
i pick JSON_MERGE_PRESERVE

**Comment by davedwwang** [comment]
I pick JSON_REMOVE and JSON_MERGE_PATCH.

**Comment by xuefengze** [comment]
I pick JSON_SET

**Comment by kadirakinkorkunc** [comment]
> I pick json_search

@niebayes , any news about this?

**Comment by unreal-asr** [comment]
The problem is that even in version 3 of apche doris there is no way to add a path to an existing object. All json editing functions in doc, always report "Otherwise, a path-value pair for a non-existent path in the json is ignored and has no effect." A function similar to JSON_MERGE_PATCH is needed.
