### ISSUE TITLE
[Enhancement] 在hive catalog中支持不同存储类型

### ISSUE THREAD

**Issue by Huguowei** [apache/doris#21426]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

当前当hive表的数据存储在不同存储类型时（如hdfs、华为云obs），需要创建多个catalog分别对应（hive_hdfs hive_obs），实际上hive metastore只有一份，并且两个catalog中看到的表完全一致。
不支持查询hive_hdfs中的obs表，或hive_obs中的hdfs表。
如果将这两种配置集成到一起，在发起查询时自动判断是使用hdfs或obs，应该能更方便的使用，也避免了能看到表却不能查询的问题。

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lucienoz** [comment]
在使用doris查询hive catalog下的hudi表时会存在针对性的查询优化么? @melin
