### ISSUE TITLE
[Bug] Report unexpected exception for a nested sub query.

### ISSUE THREAD

**Issue by lide-reed** [apache/doris#21436]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.x, 2.x, master

### What's Wrong?

CREATE TABLE t (
  c1 varchar(50) NULL,
  c2 varchar(20) NULL,
  c3 varchar(10) NULL,
  c4 bigint(20) NULL
) ENGINE=OLAP
DUPLICATE KEY(`c1`)
DISTRIBUTED BY HASH(`c1`) BUCKETS 3;

SELECT c3
FROM (
  SELECT c1, c2, c3
    , if(r_num = 1, c4, 0) AS sales_quantity
  FROM (
    SELECT c1
      , if(c2 IS NULL, '', c2) AS c2
      , row_number() OVER (PARTITION BY c3, c1 ) AS r_num, c3, c4
    FROM t
  ) t1
) tmp;

### What You Expected?

no error

### How to Reproduce?

MySQL [testdb]> CREATE TABLE t (
    ->   c1 varchar(50) NULL,
    ->   c2 varchar(20) NULL,
    ->   c3 varchar(10) NULL,
    ->   c4 bigint(20) NULL
    -> ) ENGINE=OLAP
    -> DUPLICATE KEY(`c1`)
    -> DISTRIBUTED BY HASH(`c1`) BUCKETS 3;
Query OK, 0 rows affected (0.01 sec)

MySQL [testdb]> 
MySQL [testdb]> 
MySQL [testdb]> SELECT c3
    -> FROM (
    ->   SELECT c1, c2, c3
    ->     , if(r_num = 1, c4, 0) AS sales_quantity
    ->   FROM (
    ->     SELECT c1
    ->       , if(c2 IS NULL, '', c2) AS c2
    ->       , row_number() OVER (PARTITION BY c3, c1 ) AS r_num, c3, c4
    ->     FROM t
    ->   ) t1
    -> ) tmp;
ERROR 1105 (HY000): errCode = 2, detailMessage = Unexpected exception: Index: 3, Size: 2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lide-reed** [comment]
1.1.5 OK

-----
MySQL [testdb]> CREATE TABLE t (
    ->   c1 varchar(50) NULL,
    ->   c2 varchar(20) NULL,
    ->   c3 varchar(10) NULL,
    ->   c4 bigint(20) NULL
    -> ) ENGINE=OLAP
    -> DUPLICATE KEY(`c1`)
    -> DISTRIBUTED BY HASH(`c1`) BUCKETS 3;
Query OK, 0 rows affected (0.01 sec)

MySQL [testdb]> 
MySQL [testdb]> 
MySQL [testdb]> SELECT c3
    -> FROM (
    ->   SELECT c1, c2, c3
    ->     , if(r_num = 1, c4, 0) AS sales_quantity
    ->   FROM (
    ->     SELECT c1
    ->       , if(c2 IS NULL, '', c2) AS c2
    ->       , row_number() OVER (PARTITION BY c3, c1 ) AS r_num, c3, c4
    ->     FROM t
    ->   ) t1
    -> ) tmp;
Empty set (0.01 sec)

MySQL [testdb]> explain SELECT c3 FROM (   SELECT c1, c2, c3     , if(r_num = 1, c4, 0) AS sales_quantity   FROM (     SELECT c1       , if(c2 IS NULL, '', c2) AS c2       , row_number() OVER (PARTITION BY c3, c1 ) AS r_num, c3, c4     FROM t   ) t1 ) tmp;
+------------------------------------------------------------------------------------------------------+
| Explain String                                                                                       |
+------------------------------------------------------------------------------------------------------+
| PLAN FRAGMENT 0                                                                                      |
|   OUTPUT EXPRS:`c3`                                                                                  |
|   PARTITION: HASH_PARTITIONED: `default_cluster:testdb`.`t`.`c1`                                     |
|                                                                                                      |
|   VRESULT SINK                                                                                       |
|                                                                                                      |
|   0:VOlapScanNode                                                                                    |
|      TABLE: t(null), PREAGGREGATION: OFF. Reason: No AggregateInfo No AggregateInfo No AggregateInfo |
|      partitions=0/1, tablets=0/0, tabletList=                                                        |
|      cardinality=0, avgRowSize=16.0, numNodes=1                                                      |
+------------------------------------------------------------------------------------------------------+
10 rows in set (0.00 sec)

**Comment by morrySnow** [comment]
i test the latest master. it is ok

**Comment by starocean999** [comment]
I tested 1.2-lts, it's OK
