### ISSUE TITLE
[Bug] StringParser::string_to_decimal maybe out of bounds.

### ISSUE THREAD

**Issue by gohalo** [apache/doris#21453]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

when try to get divisor through get_scale_multiplier() function, maybe out of bounds. i don't known if this will get the wrong result.

### What You Expected?

as descript above.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gohalo** [comment]
this can be reproduced by the following sql.

```
CREATE TABLE IF NOT EXISTS example(
    `user_id` LARGEINT NOT NULL,
    `date` DATE NOT NULL,
    `city` VARCHAR(20),
    `age` SMALLINT,
    `sex` TINYINT,
    `cost` DECIMALv3(20, 2) SUM DEFAULT "0"
)
AGGREGATE KEY(`user_id`, `date`, `city`, `age`, `sex`)
DISTRIBUTED BY HASH(`user_id`) BUCKETS 1
PROPERTIES (
    "replication_allocation" = "tag.location.default: 1"
);
```

save the following data as test.csv file.

```
10000,2017-10-01,BeiJing,20,0,0.123456e-60
```

and then load the data with following shell command.

```
curl --location-trusted -u root: -T test.csv -H "column_separator:," http://127.0.0.1:29980/api/test/example/_stream_load
```

**Comment by stalary** [comment]
Have some error log?
