### ISSUE TITLE
[Bug] "errCode = 2, detailMessage = couldn't resolve slot descriptor" error happens when using  GROUPING SETS in subquery

### ISSUE THREAD

**Issue by SinyoWong** [apache/doris#21464]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris 1.2.2

### What's Wrong?

"errCode = 2, detailMessage = couldn't resolve slot descriptor" error happens when using  GROUPING SETS in subquery,
when the query without the metric column，error happens :
![image](https://github.com/apache/doris/assets/38577585/5d69dbf3-a85b-4932-ac1c-b0f9a59846bc)
when add the metric  column `pod` , the query is ok :
![image](https://github.com/apache/doris/assets/38577585/53ba90c0-6250-46c3-ae01-65e188d81a52)
when add a DIY column `diy_column` , the query is ok :
![image](https://github.com/apache/doris/assets/38577585/c033e634-be87-483b-810c-1f7ef5c84f35)

### What You Expected?

the query should be work with or without the metric column or the DIY column .

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
Try it in 1.2.5, it can resolve this problem.

**Comment by SinyoWong** [comment]
This problem is solved in doris 1.2.3.

**Comment by chenxingbao** [comment]
这个问题在2.0.3的版本还是存在哈

**Comment by jaychang9** [comment]
2.1.2版本还是存在

**Comment by MaxLinyun** [comment]
1.2.8版本也还存在该问题，可以通过“在 select Group Set 的节点里面，加一个 0 AS col_name”，绕过报错
