### ISSUE TITLE
[Bug] lateral view query questions

### ISSUE THREAD

**Issue by zhangy5** [apache/doris#21465]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master: doris-0.0.0-trunk-11e18f4

### What's Wrong?

wrong result:
<img width="1130" alt="image" src="https://github.com/apache/doris/assets/10826066/f59b6887-d389-4367-b6c9-0f08a3f38ee8">

query timeout:
<img width="1431" alt="image" src="https://github.com/apache/doris/assets/10826066/13d4be42-32df-466b-84e8-801ddd5c9337">
be core:
<img width="1439" alt="image" src="https://github.com/apache/doris/assets/10826066/debda6a3-e461-4c27-9f5a-afbb9811f087">

### What You Expected?

https://github.com/apache/doris/blob/master/docs/zh-CN/docs/sql-manual/sql-functions/table-functions/explode-split.md

![image](https://github.com/apache/doris/assets/10826066/88e57db5-66da-46fa-9878-9aad12c7120a)

### How to Reproduce?

```
CREATE TABLE `example1` (   `k1` bigint(20) NULL COMMENT 'k1', k2 varchar(20))DISTRIBUTED BY HASH(`k1`) BUCKETS 1;
insert into example1 values(1, ''), (2, null), (3, ','), (4, '1'), (5, '1, 2, 3'), (6, 'a, b, c');
select k1, e1 from example1 lateral view explode_split(k2, ',') tmp1 as e1 where k1 = 3 order by k1, e1;
select k1,e1 from example1 lateral view explode_json_array_int('[9223372036854775807,9223372036854775808]') tmp as e1 order by k1,e1;
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ixzc** [comment]
We will fix documentation errors and be core issues.

**Comment by ixzc** [comment]
fixed. https://github.com/apache/doris/pull/24284
