### ISSUE TITLE
[Bug] Setting the query timeout parameter in the JDBC connection parameters does not take effect.

### ISSUE THREAD

**Issue by successok** [apache/doris#21557]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

apache doris 1.2.3

### What's Wrong?

When using JDBC to read a table with a very large amount of data, the query may fail because it exceeds the default 300s timeout. Adding `?queryTimeout=3600&connectTimeout=10000&socketTimeout=10000` to the JDBC parameters does not have any effect.

### What You Expected?

set the query timeout parameter in the JDBC connection parameters

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yuanyuan8983** [comment]
Hello, you can try it like this, log in doris and SET the session variable parameter SET global query_timeout = 3600; You can add my wechat problems and let's see together: cyllyy810222

**Comment by bs352** [comment]
May I ask what is the status of this issue? It is marked as completed, but I still encounter this issue when trying to set queryTimeout via jdbc connection string variable.

Doris version: 2.0.15
PS: use SET query_timout statement works at session level.
