### ISSUE TITLE
[Enhancement] show stream load does not show transaction ID

### ISSUE THREAD

**Issue by xutaoustc** [apache/doris#21714]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

show stream load does not show transaction ID

### Solution

Should show the transaction ID in streamLoad

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
Why do you need the transactionId? I think label will work for most scenarios.
