### ISSUE TITLE
[Bug] doc create table statment goes failed

### ISSUE THREAD

**Issue by dinggege1024** [apache/doris#21851]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

All version

### What's Wrong?
![Uploading image.png…]()

![image](https://github.com/apache/doris/assets/109070189/265cdc1f-16a8-418b-b077-2c403bd87e72)

Example SQL run failed.

bucket key should be not null

### What You Expected?

work

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vinlee19** [comment]
I didn't reproduce your results.
![07UH5fExmD](https://github.com/apache/doris/assets/31833513/ce5614db-8c34-47eb-8452-6433e7bdc6f7)

**Comment by dinggege1024** [comment]
> I didn't reproduce your results. ![07UH5fExmD](https://user-images.githubusercontent.com/31833513/253868156-ce5614db-8c34-47eb-8452-6433e7bdc6f7.jpg)

sorry, root cause is replica num.

**Comment by dinggege1024** [comment]
So, i do not think this is a bug. Thks~
