### ISSUE TITLE
[Bug] add_month error

### ISSUE THREAD

**Issue by yqzdy1207** [apache/doris#22025]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.5

### What's Wrong?

select add_months('2023-04-30',-1);

应该返回2023-03-31 而不是 2023-03-30，这在计算每月的环比的时候，取值有问题。

hive 和 oracle 中都是返回 2023-03-31

### What You Expected?

 2023-03-30

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hf200012** [comment]
MySQL does not have a function with the same name, and the result after execution of the corresponding function is consistent with ours

```
SELECT date_sub('2023-06-30', interval 1 month)
The return value is: 2023-05-30
```

**Comment by flyMei** [comment]
按照正常逻辑    add_months('2023-04-30',-1);得出的结果应该是什么？这样关掉是不是不太合适
