### ISSUE TITLE
[Bug] (multi catalog) failed to get all database from hms client

### ISSUE THREAD

**Issue by noobcosmo** [apache/doris#22083]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris 1.2.6
CDP 7.4.4

### What's Wrong?

failed to get all database from hms client after create hive catalog

> 2023-07-21 15:46:54,347 WARN (mysql-nio-pool-10|511) [StmtExecutor.execute():593] execute Exception. stmt[165, f14302b309d9477e-906182f215bdcd27]
> org.apache.doris.datasource.HMSClientException: failed to get all database from hms client. reason: java.lang.NullPointerException: null
> 	at org.apache.doris.datasource.hive.PooledHiveMetaStoreClient.getAllDatabases(PooledHiveMetaStoreClient.java:75) ~[doris-fe.jar:1.2-SNAPSHOT]
> 	at org.apache.doris.datasource.HMSExternalCatalog.init(HMSExternalCatalog.java:116) ~[doris-fe.jar:1.2-SNAPSHOT]
> 	at org.apache.doris.datasource.ExternalCatalog.makeSureInitialized(ExternalCatalog.java:138) ~[doris-fe.jar:1.2-SNAPSHOT]
> 	at org.apache.doris.datasource.HMSExternalCatalog.listDatabaseNames(HMSExternalCatalog.java:172) ~[doris-fe.jar:1.2-SNAPSHOT]
> 	at org.apache.doris.datasource.ExternalCatalog.getDbNames(ExternalCatalog.java:213) ~[doris-fe.jar:1.2-SNAPSHOT]
> 	at org.apache.doris.qe.ShowExecutor.handleShowDb(ShowExecutor.java:697) ~[doris-fe.jar:1.2-SNAPSHOT]
> 	at org.apache.doris.qe.ShowExecutor.execute(ShowExecutor.java:250) ~[doris-fe.jar:1.2-SNAPSHOT]
> 	at org.apache.doris.qe.StmtExecutor.handleShow(StmtExecutor.java:1692) ~[doris-fe.jar:1.2-SNAPSHOT]
> 	at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:567) ~[doris-fe.jar:1.2-SNAPSHOT]
> 	at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:409) ~[doris-fe.jar:1.2-SNAPSHOT]
> 	at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:330) ~[doris-fe.jar:1.2-SNAPSHOT]
> 	at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:473) ~[doris-fe.jar:1.2-SNAPSHOT]
> 	at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:700) ~[doris-fe.jar:1.2-SNAPSHOT]
> 	at org.apache.doris.mysql.ReadListener.lambda$handleEvent$0(ReadListener.java:52) ~[doris-fe.jar:1.2-SNAPSHOT]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_191]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_191]
> 	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_191]
> Caused by: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.metastore.HiveMetaStoreClient
> 	at org.apache.hadoop.hive.metastore.utils.JavaUtils.newInstance(JavaUtils.java:86) ~[hive-shade-3-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
> 	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.(RetryingMetaStoreClient.java:95) ~[hive-shade-3-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
> 	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:148) ~[hive-shade-3-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
> 	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:119) ~[hive-shade-3-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
> 	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:112) ~[hive-shade-3-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
> 	at org.apache.doris.datasource.hive.PooledHiveMetaStoreClient$CachedClient.(PooledHiveMetaStoreClient.java:190) ~[doris-fe.jar:1.2-SNAPSHOT]
> 	at org.apache.doris.datasource.hive.PooledHiveMetaStoreClient$CachedClient.(PooledHiveMetaStoreClient.java:178) ~[doris-fe.jar:1.2-SNAPSHOT]
> 	at org.apache.doris.datasource.hive.PooledHiveMetaStoreClient.getClient(PooledHiveMetaStoreClient.java:214) ~[doris-fe.jar:1.2-SNAPSHOT]
> 	at org.apache.doris.datasource.hive.PooledHiveMetaStoreClient.getAllDatabases(PooledHiveMetaStoreClient.java:72) ~[doris-fe.jar:1.2-SNAPSHOT]
> 	... 16 more
> Caused by: java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
> 	at org.apache.hadoop.hive.metastore.utils.JavaUtils.newInstance(JavaUtils.java:84) ~[hive-shade-3-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
> 	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.(RetryingMetaStoreClient.java:95) ~[hive-shade-3-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
> 	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:148) ~[hive-shade-3-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
> 	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:119) ~[hive-shade-3-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
> 	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:112) ~[hive-shade-3-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
> 	at org.apache.doris.datasource.hive.PooledHiveMetaStoreClient$CachedClient.(PooledHiveMetaStoreClient.java:190) ~[doris-fe.jar:1.2-SNAPSHOT]
> 	at org.apache.doris.datasource.hive.PooledHiveMetaStoreClient$CachedClient.(PooledHiveMetaStoreClient.java:178) ~[doris-fe.jar:1.2-SNAPSHOT]
> 	at org.apache.doris.datasource.hive.PooledHiveMetaStoreClient.getClient(PooledHiveMetaStoreClient.java:214) ~[doris-fe.jar:1.2-SNAPSHOT]
> 	at org.apache.doris.datasource.hive.PooledHiveMetaStoreClient.getAllDatabases(PooledHiveMetaStoreClient.java:72) ~[doris-fe.jar:1.2-SNAPSHOT]
> 	... 16 more
> Caused by: java.lang.NullPointerException
> 	at org.apache.hadoop.util.StringUtils.stringifyException(StringUtils.java:90) ~[hadoop-common-3.3.5.jar:?]
> 	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.open(HiveMetaStoreClient.java:756) ~[doris-fe.jar:1.0.2-SNAPSHOT]
> 	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.(HiveMetaStoreClient.java:415) ~[doris-fe.jar:1.0.2-SNAPSHOT]
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
> 	at org.apache.hadoop.hive.metastore.utils.JavaUtils.newInstance(JavaUtils.java:84) ~[hive-shade-3-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
> 	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.(RetryingMetaStoreClient.java:95) ~[hive-shade-3-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
> 	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:148) ~[hive-shade-3-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
> 	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:119) ~[hive-shade-3-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
> 	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:112) ~[hive-shade-3-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
> 	at org.apache.doris.datasource.hive.PooledHiveMetaStoreClient$CachedClient.(PooledHiveMetaStoreClient.java:190) ~[doris-fe.jar:1.2-SNAPSHOT]
> 	at org.apache.doris.datasource.hive.PooledHiveMetaStoreClient$CachedClient.(PooledHiveMetaStoreClient.java:178) ~[doris-fe.jar:1.2-SNAPSHOT]
> 	at org.apache.doris.datasource.hive.PooledHiveMetaStoreClient.getClient(PooledHiveMetaStoreClient.java:214) ~[doris-fe.jar:1.2-SNAPSHOT]
> 	at org.apache.doris.datasource.hive.PooledHiveMetaStoreClient.getAllDatabases(PooledHiveMetaStoreClient.java:72) ~[doris-fe.jar:1.2-SNAPSHOT]
> 	... 16 more

### What You Expected?

fix this problem

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vinlee19** [comment]
Please describe your catalog statement。

**Comment by noobcosmo** [comment]
I changed the version to 2.0 and solved the problem by following [FAQ](https://doris.apache.org/zh-CN/docs/dev/lakehouse/faq)
