### ISSUE TITLE
[Bug] typo maxIdelTime

### ISSUE THREAD

**Issue by jasonchrion** [apache/doris#22198]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

there's a typo `maxIdelTime` in java files and be.conf :

https://github.com/apache/doris/blob/master/fe/be-java-extensions/jdbc-scanner/src/main/java/org/apache/doris/jdbc/JdbcExecutor.java#L91

`private int maxIdelTime;`

https://github.com/apache/doris/blob/master/conf/be.conf#L22

`-DJDBC_MAX_IDEL_TIME=300000`

### What You Expected?

it should be maxIdleTime.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zy-kkk** [comment]
-DJDBC_MAX_IDEL_TIME=300000 is passed as an argument to the JVM started by the BE process, and then JdbcExecuter will take the value of JDBC_MAX_IDEL_TIME and assign it to maxIdelTime. Then put it into the Druid connection pool for use.
You should pay attention to:
https://github.com/apache/doris/blob/master/fe/be-java-extensions/jdbc-scanner/src/main/java/org/apache/doris/jdbc/JdbcExecutor.java#L106
`maxIdelTime = Integer.valueOf(System.getProperty("JDBC_MAX_IDEL_TIME", "300000"));`

**Comment by BePPPower** [comment]
Thank you for reviewing code!
