### ISSUE TITLE
[Bug] doris 1.2.3/1.2.6 function char and trim raise error

### ISSUE THREAD

**Issue by jalousiex** [apache/doris#22200]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Server version: 5.7.99 Doris version doris-1.2.3-rc02-Unknown
also tried 1.2.6
client version: mysql  Ver 8.0.30 for Linux on x86_64 (Source distribution)

### What's Wrong?

mysql> select trim('ababccaab','ab') str;
ERROR 1105 (HY000): errCode = 2, detailMessage = No matching function with signature: trim(varchar(-1), varchar(-1)).
mysql> select char(10) as str;
ERROR 1105 (HY000): errCode = 2, detailMessage = No matching function with signature: char(tinyint(4)).

### What You Expected?

function worked as doc says

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zy-kkk** [comment]
you can try 1.2.6

**Comment by jalousiex** [comment]
> 

tried, the same result

**Comment by powerLambda** [comment]
example sql "select char(15049882, 15179199, 14989469);" does not work, 
**SQL Error [1105] [HY000]: errCode = 2, detailMessage = No matching function with signature: char(int(11), int(11), int(11)).**

https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-functions/string-functions/char
```
mysql> select char(68, 111, 114, 105, 115);
+--------------------------------------+
| char('utf8', 68, 111, 114, 105, 115) |
+--------------------------------------+
| Doris                                |
+--------------------------------------+

mysql> select char(15049882, 15179199, 14989469);
+--------------------------------------------+
| char('utf8', 15049882, 15179199, 14989469) |
+--------------------------------------------+
| 多睿丝                                     |
+--------------------------------------------+

mysql> select char(255);
+-------------------+
| char('utf8', 255) |
+-------------------+
| NULL              |
+-------------------+
```

**Comment by jalousiex** [comment]
now 2.0 solved
