### ISSUE TITLE
[Bug] BE core at je_arena_dalloc_promoted

### ISSUE THREAD

**Issue by lide-reed** [apache/doris#22324]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris 1.2.4 

### What's Wrong?

*** Query id: 613c7802e7884ae2-b0e8965e5d4da9a0 ***
*** Aborted at 1683802633 (unix time) try "date -d @1683802633" if you are using GNU date ***
*** Current BE git commitID: f90ce00 ***
*** SIGSEGV address not mapped to object (@0x0) received by PID 4734 (TID 0x7fb583dfe700) from PID 0; stack trace: ***
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /data/doris-1.x/be/src/common/signal_handler.h:420
 1# os::Linux::chained_handler(int, siginfo*, void*) in /usr/local/jdk/jre/lib/amd64/server/libjvm.so
 2# JVM_handle_linux_signal in /usr/local/jdk/jre/lib/amd64/server/libjvm.so
 3# signalHandler(int, siginfo*, void*) in /usr/local/jdk/jre/lib/amd64/server/libjvm.so
 4# 0x00007FB751054400 in /lib64/libc.so.6
 5# je_arena_dalloc_promoted at ../src/arena.c:1604
 6# __pthread_create_2_1 in /lib64/libpthread.so.0
 7# doris::Thread::start_thread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void ()> const&, unsigned long, scoped_refptr<doris::Thread>*) at /data/doris-1.x/be/src/util/thread.cpp:408
 8# doris::ThreadPool::create_thread() at /data/doris-1.x/be/src/util/threadpool.cpp:604
 9# doris::ThreadPool::do_submit(std::shared_ptr<doris::Runnable>, doris::ThreadPoolToken*) at /data/doris-1.x/be/src/util/threadpool.cpp:444
10# doris::ThreadPool::submit_func(std::function<void ()>) at /data/doris-1.x/be/src/util/threadpool.cpp:349
11# doris::FragmentMgr::exec_plan_fragment(doris::TExecPlanFragmentParams const&, std::function<void (doris::PlanFragmentExecutor*)>) at /var/local/ldb-toolchain/include/c++/11/bits/std_function.h:328
12# doris::FragmentMgr::exec_plan_fragment(doris::TExecPlanFragmentParams const&) at /data/doris-1.x/be/src/runtime/fragment_mgr.cpp:563
13# doris::PInternalServiceImpl::_exec_plan_fragment(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, doris::PFragmentRequestVersion, bool) at /data/doris-1.x/be/src/service/internal_service.cpp:372
14# doris::PInternalServiceImpl::exec_plan_fragment(google::protobuf::RpcController*, doris::PExecPlanFragmentRequest const*, doris::PExecPlanFragmentResult*, google::protobuf::Closure*) at /data/doris-1.x/be/src/service/internal_service.cpp:195
15# brpc::policy::ProcessHttpRequest(brpc::InputMessageBase*) in /usr/local/service/doris/lib/be/doris_be
16# brpc::ProcessInputMessage(void*) in /usr/local/service/doris/lib/be/doris_be
17# brpc::InputMessenger::OnNewMessages(brpc::Socket*) in /usr/local/service/doris/lib/be/doris_be
18# brpc::Socket::ProcessEvent(void*) in /usr/local/service/doris/lib/be/doris_be
19# bthread::TaskGroup::task_runner(long) in /usr/local/service/doris/lib/be/doris_be
20# bthread_make_fcontext in /usr/local/service/doris/lib/be/doris_be

### What You Expected?

no core

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lide-reed** [comment]
频繁出现，同样版本编译tcmalloc版本替换后没再出现

**Comment by vinlee19** [comment]
What is your java version? jdk 8 or jdk11?

**Comment by lide-reed** [comment]
jdk 8

**Comment by lide-reed** [comment]
It seems fixed by https://github.com/apache/doris/pull/21486
