### ISSUE TITLE
[Bug] (query) select count 和 intersect_count一起查询有bug，返回结果0

### ISSUE THREAD

**Issue by caiconghui** [apache/doris#22476]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

branch-1.2-lts

### What's Wrong?

CREATE TABLE test1 (
dt1 date NOT NULL,
dt2 date NOT NULL ,
id varchar(256) NULL,
type smallint(6) MAX NULL,
id_bitmap bitmap BITMAP_UNION NULL
) ENGINE=OLAP
AGGREGATE KEY(dt1, dt2, id)
PARTITION BY RANGE(dt1)
(PARTITION p20230725 VALUES [('2023-07-25'), ('2023-07-26')))
DISTRIBUTED BY HASH(dt1, dt2) BUCKETS 15;

insert into test1
select
str_to_date('2023-07-25','%Y-%m-%d') as dt1,
str_to_date('2023-07-25','%Y-%m-%d') as dt2,
'aaaaaaaaaa' as id,
1 as type,
BITMAP_HASH64('aaaaaaaaaa') as id_bitmap

select count(distinct if(type=1, id,null)) as count1,
intersect_count(id_bitmap, type, 1) as count2_bitmap from test1;

+--------+---------------+
| count1 | count2_bitmap |
+--------+---------------+
|      1 |             0 |
+--------+---------------+
1 row in set (0.02 sec)

### What You Expected?

return result both 1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by StLeoX** [comment]
intersect_count 的结果没问题吧。
id_bitmap 和 '1' 取交集，就是 'aaaaaaaaaa' 和 '1' 取交集，为空。

**Comment by caiconghui** [comment]
> intersect_count 的结果没问题吧。 id_bitmap 和 '1' 取交集，就是 'aaaaaaaaaa' 和 '1' 取交集，为空。

mysql> select intersect_count(id_bitmap, type, 1) as count2_bitmap from test1;
+---------------+
| count2_bitmap |
+---------------+
|             1 |
+---------------+
1 row in set (0.02 sec)
