### ISSUE TITLE
[Bug] doris create catalog for hive. Exception

### ISSUE THREAD

**Issue by dongsilun** [apache/doris#22584]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris-1.2.6
Hive-3.1.2

### What's Wrong?

I've copy hive-site.xml, hdfs-site.xml and core-site.xml to fe and be /conf.
I create a catalog for hive and I don't use kerberos.
There is a "org.apache.thrift.TApplicationException: Internal error processing initExternalCtlMeta" after I switch this catalog and run any sql.
Beside, if I create external table for hive, there is a —— org.apache.thrift.transport.TTransportException: GSS initiate failed.
![微信图片_20230804084512](https://github.com/apache/doris/assets/70750474/6196ac9c-1a74-4a30-9013-4fab53da279a)

### What You Expected?

How to fix it？

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhaoyankun** [comment]
i meet same question, How to solve it
