### ISSUE TITLE
[Bug] Error in parsing the delete statement

### ISSUE THREAD

**Issue by luozenglin** [apache/doris#22679]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0

### What's Wrong?
For the stock table containing the `date` type:
```
MySQL [testdb]> delete from cost2 where date = '2021-01-01';
ERROR 1105 (HY000): errCode = 2, detailMessage = errCode = 2, detailMessage = Left expr of binary predicate should be column name, predicate=`date` = '2021-01-01 00:00:00'
```

### What You Expected?

Successfully deleted

### How to Reproduce?

```
 ADMIN SET FRONTEND CONFIG ("enable_date_conversion" = "false");

 ADMIN SET FRONTEND CONFIG ("disable_datev1" = "false");

CREATE TABLE `cost` (
  `id` bigint(20) NULL,
  `name` varchar(20) NULL,
  `date` date NULL,
  `cost` bigint(20) SUM NULL
) ENGINE=OLAP
AGGREGATE KEY(`id`, `name`, `date`)
COMMENT 'OLAP'
DISTRIBUTED BY HASH(`id`, `name`) BUCKETS 8
PROPERTIES (
"replication_allocation" = "tag.location.default: 1"
);

insert into cost values (1, 'abc', '2021-01-01', 100);

delete from cost where date = '2021-01-01';
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by w517424787** [comment]
delete from cost2 where `date` = '2021-01-01' 不能删除吗？

**Comment by w517424787** [comment]
> 

在2.0版本上测试了，可以正常删除了，没有报错！
![image](https://github.com/apache/doris/assets/22090407/6356543f-8ba5-450e-8793-8563672d5fc9)

**Comment by luozenglin** [comment]
> > 
> 
> 在2.0版本上测试了，可以正常删除了，没有报错！ ![image](https://user-images.githubusercontent.com/22090407/258786926-6356543f-8ba5-450e-8793-8563672d5fc9.png)

Please strictly follow the reproduction steps given above
