### ISSUE TITLE
[Bug] 升级到  doris-2.0.0-rc04 后，jdbc sqlserver catalog 无法访问

### ISSUE THREAD

**Issue by ynzzxc** [apache/doris#22931]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

 doris-2.0.0-rc04

### What's Wrong?

![图片](https://github.com/apache/doris/assets/128353785/71ad4c80-8b82-4821-a02b-ee9d4babfd98)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ynzzxc** [comment]
如果 jdbc_url 中没有 useBulkCopyForBatchInsert=true，则 doris 会在末尾自动追加 “?useBulkCopyForBatchInsert=true”，导致错误。因此暂时解决该问题的办法是主动在 jdbc_url 末尾加上“;useBulkCopyForBatchInsert=true”，例如："jdbc_url" = "jdbc:sqlserver://xxx:xxx;DataBaseName=test;encrypt=false;useBulkCopyForBatchInsert=true"

**Comment by zy-kkk** [comment]
https://github.com/apache/doris/pull/23841
