### ISSUE TITLE
[Enhancement] Catalog JDBC for sqlserver uniqueidentifier Type

### ISSUE THREAD

**Issue by gojumprope** [apache/doris#23001]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

SQL Error [1105] [HY000]: errCode = 2, detailMessage = Unsupported type 'UNSUPPORTED_TYPE' in '`sqlserver_catalog`.`default_cluster:dbo`.`TestTable`.`Id`'.

### Solution

support data type uniqueidentifier for JDBC sql server

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zy-kkk** [comment]
That's a good idea. I'll take a look

**Comment by peak-xu** [comment]
Has it been fixed? Which version will be released

**Comment by peak-xu** [comment]
I see 2.0.1
