### ISSUE TITLE
[Bug] JDBC SQL Server unable to filter cast(column as datetime)

### ISSUE THREAD

**Issue by gojumprope** [apache/doris#23079]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.0

### What's Wrong?

CAUSED BY: SQLServerException: Line 1: Length or precision specification 0 is invalid.

### What You Expected?

able to filter datetime when cast column as datetime

### How to Reproduce?

select * from sqlserver_table
where cast(valuedatetime as datetime) >= '2023-08-16 00:00:00.000'

### Anything Else?

We are able to filter without casting it to datetime

select * from sqlserver_table
where valuedatetime >= '2023-08-16 00:00:00.000'

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zy-kkk** [comment]
I'm going to try to reproduce it and fix it

**Comment by zy-kkk** [comment]
Can you give me the sqlserver table structure, or add my wechat :zyk815574403

**Comment by zy-kkk** [comment]
I'm sorry I can't reproduce your problem, try setting `SET enable_nereids_planner=true;` If you still have questions, please let me know

**Comment by gojumprope** [comment]
Thanks, it is working when enable_nereids_planner is set to true
