### ISSUE TITLE
[Bug]  Be OOM when quering with regexp_extract_all and regexp_replace

### ISSUE THREAD

**Issue by yuxuan-luo** [apache/doris#23242]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.6,master

### What's Wrong?

select regexp_extract_all('asdfg', regexp_replace( regexp_replace( regexp_replace( regexp_replace( regexp_replace( regexp_replace( CONCAT('\(', 'zxc', '\)'), 'z', 'z|' ), 'x', 'x|' ), 'c', 'c|' ),  'dfg', 'dfg|' ), 'qwe', 'qwe|' ), '\\|$', '' ) );

执行这个sql会导致 be 内存飙高到 100 并被操作系统 kill 掉
### What You Expected?

可以正常使用

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lide-reed** [comment]
select regexp_extract_all('asdfg', '(z|x|c|)');   单纯这个语句就会hang住
