### ISSUE TITLE
[Bug] JDBC Catalog column data-type[tinyint(1)] mapping wrong to [boolean]

### ISSUE THREAD

**Issue by alanredsheep** [apache/doris#23447]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.6-rc03

### What's Wrong?

the mysql ddl
```
CREATE TABLE `table1` (
`id` int NOT NULL AUTO_INCREMENT,
`type` tinyint(1) NOT NULL COMMENT 'type [1,2,3]'
PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb3 COMMENT = ''
```
show create table through doris jdbc catalog
```
show create table mysql_catalog.db1.table1;
-- result as below
CREATE TABLE `table1` (
  `id` int(11) NOT NULL,
  `type` boolean NOT NULL COMMENT 'type [1,2,3]'
) ENGINE=JDBC_EXTERNAL_TABLE;
```
The tinyint(1) become boolean. And the query result is also wrong.

query on mysql
```
select distinct type from table1;
-- result is 2
```
query on doris jdbc catalog
```
select distinct type from mysql_catalog.db1.table1;
-- result is 1
```
 

### What You Expected?

[jdbc catalog](https://doris.apache.org/zh-CN/docs/1.2/lakehouse/multi-catalog/jdbc#mysql)

As the docs describe, the mysql [tinyint] should be mapping to doris [tinyint].
The tinyint(1) should be mapping to doris [tinyint] too.Then the query result wouldn't be wrong.

### Anything Else?

I hope this can be fixed on 1.2.x version.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zy-kkk** [comment]
It's fix by https://github.com/apache/doris/pull/22091
