### ISSUE TITLE
查询 JDBC Catalog 外部表时异常

### ISSUE THREAD

**Issue by xujiabing-001** [apache/doris#23461]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0-beta

### What's Wrong?

select count(*) from aaa_10_126_128.`b_v1.0`.access_record
如上sql所示，连接的 JDBC Catalog 外部数据库是mysql8，aaa_10_126_128是一个 JDBC Catalog 名称，b_v1.0 是数据库名称，access_record 是数据表名称。现在的问题是由于数据库名称是有【.】的，所以加了【``】这两个符号，但提示如下信息：
--------------------------------------------------------------------------
ERROR 1105 (HY000): errCode = 2, detailMessage = (192.168.103.3)[CANCELLED][INTERNAL_ERROR]UdfRuntimeException: JDBC executor sql has error: 
CAUSED BY: SQLSyntaxErrorException: Table 'b_v1.0.access_record' doesn't exist
--------------------------------------------------------------------------
用 explain select count(*) from aaa_10_126_128.`b_v1.0`.access_record 查看，就会发现解析错误

### What You Expected?

执行正常

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by tudouzhao** [comment]
Actually it is not a good habit to create table or database which has a name with comma.
for example, when creating database with name 'aaa.bb', then creating a table 'c.d' in aaa.bb.
It is very difficult for mysql to distinguish which part is correct database name.
Of course, it may be a bug of doris.
But I recommend optimizing your naming habits, which will benifits your business.
@xujiabing-001

**Comment by xujiabing-001** [comment]
> Actually it is not a good habit to create table or database which has a name with comma. for example, when creating database with name 'aaa.bb', then creating a table 'c.d' in aaa.bb. It is very difficult for mysql to distinguish which part is correct database name. Of course, it may be a bug of doris. But I recommend optimizing your naming habits, which will benifits your business. @xujiabing-001

数据库命令确实不规范，但现在已经在使用了，不能马上就能修改，那在doris里怎么解决这个问题呢

**Comment by zy-kkk** [comment]
https://github.com/apache/doris/pull/24520
This PR fixes the issue and can be tested until 2.0.3 is released
