### ISSUE TITLE
[Bug] 使用官方提供的docker-compose文件部署后BE起不来

### ISSUE THREAD

**Issue by TimothyDing** [apache/doris#23482]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.0

### What's Wrong?

[Bug] 使用官方提供的docker-compose文件部署后BE起不来。
![image](https://github.com/apache/doris/assets/47961320/6bde2e7e-49b8-40da-9b5c-d5a91097a46a)

启动后，BE始终起不来

### What You Expected?

执行docker-compose up -d 能部署完成

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ixzc** [comment]
You can try it again by following the link below
https://doris.apache.org/zh-CN/docs/dev/install/construct-docker/run-docker-cluster

**Comment by TimothyDing** [comment]
@ixzc Thanks.
