### ISSUE TITLE
[Bug] Sql cache return wrong result

### ISSUE THREAD

**Issue by dutyu** [apache/doris#23548]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

all version

### What's Wrong?

When enable query sql cache, if we delete some partition(s), the cache will not be refreshed and the query will return wrong result.

### What You Expected?

Query cache should return right result.

### How to Reproduce?

1. At `fe.conf`,  set `cache_last_version_interval_second=0`, `cache_enable_sql_mode=true`, then set session variable `set enable_sql_cache=true`,  and create a table like this:  
```sql
CREATE TABLE `tbl_test` (
  `siteid` int(11) NOT NULL DEFAULT "10",
  `citycode` smallint(6) NOT NULL DEFAULT "0",
  `username` varchar(32) NOT NULL DEFAULT "",
  `pday` varchar(20) NOT NULL DEFAULT "",
  `pv` bigint(20) SUM NOT NULL DEFAULT "0",
  INDEX siteid_Idx (`siteid`) USING BITMAP COMMENT '创建表加siteid列索引'
) ENGINE=OLAP
AGGREGATE KEY(`siteid`, `citycode`, `username`, `pday`)
PARTITION BY LIST(`pday`)
(
    PARTITION `p_20230825` VALUES IN ("20230825"),
    PARTITION `p_20230826` VALUES IN ("20230826"),
    PARTITION `p_20230827` VALUES IN ("20230827")
)
DISTRIBUTED BY HASH(`siteid`) BUCKETS 10
PROPERTIES (
"replication_allocation" = "tag.location.default: 1"
);    
```

2. insert some data:  
```sql
insert into `tbl_test` values(1, 1, 'test', '20230825', 1);
insert into `tbl_test` values(1, 1, 'test', '20230826', 1);
insert into `tbl_test` values(1, 1, 'test', '20230827', 1);
```
3. execute a query: `select * from tbl_test`, it will return 3 rows.
4. delete partition  `p_20230826` by executing `alter table tbl_test drop partition p_20230826`.
5. execute this query again: `select * from tbl_test`, it will return 3 rows too (in fact the right result should be 2, the row in partition `p_20230826` should not be returned).

![image](https://github.com/apache/doris/assets/5926365/95d14580-8044-4f68-b00a-c8539278589e)

### Anything Else?

The reason is that sql cache just use `partitionKey` , `latestVersion` and `latestTime` to check if the cache should be returned, if we delete some partition(s) which is not the latest updated partition, the all above values are not changed, so the cache will hit. 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by nimuyuhan** [comment]
Test the master branch code and the problem cannot be repeated.The cache_last_version_interval_second variable does not exist.
