### ISSUE TITLE
[Bug] NOT IN operator result cannot get null data

### ISSUE THREAD

**Issue by gojumprope** [apache/doris#23553]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.0

### What's Wrong?

unable to get null row when filter column NOT IN (something)

### What You Expected?

able to get null row 

### How to Reproduce?

SELECT b.aa FROM (
	SELECT 1 aa
	UNION ALL 
	SELECT NULL 
	UNION ALL
	SELECT 2
) b WHERE b.aa NOT IN ('12312')

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Min47** [comment]
Please solve this asap!
