### ISSUE TITLE
[Bug] All BEs crashed when decimalv3 meets function collect_list

### ISSUE THREAD

**Issue by shawn0762** [apache/doris#23606]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-1.2.6-rc03-Unknown

### What's Wrong?

Passing a decimalv3 column to function collect_list cause all BEs crashed.
And one of BEs logs some information: 

`F0829 10:43:51.419387   562 column_string.h:66] string column length is too large: total_length=18446603666933678141 ,element_number=9`

### What You Expected?

no

### How to Reproduce?

`
CREATE TABLE `decimalv3_test` (
  `d` date NULL,
  `pid` int(11) NULL,
  `money` decimalv3(8, 2) REPLACE_IF_NOT_NULL NULL
) ENGINE=OLAP
AGGREGATE KEY(`d`, `pid`)
COMMENT 'OLAP'
DISTRIBUTED BY HASH(`d`) BUCKETS 3
PROPERTIES (
  "replication_allocation" = "tag.location.default: 3",
  "in_memory" = "false",
  "storage_format" = "V2",
  "disable_auto_compaction" = "false"
);

insert into decimalv3_test values ('2023-08-01', 1, 7.6), ('2023-08-01', 2, 99.89), ('2023-08-02', 1, 79.6), ('2023-08-02', 3, 67.89);

select d, collect_list(pid), collect_list(money) from decimalv3_test group by d
`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ixzc** [comment]
we will fix it.

**Comment by ixzc** [comment]
fix https://github.com/apache/doris/pull/23629
![image](https://github.com/apache/doris/assets/49646212/76e9c986-3bd8-4568-a52b-19e843a4213f)
