### ISSUE TITLE
[Bug] Function ifnull if value type is double or decimal return only digits before the decimal point

### ISSUE THREAD

**Issue by MRYOG** [apache/doris#23623]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.6-release

### What's Wrong?

create SQL :
CREATE TABLE `test_ifnull` (
  `id` int(11) NULL COMMENT '',
  `t_decimal` DECIMALV3(26, 9) NULL,
  `test_double` double NULL
) ENGINE = OLAP 
DUPLICATE KEY(`id`) 
COMMENT 'test_table' 
DISTRIBUTED BY HASH(`id`) BUCKETS 1 
PROPERTIES (
  "compression" = "ZSTD"
);

insert SQL:
insert into test_ifnull VALUES(1,11111.11111,2222.22222)

test SQL : 
select id,t_decimal,test_double,ifnull(t_decimal,test_double) as if_dou,ifnull(test_double,t_decimal) as if_dei from test_ifnull

### What You Expected?

return right value

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by MRYOG** [comment]
<img width="1109" alt="image" src="https://github.com/apache/doris/assets/10381662/64a999b1-0ed7-4a56-9251-927507c7fa8b">

**Comment by nimuyuhan** [comment]
<img width="654" alt="image" src="https://github.com/apache/doris/assets/3031530/9e7d18e8-928c-489a-9db5-3bc5feef13c3">

**Comment by ixzc** [comment]
I've tested it. 1.2.6  have this problem, we will fix it. but 2.0.0 is ok.
