### ISSUE TITLE
[Bug] Function coalesce if value is decimal or double return wrong value

### ISSUE THREAD

**Issue by MRYOG** [apache/doris#23624]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.6-release

### What's Wrong?

create SQL :
CREATE TABLE `test_ifnull` (
  `id` int(11) NULL COMMENT '',
  `t_decimal` DECIMALV3(26, 9) NULL,
  `test_double` double NULL
) ENGINE = OLAP 
DUPLICATE KEY(`id`) 
COMMENT 'test_table' 
DISTRIBUTED BY HASH(`id`) BUCKETS 1 
PROPERTIES (
  "compression" = "ZSTD"
);

insert SQL:
insert into test_ifnull VALUES(1,11111.11111,2222.22222)

test SQL : 
select id,t_decimal,test_double,coalesce(t_decimal,test_double) as co_dou,coalesce(test_double,t_decimal) as co_dei from test_ifnull

<img width="1122" alt="image" src="https://github.com/apache/doris/assets/10381662/f8cefecf-b86d-406d-8fe1-d868b9ba03b4">

### What You Expected?

return right value

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ixzc** [comment]
thanks, we will fix it.

**Comment by ixzc** [comment]
fixed.   https://github.com/apache/doris/pull/23691
This issue currently only occurs in version 1.2.6, but 2.0.0 is fine.
