### ISSUE TITLE
[Bug] The use of process substitution (<(...)) in the newly added code within env.sh causes sh build.sh to fail

### ISSUE THREAD

**Issue by jyf111** [apache/doris#23688]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

git commit a1505d25

### What's Wrong?

PR #23618 uses process substitution (`<(...)`) in env.sh, which is not supported by `sh`.

As a result, when I follow the doc [use-off-the-shelf-image](https://doris.apache.org/docs/dev/install/source-install/compilation-general/#use-off-the-shelf-image) and run `sh build.sh`, it fails, and I need to run `bash build.sh` or `./build.sh` instead.

```bash
$ sh build.sh
Python 2.7.5
/root/doris/env.sh: line 149: syntax error near unexpected token `<'
$ which sh
/usr/bin/sh
```

### What You Expected?

Run `sh build.sh` successfully.

### How to Reproduce?

Git clone the latest code and follow the doc [use-off-the-shelf-image](https://doris.apache.org/docs/dev/install/source-install/compilation-general/#use-off-the-shelf-image).

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jyf111** [comment]
I noticed that PR #23676 fixed this :)

**Comment by adonis0147** [comment]
Hi @jyf111 , we should use `bash` instead of `sh` to run the shell scripts in the codebase.

For examples:
1. `bash build.sh`
2. `./build.sh`

**Comment by jyf111** [comment]
Yes, but the docs state `sh build.sh`, and I think we should keep `sh build.sh` run successfully.

**Comment by jyf111** [comment]
OK, but there are many `sh build.sh` in the docs, you fix it, or I submit a PR later?

**Comment by adonis0147** [comment]
> OK, but there are many `sh build.sh` in the docs, you fix it, or I submit a PR later?

I'm looking forward to your PRs. Thanks for your contributions!

**Comment by jyf111** [comment]
Hi, I've noticed that `sh *.sh` is commonly used in the docs, and in many cases, `sh` is just a symlink to `bash`.

So, I think it is better to keep the docs as it is.
