### ISSUE TITLE
[Bug] java不能通过httpclient提交数据到doris

### ISSUE THREAD

**Issue by dafanshu** [apache/doris#23712]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-2.0.0

### What's Wrong?

Reason: JSON data is array-object, `strip_outer_array` must be TRUE.. src line [[{"time":1691028275256,"code":"kkk","name":“test”,"create_time":"2023-08-08T06:21:03"}]];

### What You Expected?

success

### How to Reproduce?

HttpPut put = new HttpPut(this.loadUrl);
            put.setHeader(HttpHeaders.EXPECT, "100-continue");
            put.setHeader(HttpHeaders.AUTHORIZATION, this.authorization);
            put.setHeader(HttpHeaders.CONTENT_TYPE, "application/json; charset=UTF-8");
            put.setHeader("format", "json");
            put.setHeader("strip_outer_array", "true");

            HttpEntity entity = new StringEntity(content, ContentType.APPLICATION_JSON);
            put.setEntity(entity);

            try (CloseableHttpResponse response = client.execute(put)) {

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yagagagaga** [comment]
It looks like your data has an extra layer of square brackets.
