### ISSUE TITLE
When showing the catalog of max compute, the key did not mask

### ISSUE THREAD

**Issue by 0xqq** [apache/doris#24019]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.1

### What's Wrong?

When showing the catalog of max compute, the key did not mask 

show create catalog mc ；

 mc.secret_key and mc.access_key not mask.

### What You Expected?

 mc.secret_key or mc.access_key   mask.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wsjz** [comment]
https://github.com/apache/doris/pull/24124
