### ISSUE TITLE
from_second result error 

### ISSUE THREAD

**Issue by 0xqq** [apache/doris#24131]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.1

### What's Wrong?

select from_second(21474836470)

SQL 错误 [1105] [HY000]: errCode = 2, detailMessage = (xxxx.xxxx)[INTERNAL_ERROR]Function from_second get failed, expr is VectorizedFnCall[from_second](arguments=Int64,return=Nullable(DateTimeV2)) and return type is Nullable(DateTimeV2).

### What You Expected?

The result is correct

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LemonLiTree** [comment]
https://github.com/apache/doris/pull/23902 
Version 2.0.2 will support

**Comment by LemonLiTree** [comment]
https://github.com/apache/doris/pull/23902
Version 2.0.2 will support
