### ISSUE TITLE
请问DORIS 有没有微信技术支持群？

### ISSUE THREAD

**Issue by hillbun** [apache/doris#24282]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

请问DORIS 有没有微信技术支持群？

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ixzc** [comment]
add my wechat: 17625672480
