### ISSUE TITLE
[Bug](multi-catalog)Es catalog needs to verify whether it is a valid configuration.

### ISSUE THREAD

**Issue by liugddx** [apache/doris#24305]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

Es configuration error address can also be.

### What You Expected?

If es is unavailable, catalog creation fails.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by qidaye** [comment]
> Es configuration error address can also be.


What's the problem?

**Comment by liugddx** [comment]
> > Es configuration error address can also be.
> 
> What's the problem?

I configured a wrong es address. The catalog should not be created successfully but directly return failure. Is that so?
