### ISSUE TITLE
[Bug] streamload 的 DATETIMEV2 类型 不支持毫秒级？

### ISSUE THREAD

**Issue by Liangjiajjj** [apache/doris#24371]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

version doris-2.0.0-rc04(AVX2) RELEASE

### What's Wrong?

 Streamload 的 DATETIMEV2 类型 不支持毫秒级
使用stream load 和 Insert into 之后再使用 select 查询没有显示毫秒

<img width="371" alt="image" src="https://github.com/apache/doris/assets/34033349/77fec74f-a187-4b3b-a9d3-68ac6768ede0">

Create Sql：

CREATE TABLE IF NOT EXISTS test.example_tbl
(
    `user_id` LARGEINT NOT NULL COMMENT "用户id",
    `date` DATETIMEV2 NOT NULL COMMENT "数据灌入日期时间",
)
AGGREGATE KEY(`user_id`, `date`)
DISTRIBUTED BY HASH(`user_id`) BUCKETS 1
PROPERTIES (
"replication_allocation" = "tag.location.default: 1"
);

Insert into Sql：

INSERT INTO test.example_tbl
(user_id, `date`)
VALUES(222, '2023-01-11 11:11:11:333');

Streamload：

curl --location --request PUT 'http://192.168.2.120:8040/api/test/example_tbl/_stream_load' \
--header 'Authorization: Basic eGxpbms6WGxpbmshIzc4YWRpdQ==' \
--header 'read_json_by_line: false' \
--header 'format: json' \
--header 'strip_outer_array: true' \
--header 'Expect: 100-continue' \
--header 'connection: keep-alive' \
--header 'User-Agent: Apifox/1.0.0 (https://apifox.com)' \
--header 'Content-Type: application/json' \
--data-raw '[
    {
        "user_id": 1111,
        "date": "2023-01-11 11:11:11.111"
    }
]'

### What You Expected?

DATETIMEV2 的数据显示毫秒级，同毫秒级互相覆盖

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LOVEGISER** [comment]
create table ddl like this is work in stream load, but not work in insert into values :
`CREATE TABLE IF NOT EXISTS test.example_tbl
(
user_id LARGEINT NOT NULL COMMENT "用户id",
date DATETIMEV2(3) NOT NULL COMMENT "数据灌入日期时间",
)
AGGREGATE KEY(user_id, date)
DISTRIBUTED BY HASH(user_id) BUCKETS 1
PROPERTIES (
"replication_allocation" = "tag.location.default: 1"
);
`

**Comment by Liangjiajjj** [comment]
thanks a lot.
