### ISSUE TITLE
[Feature] support unix_timestamp() with microseconds

### ISSUE THREAD

**Issue by zclllyybb** [apache/doris#24382]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

mysql:
```SQL
select unix_timestamp(cast('2020-12-12 12:12:12.123' as datetime(3)));


unix_timestamp(cast('2020-12-12 12:12:12.123' as datetime(3)))
--
1607746332.123
```
ours:
```SQL
mysql> select unix_timestamp(cast('2020-12-12 12:12:12.123' as datetimev2(3)));
+------------+
| 1607746332 |
+------------+
| 1607746332 |
+------------+
1 row in set (0.10 sec)
```

so we need a new version of `unix_timestamp` which could calculate the microseconds.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by YangWithU** [comment]
Hello, I'd like to take the issue

**Comment by zclllyybb** [comment]
> Hello, I'd like to take the issue

sure, please add my wechat torch-wood_

**Comment by zclllyybb** [comment]
> 支持13位毫秒是不是更好

we should be compatible with mysql first. the timestamp with 13-digit is also considerable then.

**Comment by 435qb** [comment]
Can I work on this？
