### ISSUE TITLE
[Bug] group_concat don't support using distinct with order by together

### ISSUE THREAD

**Issue by pengtao211** [apache/doris#24581]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.1

### What's Wrong?

1105 - errCode = 2, detailMessage = group_concat don't support using distinct with order by together: group_concat(DISTINCT `time` ORDER BY `time` ASC)

### What You Expected?

I hope the group_concat support using distinct with order by together

### How to Reproduce?

SELECT day, GROUP_CONCAT(distinct time ORDER BY time) FROM (
SELECT 'Monday' day, '15:00-21:00' time
UNION ALL
SELECT 'Monday' day, '09:00-13:00' time
UNION ALL
SELECT 'Monday' day, '09:00-13:00' time
) tab
GROUP BY day

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ixzc** [comment]
This is not supported. You can do it another way

**Comment by pengtao211** [comment]
> This is not supported. You can do it another way

What is the other way？

**Comment by ixzc** [comment]
like this:


CREATE TABLE test_GROUP_CONCAT(
  value varchar(10)
)ENGINE=OLAP
DISTRIBUTED BY HASH(`value`)    
PROPERTIES
(
    "replication_num" = "1"
);

INSERT INTO test_GROUP_CONCAT (value)
VALUES ('a'), ('b'), ('c'), ('c');

select GROUP_CONCAT( `value`ORDER BY `value` ASC) from 
(
    select distinct value
    from test_GROUP_CONCAT
) a ;

**Comment by over-space** [comment]
group_concat can be converted to ARRAY_JOIN, ARRAY_SORT, COLLECT_SET/COLLECT_LIST combinations.

like this:

<img width="997" alt="image" src="https://github.com/apache/doris/assets/17663914/70f2eb5c-3232-4cf3-97ae-87d59b98cbfa">

**Comment by pengtao211** [comment]
> group_concat can be converted to ARRAY_JOIN, ARRAY_SORT, COLLECT_SET/COLLECT_LIST combinations.
> 
> like this:
> 
> <img alt="image" width="997" src="https://private-user-images.githubusercontent.com/17663914/343684640-70f2eb5c-3232-4cf3-97ae-87d59b98cbfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NzcwNDIsIm5iZiI6MTcxOTQ3Njc0MiwicGF0aCI6Ii8xNzY2MzkxNC8zNDM2ODQ2NDAtNzBmMmViNWMtMzIzMi00Y2YzLTk3YWUtODdkNTliOThjYmZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA4MjU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhMzQwN2RmMjk3ZTUxOWJkZTM4ZGZkZTY4ODYzMjdlNzcxYmM3ZTRhMWU1NWE0ZWJhMWI0Zjk3ZjBkMzdlMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.guuGpsL07O0PowtUNVL5_hRhFGc27VkvlOmnouWqwRM">

thank

**Comment by pengtao211** [comment]
> group_concat can be converted to ARRAY_JOIN, ARRAY_SORT, COLLECT_SET/COLLECT_LIST combinations.
> 
> like this:
> 
> <img alt="image" width="997" src="https://private-user-images.githubusercontent.com/17663914/343684640-70f2eb5c-3232-4cf3-97ae-87d59b98cbfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NzcwNDIsIm5iZiI6MTcxOTQ3Njc0MiwicGF0aCI6Ii8xNzY2MzkxNC8zNDM2ODQ2NDAtNzBmMmViNWMtMzIzMi00Y2YzLTk3YWUtODdkNTliOThjYmZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA4MjU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhMzQwN2RmMjk3ZTUxOWJkZTM4ZGZkZTY4ODYzMjdlNzcxYmM3ZTRhMWU1NWE0ZWJhMWI0Zjk3ZjBkMzdlMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.guuGpsL07O0PowtUNVL5_hRhFGc27VkvlOmnouWqwRM">

thank
