### ISSUE TITLE
[Bug] except sytex should be support input sungle column calc

### ISSUE THREAD

**Issue by LuGuangming** [apache/doris#24814]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.x

### What's Wrong?

except single column wrong
![image](https://github.com/apache/doris/assets/71873108/da483012-3a64-42ef-9d33-47d932ae3771)

### What You Expected?

except sytex should be support  input sungle column calc

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FrommyMind** [comment]
I just try redo what you had done, 

when I tried the sql after analyze command , it worked.
```sql
analyze table student;
SELECT * except(age) from student;
```

could you please just do a double check?

**Comment by liugddx** [comment]
Can you post be’s log and fe’s log here?
