### ISSUE TITLE
[Bug] Website https://doris.apache.org/ not working properly

### ISSUE THREAD

**Issue by leolivier** [apache/doris#25047]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

NO version: linked to the website

### What's Wrong?

![image](https://github.com/apache/doris/assets/4014752/b99511c9-21cc-4af2-ab9f-eb2e15bf362a)
Tested on Edge and Firefox with same error

### What You Expected?

A properly working website

### How to Reproduce?

Just open the website url. 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ixzc** [comment]
It's OK, you can try it again.
<img width="1141" alt="image" src="https://github.com/apache/doris/assets/49646212/cf435722-1a3f-4c03-a512-701c8b9ee5a7">

**Comment by leolivier** [comment]
Working again, thank you
