### ISSUE TITLE
[Bug] Failed to create auto partition

### ISSUE THREAD

**Issue by actcwlf** [apache/doris#25070]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.0

### What's Wrong?

use example from [document](https://doris.apache.org/zh-CN/docs/dev/advanced/partition/auto-partition)
```
MySQL [db]> CREATE TABLE `DAILY_TRADE_VALUE`
    -> (
    ->     `TRADE_DATE`              datev2 NULL COMMENT '交易日期',
    ->     `TRADE_ID`                varchar(40) NULL COMMENT '交易编号'
    -> )
    -> UNIQUE KEY(`TRADE_DATE`, `TRADE_ID`)
    -> AUTO PARTITION BY RANGE date_trunc(`TRADE_DATE`, 'year')
    -> (
    -> )
    -> DISTRIBUTED BY HASH(`TRADE_DATE`) BUCKETS 10
    -> PROPERTIES (
    ->   "replication_num" = "1"
    -> );
ERROR 1105 (HY000): errCode = 2, detailMessage = Syntax error in line 7:
AUTO PARTITION BY RANGE date_trunc(`TRADE_DATE`, 'year')
^
Encountered: AUTO
Expected
```

### What You Expected?

table created successfully.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ixzc** [comment]
Auto partition has been supported since version 2.0.3 ：https://doris.apache.org/zh-CN/docs/dev/advanced/partition/auto-partition

**Comment by actcwlf** [comment]
Thanks for your reply, I missed that version tag
