### ISSUE TITLE
[Bug] where，某些情况下多个条件无法被正确解释？

### ISSUE THREAD

**Issue by ynzzxc** [apache/doris#25081]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0

### What's Wrong?

示例如下：
条件1
![图片](https://github.com/apache/doris/assets/128353785/8fbafc76-7bc2-4f36-88fe-917e696908c2)
返回了正确结果；

条件2
![图片](https://github.com/apache/doris/assets/128353785/60c85c93-3332-41e8-8adc-5d02fbf9d98c)
返回了正确结果；

条件1 and 条件2
![图片](https://github.com/apache/doris/assets/128353785/2faa8906-7540-4995-acba-6958bb9dd557)
返回了错误结果；

### What You Expected?

1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yiguolei** [comment]
![img_v2_535a6013-a61b-4097-948c-4a14492732eg](https://github.com/apache/doris/assets/9208457/32ac0b63-3e05-4e88-8618-ca91258f15f0)
Your question is not clear. I do not think if both 1 and 2 has result, then 3 has result....

**Comment by ynzzxc** [comment]
> ![img_v2_535a6013-a61b-4097-948c-4a14492732eg](https://user-images.githubusercontent.com/9208457/273384140-32ac0b63-3e05-4e88-8618-ca91258f15f0.jpg) Your question is not clear. I do not think if both 1 and 2 has result, then 3 has result....

确实如此，但我并不是通过1,2有结果推导出3应当有结果，而是已经知道1,2,3都有结果，然后检验 doris 是否能返回正确结果，验证的结果是 1,2 返回了正确结果，3返回了错误结果。通过进一步测试，我发现在3场景下总是返回错误结果

**Comment by wyx123654** [comment]
是否可以先向表中插入一条满足3查询条件的数据然后再进行查询测试

**Comment by ynzzxc** [comment]
> 是否可以先向表中插入一条满足3查询条件的数据然后再进行查询测试

表中有已经有数十万条满足3查询条件的数据，这也是我为什么说3返回了错误结果的原因

**Comment by ynzzxc** [comment]
设置 set experimental_enable_nereids_planner = false; 可解决
