### ISSUE TITLE
[Bug] function JSON_EXTRACT return 'null' rather than NULL if cannot find result by extract_path

### ISSUE THREAD

**Issue by Yulei-Yang** [apache/doris#25102]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2 & trunk

### What's Wrong?

<img width="1611" alt="image" src="https://github.com/apache/doris/assets/28004179/853953bc-488c-4110-ac7c-c68a50acc490">

### What You Expected?

return NULL for such case

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
Maybe null is better

**Comment by Yulei-Yang** [comment]
> Maybe null is better

no, mysql and jsonb_extract return NULL in such case
