### ISSUE TITLE
[Bug] The BE that supports UDF can not start successfully.

### ISSUE THREAD

**Issue by nanfeng1999** [apache/doris#25161]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

the lastest master

### What's Wrong?

> INFO: java_cmd /usr/lib/jvm/java-11-openjdk-amd64/bin/java
INFO: jdk_version 11
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/yzy/project/doris/output/be/lib/java_extensions/preload-extensions/preload-extensions-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/yzy/project/doris/output/be/lib/java_extensions/java-udf/java-udf-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/yzy/project/doris/output/be/lib/hadoop_hdfs/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Reload4jLoggerFactory]

Exception: java.lang.StackOverflowError thrown from the UncaughtExceptionHandler in thread "process reaper"

### What You Expected?

run success

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DongLiang-0** [comment]
You can try using jdk8.

**Comment by nanfeng1999** [comment]
> You can try using jdk8.

Using Java 8 can solve this problem, but it should be mentioned on the official website?
