### ISSUE TITLE
[Bug] 建表数据类型设置为INT，会在插入数据时将有数据的存为null

### ISSUE THREAD

**Issue by lilei-github1** [apache/doris#25617]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.6

### What's Wrong?

我建表设置字段为INT类型，有大概率会将有整数值的数据写入库后变为null。这个现象必现。疑惑的是有的数据是null,有时候又不是 

### What You Expected?

如果是问题，麻烦修复下。如果问题存在，麻烦给我一个鼓励，谢谢

### How to Reproduce?

无

### Anything Else?

无

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lilei-github1** [comment]
抱歉，我想了下，应该是我设置了INT类型。但是要写入的数据不是我非常了解的。导致看起来里面的数据是整数，实际其中包含着复数类型，例如数据里是36.0，但我使用wps工具查看，看到的是36，导致我判断为整数，所以无法写入。感谢你们的付出



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月19日(周四) 下午5:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [apache/doris] [Bug] 建表数据类型设置为INT，会在插入数据时将有数据的存为null (Issue #25617)




 
Can you provide a reproducible case?

**Comment by LemonLiTree** [comment]
ok
