### ISSUE TITLE
[Bug] need selectBaseIndex but have mv expr（普通视图与物化视图同时存在时）

### ISSUE THREAD

**Issue by ynzzxc** [apache/doris#25692]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.02

### What's Wrong?

base表duplicate模型，当我先创建一个物化视图，再创建一个包含聚合的普通视图，然后去查询普通视图时，似乎无法定位selectbaseindex，如下图
![图片](https://github.com/apache/doris/assets/128353785/aa5185cf-0418-4279-9ec7-73493ab5915a)

### What You Expected?

1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LemonLiTree** [comment]
Can you provide the  create table statement?

**Comment by ynzzxc** [comment]
> Can you provide the create table statement?

这个问题已经被确认是一个bug，会尽快修复

**Comment by ynzzxc** [comment]
新优化器 bug，关闭新优化器即可解决 SET enable_nereids_planner=false;
