### ISSUE TITLE
[Enhancement] Implement format methods for `Status`

### ISSUE THREAD

**Issue by platoneko** [apache/doris#25974]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Implementing format methods for `Status`, then developers can format status directly  in `fmt`.
Current:
```c++
fmt::format("{}", status.to_string());
```
Expected:
```c++
fmt::format("{}", status);
```

### Solution

See https://wgml.pl/blog/formatting-user-defined-types-fmt.html

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Dragonliu2018** [comment]
I want to try it.
