### ISSUE TITLE
[Bug]  be specifies that the ssd fails to start and crashes when storage_root_path is configured

### ISSUE THREAD

**Issue by xingyingone** [apache/doris#25986]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-2.0.2-rc05-ae923f7

### What's Wrong?

![f66bcc30fa0ae688e8a78020bde15b3](https://github.com/apache/doris/assets/16775757/47b51864-336e-4f30-9888-b99c515ba21f)
![422a84104c4a1e3dfdd9a16dc592ef3](https://github.com/apache/doris/assets/16775757/ea4559fe-8d59-4192-9760-44ee6a267f02)

如上，目录已经存在了，但是配置了SSD就会crash。改成medium方式配置也一样会crash

### What You Expected?

The configuration described in the official documentation should be supported

### How to Reproduce?

按照上述方式配置storage_root_path

### Anything Else?

无

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xingyingone** [comment]
![image](https://github.com/apache/doris/assets/16775757/ecc01f00-582e-4441-98b8-9e90fd7c29f1)

**Comment by ixzc** [comment]
You misunderstand the document. https://doris.apache.org/zh-CN/docs/admin-manual/config/be-config?_highlight=ssd
You should use medium, not 100
