### ISSUE TITLE
如何使用doris进行（分钟，小时和天等级别的）大数据自动聚合以支撑较长时间范围的高性能数据查询？

### ISSUE THREAD

**Issue by wangchong2023** [apache/doris#26077]
我们的原始数据规模较大，又需要查询短期（分钟，小时）和长期（天，月，年）的数据统计。想请教一下如何使用Doris的建表模型来实现这一功能？而且尽量避免在上层的业务层感知这种自动聚合？
物化视图可以支持这一功能吗？

**Comment by hf200012** [comment]
加我微信聊35926237

Constantine ***@***.***>于2023年10月29日 周日16:24写道：

**Comment by wangchong2023** [comment]
@hf200012 
是不是[v2.1版本](https://github.com/apache/doris/issues/31770)已经支持Job调度来解决该问题了？
<img width="876" alt="image" src="https://github.com/apache/doris/assets/127951479/a20ffc91-a0e8-4ad9-ab4c-c153c56c9341">

**Comment by smallyao** [comment]
@wangchong2023  最后用的什么方案解决的？：）

**Comment by wangchong2023** [comment]
> @wangchong2023 最后用的什么方案解决的？：）

@smallyao 业务层代码做调度啊

**Comment by smallyao** [comment]
@wangchong2023  Doris的聚合模型或者物化视图是不是也可以？你们这边数据量级如何？

**Comment by smallyao** [comment]
@wangchong2023  Doris的聚合模型或者物化视图是不是也可以？

**Comment by ChenShuai1981** [comment]
mv和job scheduler都不是实时的，如何确保不同时间粒度聚合查询结果的一致性？
