### ISSUE TITLE
[Bug] 'days_add' funtion return incorrect date type

### ISSUE THREAD

**Issue by Larborator** [apache/doris#26098]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.2

### What's Wrong?

The return type **is not** consistent with that of the parameter date.

![image](https://github.com/apache/doris/assets/19779893/7d892590-0ef1-4bc8-98c8-83b3104d3499)

### What You Expected?

Return '2023-02-03'

### How to Reproduce?

```select days_add(str_to_date("20230202",'%Y%m%d'), 1) AS dt; ```

### Anything Else?

Looks like a display bug

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
let me try

**Comment by liugddx** [comment]
<img width="635" alt="image" src="https://github.com/apache/doris/assets/48236177/c6b93952-9022-4148-9165-e6b4b25c6210">

Already fixed.

**Comment by LemonLiTree** [comment]
`set experimental_enable_nereids_planner = true;`

**Comment by Larborator** [comment]
> <img alt="image" width="635" src="https://user-images.githubusercontent.com/48236177/279417270-c6b93952-9022-4148-9165-e6b4b25c6210.png">
> Already fixed.



> <img alt="image" width="635" src="https://user-images.githubusercontent.com/48236177/279417270-c6b93952-9022-4148-9165-e6b4b25c6210.png">
> Already fixed.

thanks, do you know the specific PR?
