### ISSUE TITLE
[Bug] Doris文本排序跟Mysql不一致

### ISSUE THREAD

**Issue by xiaolei55** [apache/doris#26195]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.2

### What's Wrong?

Doris对于文本类型的排序跟Mysql不一致

### What You Expected?

Doris对于文本类型的排序保持跟Mysql一致

### How to Reproduce?

复现表结构及测试数据

mysql：

CREATE TABLE `test_user` (
  `id` int(11) NOT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

INSERT INTO `test_user`(`id`, `NAME`) VALUES (10010535, 'clover op');
INSERT INTO `test_user`(`id`, `NAME`) VALUES (10010625, 'clover opliu');
INSERT INTO `test_user`(`id`, `NAME`) VALUES (10010594, 'clover05 test');
INSERT INTO `test_user`(`id`, `NAME`) VALUES (10014598, 'Danny 465498498465498 TESTI');
INSERT INTO `test_user`(`id`, `NAME`) VALUES (10014592, 'Danny 5654654684 TESTIII');
INSERT INTO `test_user`(`id`, `NAME`) VALUES (10015808, 'Danny TEST TESTcommission');
INSERT INTO `test_user`(`id`, `NAME`) VALUES (10015824, 'Danny TEST TESTDFIF');
INSERT INTO `test_user`(`id`, `NAME`) VALUES (10014579, 'Danny TESTII');
INSERT INTO `test_user`(`id`, `NAME`) VALUES (10014577, 'Danny TESTTTEST');
INSERT INTO `test_user`(`id`, `NAME`) VALUES (10014458, 'DannycomminTEST TEST');
INSERT INTO `test_user`(`id`, `NAME`) VALUES (10013772, 'DannyMay Danny TEST');
INSERT INTO `test_user`(`id`, `NAME`) VALUES (10017010, 'DannyMTV TEST');
INSERT INTO `test_user`(`id`, `NAME`) VALUES (10018208, 'DannyMTV TEST TESTIII');
INSERT INTO `test_user`(`id`, `NAME`) VALUES (10015314, 'DannyTEST TESTFDXDDFC');
INSERT INTO `test_user`(`id`, `NAME`) VALUES (10013827, 'DannyTESTRR 54654 TEST');
INSERT INTO `test_user`(`id`, `NAME`) VALUES (10013193, 'jerry test');
INSERT INTO `test_user`(`id`, `NAME`) VALUES (10014037, 'jerry test');
INSERT INTO `test_user`(`id`, `NAME`) VALUES (10018934, 'jerry user');
INSERT INTO `test_user`(`id`, `NAME`) VALUES (10015070, 'jerry user 1040');
INSERT INTO `test_user`(`id`, `NAME`) VALUES (10014427, 'jerry user yilingsanba2');

doris：

  CREATE TABLE
IF NOT EXISTS ods_test_user (
  `id` INT NOT NULL COMMENT "tuo.user_id",
  `NAME` VARCHAR ( 255 )  COMMENT "tu.real_name"

  ) 
  UNIQUE  KEY (`id`) 
  DISTRIBUTED BY HASH (`id`) BUCKETS 1 
  PROPERTIES (
     "replication_allocation" = "tag.location.default: 1",
    "enable_unique_key_merge_on_write" = "true",
    "light_schema_change" = "true",
    "store_row_column" = "true"
  );
  
INSERT INTO `ods_test_user`(`id`, `NAME`) VALUES (10010535, 'clover op');
INSERT INTO `ods_test_user`(`id`, `NAME`) VALUES (10010625, 'clover opliu');
INSERT INTO `ods_test_user`(`id`, `NAME`) VALUES (10010594, 'clover05 test');
INSERT INTO `ods_test_user`(`id`, `NAME`) VALUES (10014598, 'Danny 465498498465498 TESTI');
INSERT INTO `ods_test_user`(`id`, `NAME`) VALUES (10014592, 'Danny 5654654684 TESTIII');
INSERT INTO `ods_test_user`(`id`, `NAME`) VALUES (10015808, 'Danny TEST TESTcommission');
INSERT INTO `ods_test_user`(`id`, `NAME`) VALUES (10015824, 'Danny TEST TESTDFIF');
INSERT INTO `ods_test_user`(`id`, `NAME`) VALUES (10014579, 'Danny TESTII');
INSERT INTO `ods_test_user`(`id`, `NAME`) VALUES (10014577, 'Danny TESTTTEST');
INSERT INTO `ods_test_user`(`id`, `NAME`) VALUES (10014458, 'DannycomminTEST TEST');
INSERT INTO `ods_test_user`(`id`, `NAME`) VALUES (10013772, 'DannyMay Danny TEST');
INSERT INTO `ods_test_user`(`id`, `NAME`) VALUES (10017010, 'DannyMTV TEST');
INSERT INTO `ods_test_user`(`id`, `NAME`) VALUES (10018208, 'DannyMTV TEST TESTIII');
INSERT INTO `ods_test_user`(`id`, `NAME`) VALUES (10015314, 'DannyTEST TESTFDXDDFC');
INSERT INTO `ods_test_user`(`id`, `NAME`) VALUES (10013827, 'DannyTESTRR 54654 TEST');
INSERT INTO `ods_test_user`(`id`, `NAME`) VALUES (10013193, 'jerry test');
INSERT INTO `ods_test_user`(`id`, `NAME`) VALUES (10014037, 'jerry test');
INSERT INTO `ods_test_user`(`id`, `NAME`) VALUES (10018934, 'jerry user');
INSERT INTO `ods_test_user`(`id`, `NAME`) VALUES (10015070, 'jerry user 1040');
INSERT INTO `ods_test_user`(`id`, `NAME`) VALUES (10014427, 'jerry user yilingsanba2');

排序结果：
mysql
select * from test_user order by NAME asc;
![image](https://github.com/apache/doris/assets/112077320/bc5526a5-0d21-48f4-96c3-f085b5f51a88)

doris
select * from ods_test_user order by NAME asc;
![image](https://github.com/apache/doris/assets/112077320/9beefd94-9587-4dc0-9d2a-968d3054e4a8)

临时方法可以使用小写进行排序，doris sql如下：
select * from ods_test_user order by lower(NAME);

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhiqiang-hhhh** [comment]
It is not a bug. Order by char is based on ASIC value.
