### ISSUE TITLE
[Bug] export parquet format got wrong result

### ISSUE THREAD

**Issue by cambyzju** [apache/doris#26207]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-2.0.3-rc01dev-8cbd8fd3fd

### What's Wrong?

export table will null data, use parquet format got wrong result

### What You Expected?

export correct result

### How to Reproduce?

1. create table:
`> create table test_for_export_parquet (k1 int, v1 int) duplicate key(k1) distributed by hash(k1) buckets 1;`

2. insert data **with NULL**, and make sure the last row do not with null
`insert into test_for_export_parquet values(1, null),(2,2),(3,3),(4,4);`

3. check data
```
> select * from test_for_export_parquet;
+------+------+
| k1   | v1   |
+------+------+
|    1 | NULL |
|    2 |    2 |
|    3 |    3 |
|    4 |    4 |
+------+------+
4 rows in set (0.021 sec)
```

4. export table using parquet format, for example:
```
EXPORT TABLE test_for_export_parquet TO "s3://xxx"
PROPERTIES (
  "column_separator"="\\x07",
  "line_delimiter" = "\\x07",
  "format" = "parquet"
) WITH s3 (
  "AWS_ENDPOINT" = "",
  "AWS_ACCESS_KEY" = "",
  "AWS_SECRET_KEY"="",
  "AWS_REGION" = "",
  "use_path_style" = "false"
)
```

5. check the output parquet file, we find data is wrong
<img width="509" alt="image" src="https://github.com/apache/doris/assets/10771715/b033c825-c767-488f-9ca6-e17e0bde7296">

### Anything Else?

In vparquet_writer.cpp, we use WriteBatch to write parquet data, actually we should use WriteBatchSpaced.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by cambyzju** [comment]
Master version also has problem...

doris-0.0.0-trunk-5efc6c4233

<img width="509" alt="image" src="https://github.com/apache/doris/assets/10771715/6d68747d-030e-4a8f-bd23-441fc70fc020">

**Comment by morningman** [comment]
And I also test the master branch, still works fine.
Please check your FE\BE version
