### ISSUE TITLE
doris/be/lib/doris_be: cannot execute binary file

### ISSUE THREAD

**Issue by codeDing18** [apache/doris#26387]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris 2.0.2
macos 14.1 (23B74)
jdk1.8

### What's Wrong?

I download the [apache-doris-2.0.2-bin-x64.tar.gz](https://apache-doris-releases.oss-accelerate.aliyuncs.com/apache-doris-2.0.2-bin-x64.tar.gz) from [the latest binary version of Doris](https://doris.apache.org/zh-CN/download/) .I execute the command `be/bin/start_be.sh --daemon`.Then be/log/be.out show `be/lib/doris_be: cannot execute binary file`.I can not start  be server.

### What You Expected?

I just want be server to start.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ixzc** [comment]
This is for linux, so you should compile it by yourself.

**Comment by codeDing18** [comment]
> This is for linux, so you should compile it by yourself.

thx
