### ISSUE TITLE
insert executeUpdate SQLException

### ISSUE THREAD

**Issue by sdhzwc** [apache/doris#26555]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.2

### What's Wrong?

![image](https://github.com/apache/doris/assets/46134044/2c5db604-00d7-4442-aa85-498515afcee7)
mysql库 pg库 我测试都没问题

### What You Expected?

能够批量执行

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LemonLiTree** [comment]
It doesn’t look like Doris is reporting error
