### ISSUE TITLE
[Bug] CREATE USER ·····UNBOUNDED，中UNBOUNDED参数无效

### ISSUE THREAD

**Issue by le229** [apache/doris#26559]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.2

### What's Wrong?

CREATE USER jack IDENTIFIED BY '123456'  FAILED_LOGIN_ATTEMPTS 3 PASSWORD_LOCK_TIME UNBOUNDED;
UNBOUNDED 参数无法生效，如果是具体天数锁定可以生效。

### What You Expected?

UNBOUNDED 参数可以生效

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LemonLiTree** [comment]
I will fix it

**Comment by LemonLiTree** [comment]
https://github.com/apache/doris/pull/26585
