### ISSUE TITLE
[Bug] jsonb 插入报错

### ISSUE THREAD

**Issue by aopangzi** [apache/doris#26580]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-2.0.2-rc05

### What's Wrong?

json字段内容：{"人员信息报备表模板": "{\"88641855e5849d0e027b8249a4dfee18\":{\"name\":\"人员信息报备表.xlsx\",\"path\":\"/data/app/code/USERRES/fields/88641855e5849d0e027b8249a4dfee18\"}}"}
doris字段类型json时，通过mysql抽取数据进行插入报错：
Execution failed: Error Failed to execute sql: java.sql.SQLException: (conn=1687) errCode = 2, detailMessage = Invalid jsonb literal: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 19 path $.人员信息报备表模板

### What You Expected?

json字段可以正常插入不报错

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LemonLiTree** [comment]
It doesn’t look like this is legal json

**Comment by aopangzi** [comment]
是合法的，mysql可以插入，json格式化工具可以验证通过，贴上来被转换了。

> It doesn’t look like this is legal json

**Comment by foundation1** [comment]
大佬这个问题我也遇到了 你是怎么解决的啊
![image](https://github.com/apache/doris/assets/28500506/e0b190bc-ebbc-433b-b0e2-13ee33d5785e)
