### ISSUE TITLE
[Bug] date_trunc跟文档说的不一样，不支持填不存在的unit

### ISSUE THREAD

**Issue by paything** [apache/doris#27077]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.2

### What's Wrong?

https://doris.apache.org/docs/sql-manual/sql-functions/date-time-functions/date-trunc?_highlight=date

DATE_TRUNC
funtion

unit is the time unit you want to truncate. The optional values are as follows: [second,minute,hour,day,week,month,quarter,year]。 If unit does not meet the above optional values, the result will return NULL.

when i use the unit does not meet the above optional values
the result return is not NULL but throw a error
errCode = 2, detailMessage = date_trunc function second param only support argument is year|quarter|month|week|day|hour|minute|second

### What You Expected?

when i excute

select date_trunc('2022-02-02 02:02:02','all')

please return 
NULL

or support decade unit

### How to Reproduce?

excute

select date_trunc('2022-02-02 02:02:02','all')

### Anything Else?

希望可以像文档说的那样支持

unit 参数是您希望截断的时间间隔，可选的值如下：[second,minute,hour,day,week,month,quarter,year]。
 如果unit 不符合上述可选值，结果将返回NULL。

尤其是后半句话
别报错了

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Yulei-Yang** [comment]
clickhouse throw error for such case too
