### ISSUE TITLE
[Bug] Catalog connections not released

### ISSUE THREAD

**Issue by jztian** [apache/doris#27263]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-2.0.2-rc05-ae923f7

### What's Wrong?

CREATE CATALOG `adb_mysql` PROPERTIES (
"user" = "xxx",
"type" = "jdbc",
"password" = "XXX",
"jdbc_url" = "jdbc:mysql://xxx.ads.aliyuncs.com:3306?socketTimeout=600000",
"driver_url" = "file:///opt/lib/mysql-connector-java-5.1.49.jar",
"driver_class" = "com.mysql.jdbc.Driver"
);

Doris catalog connects to adb, and after running for a period of time, the number of connections increases to over 200.
(Call the adb API to obtain data on the number of connections)

 jmap -histo:live 3893933 > 1.jmap
[1.jmap.zip](https://github.com/apache/doris/files/13406097/1.jmap.zip)

### What You Expected?

Normal number of connections

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
What actions did you perform?

**Comment by jztian** [comment]
> What actions did you perform?
Push data to adb.
example: insert into  adb_catalog.db.table select  internal.db.table
Execute every 30 seconds, incremental push

**Comment by shedar** [comment]
I was able to reproduce connections growing with jdbc postgresql catalog, on refresh+select cycle.
```sql
refresh catalog pg_jdbc_app;
select * from pg_jdbc_app.public.data limit 20;
```
From looking at source code, it seems, that [setUninitialized](https://github.com/apache/doris/blob/master/fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalCatalog.java#L290) doesn't trigger onClose, and onClose is [used by JdbcExternalCatalog](https://github.com/apache/doris/blob/master/fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/JdbcExternalCatalog.java#L74) to release connections. So after refresh a new jdbc client is created with a new connection, increasing the count

**Comment by liugddx** [comment]
> I was able to reproduce connections growing with jdbc postgresql catalog, on refresh+select cycle.
> 
> ```sql
> refresh catalog pg_jdbc_app;
> select * from pg_jdbc_app.public.data limit 20;
> ```
> 
> From looking at source code, it seems, that [setUninitialized](https://github.com/apache/doris/blob/master/fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalCatalog.java#L290) doesn't trigger onClose, and onClose is [used by JdbcExternalCatalog](https://github.com/apache/doris/blob/master/fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/JdbcExternalCatalog.java#L74) to release connections. So after refresh a new jdbc client is created with a new connection, increasing the count

Yes, you are right.
