### ISSUE TITLE
[Bug] 在明细模型上建立物化视图后，聚合查询结果不正确

### ISSUE THREAD

**Issue by tangbinyeer** [apache/doris#27277]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.2

### What's Wrong?

按照官方文档，创建明细基表：
`create table sales_records(record_id int, seller_id int, store_id int, sale_date date, sale_amt bigint) distributed by hash(record_id) properties("replication_num" = "1");`

建立物化视图：
`create materialized view store_amt as select store_id, sum(sale_amt) from sales_records group by store_id;`

插入数据：
`insert into sales_records values(1,1,1,"2020-02-02",1),(1,2,2,"2020-02-02",1);`
注意：这里store_id 不同。

查询聚合数据：
`SELECT store_id, sum(sale_amt) FROM sales_records GROUP BY store_id;`
结果：
![image](https://github.com/apache/doris/assets/30048177/1357000d-9536-4b96-9783-b034e3c4a694)
期望结果：
应该有两条结果，分别表示 store_id=1和store_id=2的汇聚结果。

explain确认走了物化视图：
`EXPLAIN SELECT store_id, sum(sale_amt) FROM sales_records GROUP BY store_id;`
![image](https://github.com/apache/doris/assets/30048177/43787992-81b2-4421-89ad-ba91037b494e)

另外：当我先建立明细表，然后插入多条明细数据，再建立物化视图后，查询结果是正确的，但当再次插入数据后，结果就不正确了。

### What You Expected?

分组聚合结果正确

### How to Reproduce?

按照问题里步骤操作

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by tangbinyeer** [comment]
进一步测试发现，在insert into values跟一条数据的情况下，统计是正确的，但同时插入多条数据时，结果是错误的。

**Comment by BiteTheDDDDt** [comment]
very thanks for your report,I fix it on #27297.

**Comment by tangbinyeer** [comment]
请问什么时候能发布啊，2.0.2版本太多问题了，迫切需要发布新版解决。
master编译报错，跑不通···

**Comment by BiteTheDDDDt** [comment]
we will release 2.0.3 on next week.

**Comment by tangbinyeer** [comment]
@BiteTheDDDDt 
物化视图仍然存在问题。

在2.0.3 使用聚合模型，然后建立物化视图后，查询走物化视图得结果和不走物化视图得结果不一致。
走物化视图：
![image](https://github.com/apache/doris/assets/30048177/0bbbfb4e-8378-42b1-8e00-1392ed97c3b5)
不走物化视图：
![image](https://github.com/apache/doris/assets/30048177/29ae698a-b28e-494c-a1c0-d7b166cc24b6)

**Comment by BiteTheDDDDt** [comment]
> @BiteTheDDDDt 物化视图仍然存在问题。
> 
> 在2.0.3 使用聚合模型，然后建立物化视图后，查询走物化视图得结果和不走物化视图得结果不一致。 走物化视图： ![image](https://private-user-images.githubusercontent.com/30048177/290467323-0bbbfb4e-8378-42b1-8e00-1392ed97c3b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NDU2NDQsIm5iZiI6MTcwMjU0NTM0NCwicGF0aCI6Ii8zMDA0ODE3Ny8yOTA0NjczMjMtMGJiYmZiNGUtODM3OC00MmIxLThlMDAtMTM5MmVkOTdjM2I1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDA5MTU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwM2ViMzUyMzUwZmRlZWFkOGFlMzM1M2VlZjZiNDI4ZjVhYzYwZWExN2NlNzE0NWZkZTc0Mzk0ZWU2MTkxYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iovk-f3e8OanNzeGcoCBREUyFU2hb7MY8CL8npmWu0A) 不走物化视图： ![image](https://private-user-images.githubusercontent.com/30048177/290467884-29ae698a-b28e-494c-a1c0-d7b166cc24b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NDU2NDQsIm5iZiI6MTcwMjU0NTM0NCwicGF0aCI6Ii8zMDA0ODE3Ny8yOTA0Njc4ODQtMjlhZTY5OGEtYjI4ZS00OTRjLWExYzAtZDdiMTY2Y2MyNGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDA5MTU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhODY5OTViMTkwZTdiZTUzZDRkNTI2MGNkOTRiYTE3MjFiMGQ0NDIyNmJhOTY5YmJiNGMzODQ4ZDg0ZGFkNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SO3rUu0-jm0y3SRsVTEDcJNHZpOCe0jDFb1joo9Z3sM)


Can you provide a reproduction method?

**Comment by tangbinyeer** [comment]
上面的数据我没有记录复现的数据，但我使用了新的数据复现出了类似的问题。
[复现步骤.zip](https://github.com/apache/doris/files/13671452/default.zip)

**Comment by tangbinyeer** [comment]
抱歉，这个可能是个乌龙，我们得BE节点没有正确升级。

**Comment by tangbinyeer** [comment]
测试2.0.3上正常，可以关闭。
给你带来麻烦十分抱歉。
