### ISSUE TITLE
[Enhancement] Reduct the unnecessary ALWAYS_NULLABLE in nullable mode

### ISSUE THREAD

**Issue by zclllyybb** [apache/doris#27435]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

for many doris' functions, they have nullable mode `ALWAYS_NULLABLE` but in fact no need to be. many of them could be changed to `DEPEND_ON_ARGUMENT` or `CUSTOM` just like https://github.com/apache/doris/pull/27343, https://github.com/apache/doris/pull/22321 and https://github.com/apache/doris/pull/26827. 

### Solution

It may relate to 3 position: BE's function's implementation, function prototype of Nereids planner and function prototype of Legacy planner.
If could reduct it, reduct it.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by koarz** [comment]
l want try

**Comment by zclllyybb** [comment]
> l want try

sure! u can add my wechat torch-wood_ for more information
