### ISSUE TITLE
[Bug] SQL: INSERT INTO table1 WITH test1 as () SELECT * FROM test Error

### ISSUE THREAD

**Issue by MRYOG** [apache/doris#27520]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.2-rc2

### What's Wrong?

![d1](https://github.com/apache/doris/assets/10381662/5f80fc26-6ea1-4094-950a-64042d980a7a)
![d2](https://github.com/apache/doris/assets/10381662/ce77708a-4c1a-4c7a-a4e7-18b520014c64)
<img width="978" alt="image" src="https://github.com/apache/doris/assets/10381662/5a70a76d-e23c-44dd-b5c9-3f059ac2d146">

CREATE TABLE `test_day_dev` (
  `day_id` int(11) NULL COMMENT 'day_id',
  `dev_cnt` int(11) NULL COMMENT 'dev_cnt'
) ENGINE = OLAP DUPLICATE KEY(`day_id`) 
COMMENT 'test每日设备数' 
DISTRIBUTED BY HASH(`day_id`) 
BUCKETS 1 PROPERTIES (
  "replication_allocation" = "tag.location.default: 3",
  "is_being_synced" = "false",
  "storage_format" = "V2",
  "disable_auto_compaction" = "false",
  "enable_single_replica_compaction" = "false"
);

### What You Expected?

Fix

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by bingquanzhao** [comment]
Execute set enable_nereids_dml=true; and then run sql
