### ISSUE TITLE
[Bug] FE 频繁打满64G内存导致宕机，集群上只有Broker Load在定时执行，过一段时间内存就满了

### ISSUE THREAD

**Issue by DA1OOO** [apache/doris#27594]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

版本 2.0.1.1 release

### What's Wrong?
下图是内存使用情况，内存无法回收，每次需要重启，过一段时间又满了：
![image](https://github.com/apache/doris/assets/56857867/9c895a3b-d0a9-49e3-9402-9657e6dcf1b5)
版本 2.0.1.1 release
JVM -xmx64g
宕机前gc日志：
![image](https://github.com/apache/doris/assets/56857867/48bb9830-14a7-4e82-999d-d8b58052a208)
宕机前fe.log:
![image](https://github.com/apache/doris/assets/56857867/dfa2bee2-0741-415b-8030-44d1547c5546)
来自该机器的sql只有broker load，show load，show partitions，drop partition，add partition这几类。

### What You Expected?

什么原因导致FE 宕机，应该不是64g内存也不够吧

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zengxiangqi1031** [comment]
遇到同样的问题，doris 2.0.2 release

**Comment by liugddx** [comment]
Using G1GC

**Comment by DA1OOO** [comment]
> Using G1GC

thanks, i will try

**Comment by DA1OOO** [comment]
btw, i used broker 2.0.2, not 2.0.1.1.

**Comment by DA1OOO** [comment]
![image](https://github.com/apache/doris/assets/56857867/ccc6661c-eb4e-4632-a9ab-5373f258440c)

**Comment by liugddx** [comment]
https://doris.apache.org/zh-CN/docs/1.2/admin-manual/query-profile?_highlight=profile#%E5%90%8D%E8%AF%8D%E8%A7%A3%E9%87%8A

Maybe you need to turn off the global profile `SET [GLOBAL] enable_profile=false;`

**Comment by DA1OOO** [comment]
是不是因为我开启了SET [GLOBAL] enable_profile=true; 且没有配置max_query_profile_num，profile存储在内存？ @liugddx

**Comment by DA1OOO** [comment]
After reviewing the source code, the default max_query_profile_num seems to be 100, so it would't keep pushing profile into memory?

**Comment by liugddx** [comment]
> After reviewing the source code, the default max_query_profile_num seems to be 100, so it would't keep pushing profile into memory?

I don’t have a detailed understanding yet. You can continue to follow or provide more detailed log information.

**Comment by DA1OOO** [comment]
After restart fe and `SET [GLOBAL] enable_profile=false`:
![image](https://github.com/apache/doris/assets/56857867/4c928f53-b9a6-4206-a002-8a895ebb6307)
![image](https://github.com/apache/doris/assets/56857867/9711dc7f-a232-46dc-bdc5-ad4b648c7ee6)
I have a broker load task running from 11:34 to 11:36, which is when the memory is rapidly increasing.

**Comment by liugddx** [comment]
Has this memory problem affected usage? In addition, will the memory be lost by gc?

**Comment by DA1OOO** [comment]
I need to observer the change of memory after closeing the `enable_profile`. But before closing it, memory just lost a little by gc, after the memory reaches the maximum value set by `-xmx`, FE will stop serving.
![image](https://github.com/apache/doris/assets/56857867/b76f6777-40cc-4166-83df-930bc08a6d55)

**Comment by wj215318** [comment]
> I need to observer the change of memory after closeing the `enable_profile`. But before closing it, memory just lost a little by gc, after the memory reaches the maximum value set by `-xmx`, FE will stop serving. ![image](https://private-user-images.githubusercontent.com/56857867/286496533-b76f6777-40cc-4166-83df-930bc08a6d55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMzI1MjAsIm5iZiI6MTcwMTMzMjIyMCwicGF0aCI6Ii81Njg1Nzg2Ny8yODY0OTY1MzMtYjc2ZjY3NzctNDBjYy00MTY2LTgzZGYtOTMwYmMwOGE2ZDU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA4MTcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjMzA4MTE4MTk3OTc0OTVkYWQ4N2ZlZmI2N2NjY2QwMjYyMmRiZTkyZTZkOTA1NDdkNTZkODMxYWU0MWVlY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CFZSVPCT6czVa1IrEeEWZ5XhQSbey8xegyXEVuXFPAk)

how about fe memory after closeing the enable_profile,thanks

**Comment by DA1OOO** [comment]
![image](https://github.com/apache/doris/assets/56857867/678886b4-b103-48cb-baf5-6a85730977bb)
It seems become normal now. Maybe remove profile have some bug.

**Comment by DA1OOO** [comment]
Due to the impact of dumping on the normal use of the cluster, we did not dump the JVM data. If you discover anything after dumping, please share the specific situation here. @wj215318 Thanks!

**Comment by DA1OOO** [comment]
@wj215318 btw, 2.0.2 release don't have this problem.

**Comment by ziyanTOP** [comment]
一样的问题，minor gc的频率跟不上老年代增长的速度，最后三个fe节点全部查询排队超时卡死宕机，建议用prometheus+grafana监控fe的JVM，看看到底问题出在哪，顺便改下你的参数，年轻代等于老年代的1/3，并且不要用-XX:NewRatio=3这种，而是固定设置成-Xmn16G，打开CMS的并行重标记，不然minor gc那点时间这么多内存根本标记不完，然后调低CMS初始化时的内存占比，80%太靠后了，可能gc没完成服务就down了，可以改成60或者65，实测有效，我的集群调整完至今没有fe宕机

**Comment by zhbdesign** [comment]
> 一样的问题，minor gc的频率跟不上老年代增长的速度，最后三个fe节点全部查询排队超时卡死宕机，建议用prometheus+grafana监控fe的JVM，看看到底问题出在哪，顺便改下你的参数，年轻代等于老年代的1/3，并且不要用-XX:NewRatio=3这种，而是固定设置成-Xmn16G，打开CMS的并行重标记，不然minor gc那点时间这么多内存根本标记不完，然后调低CMS初始化时的内存占比，80%太靠后了，可能gc没完成服务就down了，可以改成60或者65，实测有效，我的集群调整完至今没有fe宕机

修改后的启动参数可以分享下

**Comment by ziyanTOP** [comment]
JAVA_OPTS="-server -Xmx64g -Xmn16g -Xms32g -XX:+UseMembar -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=15 -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSClassUnloadingEnabled -XX:+CMSParallelRemarkEnabled -XX:CMSInitiatingOccupancyFraction=65 -XX:SoftRefLRUPolicyMSPerMB=0 -Xloggc:$DORIS_HOME/log/fe.gc.log.$DATE" @zhbdesign 具体内存大小根据机器的实际值来设置

**Comment by DA1OOO** [comment]
用了G1回收器 调大JVM内存后。目前正常。
![image](https://github.com/apache/doris/assets/56857867/9b4ca783-8218-4818-8a05-95edfd0b2f13)
还是不理解为什么内存增速这么快。

**Comment by ihadoop** [comment]
dump下来的文件可以上传上来
