### ISSUE TITLE
[Bug] [jdbc-catalog]When writing to an external table, it is not written in the field order of insert, but in the field order of the table

### ISSUE THREAD

**Issue by sky-cc** [apache/doris#27695]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.2

### What's Wrong?

When writing to an external table, it is not written in the field order of insert, but in the field order of the table

### What You Expected?

fix it

### How to Reproduce?

create table in doris1(version:2.0.2)
CREATE TABLE `test` (
  `gameid` varchar(50) NOT NULL DEFAULT "",
  `aid` int(11) NOT NULL DEFAULT "0",
  `bid` int(11) NOT NULL DEFAULT "0",
  `cid` int(11) NOT NULL DEFAULT "0",
  `did` int(11) NOT NULL DEFAULT "0",
  `pname` varchar(255) NOT NULL DEFAULT "其他"
) ENGINE=OLAP
UNIQUE KEY(`gameid`, `aid`, `bid`, `cid`)
COMMENT 'OLAP'
DISTRIBUTED BY HASH(`gameid`) BUCKETS 3
PROPERTIES (
"replication_allocation" = "tag.location.default: 3",
"is_being_synced" = "false",
"storage_format" = "V2",
"enable_unique_key_merge_on_write" = "true",
"light_schema_change" = "true",
"disable_auto_compaction" = "false",
"enable_single_replica_compaction" = "false"
);

executing the sql in doris2(version:2.0.2)
insert into doris1.test.test(gameid,did,cid,bid,aid,pname) values('g1',4,3,2,1,'p1');
![image](https://github.com/apache/doris/assets/64391288/7bba616f-38d2-45d8-a4a5-fd65cf29d1fc)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
Try it with the latest version
