### ISSUE TITLE
[Feature] Adding error code for unknown table

### ISSUE THREAD

**Issue by actcwlf** [apache/doris#27751]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

In mysql, code 1146, 1049, 1051 represent  `Table '%s.%s' doesn't exist`, `Unknown database '%s'` and `Message: Unknown table '%s'` respectively. But I cannot find relevent error code in [error table](https://github.com/apache/doris/blob/master/docs/en/docs/admin-manual/maint-monitor/doris-error-code.md). Perhaps adding these error code will improve the user experience.

### Use case

Run
```sql
DESCRIBE test_table -- non-existent table
```
current
```
ERROR 1105 (HY000): errCode = 2, detailMessage = Unknown table 'test_table'
```
expectation
```
ERROR <specialized error code> (HY000): errCode = 2, detailMessage = Unknown table 'test_table'
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Vallishp** [comment]
i will look into it. pls assign to me
