### ISSUE TITLE
[Bug] postgresql  catalog  insert into 指定列名顺序失败

### ISSUE THREAD

**Issue by wz11wz** [apache/doris#28120]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.2

### What's Wrong?

INSERT INTO
  albite.test.t_shijianfenzhong WITH LABEL `8ec07d59-b797-409f-9725-bef84f2fefef`(yewushijian,biaozhunzhi, shujuchulishijian)
select
  YEWUSHJ,
  BIAOZHUNZH,
  NOW(3)
FROM
  test3.S_RILIFZH
where
  S_RILIFZH.BIAOZHUNZH = 1
  and test3.S_RILIFZH.YEWUSHJ >= '2023-12-04 00:00:00'
   limit 10000

![image](https://github.com/apache/doris/assets/153170301/2f631095-9d79-4daa-b6d0-0822a12f1e2a)

insert into 指定 列名顺序  和  select 列名顺序是一致的。但是 报错信息插入的顺序并不是指定的顺序。

### What You Expected?

支持指定顺序插入

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Yulei-Yang** [comment]
fixed in master: https://github.com/apache/doris/pull/27855

**Comment by wz11wz** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
