### ISSUE TITLE
[Enhancement] fix potential bugs relating to discarded 

### ISSUE THREAD

**Issue by zclllyybb** [apache/doris#28160]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

In https://github.com/apache/doris/pull/23395/files we changed `Status` to `[[nodiscard]]`. But it still some issues that not deal properly.

### Solution

If the function have return type of `Status`, change `static_cast<void>` to `RETURN_IF_ERROR` of changes in pr https://github.com/apache/doris/pull/23395

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zclllyybb** [comment]
> its my pleasure to get clgg's issue!

feel free to ask if meet any trouble. 

And this task will not be assigned cuz there could be many people fix it together.

**Comment by RookieRascal** [comment]
how do I contribute can somebody assist

**Comment by zclllyybb** [comment]
> how do I contribute can somebody assist

actually this issue has finished.

**Comment by RookieRascal** [comment]
> > how do I contribute can somebody assist
> 
> actually this issue has finished. 

Thank you for letting me know
