### ISSUE TITLE
[Bug] jsonb_extract_string  get json arrary content is error

### ISSUE THREAD

**Issue by wz11wz** [apache/doris#28273]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.2

### What's Wrong?

SELECT jsonb_extract_string('[{"type":"compare","operator":">","data":"100"}]', "$.[0].operator");

![image](https://github.com/apache/doris/assets/153170301/08200026-7c3d-4c43-af29-4c83d64121cb)

### What You Expected?

do

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LemonLiTree** [comment]
```sql
 SELECT jsonb_extract_string('[{"type":"compare","operator":">","data":"100"}]', "$[0].operator");
 ```
