### ISSUE TITLE
[Bug] 读aws glue数据不支持国内版

### ISSUE THREAD

**Issue by liuyong19892** [apache/doris#28335]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master版本
最新版应该也会有这个问题

### What's Wrong?

<img width="740" alt="image" src="https://github.com/apache/doris/assets/3862966/366faa06-796c-487b-ad8b-5bfbd93638cb">
能看到glue的database及tables但是查询报错：
<img width="1279" alt="image" src="https://github.com/apache/doris/assets/3862966/c15cf6f6-10a6-4b65-b079-c75443210f13">

可能是 xxx.s3.cn-north-1.amazonaws.com  改为------->  xxx.s3.cn-north-1.amazonaws.com.cn 
我这是国内的aws 

### What You Expected?

如果是我提到的原因希望能修复  如果不是希望能帮忙定位下问题原因

### How to Reproduce?

CREATE CATALOG hive_catalog_glue PROPERTIES (
    "type"="hms",
    "hive.metastore.type" = "glue",
    "glue.endpoint" = "https://glue.cn-north-1.amazonaws.com.cn",
    "glue.access_key" = "xxx",
    "glue.secret_key" = "xxx"
);

switch hive_catalog_glue;
use xxx;
select * from xxx limit 1;

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by morningman** [comment]
I will try to fix this next week

**Comment by wsjz** [comment]
![image](https://github.com/apache/doris/assets/18522955/b87f7cbe-8eee-49c3-bdf7-9c615f9c811a)
看起来glue访问没问题，问题在于查询语句扫描的这个s3地址格式还不支持，它不是我们平时用的s3存储路径，这个s3路径是开启了什么其他服务呢

**Comment by liuyong19892** [comment]
是的  s3地址加个.cn后缀就行了  2.1版本能fix上去吗
