### ISSUE TITLE
[Bug] (ip functions) a bug occurred while executing ipv4stringtonumordefault function

### ISSUE THREAD

**Issue by sjyango** [apache/doris#28387]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

<img width="1846" alt="image" src="https://github.com/apache/doris/assets/114391101/a61454fb-da6a-4fc1-98ae-9eb0e706e05e">

### What You Expected?

When handling NULL values, ipv4stringtonumordefault should return 0 instead of an error message

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by superdiaodiao** [comment]
This behavior meets our expectation.
The column for ipv4stringtonum or ipv4stringtonumordefault is set to be **always not nullable**.
If you want to not check for this, you can use **ipv4stringtonumornull** or use the **nvl** function to deal with your column first.

**Comment by sjyango** [comment]
> This behavior meets our expectation. The column for ipv4stringtonum or ipv4stringtonumordefault is set to be **always not nullable**, so that we can have a precheck for the Null situation.
> 
> If you want to not check for this, you can use **ipv4stringtonumornull** or use the **nvl** function to deal with your column first.

But function ipv4stringtonumordefault 's behavior is different from what is defined in ClickHouse
<img width="1340" alt="image" src="https://github.com/apache/doris/assets/114391101/3206c0b6-943b-4d7d-bf82-880dc8ab631b">

**Comment by superdiaodiao** [comment]
> > This behavior meets our expectation. The column for ipv4stringtonum or ipv4stringtonumordefault is set to be **always not nullable**, so that we can have a precheck for the Null situation.
> > If you want to not check for this, you can use **ipv4stringtonumornull** or use the **nvl** function to deal with your column first.
> 
> But function ipv4stringtonumordefault 's behavior is different from what is defined in ClickHouse <img alt="image" width="1340" src="https://private-user-images.githubusercontent.com/114391101/290455574-3206c0b6-943b-4d7d-bf82-880dc8ab631b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NDM4MDIsIm5iZiI6MTcwMjU0MzUwMiwicGF0aCI6Ii8xMTQzOTExMDEvMjkwNDU1NTc0LTMyMDZjMGI2LTk0M2ItNGQ3ZC1iZjgyLTg4MGRjOGFiNjMxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNFQwODQ1MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDhmNTBmOWUzNzI3NzYwMWIwZGNkZTYwNGU5N2JiYWQwMzc0NDAyNGM4ODU0NDAzMzIwMzc1OWZiMjUwYWNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yaUM5LO4XPNjtiKBql83lQbV4j2SzSQzzuDPKT0H_k8">

In Clickhouse, are these ipv4 stringtonum functions: ipv4stringtonum(ordefault, ornull) all set to nullable?

**Comment by superdiaodiao** [comment]
> > This behavior meets our expectation. The column for ipv4stringtonum or ipv4stringtonumordefault is set to be **always not nullable**, so that we can have a precheck for the Null situation.
> > If you want to not check for this, you can use **ipv4stringtonumornull** or use the **nvl** function to deal with your column first.
> 
> But function ipv4stringtonumordefault 's behavior is different from what is defined in ClickHouse 

In Clickhouse, are these ipv4 stringtonum functions: ipv4stringtonum(ordefault, ornull) all set to nullable?

**Comment by sjyango** [comment]
> > > This behavior meets our expectation. The column for ipv4stringtonum or ipv4stringtonumordefault is set to be **always not nullable**, so that we can have a precheck for the Null situation.
> > > If you want to not check for this, you can use **ipv4stringtonumornull** or use the **nvl** function to deal with your column first.
> > 
> > 
> > But function ipv4stringtonumordefault 's behavior is different from what is defined in ClickHouse
> 
> In Clickhouse, are these ipv4 stringtonum functions: ipv4stringtonum(ordefault, ornull) all set to nullable column input?

I think so. 
In my opinion, ipv4stringtonum (ordefault, ornull) needs to support handling nullable columns, and then take different actions based on different values in the function logic. For example, when encountering NULL or invalid format ip strings, ipv4stringtonum will throw an exception, ipv4stringtonumordefault will return 0, and ipv4stringtonumornull will return NULL.

I analyzed your code and found that you defined Ipv4StringToNumOrDefault as AlwaysNotNullable in fe, but in be's get_return_type_impl function, ambiguity occurred in the implementation of the function. If IPStringToNumExceptionMode is set to Default, the return type may be nullable, making it impossible to call Ipv4StringToNumOrDefault to handle columns with null values
<img width="1167" alt="image" src="https://github.com/apache/doris/assets/114391101/f37e4b2e-c953-4398-b558-1b1b013eee31">

**Comment by superdiaodiao** [comment]
> > > > This behavior meets our expectation. The column for ipv4stringtonum or ipv4stringtonumordefault is set to be **always not nullable**, so that we can have a precheck for the Null situation.
> > > > If you want to not check for this, you can use **ipv4stringtonumornull** or use the **nvl** function to deal with your column first.
> > > 
> > > 
> > > But function ipv4stringtonumordefault 's behavior is different from what is defined in ClickHouse
> > 
> > 
> > In Clickhouse, are these ipv4 stringtonum functions: ipv4stringtonum(ordefault, ornull) all set to nullable column input?
> 
> I think so. In my opinion, ipv4stringtonum (ordefault, ornull) needs to support handling nullable columns, and then take different actions based on different values in the function logic. For example, when encountering NULL or invalid format ip strings, ipv4stringtonum will throw an exception, ipv4stringtonumordefault will return 0, and ipv4stringtonumornull will return NULL.
> 
> I analyzed your code and found that you defined Ipv4StringToNumOrDefault as AlwaysNotNullable in fe, but in be's get_return_type_impl function, ambiguity occurred in the implementation of the function. If IPStringToNumExceptionMode is set to Default, the return type may be nullable, making it impossible to call Ipv4StringToNumOrDefault to handle columns with null values 

These situations were considered in the process of development. In my opinion, if ipv4stringtonumordefault and ipv4stringtonumornull both take nullable column input, it seems that there is almost no difference between them. So we choose to make some gaps between them.

But, I will discuss these with Doris Team ASAP and decide wether we can change.

**Comment by sjyango** [comment]
May I ask if you are in the "Doris Future" developer communication wx group? and can you share your WeChat to maintain communication?
