### ISSUE TITLE
[Feature] catalog 以后可以支持tdengine吗？

### ISSUE THREAD

**Issue by tcsll** [apache/doris#28439]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
use jdbc catalog

**Comment by tcsll** [comment]
> use jdbc catalog

执行create catalog 
如果写 jdbc:TAOS-RS://ip.. 会报不支持的jdbc类型；
如果写 jbbc: ${其他}://..  比如mysql/clickhouse ，虽然catalog可以创建成功，但是swtich catalog&show databases就无法执行了。
我的url与class是:
    "driver_url" = "taos-jdbcdriver-2.0.39-dist.jar",
    "driver_class" = "com.taosdata.jdbc.rs.RestfulDriver"
或者
    "driver_url" = "mysql-connector-java-8.0.25.jar",
    "driver_class" = "com.mysql.cj.jdbc.Driver"

依赖包同时放到了lib与jdbc_drivers文件夹下

所以我是哪个步骤有问题?
谢谢。

**Comment by liugddx** [comment]
There are some problems, but it's just a simple adaptation.

**Comment by tcsll** [comment]
> but it's just a simple adaptation.
Will it be perfect in the future?
thanks

**Comment by tcsll** [comment]
> There are some problems, but it's just a simple adaptation.



Will it be perfect in the future?
thanks

**Comment by morningman** [comment]
Will not support in near future.
We are trying to make catalog pluggable, after that, it will be more easy to connect to other catalog

**Comment by tcsll** [comment]
ok ，thank you very much！

**Comment by tcsll** [comment]
> Will not support in near future. We are trying to make catalog pluggable, after that, it will be more easy to connect to other catalog


ok, thank you very much !
