### ISSUE TITLE
[Feature] Support `kill query_id`

### ISSUE THREAD

**Issue by morningman** [apache/doris#28517]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Support new stmt `kill query_id`;
it can cancel the query by `query_id`.

Currently, Doris only support cancel query by `connection_id`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by nanfeng1999** [comment]
i will try it
