### ISSUE TITLE
[Bug]  Create View Error

### ISSUE THREAD

**Issue by cjj2010** [apache/doris#28548]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-2.0.0-rc04

### What's Wrong?

Error reported when creating view e.g
![image](https://github.com/apache/doris/assets/45192870/f71924ec-25ef-4083-9924-33144040e801)

### What You Expected?

Creating views normally

### How to Reproduce?

e.g Normal Query
` create view asd as
 
 
 select
	custId ,
	shipperId ,
	shipAddress, IFNULL(map1["custId ,shipperId ,shipAddress"], 0) as "Boulevard"
from
	(
	select
		custId ,
		shipperId ,
		shipAddress,
		map_agg(shipAddress,
		totalfreight) as map1
	from
		(
		select
			x.custId ,
			x.shipperId ,
			x.shipAddress ,
			sum(x.freight) as totalfreight
		from
			qixi_ods.salesorder x
		group by
			x.custId ,
			x.shipperId ,
			x.shipAddress,
			x.freight
) a
	group by
		custId ,
		shipperId ,
		shipAddress,
		totalfreight
 ) t
 `
![image](https://github.com/apache/doris/assets/45192870/60ca4610-1c41-4985-8130-5b4b93a8ade5)

create view 

`create view asd as
 select
	custId ,
	shipperId ,
	shipAddress, IFNULL(map1["custId ,shipperId ,shipAddress"], 0) as "Boulevard"
from
	(
	select
		custId ,
		shipperId ,
		shipAddress,
		map_agg(shipAddress,
		totalfreight) as map1
	from
		(
		select
			x.custId ,
			x.shipperId ,
			x.shipAddress ,
			sum(x.freight) as totalfreight
		from
			qixi_ods.salesorder x
		group by
			x.custId ,
			x.shipperId ,
			x.shipAddress,
			x.freight
) a
	group by
		custId ,
		shipperId ,
		shipAddress,
		totalfreight
 ) t
 `

![image](https://github.com/apache/doris/assets/45192870/a87c29b0-ce6a-4a32-aea9-41b96d4a9fdd)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
use 2.0.3 and try again.

**Comment by cjj2010** [comment]
> use 2.0.3 and try again.

The experiment passed, thank you very much
