### ISSUE TITLE
[Bug] 对启用merge-on-write表进行高并发插入的场合，频发发生E-3115异常。

### ISSUE THREAD

**Issue by polarbearmx** [apache/doris#28634]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.3

### What's Wrong?

对merge-on-write表进行频发插入的情况下，频发发生【E-3115】发布版本不连续的异常。
fe的DatabaseTransactionMgr.commitTransaction方法中，通过writeLock保护TransactionState对获取table的Partition的nextVersion。
但是，后面的updateCatalogAfterCommited方法对Partition的nextVersion自增的操作并没有在writeLock保护范围内。
第一个线程没有修改Partition.nextVersion就释放了锁，所以，第二个线程进入加锁区域获取Partition的nextVersion时，第一个线程可能没有完成Partition.nextVersion的自增；两个线程发往BE的publish_req中包含相同的Partition.extVersion。
DatabaseTransactionMgr.commitTransaction==================================================
        transactionState.beforeStateTransform(TransactionStatus.COMMITTED);
        // transaction state transform
        boolean txnOperated = false;
        writeLock();
        try {
            if (is2PC) {
                unprotectedCommitTransaction2PC(transactionState, db);
            } else {
                unprotectedCommitTransaction(transactionState, errorReplicaIds,
                        tableToPartition, totalInvolvedBackends, db);
            }
            txnOperated = true;
        } finally {
            writeUnlock();
            // after state transform
            transactionState.afterStateTransform(TransactionStatus.COMMITTED, txnOperated);
        }

        // update nextVersion because of the failure of persistent transaction resulting in error version
        updateCatalogAfterCommitted(transactionState, db);
be的EnginePublishVersionTask::finish时，线程1的版本被正常发布后，线程2永远不满足对merge-on-write的publish版本连续性判断。
=================================================
                if (tablet_state == TabletState::TABLET_RUNNING &&
                    version.first != max_version.second + 1) {
                    VLOG_NOTICE << "uniq key with merge-on-write version not continuous, current "
                                   "max "
                                   "version="
                                << max_version.second << ", publish_version=" << version.first
                                << " tablet_id=" << tablet->tablet_id();
                    // If a tablet migrates out and back, the previously failed
                    // publish task may retry on the new tablet, so check
                    // whether the version exists. if not exist, then set
                    // publish failed
                    if (!tablet->check_version_exist(version)) {
                        add_error_tablet_id(tablet_info.tablet_id);
                        res = Status::Error<PUBLISH_VERSION_NOT_CONTINUOUS>();
                    }
                    continue;
                }

日志===================================================================================
W1021 12:53:16.891216 391149 task_worker_pool.cpp:723] failed to publish version|signature=247156074|transaction_id=247156074|error_tablets_num=4|error=[E-3115]
I1021 12:53:16.891402 391144 task_worker_pool.cpp:693] task elapsed 11 seconds since it is inserted to queue, it is timeout
W1021 12:53:16.891413 391144 task_worker_pool.cpp:723] failed to publish version|signature=247156709|transaction_id=247156709|error_tablets_num=18|error=[E-3115]
I1021 12:53:16.892107 391147 task_worker_pool.cpp:693] task elapsed 11 seconds since it is inserted to queue, it is timeout
W1021 12:53:16.892119 391147 task_worker_pool.cpp:723] failed to publish version|signature=247155948|transaction_id=247155948|error_tablets_num=16|error=[E-3115]
I1021 12:53:16.892413 391149 task_worker_pool.cpp:693] task elapsed 11 seconds since it is inserted to queue, it is timeout
W1021 12:53:16.892421 391149 task_worker_pool.cpp:723] failed to publish version|signature=247181244|transaction_id=247181244|error_tablets_num=12|error=[E-3115]
I1021 12:53:16.892585 391143 task_worker_pool.cpp:693] task elapsed 11 seconds since it is inserted to queue, it is timeout
W1021 12:53:16.892601 391143 task_worker_pool.cpp:723] failed to publish version|signature=247156698|transaction_id=247156698|error_tablets_num=18|error=[E-3115]
I1021 12:53:16.892611 391144 task_worker_pool.cpp:693] task elapsed 11 seconds since it is inserted to queue, it is timeout
W1021 12:53:16.892628 391144 task_worker_pool.cpp:723] failed to publish version|signature=247156081|transaction_id=247156081|error_tablets_num=15|error=[E-3115]
I1021 12:53:16.892690 391149 task_worker_pool.cpp:693] task elapsed 11 seconds since it is inserted to queue, it is timeout
W1021 12:53:16.892696 391149 task_worker_pool.cpp:723] failed to publish version|signature=247157824|transaction_id=247157824|error_tablets_num=5|error=[E-3115]
I1021 12:53:16.893534 391148 task_worker_pool.cpp:693] task elapsed 11 seconds since it is inserted to queue, it is timeout
W1021 12:53:16.893545 391148 task_worker_pool.cpp:723] failed to publish version|signature=247156485|transaction_id=247156485|error_tablets_num=17|error=[E-3115]
I1021 12:53:16.893625 391146 task_worker_pool.cpp:693] task elapsed 11 seconds since it is inserted to queue, it is timeout
W1021 12:53:16.893637 391146 task_worker_pool.cpp:723] failed to publish version|signature=247151643|transaction_id=247151643|error_tablets_num=1|error=[E-3115]
I1021 12:53:16.893808 391148 task_worker_pool.cpp:693] task elapsed 11 seconds since it is inserted to queue, it is timeout
W1021 12:53:16.893829 391148 task_worker_pool.cpp:723] failed to publish version|signature=247154078|transaction_id=247154078|error_tablets_num=4|error=[E-3115]
I1021 12:53:16.894899 391143 task_worker_pool.cpp:693] task elapsed 11 seconds since it is inserted to queue, it is timeout
W1021 12:53:16.894918 391143 task_worker_pool.cpp:723] failed to publish version|signature=247154058|transaction_id=247154058|error_tablets_num=4|error=[E-3115]
I1021 12:53:16.895215 391147 task_worker_pool.cpp:693] task elapsed 11 seconds since it is inserted to queue, it is timeout
W1021 12:53:16.895226 391147 task_worker_pool.cpp:723] failed to publish version|signature=247156488|transaction_id=247156488|error_tablets_num=17|error=[E-3115]
I1021 12:53:16.895434 391145 task_worker_pool.cpp:693] task elapsed 11 seconds since it is inserted to queue, it is timeout
W1021 12:53:16.895453 391145 task_worker_pool.cpp:723] failed to publish version|signature=247155969|transaction_id=247155969|error_tablets_num=6|error=[E-3115]
I1021 12:53:16.895695 391145 task_worker_pool.cpp:693] task elapsed 11 seconds since it is inserted to queue, it is timeout
W1021 12:53:16.895710 391145 task_worker_pool.cpp:723] failed to publish version|signature=247155916|transaction_id=247155916|error_tablets_num=1|error=[E-3115]

### What You Expected?

如下对全局Env的table的Partition的nextVersion的自增操作应该和【unprotectedCommitTransaction2PC】在同一个writeLock的保护范围内吧，对全局Partition的nextVersion进行修改，没有锁保护，在高并发情况下，一方面，无法保证TransactionState获取正确的自增结果；另外一方面，也会有写覆盖的问题吧？
        // update nextVersion because of the failure of persistent transaction resulting in error version
        updateCatalogAfterCommitted(transactionState, db);

### How to Reproduce?

对启用merge-on-write表进行高并发插入的场合，be的日志中就会大量连续出现E-3115的异常提示。

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LemonLiTree** [comment]
方便升级到2.0.3 试试不

**Comment by polarbearmx** [comment]
已经是生产环境了，升级风险太高了，不太敢跨大版本升级。

**Comment by polarbearmx** [comment]
明白了，谢谢。
