### ISSUE TITLE
[Bug] 查询hudi mor表报错

### ISSUE THREAD

**Issue by lucienoz** [apache/doris#28652]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.3

### What's Wrong?

I1219 17:41:26.307972 1226839 internal_service.cpp:521] cancel fragment, fragment_instance_id=e229ab07404240b9-9ed80d41e7cb0232, reason: INTERNAL_ERROR
I1219 17:41:26.307994 1226839 runtime_state.h:172] task is cancelled, st = [CANCELLED]
W1219 17:41:26.308001 1226839 pipeline_fragment_context.cpp:162] PipelineFragmentContext Canceled. reason=
W1219 17:41:26.308058 1225639 fragment_mgr.cpp:482] report error status: [CANCELLED] to coordinator: TNetworkAddress(hostname=172.16.99.21, port=9020), query id: e229ab07404240b9-9ed80d41e7cb0230, instance id: e229ab07404240b9-9ed80d41e7cb0232
W1219 17:41:26.308364 1225640 fragment_mgr.cpp:482] report error status: [CANCELLED][INTERNAL_ERROR]InternalError: null

        0#  doris::JniUtil::GetJniExceptionMsg(JNIEnv_*, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) at /root/src/doris-2.0/be/src/util/jni-util.h:110
        1#  doris::vectorized::JniConnector::get_nex_block(doris::vectorized::Block*, unsigned long*, bool*) at /root/src/doris-2.0/be/src/vec/exec/jni_connector.cpp:0
        2#  doris::vectorized::HudiJniReader::get_next_block(doris::vectorized::Block*, unsigned long*, bool*) at /root/src/doris-2.0/be/src/common/status.h:442
        3#  doris::vectorized::VFileScanner::_get_block_impl(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /root/src/doris-2.0/be/src/common/status.h:442
        4#  doris::vectorized::VScanner::get_block(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /root/src/doris-2.0/be/src/vec/exec/scan/vscanner.cpp:0
        5#  doris::vectorized::ScannerScheduler::_scanner_scan(doris::vectorized::ScannerScheduler*, doris::vectorized::ScannerContext*, std::shared_ptr<doris::vectorized::VScanner>) at /root/src/doris-2.0/be/src/common/status.h:354
        6#  std::_Function_handler<void (), 

查询hudi mor表时报错doris::vectorized::ScannerScheduler::_schedule_scanners(doris::vectorized::ScannerContext*)::$_1::operator()() const::{lambda()#4}>::_M_invoke(std::_Any_data const&) at /var/local/ldb-toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr_base.h:701
        7#  doris::WorkThreadPool<true>::work_thread(int) at /var/local/ldb-toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/atomic_base.h:646
        8#  execute_native_thread_routine at /data/gcc-11.1.0/build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/unique_ptr.h:85
        9#  start_thread
        10# __clone

### What You Expected?

..

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mesat** [comment]
Could you clarify the reason for closing this issue as completed, please? @lucienoz
