### ISSUE TITLE
[Bug] doris json类型的字段目前不支持 某个key值不能为 jsonstring

### ISSUE THREAD

**Issue by foundation1** [apache/doris#28735]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.2

### What's Wrong?

我目前需要把 mysql的数据同步到doris 
原来的json 数据为

[{"854368616680689809":"[{\\"h\\": 12}]"}] 

其中key:854368616680689809 的值是一个 jsonstring  然后无法导入到doris中 插入提示 com.google.gson.stream.MalformedJsonException
![image](https://github.com/apache/doris/assets/28500506/bc392b10-af98-4efc-8c71-c95cdc70c311)

### What You Expected?

是doris 不支持这种格式的json吗 还是需要另外的配置  希望能支持这种数据格式

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LemonLiTree** [comment]
This is not a legal json, it should be `[{"854368616680689809":[{"h": 12}]}]`

**Comment by foundation1** [comment]
这个是一个合法的 只是他的值 是一个 jsonString 用工具可以解析
![image](https://github.com/apache/doris/assets/28500506/83a5e019-11a2-429f-b1ae-7d37cacbf7da)
建议还是得支持一下 因为mysql的json 就支持 不然在进行数据迁移时 就会迁移失败 需要用户自己去处理这种 json 数据 无法直接切换到doris 数据库

**Comment by foundation1** [comment]
> 这不是一个合法的json，它应该是`[{"854368616680689809":[{"h": 12}]}]`

这个是一个 合法的json 用工具可以解析  只是因为他的值是一个 jsonString
https://github.com/apache/doris/issues/28735#issuecomment-1865391158
这个数据是mysql中的  mysql的json类型就可以存储这种数据 如果doris 不支持就会导致 在做数据迁移时需要用户自己去重新处理这种json 并修改业务逻辑

**Comment by foundation1** [comment]
> This is not a legal json, it should be `[{"854368616680689809":[{"h": 12}]}]`

这个json是合法的 用解析工具可以解析
![image](https://github.com/apache/doris/assets/28500506/e3fc5701-ed85-44c5-97cf-235071d737aa)
这个数据是直接从mysql数据库中导出来的  
本来是通过datax 进行数据迁移的因为mysql中存在 json的value值为 jsonString 导致迁移失败  
在原来的mysql 库中也是json类型存储的  如果doris 不支持这种格式的json 那么用户进行数据库迁移时 就需要特殊处理这种数据 还导致用户需要去修改业务逻辑 不然无法进行数据源的切换 是否后续会支持这种格式的json？

**Comment by LemonLiTree** [comment]
<img width="1789" alt="image" src="https://github.com/apache/doris/assets/109049295/3d084e1b-0020-4cff-9cc3-ef01c1cd673f">
emmm

**Comment by LemonLiTree** [comment]
which your mysql version?

**Comment by ihadoop** [comment]
对象 JSON 对象数据类型是{}（花括号）之间插入的一系列名称或值对。 键必须是字符串，并且应当是唯一的，以逗号分隔。
