### ISSUE TITLE
[Bug] 2.0.3 查询异常

### ISSUE THREAD

**Issue by learner1212** [apache/doris#28741]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.3

### What's Wrong?

现有表结构：
表结构 ：
CREATE TABLE test (
a tinyint(4) NULL DEFAULT "0" ,
b int(11) DEFAULT "0" ,
c int(11) DEFAULT "0" ,
t DATETIMEV2 COMMENT "时间",
d bigint(20) SUM NULL DEFAULT "0",
e bigint(20) SUM NULL DEFAULT "0"
)
AGGREGATE KEY(a, b, c, t)
PARTITION BY RANGE(t) ()
DISTRIBUTED BY HASH(a) BUCKETS AUTO
PROPERTIES
(
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "DAY",
"dynamic_partition.start" = "-3",
"dynamic_partition.end" = "3",
"dynamic_partition.prefix" = "p",
"dynamic_partition.time_zone" = "Asia/Shanghai",
"dynamic_partition.create_history_partition" = "true",
"dynamic_partition.history_partition_num" = "3",
"dynamic_partition.replication_num" = "2",
"light_schema_change" = "true"
);

创建物化视图：
CREATE MATERIALIZED VIEW mv_test AS
SELECT a,b,t,SUM(d) FROM test GROUP BY 1,2,3

插入一条记录：

INSERT INTO test(a,b,c,t,d,e) VALUES (1,2,3,'2023-12-19 18:21:00', 56, 78)

然后新增维度和度量

 ALTER TABLE test
  ADD COLUMN `a1` INT KEY AFTER a,
ADD COLUMN `b1` VARCHAR(1024) KEY  AFTER  b,
ADD COLUMN `d1` BIGINT SUM AFTER d;

再插入一条数据：

INSERT INTO test(a,a1,b,b1,c,t,d,d1,e) VALUES (1,1,2,'-',3,'2023-12-20 17:21:00', 56, 78, 89)

再执行查询sql：
select b1 from test where t >= '2023-12-20 17:21:00'

报错：
Execution failed: Error Failed to execute sql: java.sql.SQLException: (conn=187) errCode = 2, detailMessage = Unexpected exception: null

### What You Expected?

解释bug出现的原因，并修复bug

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LemonLiTree** [comment]
I haven't reproduced this problem. Can you confirm that the version is `doris-2.0.3-rc06-37d31a5`?

**Comment by learner1212** [comment]
> I haven't reproduced this problem. Can you confirm that the version is `doris-2.0.3-rc06-37d31a5`?

我的版本也是 2.0.3 , 是从 https://www.selectdb.com/download/enterprise 下载的， 你这个版本是怎么获取的呢
是这个地址吗？ https://github.com/apache/doris/releases/tag/2.0.3-rc06

**Comment by LemonLiTree** [comment]
it's the same

**Comment by learner1212** [comment]
> it's the same

那我再这上面能复现啊

**Comment by learner1212** [comment]
![Catch_recompress](https://github.com/apache/doris/assets/22979092/eca6e415-afb2-4bf8-b252-f480073a7148)

**Comment by gnehil** [comment]
Enable the nereids planner and the query will execute correctly.

**Comment by learner1212** [comment]
> Enable the nereids planner and the query will execute correctly.

这个有效果，多谢
