### ISSUE TITLE
[Enhancement] Catalog配置JDBC权限能否和设置用户权限一致

### ISSUE THREAD

**Issue by MRYOG** [apache/doris#28880]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Catalog通过JDBC 方式连接的MySQL数据库，执行delete操作时，提示errCode = 2, detailMessage = External catalog 'up_mysql' is not allowed in 'DeleteStmt'
但是配置的用户有对表进行增删改查的权限

### Solution

catalog 权限能否与用户本身权限一致，不对删除等操作进行限制，可以通过本身数据库对用户的权限限制。或者doris中也可以对catalog 进行权限限制

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by cjj2010** [comment]
Sir, can you provide a detailed reproduction demo?

**Comment by zy-kkk** [comment]
This is because Doris currently does not support Delete operations on external data sources through JDBC Catalog. Currently, it only supports Select and Insert.

**Comment by cjj2010** [comment]
> This is because Doris currently does not support Delete operations on external data sources through JDBC Catalog. Currently, it only supports Select and Insert.

Is there a plan to support delete? I can help achieve
