### ISSUE TITLE
[Bug] enable pipeline resulting in longer query time In situations where there are too many tablets (0.06s -> 19s)

### ISSUE THREAD

**Issue by DA1OOO** [apache/doris#29041]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris 2.3

### What's Wrong?

**table size**: `8MB, 9k+ rows, partitioned by hour, buckets num = 9`
![image](https://github.com/apache/doris/assets/56857867/f7f7cfc1-ab83-4cdc-b6c9-4114227daf15)
**tablets number**: 15957 / 3 replica
![image](https://github.com/apache/doris/assets/56857867/ee43ed25-78bb-4f5f-b288-ffe2f941ffc1)
**difference when enable pipeline**: `0.06s -> 19s` 
<img width="884" alt="image" src="https://github.com/apache/doris/assets/56857867/8809f7a5-c692-44fd-9fe1-1e7e694b5642">
btw, in query profile, this query time as follow, different to mysql client. https://github.com/apache/doris/discussions/29024
![image](https://github.com/apache/doris/assets/56857867/5743da2f-5ae9-4c03-922d-6a083b1afd54)

Finally, explain the reason **why we have so many tablets**:
we have a table. **size = 25GB, rowCount = 302965685**, due to business continuity, we **partition by hour**.
then, we create a simple materialized view `create materialized view as select geo_country from xxx group by  geo_country`.
after created, found that tablets has doubled. but materialized view size is small. when we select on materialized view, the query is very slow.
![image](https://github.com/apache/doris/assets/56857867/e94a0590-29c8-4cb9-a9d7-604e94e7b5ec)
so we create a test table (as above) that only have 1 column, partitions by hour to test query time.
Then we discovered the problem mentioned at the beginning of the issue.

### What You Expected?

fix, we want enable pipeline to use workload group function.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DA1OOO** [comment]
Perhaps due to the Query Profile, after turning off the profile, the query speed is basically the same when opening and closing the pipeline.

**Comment by yiguolei** [comment]
@DA1OOO  Yes, it is the profile. Currently, profile will too long time to generate. If you set enable_profile=true, then the query time maybe very long. 
In doris 2.2. version, we will construct async profile to solve the problem,
