### ISSUE TITLE
[Bug] CREATE-JOB syntax not supported

### ISSUE THREAD

**Issue by Lif0820** [apache/doris#29117]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.3

### What's Wrong?

in 2.0 document, it supports the CREATE-JOB syntax, but in practice, it prompts a syntax error when used. error like this:

Failed to execute sql...
Encountered : JOB

https://doris.apache.org/zh-CN/docs/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-JOB

### What You Expected?

Is it supported, or is it used correctly, or when can it be supported?

### How to Reproduce?

CREATE JOB my_job ON SCHEDULE AT '2020-01-01 00:00:00' DO INSERT INTO db1.tbl1 SELECT * FROM db2.tbl2;

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LemonLiTree** [comment]
2.0 not support

**Comment by LemonLiTree** [comment]
https://github.com/apache/doris/pull/29136
