### ISSUE TITLE
[Bug] The error type is abnormal when compiling doris2.0.0 according to the image provided on the official website

### ISSUE THREAD

**Issue by yuqun20230302** [apache/doris#29384]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-version:doris-2.0.0-rc04
compiling environment：apache/doris:build-env-for-2.0
support avx2 instruction set
os：Linux master 5.15.0-91-generic #101~20.04.1-Ubuntu SMP Thu Nov 16 14:22:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### What's Wrong?

When I execute the compile command, I get an error, the interface is of type void and the implementation inside is of type int。

### What You Expected?

edit suceess

### How to Reproduce?

1. build environment
````bash
docker run -it --network=host --name yqdoris -v /root/.m2:/root/.m2 -v /root/yq/doris-2.0.0-rc04/:/root/doris-2.0.0-rc04/ apache/doris:build-env-for-2.0
````
2.Execute edit command
````bash
sh build.sh --clean --be --fe
````
![image](https://github.com/apache/doris/assets/126741318/1249e2ca-3091-4149-a517-e806defd1149)
![image](https://github.com/apache/doris/assets/126741318/bd8b4ba5-f11c-4763-9c11-fcdba116adb5)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LemonLiTree** [comment]
https://doris.apache.org/docs/install/source-install/compilation-with-ldb-toolchain/

**Comment by yuqun20230302** [comment]
can't use image compilation？

**Comment by rohitrs1983** [comment]
![image](https://github.com/apache/doris/assets/22505528/e01ba4ca-ae1b-4b38-a3ef-5c29bc9f9d28)

this interface of CLucene third party lib has been modified as part of commit https://github.com/apache/doris-thirdparty/commit/af6f847d17d3cff043a3e11d6511d1e14d4333d9

you need to downgrade your CLucene version

**Comment by yuqun20230302** [comment]
Sorry，Do you mean to say that the version of CLucene used by the doris2.0.0 version is abnormal, and this part of the source code needs to be rebuilt?

**Comment by rohitrs1983** [comment]
the build.sh script will download the latest version of "clucene" which leads to the compilation failure.

build.sh
update_submodule "be/src/clucene" "clucene" "https://github.com/apache/doris-thirdparty/archive/refs/heads/clucene.tar.gz"

**Comment by rohitrs1983** [comment]
> Sorry，Do you mean to say that the version of CLucene used by the doris2.0.0 version is abnormal, and this part of the source code needs to be rebuilt? ![image](https://private-user-images.githubusercontent.com/126741318/293644205-24baaacc-1679-4326-b9ee-9194a449b169.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxODE1OTAsIm5iZiI6MTcwNDE4MTI5MCwicGF0aCI6Ii8xMjY3NDEzMTgvMjkzNjQ0MjA1LTI0YmFhYWNjLTE2NzktNDMyNi1iOWVlLTkxOTRhNDQ5YjE2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQwNzQxMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OTU5MjcwNjU3NWJlMjYxNzQ2YTg4ZTg0OTRkMTYxYjU0ZjNmMDhkODE1MzgxMmQyYWVlMDVkNzg0NzkzODc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Rq4hlL9uDsgw1Xsf6mWkqGDi6TGG-zV-U-fZm2WcC24) Modify 2.3.3.4 as shown in the above figure

the build.sh script will download the latest version of "clucene" which leads to the compilation failure.

build.sh
update_submodule "be/src/clucene" "clucene" "https://github.com/apache/doris-thirdparty/archive/refs/heads/clucene.tar.gz"

**Comment by rohitrs1983** [comment]
> Sorry，Do you mean to say that the version of CLucene used by the doris2.0.0 version is abnormal, and this part of the source code needs to be rebuilt? ![image](https://private-user-images.githubusercontent.com/126741318/293644205-24baaacc-1679-4326-b9ee-9194a449b169.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxODE4OTUsIm5iZiI6MTcwNDE4MTU5NSwicGF0aCI6Ii8xMjY3NDEzMTgvMjkzNjQ0MjA1LTI0YmFhYWNjLTE2NzktNDMyNi1iOWVlLTkxOTRhNDQ5YjE2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQwNzQ2MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MGY0OGM4OWMwZDRhNmE4ZThhNzgzNTQzNGZlMTM1MTgyZTM0YWMxZTE2NDkwYzJmY2VhNTFjOTNjODkxMzlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jgIACJToOnboOVMXFX4hG5GcqfdRDNFdm73bt-5KQWI) Modify 2.3.3.4 as shown in the above figure

the build.sh script will download the latest version of CLucene, which leads to the compilattion failure.

build.sh
update_submodule "be/src/clucene" "clucene" "https://github.com/apache/doris-thirdparty/archive/refs/heads/clucene.tar.gz"

**Comment by LemonLiTree** [comment]
Why build 2.0.0？

**Comment by yuqun20230302** [comment]
The product uses an image built on doris2.0.0
now，orc and clucene branch What is the name of the corresponding tag. clucene has a tag similar to libclucene-,but  the tag of orc that is what

**Comment by LemonLiTree** [comment]
so do you want to build the 2.0.0 image?
