### ISSUE TITLE
[Enhancement] broke load enhanced

### ISSUE THREAD

**Issue by xingyingone** [apache/doris#29406]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

2.0.4
lzo  and snappy is not support by  broke load
![image](https://github.com/apache/doris/assets/16775757/8418410e-4aee-4470-98d2-808bb32fce9c)

### Solution

it is better to support  it

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by HowardQin** [comment]
I'm working on it.
