### ISSUE TITLE
[Bug] all BE crash after execute some query

### ISSUE THREAD

**Issue by DA1OOO** [apache/doris#29419]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris 2.0.3

### What's Wrong?

**after execute query:**
`SELECT
  count(*)
FROM
  dws_asset_domain_statistics_daily t1
INNER JOIN (
    SELECT
      account_id,
      account_name,
      ssp_id
    FROM
      dws_asset_domain_statistics_daily
    WHERE
      d_s = '2023-12-20'
    GROUP BY
      1,
      2,
      3
  ) t2 ON (
      t1.account_id <=> t2.account_id
    AND t1.account_name = t2.account_name
    AND t1.ssp_id = t2.ssp_id
    )
WHERE
  d_s = '2023-12-20'`

**all be crash. our create table :**
`CREATE TABLE dws_asset_domain_statistics_daily (
  account_id int(11) NULL,
  ssp_id int(11) NULL,
  account_name varchar(500) NULL,
  d_s date NOT NULL
) ENGINE = OLAP DUPLICATE KEY(account_id, ssp_id, account_name) 
COMMENT 'OLAP' 
PARTITION BY RANGE(d_s) (PARTITION p20231220 VALUES [('2023-12-20'), ('2023-12-21'))) 
DISTRIBUTED BY HASH(account_name) BUCKETS 9`
**insert data:**
`insert into dws_asset_domain_statistics_daily(ssp_id, d_s) values (45, '2023-12-20')`
(when this table only has one record, just one be crash)

**when I just delete one on clause, the query would not make be crash.**
such as delete **t1.account_id <=> t2.account_id**
or delete **t1.account_name = t2.account_name**
or delete **t1.ssp_id = t2.ssp_id**.

**be.out:** 
> F0102 16:02:38.069783 80177 column.h:647] Column String is not a contiguous block of memory
*** Check failure stack trace: ***
    @     0x563b63d38239  google::LogMessageFatal::~LogMessageFatal()
    @     0x563b5ca3d17d  doris::vectorized::IColumn::get_raw_data()
    @     0x563b5c394231  doris::RuntimePredicateWrapper::insert_batch()
    @     0x563b5c389af3  doris::IRuntimeFilter::insert_batch()
    @     0x563b5ef4ac4d  doris::VRuntimeFilterSlots::insert()
    @     0x563b5ef49828  doris::vectorized::ProcessRuntimeFilterBuild<>::operator()()
    @     0x563b5ef2ec03  (unknown)
    @     0x563b5ee93ced  doris::vectorized::HashJoinNode::sink()
    @     0x563b637bfe3e  doris::pipeline::StreamingOperator<>::sink()
    @     0x563b637ecb64  doris::pipeline::PipelineTask::execute()
    @     0x563b637f5593  doris::pipeline::TaskScheduler::_do_work()
    @     0x563b5c5b990f  doris::ThreadPool::dispatch_thread()
    @     0x563b5c5af88c  doris::Thread::supervise_thread()
    @     0x7f6a47f17851  start_thread
    @     0x7f6a488b267d  clone
    @              (nil)  (unknown)
*** Query id: 3c9e8d26f2cb4d10-a4d07d7b9d7187a7 ***
*** tablet id: 0 ***
*** Aborted at 1704182558 (unix time) try "date -d @1704182558" if you are using GNU date ***
*** Current BE git commitID: Unknown ***
*** SIGABRT unknown detail explain (@0x1f4000137a5) received by PID 79781 (TID 80177 OR 0x7f68787f5700) from PID 79781; stack trace: ***
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /home/work/linzhaosheng/doris_2.3/apache-doris-2.0.3-src/be/src/common/signal_handler.h:417
 1# 0x00007F6A487FD920 in /lib64/libc.so.6
 2# __GI_raise in /lib64/libc.so.6
 3# abort in /lib64/libc.so.6
 4# 0x0000563B63D3E219 in /home/work/doris/apache-doris-2.0.1.1-bin-x64/be/lib/doris_be
 5# google::LogMessage::SendToLog() in /home/work/doris/apache-doris-2.0.1.1-bin-x64/be/lib/doris_be
 6# google::LogMessage::Flush() in /home/work/doris/apache-doris-2.0.1.1-bin-x64/be/lib/doris_be
 7# google::LogMessageFatal::~LogMessageFatal() in /home/work/doris/apache-doris-2.0.1.1-bin-x64/be/lib/doris_be
 8# doris::vectorized::IColumn::get_raw_data() const at /home/work/linzhaosheng/doris_2.3/apache-doris-2.0.3-src/be/src/vec/columns/column.h:647
 9# doris::RuntimePredicateWrapper::insert_batch(COW<doris::vectorized::IColumn>::immutable_ptr<doris::vectorized::IColumn>, std::vector<int, std::allocator<int> > const&) at /home/work/linzhaosheng/doris_2.3/apache-doris-2.0.3-src/be/src/exprs/runtime_filter.cpp:592
10# doris::IRuntimeFilter::insert_batch(COW<doris::vectorized::IColumn>::immutable_ptr<doris::vectorized::IColumn>, std::vector<int, std::allocator<int> > const&) at /home/work/linzhaosheng/doris_2.3/apache-doris-2.0.3-src/be/src/exprs/runtime_filter.cpp:1148
11# doris::VRuntimeFilterSlots::insert(std::unordered_map<doris::vectorized::Block const*, std::vector<int, std::allocator<int> >, std::hash<doris::vectorized::Block const*>, std::equal_to<doris::vectorized::Block const*>, std::allocator<std::pair<doris::vectorized::Block const* const, std::vector<int, std::allocator<int> > > > >&) at /home/work/linzhaosheng/doris_2.3/apache-doris-2.0.3-src/be/src/exprs/runtime_filter_slots.h:198
12# doris::vectorized::ProcessRuntimeFilterBuild<doris::vectorized::SerializedHashTableContext<doris::vectorized::RowRefList> >::operator()(doris::RuntimeState*, doris::vectorized::SerializedHashTableContext<doris::vectorized::RowRefList>&) at /home/work/linzhaosheng/doris_2.3/apache-doris-2.0.3-src/be/src/vec/exec/join/vhash_join_node.cpp:304
13# _ZNSt8__detail9__variant17__gen_vtable_implINS0_12_Multi_arrayIPFNS0_21__deduce_visit_resultIN5doris6StatusEEEONS4_10vectorized8OverloadIJZNS7_12HashJoinNode4sinkEPNS4_12RuntimeStateEPNS7_5BlockEbE3$_0ZNS9_4sinkESB_SD_bE3$_1EEERSt7variantIJSt9monostateNS7_26SerializedHashTableContextINS7_10RowRefListEEENS7_27PrimaryTypeHashTableContextIhSL_EENSN_ItSL_EENSN_IjSL_EENSN_ImSL_EENSN_INS7_7UInt128ESL_EENSN_INS7_7UInt256ESL_EENS7_24FixedKeyHashTableContextImLb1ESL_EENSW_ImLb0ESL_EENSW_ISS_Lb1ESL_EENSW_ISS_Lb0ESL_EENSW_ISU_Lb1ESL_EENSW_ISU_Lb0ESL_EENSK_INS7_18RowRefListWithFlagEEENSN_IhS13_EENSN_ItS13_EENSN_IjS13_EENSN_ImS13_EENSN_ISS_S13_EENSN_ISU_S13_EENSW_ImLb1ES13_EENSW_ImLb0ES13_EENSW_ISS_Lb1ES13_EENSW_ISS_Lb0ES13_EENSW_ISU_Lb1ES13_EENSW_ISU_Lb0ES13_EENSK_INS7_19RowRefListWithFlagsEEENSN_IhS1H_EENSN_ItS1H_EENSN_IjS1H_EENSN_ImS1H_EENSN_ISS_S1H_EENSN_ISU_S1H_EENSW_ImLb1ES1H_EENSW_ImLb0ES1H_EENSW_ISS_Lb1ES1H_EENSW_ISS_Lb0ES1H_EENSW_ISU_Lb1ES1H_EENSW_ISU_Lb0ES1H_EEEEEJEEESt16integer_sequenceImJLm1EEEE14__visit_invokeESH_S1W_ at /home/work/linzhaosheng/tools/ldb_toolchain_gen_bin/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/variant:1013
14# doris::vectorized::HashJoinNode::sink(doris::RuntimeState*, doris::vectorized::Block*, bool) at /home/work/linzhaosheng/doris_2.3/apache-doris-2.0.3-src/be/src/vec/exec/join/vhash_join_node.cpp:967
15# doris::pipeline::StreamingOperator<doris::pipeline::HashJoinBuildSinkBuilder>::sink(doris::RuntimeState*, doris::vectorized::Block*, doris::pipeline::SourceState) at /home/work/linzhaosheng/doris_2.3/apache-doris-2.0.3-src/be/src/pipeline/exec/operator.h:347
16# doris::pipeline::PipelineTask::execute(bool*) at /home/work/linzhaosheng/doris_2.3/apache-doris-2.0.3-src/be/src/pipeline/pipeline_task.cpp:266
17# doris::pipeline::TaskScheduler::_do_work(unsigned long) at /home/work/linzhaosheng/doris_2.3/apache-doris-2.0.3-src/be/src/pipeline/task_scheduler.cpp:267
18# doris::ThreadPool::dispatch_thread() in /home/work/doris/apache-doris-2.0.1.1-bin-x64/be/lib/doris_be
19# doris::Thread::supervise_thread(void*) at /home/work/linzhaosheng/doris_2.3/apache-doris-2.0.3-src/be/src/util/thread.cpp:499
20# start_thread in /lib64/libpthread.so.0
21# clone in /lib64/libc.so.6

### What You Expected?

be not crash

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xingyingone** [comment]
is there  "Bad cast from type" in your error log

**Comment by DA1OOO** [comment]
> is there "Bad cast from type" in your error log

I have encountered many times of BE crash caused by error like bad cast type. some have been fixed.

**Comment by DA1OOO** [comment]
this is a new case about bad cast type. maybe it is relative to `<=>`

**Comment by yiguolei** [comment]
This is a bug, will fix in 204 or 205
