### ISSUE TITLE
[Bug] [ERROR] Could not execute SQL statement. Reason: org.apache.doris.flink.exception.DorisRuntimeException: Load Doris data failed, schema size of fetch data is wrong.

### ISSUE THREAD

**Issue by devchai123** [apache/doris#29473]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.3

### What's Wrong?

CREATE TABLE doris_sink (
--   PRIMARY KEY (`id`) NOT ENFORCED
  `task_id` INT,
  `@timestamp` TIMESTAMP WITHOUT TIME ZONE,
  `req_starttime` TIMESTAMP WITHOUT TIME ZONE,
  `req_timeout` BIGINT,
  `msg` STRING,
  PRIMARY KEY (`task_id`) NOT ENFORCED
) WITH (
  'connector' = 'doris',
  'fenodes' = '192.168.234.205:8030',
  'jdbc-url' = 'jdbc:mysql://192.168.234.205:9030',
  'table.identifier' = 'dnsbeat_metric.example_tbl_unique',
  'username' = 'root',
  'sink.label-prefix' = 'doris_label',
  'doris.request.retries' = '3',
  'doris.request.connect.timeout.ms' = '30000'
);

flink SQL-client 链接doris 作为输出到数据的终端  在flinksql 里边报了这个错误[ERROR] Could not execute SQL statement. Reason:
org.apache.doris.flink.exception.DorisRuntimeException: Load Doris data failed, schema size of fetch data is wrong.   

### What You Expected?

期待 flink结合doris   吧kafka的数据处理完成写到doris中

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JNSimba** [comment]
flink doris connector 1.5.1 fix it
