### ISSUE TITLE
[Bug] 严重BUG，参数写反导致BE全挂

### ISSUE THREAD

**Issue by linzhicong1996** [apache/doris#29664]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris 2.0.3

### What's Wrong?

使用SPLIT_BY_STRING函数参数写反，将字段写到分割符号，导致3BE直接全部挂掉。分割数量300W+

### What You Expected?

可以提示报错，也可以报告执行失败，但是BE直接挂掉太危险了。相当与只要有查询权限就能直接导致集群崩溃

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by linzhicong1996** [comment]
SELECT SPLIT_BY_STRING(check_total_volume,'*') AS box_size FROM ex.extable;
err sql :SELECT SPLIT_BY_STRING('*,'check_total_volume) AS box_size FROM ex.extable;
check_total_volume: 15*1.5*19

**Comment by felixwluo** [comment]
Please give me the table structure and test data @linzhicong1996

**Comment by linzhicong1996** [comment]
> Please give me the table structure and test data @linzhicong1996

-- 该表结构只有关键字段，全表49个字段
CREATE TABLE `ods_test_table` (
  `id` varchar(200) NOT NULL,
  `total_volume` varchar(200) NULL,
  `check_total_volume` varchar(200) NULL,
  `last_updated_on` datetime NOT NULL,
  `cases` text NULL,
  `is_deleted` boolean NOT NULL DEFAULT "0"',
  `update_time` datetime NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=OLAP
UNIQUE KEY(`id`)
COMMENT 'OLAP'
DISTRIBUTED BY HASH(`id`) BUCKETS 10
PROPERTIES (
"replication_allocation" = "tag.location.default: 3",
"is_being_synced" = "false",
"storage_format" = "V2",
"light_schema_change" = "true",
"disable_auto_compaction" = "false",
"enable_single_replica_compaction" = "false"
);

**Comment by linzhicong1996** [comment]
![image](https://github.com/apache/doris/assets/94167908/31010713-290d-4e3c-8ec6-e3889a702ff7)

**Comment by felixwluo** [comment]
Okay, let me repeat that

**Comment by felixwluo** [comment]
<img width="197" alt="image" src="https://github.com/apache/doris/assets/131352377/58f1df9e-7a02-4430-8970-c336f662dcce">
Looks like 2.0.4 has been fixed @linzhicong1996

**Comment by BiteTheDDDDt** [comment]
https://github.com/apache/doris/pull/28030
