### ISSUE TITLE
[Bug]  UNIQUE KEY can't merge primary key

### ISSUE THREAD

**Issue by SongJok** [apache/doris#29674]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.3

### What's Wrong?

In the same SQL batch,when I use DUPLICATE KEY table data  insert into  UNIQUE KEY table data,every primary key has one record value for older

### What You Expected?

In the same SQL batch,I hope latest data merge into table

### How to Reproduce?

drop table if exists test.user_info_test;
CREATE TABLE if not exists test.user_info_test (
  `user_id` int(11) NOT NULL COMMENT '用户ID',
  `age` int(11) NULL DEFAULT "0" COMMENT '年龄',
  `scores` int(11) NULL DEFAULT "0" COMMENT '得分'
)
UNIQUE KEY(`user_id`)
DISTRIBUTED BY HASH(`user_id`) BUCKETS 1
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"enable_unique_key_merge_on_write" = "true"
);

insert into test.user_info_test
(user_id,age,scores)
select user_id,age,scores 
from
(select 6666 user_id ,17 age,1000 scores 
union all
select 6666 user_id ,18 age,2000 scores 
union all
select 6666 user_id ,19 age,3000 scores 
union all
select 6666 user_id ,20 age,4000 scores)that
-- order by age desc;
order by age desc;

select * from test.user_info_test ;

### Anything Else?

After testing, if each primary key data is inserted one by one, it can be solved, but it does not comply with the implementation of this function, so this should be a bug

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hf200012** [comment]
This is completely expected
![image](https://github.com/apache/doris/assets/820301/5c307b81-1777-4b1a-b450-dc15915cbd67)

**Comment by SongJok** [comment]
My understanding is insertion order
1:age=20
2:age=19 把is_delete的标记打给 age=20
3:age=18  把is_delete的标记打给 age=19
4:age=17 把is_delete的标记打给 age=18
最终结果为 age=17

I set one less parameter ："function_column.sequence_col" = 'column_name',
