### ISSUE TITLE
[Bug] Process one query failed because. org.apache.doris.common.AnalysisException: errCode = 2, detailMessage = Syntax error in line 1: ...ORDER BY ORDINAL_POSITION SEPARATOR ', ') PARAMETER, R...

### ISSUE THREAD

**Issue by Marsrick** [apache/doris#29695]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

version -2.0.1

### What's Wrong?

Process one query failed because.
org.apache.doris.common.AnalysisException: errCode = 2, detailMessage = Syntax error in line 1:
...ORDER BY ORDINAL_POSITION SEPARATOR ', ') PARAMETER, R...

### What You Expected?

fe
![Uploading c3c4190c4e7f363978538551572f973.png…]()

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LemonLiTree** [comment]
Syntax error...
