### ISSUE TITLE
[Feature]Doris是否支持对运行中SQL资源消耗的实时监控 

### ISSUE THREAD

**Issue by Yato-song** [apache/doris#29781]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

根据Doris的官方文档，我能对整个Doris集群的资源消耗情况实现监控，但针对每一个在运行中的SQL，是否有监控每个SQL资源消耗的方法，比如我想查看当前运行中sql的内存消耗，CPU时长，溢出文件等

### Use case

我希望能够观察到每个sql的资源消耗情况，以便对大SQL慢SQL去针对性的进行优化和治理

### Related issues

none

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangbo** [comment]
查询的整体cpu时间/单be的peakmemory/scanrows/scanbytes这些数据在fe.audit.log里已经有了
这些数据的查询运行时查询预计下周可以完成支持

**Comment by Yato-song** [comment]
> 查询的整体cpu时间/单be的peakmemory/scanrows/scanbytes这些数据在fe.audit.log里已经有了 这些数据的查询运行时查询预计下周可以完成支持

是指下周会上线新版本，增加这个新特性吗

**Comment by wangbo** [comment]
> > 查询的整体cpu时间/单be的peakmemory/scanrows/scanbytes这些数据在fe.audit.log里已经有了 这些数据的查询运行时查询预计下周可以完成支持
> 
> 是指下周会上线新版本，增加这个新特性吗

主分支可用，不过距离release到稳定版可能还需要一段时间，一个是得看下这个特性要cherry-pick哪个发行版本，另一个是对这个功能本身的测试和验证需要些时间

**Comment by Yato-song** [comment]
> > > 查询的整体cpu时间/单be的peakmemory/scanrows/scanbytes这些数据在fe.audit.log里已经有了 这些数据的查询运行时查询预计下周可以完成支持
> > 
> > 
> > 是指下周会上线新版本，增加这个新特性吗
> 
> 指的是主分支可用。 主分支可用距离release到稳定版可能还需要一段时间，一个是得看下这个特性要cherry-pick哪个发行版本，另一个是对这个功能本身的测试和验证需要些时间

了解了，感谢

**Comment by wangbo** [comment]
#29999
