### ISSUE TITLE
[Bug] old planner can not rewrite BetweenPredicate  in having

### ISSUE THREAD

**Issue by iwanttobepowerful** [apache/doris#29798]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

```sql
create table  test(a DATE,b varchar(100),c varchar (100),d varchar(100),e int,f int)  
ENGINE=OLAP
DUPLICATE KEY( a )
COMMENT "OLAP"
DISTRIBUTED BY HASH( e ) BUCKETS  auto
PROPERTIES (
    "replication_num" = "1"
);

set experimental_enable_nereids_planner = false;

select t1.a,t1.b,t1.c,t1.f,t1.d,t1.e,stddev_pop(t1.d+t1.e) std from test t1 
group by t1.f,t1.d,t1.e,t1.a,t1.b,t1.c
having t1.b between 'aa' and 'bb';

```

ERROR 1105 (HY000): IllegalStateException, msg: java.lang.IllegalStateException: BetweenPredicate needs to be rewritten into a CompoundPredicate.

### What You Expected?

can get result

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ihadoop** [comment]
我试了一下最新版本的不报错。
![image](https://github.com/apache/doris/assets/5036560/8da4bd9b-27b7-47a2-ae73-4410bd63ca76)

**Comment by Nitin-Kashyap** [comment]
I can look into it!

issue seems to be because BetweenPredicate is pushed down to ScanNode. And the rewritten expression (BetweenPredicate to CompoundPredicate) even if done is not applied to pushdown predicates
