### ISSUE TITLE
[Bug] 关于date数据类型的问题

### ISSUE THREAD

**Issue by JOKERWING** [apache/doris#29826]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris version doris-2.0.1

### What's Wrong?

今天遇到一个很奇怪的问题。

有一个表，表里有一个字段名称为‘date’，数据类型为date。存储的数据为每年每月的1号，例如：2022-11-01、2023-01-01、2023-05-01....

然后我运行了一个sql语句：
`SELECT distinct date FROM test_date  WHERE date = '2024-00-01' `

执行这个sql本，不应该有结果的。但是，我确得到如下内容：
![520FE159-7605-42a0-928F-2347B048594D](https://github.com/apache/doris/assets/41933153/ab044e97-8648-4ef7-b7f4-4faf16c35faf)

查询到了 2023-07-01到2023-12-01 这些日期。
很奇怪，能帮忙解答下这个问题吗？

### What You Expected?

我不确定这是不是bug，但我想搞清楚这是为什么。

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ccoffline** [comment]
可以贴一下create sql么，最好再加些样本数据，确保其他人能复现

**Comment by JOKERWING** [comment]
> 可以贴一下create sql么，最好再加些样本数据，确保其他人能复现

好的。下面是我的sql。


 建表DDL：
`-- test_date definition

CREATE TABLE `test_date` (
  `id` varchar(10) NULL,
  `date` date NULL COMMENT '日期'
) ENGINE=OLAP
UNIQUE KEY(`id`, `date`)
COMMENT 'OLAP'
PARTITION BY RANGE(`date`)
(PARTITION p00000101 VALUES [('0000-01-01'), ('2023-01-01')),
PARTITION p20230101 VALUES [('2023-01-01'), ('2023-07-01')),
PARTITION p20230701 VALUES [('2023-07-01'), ('2024-01-01')),
PARTITION p20240101 VALUES [('2024-01-01'), ('2024-07-01')),
PARTITION p20240701 VALUES [('2024-07-01'), ('2025-01-01')),
PARTITION p20250101 VALUES [('2025-01-01'), ('2025-07-01')),
PARTITION p20250701 VALUES [('2025-07-01'), ('2026-01-01')),
PARTITION p20260101 VALUES [('2026-01-01'), ('2026-07-01')),
PARTITION p20260701 VALUES [('2026-07-01'), ('2027-01-01')),
PARTITION p20270101 VALUES [('2027-01-01'), ('2027-07-01')),
PARTITION p20270701 VALUES [('2027-07-01'), ('2028-01-01')),
PARTITION p20280101 VALUES [('2028-01-01'), ('2028-07-01')),
PARTITION p20280701 VALUES [('2028-07-01'), ('2029-01-01')),
PARTITION p20290101 VALUES [('2029-01-01'), ('2029-07-01')),
PARTITION p20290701 VALUES [('2029-07-01'), ('2030-01-01')),
PARTITION p20300101 VALUES [('2030-01-01'), ('2100-01-01')))
DISTRIBUTED BY HASH(`id`) BUCKETS 10
PROPERTIES (
"replication_allocation" = "tag.location.default: 3",
"is_being_synced" = "false",
"storage_format" = "V2",
"disable_auto_compaction" = "false",
"enable_single_replica_compaction" = "false"
);`


部分模拟数据：
`INSERT INTO test_date (id, `date`) VALUES('01', '2022-10-01');
INSERT INTO test_date (id, `date`) VALUES('02', '2022-10-01');
INSERT INTO test_date (id, `date`) VALUES('01', '2022-11-01');
INSERT INTO test_date (id, `date`) VALUES('02', '2022-11-01');
INSERT INTO test_date (id, `date`) VALUES('01', '2022-12-01');
INSERT INTO test_date (id, `date`) VALUES('02', '2022-12-01');
INSERT INTO test_date (id, `date`) VALUES('03', '2023-01-01');
INSERT INTO test_date (id, `date`) VALUES('01', '2023-02-01');
INSERT INTO test_date (id, `date`) VALUES('03', '2023-03-01');
INSERT INTO test_date (id, `date`) VALUES('03', '2023-04-01');
INSERT INTO test_date (id, `date`) VALUES('03', '2023-05-01');
INSERT INTO test_date (id, `date`) VALUES('03', '2023-06-01');
INSERT INTO test_date (id, `date`) VALUES('04', '2023-06-01');
INSERT INTO test_date (id, `date`) VALUES('03', '2023-07-01');
INSERT INTO test_date (id, `date`) VALUES('04', '2023-07-01');
INSERT INTO test_date (id, `date`) VALUES('03', '2023-08-01');
INSERT INTO test_date (id, `date`) VALUES('04', '2023-08-01');
INSERT INTO test_date (id, `date`) VALUES('03', '2023-09-01');
INSERT INTO test_date (id, `date`) VALUES('04', '2023-09-01');
INSERT INTO test_date (id, `date`) VALUES('03', '2023-10-01');
INSERT INTO test_date (id, `date`) VALUES('04', '2023-10-01');
INSERT INTO test_date (id, `date`) VALUES('01', '2023-11-01');
INSERT INTO test_date (id, `date`) VALUES('02', '2023-11-01');
INSERT INTO test_date (id, `date`) VALUES('03', '2023-11-01');
INSERT INTO test_date (id, `date`) VALUES('03', '2023-12-01');
INSERT INTO test_date (id, `date`) VALUES('04', '2023-12-01');
INSERT INTO test_date (id, `date`) VALUES('0A', '2023-12-01');
INSERT INTO test_date (id, `date`) VALUES('06', '2024-01-01');
INSERT INTO test_date (id, `date`) VALUES('07', '2024-01-01');`


执行查询结果的sql：
` SELECT distinct date 
 FROM test_date 
 WHERE date = '2024-00-01' `

**Comment by ccoffline** [comment]
我在2.0.1上测试的结果
```sql
mysql> select * from test_date;
+------+------------+
| id   | date       |
+------+------------+
| 01   | 2023-02-01 |
| 03   | 2023-01-01 |
| 03   | 2023-03-01 |
| 03   | 2023-04-01 |
| 03   | 2023-05-01 |
| 03   | 2023-06-01 |
| 01   | 2023-11-01 |
| 03   | 2023-07-01 |
| 03   | 2023-08-01 |
| 03   | 2023-09-01 |
| 03   | 2023-10-01 |
| 03   | 2023-11-01 |
| 03   | 2023-12-01 |
| 0A   | 2023-12-01 |
| 04   | 2023-07-01 |
| 04   | 2023-08-01 |
| 04   | 2023-09-01 |
| 04   | 2023-10-01 |
| 04   | 2023-12-01 |
| 06   | 2024-01-01 |
| 07   | 2024-01-01 |
| 04   | 2023-06-01 |
| 02   | 2022-10-01 |
| 02   | 2022-11-01 |
| 02   | 2022-12-01 |
| 02   | 2023-11-01 |
| 01   | 2022-10-01 |
| 01   | 2022-11-01 |
| 01   | 2022-12-01 |
+------+------------+
29 rows in set (0.03 sec)

mysql> SELECT distinct date FROM test_date  WHERE date = '2024-00-01';
Empty set (0.04 sec)
```
在最新版上会报错。所以错误的日期格式对于Doris来讲是未定义行为，尽量避免一下。
```sql
mysql> SELECT distinct date FROM test_date  WHERE date = '2024-00-01';
ERROR 1105 (HY000): errCode = 2, detailMessage = Incorrect datetime value: CAST('2024-00-01' AS DATETIMEV2(0)) in expression: (CAST(`date` AS DATETIMEV2(0)) = CAST('2024-00-01' AS DATETIMEV2(0)))
```

**Comment by JOKERWING** [comment]
> 我在2.0.1上测试的结果
> 
> ```sql
> mysql> select * from test_date;
> +------+------------+
> | id   | date       |
> +------+------------+
> | 01   | 2023-02-01 |
> | 03   | 2023-01-01 |
> | 03   | 2023-03-01 |
> | 03   | 2023-04-01 |
> | 03   | 2023-05-01 |
> | 03   | 2023-06-01 |
> | 01   | 2023-11-01 |
> | 03   | 2023-07-01 |
> | 03   | 2023-08-01 |
> | 03   | 2023-09-01 |
> | 03   | 2023-10-01 |
> | 03   | 2023-11-01 |
> | 03   | 2023-12-01 |
> | 0A   | 2023-12-01 |
> | 04   | 2023-07-01 |
> | 04   | 2023-08-01 |
> | 04   | 2023-09-01 |
> | 04   | 2023-10-01 |
> | 04   | 2023-12-01 |
> | 06   | 2024-01-01 |
> | 07   | 2024-01-01 |
> | 04   | 2023-06-01 |
> | 02   | 2022-10-01 |
> | 02   | 2022-11-01 |
> | 02   | 2022-12-01 |
> | 02   | 2023-11-01 |
> | 01   | 2022-10-01 |
> | 01   | 2022-11-01 |
> | 01   | 2022-12-01 |
> +------+------------+
> 29 rows in set (0.03 sec)
> 
> mysql> SELECT distinct date FROM test_date  WHERE date = '2024-00-01';
> Empty set (0.04 sec)
> ```
> 
> 在最新版上会报错。所以错误的日期格式对于Doris来讲是未定义行为，尽量避免一下。
> 
> ```sql
> mysql> SELECT distinct date FROM test_date  WHERE date = '2024-00-01';
> ERROR 1105 (HY000): errCode = 2, detailMessage = Incorrect datetime value: CAST('2024-00-01' AS DATETIMEV2(0)) in expression: (CAST(`date` AS DATETIMEV2(0)) = CAST('2024-00-01' AS DATETIMEV2(0)))
> ```

好的，你没复现出来我的问题。但没事，我之后会使用正确的日期格式去执行sql的、
谢谢您的回答~
