### ISSUE TITLE
ADD Json Type into External Table

### ISSUE THREAD

**Issue by Carey8175** [apache/doris#29974]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Cant add column of json into the external table, because all of the culumns in external table are the key columns instead of the value columns.

### Use case

We could load the json directly in external table

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LemonLiTree** [comment]
use catalog please
