### ISSUE TITLE
[Bug] backend节点实际使用的磁盘空间超出数据真实大小过多

### ISSUE THREAD

**Issue by zhangpenggh** [apache/doris#30016]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-2.0.3-rc06-37d31a5

### What's Wrong?

backend服务器配置：三台 8核32G内存500G磁盘 
只有一张大表，show data 显示数据量是 270.328 GB ， ReplicaCount：270， RowCount： 111528876
数据是用flink实时持续写入。在持续几天之后三台机器的磁盘使用率都超过90%，也就是每台服务器存储都超过了450G。 对比于show data显示的270G超出了太多。
重启其中一个backend，这一台的磁盘降到了30%左右。对比数据目录发现：
相同目录下 （{doris_storage_root}/data/21/11093/1649088725/），重启过的节点的数据和索引文件（dat和idx）只有24小时以内的，而未重启节点的数据和索引文件有最近6天的。
原因compaction之后旧的数据文件没有清理导致磁盘使用增长？？

### What You Expected?

及时清理无效的数据文件，释放磁盘空间

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhangpenggh** [comment]
通过配置path_gc_check_interval_second 可以调整清理数据文件的周期

**Comment by zhangpenggh** [comment]
还有一个问题就是在磁盘使用率达到危险水位线的时候，不会主动清理这一部分数据，而且也没提供手动清理的方法。会出现因为这部分数据过大而导致磁盘被写满的情况。
建议在磁盘达到某一阈值时自动清理。

**Comment by LemonLiTree** [comment]
达到阈值 只会限制涉及写入的操作，具体的清理逻辑 还是按配置来的
