### ISSUE TITLE
[Bug] No matching function with signature: cosine_distance

### ISSUE THREAD

**Issue by pppeace** [apache/doris#30062]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

```
{
    "msg":"success",
    "code":0,
    "data":{
        "beVersionInfo":{
            "dorisBuildVersionPrefix":"doris",
            "dorisBuildVersionMajor":2,
            "dorisBuildVersionMinor":0,
            "dorisBuildVersionPatch":2,
            "dorisBuildVersionRcVersion":"rc05",
            "dorisBuildVersion":"doris-2.0.2-rc05",
            "dorisBuildHash":"git://VM-16-12-centos@ae923f7094eb7ffbf2c87bcc7ff4bfface5ac4d4",
            "dorisBuildShortHash":"ae923f7",
            "dorisBuildTime":"Sun, 01 Oct 2023 15:52:07 UTC",
            "dorisBuildInfo":"VM-16-12-centos"
        }
    },
    "count":0
}
```

### What's Wrong?

Use the Vector Distance Functions from [document](https://doris.apache.org/zh-CN/docs/sql-manual/sql-functions/distance-functions/cosine-distance)
`SELECT cosine_distance([1, 2], [2, 3]);`

and here is the error
![image](https://github.com/apache/doris/assets/24377710/7b50d92c-5406-4918-b2be-6b82da5747a0)

### What You Expected?

The function can be used right.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LemonLiTree** [comment]
2.0 not support

**Comment by pppeace** [comment]
> 2.0 not support

Here is the [document](https://doris.apache.org/zh-CN/docs/sql-manual/sql-functions/distance-functions/cosine-distance/), it is under version 2.0.

**Comment by LemonLiTree** [comment]
doc error, I will fix it

**Comment by pppeace** [comment]
@LemonLiTree 
Thanks for reply. Do you know the plan that the vec functions can be used?

**Comment by LemonLiTree** [comment]
2.1 version
