### ISSUE TITLE
[Bug] old planner and Nereids Planner can not return same result

### ISSUE THREAD

**Issue by iwanttobepowerful** [apache/doris#30103]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

old planner and Nereids Planner can not return same result.

### What You Expected?

old planner and Nereids Planner return same result.

### How to Reproduce?

```sql
create table z1(a DECIMAL(2, 1), b DECIMAL(3, 2)) ENGINE=OLAP DUPLICATE KEY(a) COMMENT "OLAP" 
DISTRIBUTED BY HASH(a) BUCKETS  auto PROPERTIES (     "replication_num" = "1" );

create table z2(c DECIMAL(3, 2)) ENGINE=OLAP DUPLICATE KEY(c) COMMENT "OLAP" DISTRIBUTED BY HASH(c) BUCKETS  auto
 PROPERTIES (     "replication_num" = "1" );
 
 insert into z1 values(5.7, 5.70);
insert into z2 values(5.70);

select a, b from z1, z2 where a=c;

```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Nitin-Kashyap** [comment]
Issue seems to be with type difference of 2 columns.

![image](https://github.com/apache/doris/assets/66766227/193c46e9-694e-4885-9420-eb01916d4c49)

I can have a look at it..
