### ISSUE TITLE
[Bug] When using the hive catalog the hive table name is uppercase, the Doris query is reported wrong

### ISSUE THREAD

**Issue by LuGuangming** [apache/doris#30166]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.3

### What's Wrong?

When using the hive catalog the hive table name is uppercase, the Doris query is reported wrong
for example:
hive create table:
create table HIVE_test3(id int, name string) stored as orc;
doris query table error:
![image](https://github.com/apache/doris/assets/71873108/5543afcc-b231-4db4-80cf-5f4ba97aee88)

### What You Expected?

The hive is insensitive and the actual storage HDFS path is lowercase, so we need to support the hive building table with a capital table name

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AshinGau** [comment]
When I test this case, it throws `Unknown table 'HIVE_test3'`. Can you paste the result of `show tables`. If there's no `hive_test3` in `show tables`, you can refresh [hive catalog](https://doris.apache.org/zh-CN/docs/lakehouse/multi-catalog/hive#%E5%85%83%E6%95%B0%E6%8D%AE%E7%BC%93%E5%AD%98%E4%B8%8E%E5%88%B7%E6%96%B0); If there's `hive_test3` in `show tables`, you can change `select * from HIVE_test3` as `select * from hive_test3`. Then, Doris will discuss whether case-insensitive hive table name is supported.

**Comment by LuGuangming** [comment]
Hive create table:   create table HIVE_test3(id int, name string) stored as orc;   insert into HIVE_test3 values(111, 'aaa');
Doris show tables：
show tables;
![image](https://github.com/apache/doris/assets/71873108/004ffd80-5cef-4e48-8b1c-473f138e929d)
select * from hive_test3;
![image](https://github.com/apache/doris/assets/71873108/cb866368-c907-48d1-bc4e-097fbe9fc912)

**Comment by LuGuangming** [comment]
![image](https://github.com/apache/doris/assets/71873108/d32a056a-a7af-4e3b-b0a7-a92a1a3779c0)
