### ISSUE TITLE
[Bug] Doris-BE node dead and fe node alived

### ISSUE THREAD

**Issue by dzygoon** [apache/doris#30207]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.0

### What's Wrong?

My test environment consisted of a single machine with a BE node and an FE node,The configuration is 16C+32 GB,When I use the ETL tool to run a single table for 20GB of data file into the database,The BE node is down and I do not see any error message.

When I checked the past history log, I found the following error（INFO.log）：
![image](https://github.com/apache/doris/assets/96854451/32acbaf6-4e03-4611-ba63-77e876427829)

(be.WARNING.log)
![image](https://github.com/apache/doris/assets/96854451/9b23e41b-ed7b-40cb-8af8-d258f798ea68)

I also found that fe nodes could not be found for some time...

### What You Expected?

I want to know the cause of BE node downtime, how to solve these problems.

### How to Reproduce?

none.

### Anything Else?

I see similar problems in the community, but there are no answers.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Vallishp** [comment]
can you pls try these ?
1) May be can you please check the status of backend after the start of be using
show backends\G   (its on query port using mysql)

2) Check any core dump file present in the env.

3) may be try run again test case, with enabling be debug log. https://doris.apache.org/docs/1.2/advanced/best-practice/debug-log/

**Comment by dzygoon** [comment]
> can you pls try these ?
> 
> 1. May be can you please check the status of backend after the start of be using
>    show backends\G   (its on query port using mysql)
> 2. Check any core dump file present in the env.
> 3. may be try run again test case, with enabling be debug log. https://doris.apache.org/docs/1.2/advanced/best-practice/debug-log/

thanks for your reply.
1.My be node can not be started.When I first found out it was down,I tried to boot it once, it was bootable then, and I was connected via fe,But then it went down again,And then I can't start the be node anymore.
2.What is core dump file?Sorry,I don't understand.
3.I will try to turn on a higher level log for monitoring.

**Comment by Vallishp** [comment]
oh ok. then sh start_be.sh --console  might be helpful, you might get some error in the console itself, from that we can get a clue

**Comment by dzygoon** [comment]
> oh ok. then sh start_be.sh --console might be helpful, you might get some error in the console itself, from that we can get a clue

When i run start_be.sh,I will get shell command error message from console.Now i give up and redeploy be node.

**Comment by dzygoon** [comment]
> > oh ok. then sh start_be.sh --console might be helpful, you might get some error in the console itself, from that we can get a clue
> 
> When i run start_be.sh,I will get shell command error message from console.Now i give up and redeploy be node.

I want to know what is the wrong reason for deleting files?

**Comment by Vallishp** [comment]
Can you please share  screenshot or log info more?

**Comment by dzygoon** [comment]
> Can you please share screenshot or log info more?

sure.
This is be.WARNING.log partial screenshot.
![9650af123635d0650fb7f275f6655fd](https://github.com/apache/doris/assets/96854451/2b6551c7-132d-4789-8b5e-16df341f8d0e)
![image](https://github.com/apache/doris/assets/96854451/c4bde68f-0b02-42ae-9a4c-ea96dd07bfa5)
![image](https://github.com/apache/doris/assets/96854451/e7d0f652-2624-41d6-b1ac-938ba61be855)

Error msg too many...
If be node bad again,I will send more error msg.
