### ISSUE TITLE
[Bug] Inconsistent time_to_sec return value with timediff

### ISSUE THREAD

**Issue by Nenrikido** [apache/doris#30229]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.1

### What's Wrong?

When using `time_to_sec` on a value of type `TIME` returned by `timediff`, the result is always 0 if the `timediff` has been made between two date-like strings, and the result is the good one when the `timediff` has been made between 2 date objects.

### What You Expected?

We would expect `time_to_sec` to always return the amount of seconds in the `TIME` object returned by `timediff`

### How to Reproduce?

`select time_to_sec(timediff('2024-01-22', '2024-01-15')) as seconds;` returns 0 (wrong)
`select time_to_sec(timediff(to_date('2024-01-22'), to_date('2024-01-15'))) as seconds;` returns 604 800 (right)
while both `timediff('2024-01-22', '2024-01-15')` and `timediff(to_date('2024-01-22'), to_date('2024-01-15'))` return `168:00:00` which is the right value

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Mryange** [comment]
fix  in https://github.com/apache/doris/pull/30248
