### ISSUE TITLE
doris can support to limit the timeout of one sql execution

### ISSUE THREAD

**Issue by shellmeng** [apache/doris#3023]
**Is your feature request related to a problem? Please describe.**
I want to pass a timeout to one query sql, just like 'select /*+ max_execution_time(3000)*/'. once time is out, the query will return a timeout exception to the caller and kill the query inside the doris cluster to protected doris from being hurt by this dangerous query.

**Describe the solution you'd like**
just like mysql, support the timeout in a query like   'select /*+ max_execution_time(3000)*/'

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by morningman** [comment]
Currently we do not support this kind of syntax.
You can use session variable like `set query_timeout=60` to set a timeout for all queries in a session.
