### ISSUE TITLE
[Feature] support ANSI standard keyword for current_xxx

### ISSUE THREAD

**Issue by morrySnow** [apache/doris#30310]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

add below keyword
```
CURRENT_DATE
CURRENT_TIME
CURRENT_TIMESTAMP
LOCALTIME
LOCALTIMESTAMP
CURRENT_USER
```

snow flake doc: https://docs.snowflake.com/search?q=To%20comply%20with%20ANSI%20standards

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Jeecie** [comment]
May I be assigned to this issue?

This would be my first contribution to the project.
If I understand correctly, we want the sql parser/scanner/analyzer to run the same function for the following query

`select CURRENT_DATE;` is interpreted the same as `select CURRENT_DATE();`

and similarly for the other keywords mentioned.

**Comment by nanfeng1999** [comment]
I can try it

**Comment by sjyango** [comment]
I can try it
