### ISSUE TITLE
[Feature] Support some math function

### ISSUE THREAD

**Issue by HappenLee** [apache/doris#30486]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Support function：
corr https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/corr
tanh https://prestodb.io/docs/current/functions/math.html?highlight=tanh#tanh

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by nanfeng1999** [comment]
I will try it
