### ISSUE TITLE
[Bug] SELECT 10.5 DIV 2 * 2 AS "mynum" Why is the result 2

### ISSUE THREAD

**Issue by hayden520** [apache/doris#30539]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.3-rc6

### What's Wrong?

I would like to ask what is the result of executing this in the terminal and whether this is a problem.

`
mysql> SELECT 10.5 DIV 2 * 2 AS "mynum";
+-------+
| mynum |
+-------+
|     2 |
+-------+
1 row in set (0.01 sec)

mysql>
`

### What You Expected?

10

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhbdesign** [comment]
doris-2.0.2-rc05，查询结果是10

**Comment by HappenLee** [comment]
master seems right，only 2.0.3 have bug？

**Comment by morrySnow** [comment]
it is a bug in Nereids, i will fix it

**Comment by hayden520** [comment]
thx
