### ISSUE TITLE
[Bug]  BE Crash when use function mask

### ISSUE THREAD

**Issue by leevin101** [apache/doris#30624]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-1.2.7-branch-1.2-lts-56ce02d

### What's Wrong?

when execute the sql with mask function,BE will crash immediately:
  select mask("张三", '*', '#', '$');
Or
  select mask("abcDEF12345", '*', '#', '$');

output :
> 1105 - RpcException, msg: org.apache.doris.rpc.RpcException: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
 
be and fe log file cannot find any other exception.

### What You Expected?

be or fe cannot crash.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yiguolei** [comment]
@leevin101  Hi, could you please upgrade to 2.0.4 and check if it crash? And if BE crash, please provide the log/be.out file

**Comment by leevin101** [comment]
> @leevin101 Hi, could you please upgrade to 2.0.4 and check if it crash? And if BE crash, please provide the log/be.out file

2.0.5 There is no such issue. thanks！
