### ISSUE TITLE
[Feature] support pecent_rank window function

### ISSUE THREAD

**Issue by lupingqiu** [apache/doris#30636]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

mysql和postgresql提供该函数，常用于按百分比过滤数据，例如取销售额前20%的商品

https://www.mysqltutorial.org/mysql-window-functions/mysql-percent_rank-function/
https://www.postgresqltutorial.com/postgresql-window-function/postgresql-percent_rank-function/

### Use case

PERCENT_RANK() OVER (
    [PARTITION BY partition_expression, ... ]
    ORDER BY sort_expression [ASC | DESC], ...
)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by sjyango** [comment]
I can try！
