### ISSUE TITLE
[Bug] EXPORT WITH columns ERROR

### ISSUE THREAD

**Issue by user-GitHub-user** [apache/doris#30645]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.3

### What's Wrong?

export error

### What You Expected?

no error

### How to Reproduce?

```
CREATE TABLE `kec` (
`timestamp` datetime NULL COMMENT "time"
) ENGINE=OLAP
DUPLICATE KEY(`timestamp`)
COMMENT ""
PARTITION BY RANGE(timestamp)()
DISTRIBUTED BY RANDOM BUCKETS AUTO
PROPERTIES  
(  
"dynamic_partition.enable" = "true",  
"dynamic_partition.time_unit" = "HOUR",  
"dynamic_partition.end" = "24",  
"dynamic_partition.prefix" = "p",  
"replication_num" = "1"
);

insert into kec values("2024-01-31 17:01:01"); 
insert into kec values("2024-01-31 18:01:01");

EXPORT TABLE kec
where timestamp >= '2024-01-31 17:01:01'
TO "file:///tmp/timestamp_"
PROPERTIES (
"format" = "csv",
"label" = "table_kec_export",
"max_file_size" = "1GB",
"parallelism" = "2",
"columns" = "timestamp"
);

SHOW EXPORT FROM log WHERE LABEL = "table_kec_export" ORDER BY StartTime DESC\G;
```

![image](https://github.com/apache/doris/assets/18843801/8a81cc2f-24f3-4d56-a467-6edbfa97e313)

and If no columns is specified, the export succeeds

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
Exporting results to local disk is not allowed.To enable this feature, you need to add `enable_outfile_to_local=true` in fe.conf and restart FE
