### ISSUE TITLE
[Enhancement]  latest metabase can not connect to doris ，i developed a metabase driver which adapte drois 

### ISSUE THREAD

**Issue by ihadoop** [apache/doris#30686]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

when i use latest metabase (latest metabase docker or build from master) to connect doris using mysql protocol (version is 2.0.3),it can not sync database metainfo.
![image](https://github.com/apache/doris/assets/5036560/b646b620-9738-47e5-bb45-d5294003089d)

### Solution

write a doris driver which fully adapt metabase.

so i  have written  a driver which already connection to metabase  correctly.

i create a new metabase driver project and then overwrite some method

1. sql-jdbc.sync/database-type->base-type
2. mdb.spec/spec
3. driver/describe-table
4. driver/describe-database
5. driver/current-user-table-privileges (actually ,it always return true)

https://github.com/apache/doris/assets/5036560/2e309a98-db51-4a27-97e6-ce962787cbf5

i want to submit that project code (clojure code),how to do 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by morningman** [comment]
Cool, I will contact you later

**Comment by HWTsang** [comment]
Any updates?

**Comment by ihadoop** [comment]
> Any updates?

if you want to use，i can provide jar to you。

**Comment by dbuades** [comment]
@ihadoop this would be very useful! Could you open a PR please?

**Comment by ihadoop** [comment]
https://github.com/ihadoop/metabase-doris-driver

**Comment by ihadoop** [comment]
https://github.com/ihadoop/metabase-doris-driver
