### ISSUE TITLE
[Bug] sql解析错误， FUNCTION isoc.days_sub does not exist

### ISSUE THREAD

**Issue by LongWangXX** [apache/doris#30692]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.3

### What's Wrong?

select DATE_FORMAT(date_sub(curdate(),INTERVAL WEEKDAY(curdate()) +7 DAY),'%Y-%m-%d'), DATE_FORMAT(date_sub(curdate(),INTERVAL WEEKDAY(curdate()) - 1 DAY),'%Y-%m-%d');
这条sql这样子跑可执行正确；date_sub可以识别成函数
![image](https://github.com/apache/doris/assets/47943265/d80d8f4d-5eee-4d8f-9b2f-1f3daa383eec)

这样子写则无法识别函数：
SELECT count(distinct iot_id) as sum from mysql_160.isoc.t_isoc_asset_black_list_day_count 
where date>=DATE_FORMAT(date_sub(curdate(),INTERVAL WEEKDAY(curdate()) +7 DAY),'%Y-%m-%d')
and date<=  DATE_FORMAT(date_sub(curdate(),INTERVAL WEEKDAY(curdate()) - 1 DAY),'%Y-%m-%d')
![image](https://github.com/apache/doris/assets/47943265/31967d0f-327e-4016-ab27-cd2e2d16c750)

这样子写可以正常执行：
SELECT count(distinct iot_id) as sum from mysql_160.isoc.t_isoc_asset_black_list_day_count 
![image](https://github.com/apache/doris/assets/47943265/de167de5-91ed-4b21-b042-a5b37a9b7160)

### What You Expected?

解决该问题

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LemonLiTree** [comment]
Try it in mysql client

**Comment by LongWangXX** [comment]
@LemonLiTree doris web
![image](https://github.com/apache/doris/assets/47943265/07a1686b-58ec-4016-8104-452d69ae0e3f)
mysql client

**Comment by LongWangXX** [comment]
@LemonLiTree mysql client still reports an error

**Comment by zy-kkk** [comment]
I will fix it soon

**Comment by LongWangXX** [comment]
@zy-kkk Thanks
