### ISSUE TITLE
[Doris-Future] (enhance) Support more window function

### ISSUE THREAD

**Issue by zclllyybb** [apache/doris#30726]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

We should add more window function to cover other similar products' implementation. Now it includes but not limited to:
VARIANCE --- overall variance
VAR_SAMP --- sample variance
STD --- overall standard deviation
STDDEV_SAMP --- sample std
COVAR_POP --- overall covariance
COVAR_SAMP --- sample cov
CORR --- correlation coefficient
percent_rank --- percentage ranking
cume_dist --- cumulative distribution

This issue could be handled by many people. If you'd like to participate in this issue, please contact me via my we-chat: torch-wood_

### Solution

The idea solution is, for each one participating in this, you could implement one window function.
The basic usage could be found at https://doris.apache.org/docs/dev/sql-manual/sql-functions/window-functions/window-function/
And the code could be found in `aggregate_function_window.h` and `aggregate_function_window.cpp`
Have a good tour coding!

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wyxxxcat** [comment]
I want to try

**Comment by Dragonliu2018** [comment]
I want to try

**Comment by sjyango** [comment]
I want to try

**Comment by koarz** [comment]
i want try

**Comment by JT-G3601** [comment]
I want to try

**Comment by Collin033** [comment]
I want to try
