### ISSUE TITLE
[Bug] Inverted index read null bitmap error occurred

### ISSUE THREAD

**Issue by zhangpenggh** [apache/doris#30733]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.4

### What's Wrong?

查询数据时报错：[E-6002]Inverted index read null bitmap error occurred, reason=Get file size IO error: [IO_ERROR]failed to get file size /data/doris/storage/data/26/10241/1746424379/0200000000001f2ba2404679c72c978b599ce64dd57b0c83_0_10164.idx: (2), No such file or directory
查询语句： 
select distinct file_type 
  from xxxxxxxxxxx
  where last_update_time >= 'xxx' 
  and last_update_time < 'xxx' 
  and file_type is not null

建表语句：
create table xxxxx (
...
last_update_time datetime,
file_type string,
...
INDEX index_xxxx_file_type (`file_type`) USING INVERTED,
)
....

### What You Expected?

正常返回查询结果

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xiaokang** [comment]
@zhangpenggh Can you check if the file /data/doris/storage/data/26/10241/1746424379/0200000000001f2ba2404679c72c978b599ce64dd57b0c83_0_10164.idx exist?

**Comment by zhangpenggh** [comment]
file does not exist

**Comment by xiaokang** [comment]
@zhangpenggh It's fixed in 2.0.9 and higher.
