### ISSUE TITLE
[Bug] ES外表目前不能支持wildcard类型字段识别.

### ISSUE THREAD

**Issue by zhujian86** [apache/doris#30732]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris2.0.4

### What's Wrong?

使用以下语句创建的es外表
`
CREATE EXTERNAL TABLE TEST_OS_ES
ENGINE=ELASTICSEARCH
PROPERTIES (
"hosts" = "http://192.168.1.100:9200",
"index" = "test_index",
"enable_keyword_sniff" = "true"
);
`
当字段含有wildcard时查询报错，需要手工指定类型，否则查询报错：

[HY000][1105] errCode = 2, detailMessage = Unsupported type 'UNSUPPORTED_TYPE' in '`test_filed`'.

### What You Expected?

可以正确识别Wildcard类型的字段

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
let me see
