### ISSUE TITLE
doris磁盘占用实际比统计高[Bug] 

### ISSUE THREAD

**Issue by CAIDUIL** [apache/doris#30742]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.3

### What's Wrong?

以其中一个节点为例子,
doris统计该节点使用1.5TB,一共3TB
实际使用2.78TB,查看均为data目录占用
重启节点,集群,整个服务器都无效,删除大表分区大约去除了1T的数据,占用没有变动

### What You Expected?

希望能删除清除无用数据,或者有能找出无用数据手动删除的方法

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhbdesign** [comment]
回收站占用吗

**Comment by CAIDUIL** [comment]
> 回收站占用吗

用SHOW BACKENDS 查看了TrashUsedCapcatity并没有占用
期间尝试过减少大表的副本,drop 分区的操作都没有看到磁盘变动,后面我尝试使用了ADMIN REBALANCE DISK这个命令,观察了一小段时间,也没有改善

**Comment by zhbdesign** [comment]
https://github.com/apache/doris/issues/30016，看看这个

**Comment by CAIDUIL** [comment]
> [https://github.com/apache/doris/issues/30016，看看这个](https://github.com/apache/doris/issues/30016%EF%BC%8C%E7%9C%8B%E7%9C%8B%E8%BF%99%E4%B8%AA)

是的,我参考过这个issues,描述似乎和我的相同,我尝试过他的提到过的重启节点和设置更低的清理时间,短时间内似乎都没有能起到作用,最后我的问题也不知道具体是哪个操作得到解决的,不过现在是没问题了,感谢回复
