### ISSUE TITLE
[Bug] one of the Chinese document references is missing

### ISSUE THREAD

**Issue by milton4code** [apache/doris#31132]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.3

### What's Wrong?

https://doris.apache.org/zh-CN/docs/data-table/hit-the-rollup/ 
![image](https://github.com/apache/doris/assets/13265817/d923cc9f-48f5-4e22-b50d-b80847792ce9)
"前缀索引" 's link is missing 

### What You Expected?

add the "前缀索引" 's link 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jiugem** [comment]
https://doris.apache.org/zh-CN 也找不到中文了。。

**Comment by milton4code** [comment]
https://doris.apache.org/zh-CN/docs/1.2/data-table/index/prefix-index/ 这个是1.2版本中文链接,不知道是否可以替换?

**Comment by jiugem** [comment]
https://doris.apache.org/zh-CN 也找不到中文了...

**Comment by rohitrs1983** [comment]
fixed it. please review PR.
