### ISSUE TITLE
[Feature] Support xxhash function like murmur hash funcion

### ISSUE THREAD

**Issue by HappenLee** [apache/doris#31138]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

![image](https://github.com/apache/doris/assets/10553413/ed16df51-ef6d-4890-9738-c06c9966ed47)

Support xxhash like murmur hash to speed up hash compute

![image](https://github.com/apache/doris/assets/10553413/e8eefa71-84eb-4261-b5bf-cb959ccbd900)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by sjyango** [comment]
I will try！
