### ISSUE TITLE
[Feature] Support Array Type In Function and equal function

### ISSUE THREAD

**Issue by HappenLee** [apache/doris#31157]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

support two opeartor of array function
1. select [1,2] in ([1,2],[3,4])
2. select [1,2] = [1,1];

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by koarz** [comment]
i want try

**Comment by taptao** [comment]
i want pick this

**Comment by nanfeng1999** [comment]
i want try

**Comment by amorynan** [comment]
@taptao please make a proposal for it , and simple design wiki can u given ?
