### ISSUE TITLE
[Feature] Support DDL/DML on external catalog

### ISSUE THREAD

**Issue by morningman** [apache/doris#31442]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Before 2.0, Doris can only support query data from external catalog such as Hive, Hudi, etc.
Now we would like to support DDL/DML feature on external catalog

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
i want try

**Comment by lexluo09** [comment]
I'd like to try

**Comment by morningman** [comment]
We are working on the framework of this feature.
After the framework is stable, we'd like to invite more contributor to participate in developement.

**Comment by wsjz** [comment]
https://github.com/apache/doris/pull/32274
