### ISSUE TITLE
[Enhancement] do not log fatal in doris_main.cpp 

### ISSUE THREAD

**Issue by dataroaring** [apache/doris#31441]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Log(FATAL) introduces a core dump, which is confusing for users. We should print error msg and exit without a core dump.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tech-Circle-48** [comment]
please assigned to me

**Comment by 133tosakarin** [comment]
I will try
