### ISSUE TITLE
[Bug] cast constant to string get wrong result

### ISSUE THREAD

**Issue by zxealous** [apache/doris#31514]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.4 && 2.0.5

### What's Wrong?

case:
 set experimental_enable_nereids_planner = true;
select cast(cast(10000.00001 as double) as string)

master  has right result:
```
MySQL [(none)]> select cast(cast(10000.00001 as double) as string);
+-------------------------------------------+
| cast(cast(10000.00001 as DOUBLE) as TEXT) |
+-------------------------------------------+
| 10000.00001                               |
+-------------------------------------------+
1 row in set (0.010 sec)
```

2.0.4 && 2.0.5 :
```
MySQL [(none)]> select cast(cast(10000.00001 as double) as string);
+---------------------------------------------+
| cast(cast(10000.00001 as DOUBLE) as STRING) |
+---------------------------------------------+
| 10000                                       |
+---------------------------------------------+
1 row in set (0.017 sec)
```

### What You Expected?

work well

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by MRYOG** [comment]
the same as 2.0.2.1 , 
![image](https://github.com/apache/doris/assets/10381662/6e912ad2-e3ad-49e6-a18e-98c552110f2a)

**Comment by cambyzju** [comment]
1. for experimental_enable_nereids_planner = false
the problem is include from: https://github.com/apache/doris/pull/20709

2. for experimental_enable_nereids_planner = true
(TODO: some pr forget to cherry pick to 2.0)
