### ISSUE TITLE
[Bug] function DATE_FORMAT get wrong result

### ISSUE THREAD

**Issue by zxealous** [apache/doris#31524]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.5 && master

### What's Wrong?

case:
SELECT DATE_FORMAT('1999-01-01', '%X %V')

wrong result:
```
MySQL [test]> SELECT DATE_FORMAT('1999-01-01', '%X %V');
+-----------------------------------------------------------+
| date_format(cast('1999-01-01' as DATETIMEV2(0)), '%X %V') |
+-----------------------------------------------------------+
| 1999 01                                                   |
+-----------------------------------------------------------+
1 row in set (0.012 sec)
```

mysql right result:
```
mysql> SELECT DATE_FORMAT('1999-01-01', '%X %V');
+------------------------------------+
| DATE_FORMAT('1999-01-01', '%X %V') |
+------------------------------------+
| 1998 52                            |
+------------------------------------+
1 row in set (0.00 sec)
```

### What You Expected?

result same as mysql

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by felixwluo** [comment]
I'll fix it.

**Comment by zxealous** [comment]
> I'll fix it.

thanks
