### ISSUE TITLE
[Bug] 在 DUPLICATE KEY 模型下，SQL ERROR: select [key字段] from [table] where [正则表达式] order by [key字段] 

### ISSUE THREAD

**Issue by huangmaoxian** [apache/doris#31676]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Version : doris-2.0.3-rc06

### What's Wrong?

**-- 建表**
CREATE TABLE `regexp_test` (
  `a` varchar(*) NULL,
  `b` varchar(*) NULL,
  `c` varchar(*) NULL,
  `d` bigint(20) NULL,
  `e` DECIMAL(20, 8) NULL
) ENGINE=OLAP
DUPLICATE KEY(`a`, `b`)
COMMENT 'OLAP'
DISTRIBUTED BY HASH(`a`, `b`) BUCKETS 10
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"is_being_synced" = "false",
"storage_format" = "V2",
"light_schema_change" = "true",
"disable_auto_compaction" = "false",
"enable_single_replica_compaction" = "false"
);

**-- 查询报错**
SELECT 
	a,
	b 
FROM
	`regexp_test` 
WHERE
	c REGEXP '(^|)(预计sku)($|)' 
ORDER BY
	a ASC;
**-- 报错**
[CANCELLED][INTERNAL_ERROR]UDF ERROR: hs_compile regex pattern error

	0#  doris::RuntimeState::set_process_status(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) at /root/src/doris-2.0/be/src/common/status.h:354
	1#  doris::FunctionContext::set_error(char const*) at /var/local/ldb-toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/basic_string.h:187
	2#  doris::vectorized::FunctionLikeBase::hs_pr
	

**-- 查询正常**
SELECT 
	a,
	b 
FROM
	`regexp_test` 
WHERE
	c REGEXP '(^|)(预计sku)($|)';

### What You Expected?

SELECT 
	a,
	b 
FROM
	`regexp_test` 
WHERE
	c REGEXP '(^|)(预计sku)($|)' 
ORDER BY
	a ASC;
	
该语句可正常执行

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AcKing-Sam** [comment]
Hi, I have made a small test for your case. It seems that it works well.
```mysql
create table duptest (
	a varchar(5) null,
	b varchar(5) null,
	c varchar(20) null,
  d bigint(20) null,
)
ENGINE=OLAP
DUPLICATE KEY(a, b)
COMMENT 'OLAP'
DISTRIBUTED BY HASH(a, b) BUCKETS 10
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"is_being_synced" = "false",
"storage_format" = "V2",
"light_schema_change" = "true",
"disable_auto_compaction" = "false",
"enable_single_replica_compaction" = "false"
);

insert into duptest values('aa', 'aa', 'aaabb', 25);
insert into duptest values('bb', 'bb', 'caabb', 31);
insert into duptest values('aa', 'ab', 'bbabb', 26);
insert into duptest values('ab', 'aa', 'babb', 30);

SELECT a, b FROM duptest
WHERE c REGEXP '^b'
ORDER BY a ASC;
```

And the result:
```shell
mysql> select * from duptest;
+------+------+-------+------+
| a    | b    | c     | d    |
+------+------+-------+------+
| aa   | aa   | aaabb |   25 |
| bb   | bb   | caabb |   31 |
| aa   | ab   | bbabb |   26 |
| ab   | aa   | babb  |   30 |
+------+------+-------+------+
4 rows in set (0.02 sec)

mysql> SELECT a, b FROM duptest
    -> WHERE c REGEXP '^b'
    -> ORDER BY a ASC;
+------+------+
| a    | b    |
+------+------+
| aa   | ab   |
| ab   | aa   |
+------+------+
2 rows in set (0.02 sec)
```
