### ISSUE TITLE
[Feature] support agg function group_array_intersect like clickhouse `groupArrayIntersect`

### ISSUE THREAD

**Issue by HappenLee** [apache/doris#31737]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

clickhouse impl: https://github.com/ClickHouse/ClickHouse/pull/59598

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by superdiaodiao** [comment]
I want to try, please assign to me~
