### ISSUE TITLE
[Query] Questions about hash distribution prunner.

### ISSUE THREAD

**Issue by morningman** [apache/doris#3185]
**Describe the bug**
1. First to create a table with distribution key type `DATE`
```
create table tbl5 (k1 date, k2 int) distributed by hash(k1) buckets 3;
```

2. Insert one row
```
insert into tbl5 values("2020-03-20", 1);
```

3. Query like
```
select * from tbl5 where k1 = "2020-03-20";
```
This query will hit only bucket, which is expected.

And the following query:
```
select * from tbl5 where k1 = "2020-03-20 10:12:35";
```
Will also hit one bucket. Although it seems not results in wrong result.
But does it make sense?

**Comment by morrySnow** [comment]
nereids will hit all three buckets
