### ISSUE TITLE
[Bug] FE Web UI auto logout when refresh browser page

### ISSUE THREAD

**Issue by Lif0820** [apache/doris#32012]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.5

### What's Wrong?

1. login fe web ui, such as 10.10.10.1:8030 with root user
2. refresh the page
3. the browser redirect to login page again

### What You Expected?

fix it

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xumingxiang** [comment]
doris2.1 遇到同样bug

**Comment by tangbinyeer** [comment]
Has it been fixed?

**Comment by wenwj0** [comment]
#32091 Maybe Fixed by this PR.
