### ISSUE TITLE
[Bug] the database cannot be choosed in playground after upgrade to v2.1.0

### ISSUE THREAD

**Issue by WhatAKitty** [apache/doris#32025]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

v2.1.0

### What's Wrong?

the playground is bad and cannot execute any sql.
![20240309220849](https://github.com/apache/doris/assets/4178729/53d8c7bd-7fd8-40e3-a262-27c39136511f)

### What You Expected?

Can execute sql in playground and show database or table information.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xumingxiang** [comment]
遇到同样问题

**Comment by soopsle** [comment]
me too.  
but use navicat ok.

**Comment by jeffreys-cat** [comment]
Thanks for the feedback, I'll handle it.

**Comment by jeffreys-cat** [comment]
Thanks for the feedback, I'll handle it.

**Comment by H-TWINKLE** [comment]
me,too
