### ISSUE TITLE
[Bug] jdbc catalog table contains keywords 'desc'，query error

### ISSUE THREAD

**Issue by VanYue** [apache/doris#32187]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris 2.0.4

### What's Wrong?

1、MySQL 表
CREATE TABLE qwzs.`qwzs_account_option_log` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `account_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '账号id',
  `type` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '类型',
  `quit_reason` int(10) NOT NULL DEFAULT '0' COMMENT '退出原因',
  `create_time` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '记录时间',
  `relate_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '关联id',
  `desc` varchar(100) NOT NULL DEFAULT '' COMMENT '描述',
  PRIMARY KEY (`id`),
  KEY `idx_account_id` (`account_id`)
) ENGINE=InnoDB AUTO_INCREMENT=24738 DEFAULT CHARSET=utf8mb4 COMMENT='账号操作明细'

2、Doris Catalog查询报错
select * FROM jdbc_mysql.qwzs.`qwzs_account_option_log` where id > 7000000 and `desc` like '%涉嫌%'
![bug](https://github.com/apache/doris/assets/24541620/41356d3a-9b1b-449d-9998-c9df8587585f)

### What You Expected?

Query Sucess

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zy-kkk** [comment]
#29854 fix it
