### ISSUE TITLE
[Enhancement] partition name of partitions should be same

### ISSUE THREAD

**Issue by dataroaring** [apache/doris#32319]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

https://github.com/apache/doris/discussions/32183

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by cjj2010** [comment]
i will try

**Comment by zclllyybb** [comment]
maybe we should close this issue since changes on this may cause much instability
