### ISSUE TITLE
[Enhancement] when partition column is datetime, date should work in create table command

### ISSUE THREAD

**Issue by dataroaring** [apache/doris#32323]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

CREATE TABLE t_user
(
    id int,
    name string,
    pdate DATETIME
)
PARTITION BY RANGE(`pdate`)(
PARTITION pd20230418 VALUES less than ("2023-04-20")
)
DISTRIBUTED BY HASH(`id`) BUCKETS 1;

ERROR 1105 (HY000): errCode = 2, detailMessage = Invalid range value format： errCode = 2, detailMessage = date literal [2023-04-20] is invalid: errCode = 2, detailMessage = Invalid datetime value: 2023-04-20

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xiedeyantu** [comment]
I want to try it.
