### ISSUE TITLE
[Bug] packet for query is too large. Try adjusting the 'max_allowed_packet' variable on the server

### ISSUE THREAD

**Issue by hl10105210** [apache/doris#32330]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.2

### What's Wrong?

I have executed "set global max_allowed_packet = 1073741824", but inserting more than 4M of data still reports the error "packet for query is too large. Try adjusting the 'max_allowed_packet' variable on the server".

### What You Expected?

How can I solve this problem? I need to insert data in bulk.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zkPMP** [comment]
May I ask how it was resolved? I encountered the same problem
