### ISSUE TITLE
[Bug] Executing WHERE `value_col` REGEXP '.*' statement returns incorrect result

### ISSUE THREAD

**Issue by sjyango** [apache/doris#32354]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris master

### What's Wrong?

- doris:
SELECT * FROM `test_like_predicate_with_concat` WHERE `value_col` REGEXP '.*' ORDER BY `id`;
Empty set (0.17 sec)

- mysql:
SELECT * FROM `test_like_predicate_with_concat` WHERE `value_col` REGEXP '.*' ORDER BY `id`;
+------+------------------------------------------+------------------------------------+
| id   | value_col                                | pattern_col                        |
+------+------------------------------------------+------------------------------------+
|    0 | prefix0_infix0_suffix0                   | prefix0                            |
|    1 | %prefix1_infix1_suffix1                  | prefix1                            |
|    2 | prefix2_$infix2$_suffix2                 | infix2                             |
|    3 | prefix3_^infix3_suffix3                  | infix3                             |
|    4 | $$$prefix4_$$$infix4%%%_^^suffix4        | suffix4                            |
|    5 | prefix5%%$$$__infix5$_^^^%%$$suffix5     | suffix5                            |
|    6 | prefix6__^^_%%%__infix6_%^suffix6%       | prefix6__^^_%%%__infix6_%^suffix6% |
|    7 | %%%^^^$$$prefix7_infix7_suffix7%%%^^^$$$ | prefix7_infix7_suffix7             |
|    8 | prefix8_^^%%%infix8%%$$^^___suffix8      |                                    |
|    9 | prefix9$$%%%^^__infix9__&&%%$$suffix9    | NULL                               |
+------+------------------------------------------+------------------------------------+
10 rows in set (0.001 sec)

### What You Expected?

doris gets same result as mysql

### How to Reproduce?

CREATE TABLE IF NOT EXISTS `test_like_predicate_with_concat` (
        `id` int,
        `value_col` string,
        `pattern_col` string
        ) ENGINE=OLAP
        DISTRIBUTED BY HASH(`id`) BUCKETS 4
        PROPERTIES (
        "replication_allocation" = "tag.location.default: 1"
        );

INSERT INTO `test_like_predicate_with_concat` VALUES 
            (0, 'prefix0_infix0_suffix0', 'prefix0'),
            (1, '%prefix1_infix1_suffix1', 'prefix1'),
            (2, 'prefix2_$infix2$_suffix2', 'infix2'),
            (3, 'prefix3_^infix3_suffix3', 'infix3'),
            (4, '$$$prefix4_$$$infix4%%%_^^suffix4', 'suffix4'),
            (5, 'prefix5%%$$$__infix5$_^^^%%$$suffix5', 'suffix5'),
            (6, 'prefix6__^^_%%%__infix6_%^suffix6%', 'prefix6__^^_%%%__infix6_%^suffix6%'),
            (7, '%%%^^^$$$prefix7_infix7_suffix7%%%^^^$$$', 'prefix7_infix7_suffix7'),
            (8, 'prefix8_^^%%%infix8%%$$^^___suffix8', ''),
            (9, 'prefix9$$%%%^^__infix9__&&%%$$suffix9', NULL);

SELECT * FROM `test_like_predicate_with_concat` WHERE `value_col` REGEXP '.*' ORDER BY `id`;

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AcKing-Sam** [comment]
@yongjinhou Hi, could you please assign this issue to me?
I made tests on `master` and this bug still exists.

Reproduce:
```mysql
CREATE TABLE regtest (
id int,
value_col string,
pattern_col string
) 
ENGINE=OLAP
DISTRIBUTED BY HASH(id) BUCKETS 4
PROPERTIES (
"replication_allocation" = "tag.location.default: 1"
);

INSERT INTO regtest VALUES
(0, 'prefix0_infix0_suffix0', 'prefix0'),
(1, '%prefix1_infix1_suffix1', 'prefix1'),
(2, 'prefix2_$infix2$suffix2', 'infix2'),
(3, 'prefix3^infix3_suffix3', 'infix3'),
(4, '$$$prefix4_$$$infix4%%%^^suffix4', 'suffix4'),
(5, 'prefix5%%$$$__infix5$^^^%%$$suffix5', 'suffix5'),
(6, 'prefix6__^^%%%infix6%^suffix6%', 'prefix6_^^%%%infix6%^suffix6%'),
(7, '%%%^^^$$$prefix7_infix7_suffix7%%%^^^$$$', 'prefix7_infix7_suffix7'),
(8, 'prefix8^^%%%infix8%%$$^^___suffix8', ''),
(9, 'prefix9$$%%%^^infix9&&%%$$suffix9', NULL);
```

Results:
```mysql
mysql> select * from regtest;
+------+------------------------------------------+-------------------------------+
| id   | value_col                                | pattern_col                   |
+------+------------------------------------------+-------------------------------+
|    1 | %prefix1_infix1_suffix1                  | prefix1                       |
|    7 | %%%^^^$$$prefix7_infix7_suffix7%%%^^^$$$ | prefix7_infix7_suffix7        |
|    0 | prefix0_infix0_suffix0                   | prefix0                       |
|    6 | prefix6__^^%%%infix6%^suffix6%           | prefix6_^^%%%infix6%^suffix6% |
|    2 | prefix2_$infix2$suffix2                  | infix2                        |
|    4 | $$$prefix4_$$$infix4%%%^^suffix4         | suffix4                       |
|    8 | prefix8^^%%%infix8%%$$^^___suffix8       |                               |
|    3 | prefix3^infix3_suffix3                   | infix3                        |
|    5 | prefix5%%$$$__infix5$^^^%%$$suffix5      | suffix5                       |
|    9 | prefix9$$%%%^^infix9&&%%$$suffix9        | NULL                          |
+------+------------------------------------------+-------------------------------+
10 rows in set (0.04 sec)

mysql> SELECT * FROM regtest WHERE value_col REGEXP '.*' ORDER BY id;
Empty set (0.02 sec)

mysql> SELECT * FROM regtest WHERE value_col LIKE '%' ORDER BY id;
+------+------------------------------------------+-------------------------------+
| id   | value_col                                | pattern_col                   |
+------+------------------------------------------+-------------------------------+
|    0 | prefix0_infix0_suffix0                   | prefix0                       |
|    1 | %prefix1_infix1_suffix1                  | prefix1                       |
|    2 | prefix2_$infix2$suffix2                  | infix2                        |
|    3 | prefix3^infix3_suffix3                   | infix3                        |
|    4 | $$$prefix4_$$$infix4%%%^^suffix4         | suffix4                       |
|    5 | prefix5%%$$$__infix5$^^^%%$$suffix5      | suffix5                       |
|    6 | prefix6__^^%%%infix6%^suffix6%           | prefix6_^^%%%infix6%^suffix6% |
|    7 | %%%^^^$$$prefix7_infix7_suffix7%%%^^^$$$ | prefix7_infix7_suffix7        |
|    8 | prefix8^^%%%infix8%%$$^^___suffix8       |                               |
|    9 | prefix9$$%%%^^infix9&&%%$$suffix9        | NULL                          |
+------+------------------------------------------+-------------------------------+
10 rows in set (0.02 sec)

```
