### ISSUE TITLE
[Enhancement] support add partitions in batch

### ISSUE THREAD

**Issue by dataroaring** [apache/doris#32524]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

ALTER TABLE db.table ADD PARTITIONS FROM() TO()  INTERVAL num [UNIT]
e.g.
ALTER TABLE db.table ADD PARTITIONS FROM(1) TO(10)  INTERVAL 1
e.g.
ALTER TABLE db.table ADD PARTITIONS FROM("2024-01") TO("2024-12-31")  INTERVAL 1 MONTH

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Xuxiaotuan** [comment]
I want to try

**Comment by Toms1999** [comment]
Please assign it to me

**Comment by felixwluo** [comment]
pick
