### ISSUE TITLE
[Enhancement] Add more regression tests for s3 table valued function

### ISSUE THREAD

**Issue by sollhui** [apache/doris#32576]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

At present, s3 table valued function lacks some test cases, and the following additional cases need to be added:

- [ ] line_delimiter: \t
- [ ] compress_type: UNKNOWN/DEFLATE
- [ ] path_partition_keys: string | invalid value

For specific formats, there are dedicated attributes:
CSV format:

- [ ] trim_double_quotes: true | invalid value
- [ ] skip_lines: 1 | invalid value

Json format:

- [ ] read_json_by_line: false | invalid value
- [ ] strip_outer_array: true | invalid value
- [ ] json_root: string | invalid value
- [ ] jsonpaths: string | invalid value
- [ ] num_as_string: true | invalid value
- [ ] fuzzy_parse: true | invalid value

Some tests have been submitted, you can refer: https://github.com/apache/doris/blob/master/regression-test/suites/load_p0/tvf/test_s3_tvf.groovy

If you are not clear about certain attributes, you can refer: https://doris.apache.org/docs/dev/sql-manual/sql-functions/table-functions/s3/

If you are interested in one or more of them, you can reply below and feel free to ask any questions you have.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TangSiyang2001** [comment]
Actually some cases above were covered. I think a more accurate version may be like:

The cases need to be complete:

- [ ]  line_delimiter: \t
- [ ]  compress_type: UNKNOWN/LZO (is not supported by default)/DEFLATE
- [ ]  path_partition_keys: invalid value

For specific formats, there are dedicated attributes:
CSV format:
- [ ]  trim_double_quotes: true | invalid value
- [ ]  skip_lines: 1 | invalid value
- [ ]  read_json_by_line: invalid value
- [ ]  strip_outer_array: invalid value

Json format:
- [ ]  json root: string: | invalid value
- [ ]  jsonpath: string: | invalid value
- [ ]  num_as_string: true | invalid value
- [ ]  fuzzy_parse: true | invalid value

**Comment by HHoflittlefish777** [comment]
Agree with @TangSiyang2001, some test were covered. Test need added were updated.

**Comment by Sigma711** [comment]
I want to try it.
