### ISSUE TITLE
[Enhancement] add information_schema.table_options

### ISSUE THREAD

**Issue by dataroaring** [apache/doris#32572]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Add an internal table under information_schema named table_options, which contains TABLE_NAME, DISTRIBUTE_KEY, DISTRIBUTE_TYPE,BUCKETS_NUM,PARTITION_NUM,PROPERTIES

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
i want try

**Comment by Vallishp** [comment]
@dataroaring @liugddx  is this feature in progress? if not please assign to me. i can take it up. thanks.

**Comment by liugddx** [comment]
> @dataroaring @liugddx is this feature in progress? if not please assign to me. i can take it up. thanks.

you can do

**Comment by Vallishp** [comment]
> > @dataroaring @liugddx is this feature in progress? if not please assign to me. i can take it up. thanks.
> 
> you can do

ok. will work on this. thank you
