### ISSUE TITLE
[Bug] when backup job cancelled, it will retain snapshotinfos and backupmeta which take a lot of memory

### ISSUE THREAD

**Issue by nextdreamblue** [apache/doris#32645]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master/2.0/1.2

### What's Wrong?

![企业微信截图_d49e0a48-3b4a-4db2-8f92-a7b7901938ec](https://github.com/apache/doris/assets/22926391/b496358c-1641-4e63-a2aa-a999722fa377)

备份任务，因为中间出错导致任务cancel，但是任务相关的snapshotinfos和backupmeta两个变量的信息没有释放，导致内存占用较高，最终导致fe oom。

### What You Expected?

像任务正常结束一样，释放掉相关变量，释放内存占用

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wanghuan2054** [comment]
ok
