### ISSUE TITLE
Enhancement of round based function 

### ISSUE THREAD

**Issue by zhiqiang-hhhh** [apache/doris#32755]
### Discussed in https://github.com/apache/doris/discussions/32086

We need to make round based functions support using column as its scale argument.

- [x] Truncate 
- [x] Round
- [x] Floor
- [x] Ceil

**Comment by zhiqiang-hhhh** [comment]
truncate: https://github.com/apache/doris/pull/32746

**Comment by superdiaodiao** [comment]
May I ask the other three enhancement tasks assigned to anyone? If not, could you assign to me?

**Comment by zhiqiang-hhhh** [comment]
> May I ask the other three enhancement tasks assigned to anyone? If not, could you assign to me?

@superdiaodiao thanks for your attention, they are pending, and they are yours.

Just to let you know, the task is not difficult, but need much explore work in mysql.

Specifically, we need to make sure we have same behaviour with mysql, for example, in function truncate, when using literal as scale argument, its behaviour is different from using column as scale argument. I do not test the others in mysql, but I think they may have same problem.

Tips for implementation:
1. The pression of decimal should not change.
2. The scale of decimal may depend on the specific situation ( need to be same with mysql)
3. Need BEUT & regression test
4. docs update in https://github.com/apache/doris-website

Thanks your attention again, enjoy the process!

**Comment by superdiaodiao** [comment]
> @superdiaodiao thanks for your attention, they are pending, and they are yours.
> 
> Just to let you know, the task is not difficult, but need much explore work in mysql.
> 
> Specifically, we need to make sure we have same behaviour with mysql, for example, in function truncate, when using literal as scale argument, its behaviour is different from using column as scale argument. I do not test the others in mysql, but I think they may have same problem.
> 
> Tips for implementation:
> 1. The pression of decimal should not change.
> 2. The scale of decimal may depend on the specific situation ( need to be same with mysql)
> 3. Need BEUT & regression test
> 4. docs update in https://github.com/apache/doris-website
> 
> Thanks your attention again, enjoy the process!

Alright, thank you very much~~~
I will try my best and may need your review in the future PR.
