### ISSUE TITLE
[Bug]    更新模型中 array<string> 类型的字段 ，当给这个字段建立倒排索引，整个数据库直接崩溃了，现在数据库启动不了了

### ISSUE THREAD

**Issue by gospider007** [apache/doris#32802]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.1.0

### What's Wrong?

更新模型中 array<string> 类型的字段 ，当给这个字段建立倒排索引，整个数据库直接崩溃了，现在数据库启动不了了
我第一次尝试 doris , 用了两天，这两天时间里面，doris 崩溃了好几次，第一次是给更新模型中 创建 array<strcut> 类型字段，然后插入数据，还没插入几条，be 就直接崩溃，后面我删除了这个类型的字段后才可以批量插入，批量插入过程中，be 居然又崩溃了一次，我估计是频率太高了。 后面创建倒排索引又崩溃了，这下be 直接就完全启动不了了，我估计要删除整个数据目录才能启动了。
太难了。。。

### What You Expected?

要是不可以建立索引，能不能 再执行sql 的时候直接报错，这样要是在生产环境简直是灾难

### How to Reproduce?

更新模型中 array<string> 类型的字段 ，给这个字段建立倒排索引

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Lif0820** [comment]
看历史issue，因为个别语法就导致be crash这种问题很多，有点不敢上线

**Comment by amorynan** [comment]
can u give me some be out? u can join me in wechat : amorynan

**Comment by Mrkuhuo** [comment]
我也碰到了，array<string>类型的字段，写入了string字符串，直接dead给你看

**Comment by amorynan** [comment]
目前array 所以创建倒排索引还有点问题， 没有正式发布这个功能的 等内部调试完成 会随着版本发布

**Comment by amorynan** [comment]
> 我也碰到了，array类型的字段，写入了string字符串，直接dead给你看

请问一下 你们什么场景在用array 呢？

**Comment by gospider007** [comment]
> > 我也咳嗽了，数组类型的字段，写入了字符串字符串，直接死给你看
> 
> 请问一下你们都有哪些场景在用数组呢？



> > 我也咳嗽了，数组类型的字段，写入了字符串字符串，直接死给你看
> 
> 请问一下你们都有哪些场景在用数组呢？

倒排索引从es 迁移过来，之前的业务字段的值是数组，类似商品的多个标签和多个属性，需要对商品的标签和属性进行聚合， 还有模糊搜索。 主要是想从es 无缝过渡到doris 直接替换掉，es 是支持对数组进行聚合和模糊搜索的，还有自定义分词doris 好像也不支持

**Comment by amorynan** [comment]
> > > 我也咳嗽了，数组类型的字段，写入了字符串字符串，直接死给你看
> > 
> > 
> > 请问一下你们都有哪些场景在用数组呢？
> 
> > > 我也咳嗽了，数组类型的字段，写入了字符串字符串，直接死给你看
> > 
> > 
> > 请问一下你们都有哪些场景在用数组呢？
> 
> 倒排索引从es 迁移过来，之前的业务字段的值是数组，类似商品的多个标签和多个属性，需要对商品的标签和属性进行聚合， 还有模糊搜索。 主要是想从es 无缝过渡到doris 直接替换掉，es 是支持对数组进行聚合和模糊搜索的，还有自定义分词doris 好像也不支持

噢 对数组进行聚合和模糊搜索的 还有自定义分词doris 这两个我们这个季度已经在做了， 详细可以加wx ： amorynan

**Comment by alonefly1110** [comment]
我是给日期字段加了倒排索引然后数据库直接崩溃了，现在启动不了了
![image](https://github.com/apache/doris/assets/26450856/42e00d97-b4ab-4d25-9d00-0f278ca165e4)
这是报错信息

**Comment by gospider007** [comment]
2.1.4 版本解决了
