### ISSUE TITLE
[Enhancement](doris-future) Support strcmp function

### ISSUE THREAD

**Issue by zclllyybb** [apache/doris#33093]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

mysql support [strcmp](https://dev.mysql.com/doc/refman/8.3/en/string-comparison-functions.html#function_strcmp) function. we need to support it too.

### Solution

To support a function, we need:
1. function implementation and registration in BE
2. function signature and visitor for nereids planner in FE
3. function signature in doris_builtin_functions.py

you can reference like https://github.com/apache/doris/pull/33005/files

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by koarz** [comment]
i want try

**Comment by wyxxxcat** [comment]
I want try

**Comment by xiedeyantu** [comment]
I want to try it
