### ISSUE TITLE
[Bug] streamload分隔符问题：文件中字段以\t分割，单个字段中可能有“,”，streamload异常

### ISSUE THREAD

**Issue by Dong-GuoSheng** [apache/doris#33109]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.1.0版本发现（之前的版本未验证）

### What's Wrong?

文件内容以tab（\t）分割，数据中（单个字段）可能含有“,”，使用streamload指定分隔符（\t）时，仍然报列数不匹配的错误。
建表语句为：
create table test.t001(
a varchar(16),
b varchar(16),
c String)
DUPLICATE KEY (a,b)
DISTRIBUTED BY HASH(a) BUCKET 1;

文件内容：a\tb\tc,d
使用streamload导入数据，指定列名及分隔符:-H "column_sepatator=\t" -H "columns=a,b,c"
本次导入报错：
Reason: actual column number in csv file is less than schema column number. actual number: 3 schema column number: 105;line delimiter:[],column sepatator:[ ],result values:[a, b, c,d ].src line [a b c,d]

### What You Expected?

no error.

### How to Reproduce?

如上，建表语句和文件内容附上

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liaoxin01** [comment]
Using colons for http header.
-H "column_sepatator:\\t" -H "columns: a,b,c"
