### ISSUE TITLE
[Bug] ./bin/start_be.sh --daemon ,be无法启动

### ISSUE THREAD

**Issue by chengleig** [apache/doris#33107]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.1.0

### What's Wrong?

https://doris.apache.org/zh-CN/docs/get-starting/quick-start根据此文档快速开始的
./bin/start_be.sh --daemon 启动之后没有错误日志，就三行
start time: Mon Apr  1 16:20:22 CST 2024
INFO: java_cmd /usr/lib/jvm/java-1.8.0-openjdk/bin/java
INFO: jdk_version 8

### What You Expected?

期望可以将be启动起来

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wyxxxcat** [comment]
Replace the JAVA_HOME in the output/be/conf/be.conf file with the version of Java17

**Comment by wyxxxcat** [comment]
https://doris-thirdparty-1308700295.cos.ap-beijing.myqcloud.com/tools/openjdk-17.0.2_linux-x64_bin.tar.gz

**Comment by chengleig** [comment]
> Replace the JAVA_HOME in the output/be/conf/be.conf file with the version of Java17

好的，我试下

**Comment by chengleig** [comment]
start time: Mon Apr  1 16:41:23 CST 2024
INFO: java_cmd /usr/lib/jvm/java-1.8.0-openjdk/bin/java
INFO: jdk_version 8
start time: Mon Apr  1 18:32:43 CST 2024
INFO: java_cmd /opt/jdk-17.0.2/bin/java
INFO: jdk_version 17
还是不行，打印了jdk17的日志，只有三行

**Comment by wyxxxcat** [comment]
> start time: Mon Apr 1 16:41:23 CST 2024 INFO: java_cmd /usr/lib/jvm/java-1.8.0-openjdk/bin/java INFO: jdk_version 8 start time: Mon Apr 1 18:32:43 CST 2024 INFO: java_cmd /opt/jdk-17.0.2/bin/java INFO: jdk_version 17 还是不行，打印了jdk17的日志，只有三行
add my wechat yxwyx0502 Let's talk about it
