### ISSUE TITLE
[Bug] days_diff() date judgment not accurate to seconds 

### ISSUE THREAD

**Issue by HerioChen** [apache/doris#33299]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.1.0, 2.1.1

### What's Wrong?

Use days_diff() to calculate the number of days between the end date and the start date, but the date judgment is not accurate to the second.
mysql> select days_diff('2020-12-25 22:00:00','2020-12-24 22:00:00');
+------------------------------------------------------------+
| days_diff('2020-12-25 22:00:00', '2020-12-24 22:00:00') |
+------------------------------------------------------------+
|                                                                                       1 |
+------------------------------------------------------------+

mysql> select days_diff('2020-12-25 22:00:00','2020-12-24 22:00:01');
+------------------------------------------------------------+
| days_diff('2020-12-24 22:00:01', '2020-12-25 22:00:00') |
+------------------------------------------------------------+
|                                                                                       1 |
+------------------------------------------------------------+

### What You Expected?

mysql> select days_diff('2020-12-25 22:00:00','2020-12-24 22:00:00');
+------------------------------------------------------------+
| days_diff('2020-12-25 22:00:00', '2020-12-24 22:00:00') |
+------------------------------------------------------------+
|                                                                                       1 |
+------------------------------------------------------------+

mysql> select days_diff('2020-12-25 22:00:00','2020-12-24 22:00:01');
+------------------------------------------------------------+
| days_diff('2020-12-24 22:00:01', '2020-12-25 22:00:00') |
+------------------------------------------------------------+
|                                                                                       0 |
+------------------------------------------------------------+

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by felixwluo** [comment]
let me look

**Comment by felixwluo** [comment]
I'll fix it

**Comment by HappenLee** [comment]
The result same as mysql sql:`SELECT DATEDIFF('2020-12-25 22:00:01', '2020-12-24 22:00:01') AS days;` not a bug

**Comment by HerioChen** [comment]
![datediff](https://github.com/apache/doris/assets/13653297/10ce7f75-3d19-4c96-986e-8d212e0f52cb)
![days_diff](https://github.com/apache/doris/assets/13653297/9c4d8e4c-d4d1-4b95-ba1a-3c9d938ed2ff)
However, I have reviewed the descriptions and examples of the official documentation for the days_diff and datediff functions, and found that their calculation accuracy is different.
