### ISSUE TITLE
Can we update BRPC to newer version for prometheus support?

### ISSUE THREAD

**Issue by vagetablechicken** [apache/doris#3343]
brpc 0.9.5 doesn't support '/metrics' to get bvars. And the '/vars' graph is low accuracy, and may lost the real peak.

https://github.com/apache/incubator-brpc/commit/3becc72864e748774f13e4347f98b30585664ea4

**Comment by kangkaisen** [comment]
I think we could update BRPC version, but we need strict test firstly. @vagetablechicken Are you willing to do this work?

**Comment by vagetablechicken** [comment]
> I think we could update BRPC version, but we need strict test firstly. @vagetablechicken Are you willing to do this work?

OK, we'll test it on our test & product envs.
