### ISSUE TITLE
[Feature]  有bitmap_from_base64函数为什么没有hll等其他sketche的转换函数？

### ISSUE THREAD

**Issue by lukoou3** [apache/doris#33594]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

有bitmap_from_base64函数为什么没有hll等其他sketche的转换函数?

我想要直接写入hll类型，而不是使用HLL_HASH函数转换通过明细导入

我需要直接写入hll等聚合函数中间状态类型，就类似clickhouse的AggregateFunction类型支持写入任何聚合函数的中间聚合状态，只需要写入的字节数组符合对应聚合函数序列化格式就能直接写入。

### Use case

通过HLL_HASH函数导入hll类型，原始导入数据太多，直接导入hll类型导入数据会少很多。

打算把数据从druid和clickhouse迁移到doris，发现doris不是能直接写入所有的聚合函数类型。

### Related issues

Is there currently another issue associated with this? no

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by superdiaodiao** [comment]
Hey, there~
hll_from_base64(), hll_to_base64() is on the way:
https://github.com/apache/doris/pull/32089

**Comment by lukoou3** [comment]
ok.
I hope that QUANTILE-STATE can also implement a similar function for counting commonly used quantiles
