### ISSUE TITLE
jdbc catalog 查询问题

### ISSUE THREAD

**Issue by smileyboy2019** [apache/doris#33615]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.6

### What's Wrong?

org.jkiss.dbeaver.model.sql.DBSQLException: SQL 错误 [1105] [HY000]: errCode = 2, detailMessage = Unexpected exception: java.util.UnknownFormatConversionException: Conversion = '.'

### What You Expected?

jdbc 版本没有测试，有时候可以获取元数据，过一会就不行，不是很稳定，数据不能查询

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by cjj2010** [comment]
Please provide the logs of FE

**Comment by zy-kkk** [comment]
This is an issue where source errors are not returned correctly, this PR https://github.com/apache/doris/pull/40931 has fixed it
