### ISSUE TITLE
[Bug] Doris1.2 `select round(2.5)` result is 2

### ISSUE THREAD

**Issue by lordk911** [apache/doris#33676]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.7.1 and 1.2.8

### What's Wrong?

ref to doc https://doris.apache.org/docs/1.2/sql-manual/sql-functions/math-functions/round/

`select round(2.5);` should return 3 , but actually 2

### What You Expected?

same as mysql behavior return 3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by felixwluo** [comment]
I will fix

**Comment by felixwluo** [comment]
set round_precise_decimalv2_value=true;
MySQL [(none)]> select round(2.5);
+------------+
| round(2.5) |
+------------+
|          3 |
+------------+
You can set it this way to get the results you want.
