### ISSUE TITLE
Does Stream load support JSON format? Stream load支持JSON格式吗？

### ISSUE THREAD

**Issue by ighack** [apache/doris#3376]
Does Stream load support JSON format?? 
Stream load支持JSON格式吗？
还是说现在只能csv。

**Comment by imay** [comment]
Yes, only csv, json is coming soon

**Comment by morningman** [comment]
This PR will support loading json format data: #3230

**Comment by zy-kkk** [comment]
https://doris.apache.org/zh-CN/docs/dev/data-operate/import/import-way/load-json-format
