### ISSUE TITLE
[Enhancement] In doris 2.x, The Query performance of a three-replic table is 30% lower than that of a single-replic table.

### ISSUE THREAD

**Issue by LuGuangming** [apache/doris#33793]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yiguolei** [comment]
You could set use_fix_replica = 1， then FE will schedule the query to the fixed replica and if the replica is down, it will send query to another replica.
