### ISSUE TITLE
[Enhancement] Add regression case for group commit

### ISSUE THREAD

**Issue by Yukang-Lian** [apache/doris#33942]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Currently, group commit does not support partial update. We need a regression case to test this behavior.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tech-Circle-48** [comment]
please assign to me.thx
