### ISSUE TITLE
[Bug] windows can not pull master code

### ISSUE THREAD

**Issue by 769344359** [apache/doris#34058]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

$ git clone https://github.com/apache/doris
Cloning into 'doris'...
remote: Enumerating objects: 560009, done.
remote: Counting objects: 100% (1993/1993), done.
remote: Compressing objects: 100% (1324/1324), done.
remote: Total 560009 (delta 915), reused 1293 (delta 514), pack-reused 558016
Receiving objects: 100% (560009/560009), 712.11 MiB | 797.00 KiB/s, done.
Resolving deltas: 100% (378226/378226), done.
error: invalid path 'docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/parquet_table/all_partition_types2_parquet_snappy_src/decimal_col=-123456.789012/string_col=string_value/binary_col=62 69 6e 61 72 79 5f 76 61 6c 75 65/date_col=2024-03-21/timestamp_col=2024-03-21 12%3A00%3A00/char_col=char_value1                                       /varchar_col=varchar_value1/000000_0'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

### What You Expected?

git pull success in windows 10

### How to Reproduce?

in winodws 10 , run with git pull

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by superdiaodiao** [comment]
fixed on this PR
https://github.com/apache/doris/pull/34026
