### ISSUE TITLE
[Bug] doris稳定复现BE内存泄露

### ISSUE THREAD

**Issue by 28764116** [apache/doris#34164]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

apache-doris-2.1.0-bin-x64

### What's Wrong?

doris be 内存泄露：在限定最大内存使用的情况下，大内存sql查询出现内存泄露的情况。

### What You Expected?

目标：解决在出现无法执行的sql报错后，释放其产生的be内存

### How to Reproduce?

复现方式参考文档：https://naakjd3cylu.feishu.cn/docx/Fs5CdvVCpockz7xxkKWcOlKGntf

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yiguolei** [comment]
Try 2.1.2 it fix some memory leak problems.

**Comment by SoyMeng** [comment]
i will follow it

**Comment by 28764116** [comment]
确定是2.1.0版本的问题，问题已修复在2.1.2版本
