### ISSUE TITLE
[Website] Some problem about the new website.

### ISSUE THREAD

**Issue by morningman** [apache/doris#3419]
The new website is great. But there are some problems:

1. I can't find the `Version` and `Language` select button on Mobile version of the website.
2. The document under `Apache社区(Apache Community)` should not be related to the Doris version. So I suggest placing it alone in the top navigation bar.
3. `Apache Commnity` is typo, should be: `Apache Community`.
4. the icon on webbrowser tag is wrong:
![image](https://user-images.githubusercontent.com/2899462/80558182-036df580-8a0c-11ea-8da8-4a8961362c8f.png)

5. There is no `Makefile` under `docs/`, so need to modify the `build.sh` to remove the `make doc`

6. Why there are 2 `readme.md` under `docs/`

**Comment by hffariel** [comment]
1. Sidebar menu is ok now, but still has an issue related with [vuepress nav bar dropdown issue](https://github.com/vuejs/vuepress/pull/2339)(which could only be fixed by the next vuepress release).
2. Wait to be done
3. Spelling issue has been corrected.
4. Icon has been added to asf-site

**Comment by rinkydevi** [comment]
i can contribute in this issue,can please help me to proceed

**Comment by morningman** [comment]
> i can contribute in this issue,can please help me to proceed

Hi @rinkydevi , thanks for your reply.
However, this issue is very old and we currently have plans to rework the new site, so if you are interested, you can contact me on WeChat(morningman-cmy) to discuss some details.

**Comment by rinkydevi** [comment]
@morningman  thank u for your response,
but i don't currently use WeChat, so if u could provide me another medium that would be wonderful!

**Comment by morningman** [comment]
> rinkydevi

You also contact us via email: dev@doris.apache.org
See how to subscribe: http://doris.incubator.apache.org/community/subscribe-mail-list.html#_1-send-subscription-mail

**Comment by rinkydevi** [comment]
@morningman Thank u so much sir, 
i've sent the mail, and hoping to work and discuss issues under your guidance 😊

**Comment by rinkydevi** [comment]
@morningman thank u so much for this sir,
but when i sent the mail it is showing some kind of error,i will attach the screenshot below
![000](https://user-images.githubusercontent.com/82359874/152666804-c624adac-6487-4bad-8f66-d77524039809.jpg)

**Comment by morningman** [comment]
Sorry I have no idea about this error...
Have you try it again?

And be sure that you have subscribed the dev@doris mail list, or you may not be able to receive our reply.

**Comment by morningman** [comment]
> 

Or do you use any other IM such as Slack or Telegram?

**Comment by rinkydevi** [comment]
@morningman yes sir!
i have telegram:-
https://t.me/rinky_s01

**Comment by morningman** [comment]
hi @rinkydevi , Sorry, we can't use telegram properly in mainland China, can you communicate through Slack?
you can leave your email address so that I can invite you to the ApacheDoris Slack channel

**Comment by rinkydevi** [comment]
my email id is rinkysiwach@gmail.com

**Comment by morningman** [comment]
Invitation has been sent.
Or you can click here to enter: https://join.slack.com/t/apachedoriscommunity/shared_invite/zt-11jb8gesh-7IukzSrdea6mqoG0HB4gZg
