### ISSUE TITLE
[Enhancement] Add some default value function for doris

### ISSUE THREAD

**Issue by Yukang-Lian** [apache/doris#34228]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

1. localtime, localtimestamp
2. now
3. bitmap_empty
4. hll_empty
5. e
6. pi
7. uuid_numeric
8. random

### Solution

Reference #34211 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Z-SWEI** [comment]
I want to try

**Comment by Yukang-Lian** [comment]
> I want to try

Which one do you want to try?

**Comment by Z-SWEI** [comment]
> > I want to try
> 
> Which one do you want to try?

2. now
3. bitmap_empty
7. uuid_numeric
8. random

**Comment by Dragonliu2018** [comment]
I want to try 1 and 6.

**Comment by my-vegetable-has-exploded** [comment]
I'd like to try hll_empty. Thanks.
