### ISSUE TITLE
[Bug] 查询和写入报错（doris-2.1.1-rc05）

### ISSUE THREAD

**Issue by lexluo09** [apache/doris#34308]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-2.1.1-rc05

### What's Wrong?

1、查询报错
[ForkJoinPool.commonPool-worker-8] INFO  [] c.t.tcd.dubhe.client.DubheClient 491 - query doris error
java.sql.SQLException: errCode = 2, detailMessage = (11.154.213.252)[INTERNAL_ERROR]Failed add query to workload group, the workload group is shutdown. host: 11.154.213.252 Query: select id,xxx from bbbb. where dayno in ('2024-04-14','2024-04-23') and id in (xxxx)
2、写入报错
[Caused  by:  com.tencent.tme.tcd.stream.connector.doris.exception.StreamLoadException:  stream  load  error:  [INTERNAL_ERROR]Failed  add  query  to  workload  group,  the  workload  group  is  shutdown.  host:  xxxx]

### What You Expected?

查询和写入正常

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Muzi999** [comment]
> ### Search before asking
> * [x]  I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.
> 
> ### Version
> doris-2.1.1-rc05
> 
> ### What's Wrong?
> 1、查询报错 [ForkJoinPool.commonPool-worker-8] INFO [] c.t.tcd.dubhe.client.DubheClient 491 - query doris error[ForkJoinPool.commonPool-worker-8] INFO [] c.t.tcd.dubhe.client.DubheClient 491 - 查询doris错误 java.sql.SQLException: errCode = 2, detailMessage = (11.154.213.252)[INTERNAL_ERROR]Failed add query to workload group, the workload group is shutdown. host: 11.154.213.252 Query: select id,xxx from bbbb. where dayno in ('2024-04-14','2024-04-23') and id in (xxxx)java.sql.SQLException：errCode = 2，detailMessage = (11.154.213.252)[INTERNAL_ERROR]向工作负载组添加查询失败，工作负载组已关闭。主机：11.154.213.252 查询：从 bbbb 中选择 id,xxx。其中 dayno 在 ('2024-04-14','2024-04-23') 中，id 在 (xxxx) 中 2、写入报错 [Caused by: com.tencent.tme.tcd.stream.connector.doris.exception.StreamLoadException: stream load error: [INTERNAL_ERROR]Failed add query to workload group, the workload group is shutdown. host: xxxx][引起：com.tencent.tme.tcd.stream.connector.doris.exception.StreamLoadException：流加载错误：[INTERNAL_ERROR]向工作负载组添加查询失败，工作负载组已关闭。主持人：xxx]
> 
> ### What You Expected? 你期望什么？
> 查询和写入正常
> 
> ### How to Reproduce?
> _No response_
> 
> ### Anything Else?
> _No response_
> 
> ### Are you willing to submit PR?
> * [ ]  Yes I am willing to submit a PR!
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

升级到2.1.2就好了

**Comment by lexluo09** [comment]
好的，谢谢
