### ISSUE TITLE
[Bug] When performing consecutive intersections/differences of multiple tables,SQL result is error

### ISSUE THREAD

**Issue by TomaYoko** [apache/doris#34633]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.2/2.0.3/master etc.

### What's Wrong?

When performing consecutive intersections/differences of multiple tables, if the nullable attribute of a column in the left table is set to false, and the left table contains zero values while the right table contains null values, the result is incorrect. 
sql like this :
![image](https://github.com/apache/doris/assets/53637394/ac1ebdbd-cfd8-4b65-98ad-a38ac4e42891)
![image](https://github.com/apache/doris/assets/53637394/dbfa6f11-d168-45b6-90ac-288a5f5f3b74)

The correct result is the opposite of that.

### What You Expected?

this bug's reason I've found ,but due to changes in different versions, hope someone experienced can fix it.

### How to Reproduce?

just execute the sql 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by HappenLee** [comment]
It's a bug, I will do the fixed, thank you!
