### ISSUE TITLE
Why Routine Load always be aborted?

### ISSUE THREAD

**Issue by ZengRL** [apache/doris#3482]
I can see "abortedTaskNum" is increasing from "show routine load for";
FE warn log has a lot of msg about "[RoutineLoadTaskScheduler.scheduleOneTask():120] ROUTINE_LOAD_TASK=fad7edd49a14421b-b6cef88b9e79dd19, error_msg={task has been abandoned when scheduling task}"

why it can not consume?? i am sure there are many msg in kafka.

**Comment by morningman** [comment]
What is your Doris version?

**Comment by ZengRL** [comment]
> What is your Doris version?

0.11

**Comment by ZengRL** [comment]
> What is your Doris version?

0.11.25

**Comment by morningman** [comment]
`task has been abandoned when scheduling task`

This error probably because the sub task is timeout and be aborted by the FE.
There were some bugs about the scheduling of routine load task. And They are fixed already.
You can upgrade to 0.11.42 to try to solve the problem.

**Comment by ZengRL** [comment]
> `task has been abandoned when scheduling task`
> 
> This error probably because the sub task is timeout and be aborted by the FE.
> There were some bugs about the scheduling of routine load task. And They are fixed already.
> You can upgrade to 0.11.42 to try to solve the problem.

thanks very much

**Comment by ZengRL** [comment]
> What is your Doris version?

可以加个微信咨询你几个问题吗？

**Comment by ZengRL** [comment]
supplement：
① I have 300 routine load job
② Job run once in ten minutes
![image](https://user-images.githubusercontent.com/16383150/81265015-ed4bdf00-9074-11ea-8aa3-4190151b95b4.png)
③ from “SHOW ROUTINE LOAD TASK WHERE”，TxnId=-1, TxnStatus=UNKNOWN, BeId=-1
![image](https://user-images.githubusercontent.com/16383150/81265099-11a7bb80-9075-11ea-9c5b-ad5226c23539.png)
④ from fe.warn.log，“[RoutineLoadTaskScheduler.scheduleOneTask():120] ROUTINE_LOAD_TASK=3caf5792be3e4fc3-874bc30d82d29e81, error_msg={task has been abandoned when scheduling task}”
![image](https://user-images.githubusercontent.com/16383150/81265217-487dd180-9075-11ea-8b82-556036aef61f.png)
⑤ if I pause some routine load job, keep running job number about 150, there were not see than warn log

**Comment by ZengRL** [comment]
oh, I see more message in be.INFO
2020-05-07 15:24:09,351 INFO 39 [GlobalTransactionMgr.beginTransaction():193] begin transaction: txn id 4731688 with label f00c7f57f0f5400d-b25f72389b624002 from coordinator FE: 172.18.30.60
2020-05-07 15:24:09,443 INFO 39 [RoutineLoadTaskScheduler.submitTask():230] failed to submit task f00c7f57f0f5400d-b25f72389b624002, BE: 10011, error code: TOO_MANY_TASKS

**Comment by dataalive** [comment]
the problem has been fixed
