### ISSUE TITLE
[Bug] FE节点更换IP后程序无法启动

### ISSUE THREAD

**Issue by strongyc** [apache/doris#35051]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.1.2

### What's Wrong?

FE运行一段时间后，由于网管不小心把FE的ip更换了，导致FE节点无法启动柜，该如何解决[2024-05-20 13:02:15] notify new FE type transfer: UNKNOWN

### What You Expected?

[2024-05-20 13:02:15] notify new FE type transfer: UNKNOWN

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ixzc** [comment]
you can refer this:
https://mp.weixin.qq.com/s/RK77CaHEwDTv96L9kMWG9g
