### ISSUE TITLE
[Bug] predicate can't push down when query cantain ‘union all’

### ISSUE THREAD

**Issue by ryanzryu** [apache/doris#35379]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0 2.1

### What's Wrong?

I have query like this：
WITH x AS (
  SELECT 
    a.tz_name, 
    a.ddate 
  FROM 
    dim_time_zone_range a
) 
select 
  * 
from 
  (
    select 
      `tz_name`, 
      ddate 
    from 
      x 
    UNION ALL 
    select 
      '99999' AS `tz_name`, 
      ddate 
    from 
      x
  ) tmp 
where 
  tmp.ddate = '2024-04-30' 
  AND tmp.tz_name = '东八区'

when I delete  “tmp.tz_name = '东八区'” condition，doris nereids plan like this：
![image](https://github.com/apache/doris/assets/143597717/bb6c56fc-ce4f-44ac-97e2-38dfa309add9)
when I add this condition，ddate field condition don't push down on longer：
![image](https://github.com/apache/doris/assets/143597717/b2fa6349-34b0-45b7-9608-dcb570ad687a)

in the other way,  two condition can push down if delete UNION ALL 👍 
![image](https://github.com/apache/doris/assets/143597717/7b3f80e2-cd36-4f33-9d43-d224e190c1e2)

### What You Expected?

ddate field condition can push down when this query has union all statment

### How to Reproduce?

DDL:
 CREATE TABLE `dim_time_zone_range` (
  `ddate` date NULL,
  `id` bigint(20) NULL,
  `time_zone` varchar(65533) NULL,
  `zone_offset` varchar(65533) NULL,
  `tz_name` varchar(65533) NULL,
  `start_time` datetime NULL,
  `end_time` datetime NULL
) ENGINE=OLAP
UNIQUE KEY(`ddate`, `id`)
COMMENT 'OLAP'
DISTRIBUTED BY HASH(`ddate`) BUCKETS 16
PROPERTIES (
"replication_allocation" = "tag.location.default: 3",
"is_being_synced" = "false",
"storage_format" = "V2",
"light_schema_change" = "true",
"disable_auto_compaction" = "false",
"enable_single_replica_compaction" = "false"
);

insert into dim_time_zone_range values('2024-04-30',123,'UTC-8','+8','东八区','2024-04-30',2024-04-30);

query:
WITH x AS (
  SELECT 
    a.tz_name, 
    a.ddate 
  FROM 
    dim_time_zone_range  a
) 
select 
  * 
from 
  (
    select 
      `tz_name`, 
      ddate 
    from 
      x 
    UNION ALL 
    select 
      '99999' AS `tz_name`, 
      ddate 
    from 
      x
  ) tmp 
where 
  tmp.ddate = '2024-04-30' 
  AND tmp.tz_name = '东八区'

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by morrySnow** [comment]
after PR #35463, there are still some remaining issues that have not been addressed. For example, when the number of consumers is optimized below the inline threshold, they cannot be inlined correctly. Additionally, when there is only one consumer left, the filter of that consumer is not eliminated.

**Comment by ryanzryu** [comment]
您的邮件我已收到。
