### ISSUE TITLE
Doris ROUTINE LOAD使用kafka做数据源，导入是否保证分区有序？

### ISSUE THREAD

**Issue by ZhangHuirui** [apache/doris#3543]
**场景：**

- kafka中的数据(单个分区)：

`user_id = 1, user_name = zhangsan, user_status = 0
user_id = 1, user_name = zhangsan, user_status = 2
user_id = 1, user_name = zhangsan_bak, user_status = 2`

- Doris表结构：

`
CREATE TABLE `user_info` (
                        `user_id` bigint(20) NULL COMMENT "",
                        `user_name` varchar(200) REPLACE NULL COMMENT "",
                        `user_status` bigint(20) REPLACE NULL COMMENT ""
) ENGINE=OLAP
    AGGREGATE KEY(`user_id`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`user_id`) BUCKETS 128
PROPERTIES (
"storage_type" = "COLUMN"
);`

- 问题

使用Doris ROUTINE LOAD导入保证顺序吗？结果是`user_id = 1, user_name = zhangsan_bak, user_status = 2`吗？还是不一定？

**Comment by imay** [comment]
If these rows are in the same kafka partition, the order may be kept.
If they are in different partitions, the order can not be kept

**Comment by ZhangHuirui** [comment]
I see. Ordered Message is Not Supported?
