### ISSUE TITLE
[Enhancement] (Nereids) let insert statement support CTE

### ISSUE THREAD

**Issue by morrySnow** [apache/doris#35784]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

let nereids support syntax like:
```sql
WITH cte1 as (
  ...
)
INSERT INTO tbl1
SELECT ...
```

legacy planner do not need to support this syntax

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Dragonliu2018** [comment]
i want to try it.

**Comment by morrySnow** [comment]
> i want to try it.

Great, I'll assign this issue to you.
