### ISSUE TITLE
[ MySQL compatibility]Open view/design view using navicat report  syntax error

### ISSUE THREAD

**Issue by wutiangan** [apache/doris#3582]
### How to reproduce this problem
using Navicat

1、create a view
2、Click the button of "open view " or "design view", 

As shown in the figure below

![EE4A68D864642A270344547E9E0C9355](https://user-images.githubusercontent.com/6271078/81803734-b11fef00-954a-11ea-9ebf-42d7f80614f8.PNG)

### Query SQL：
`MySQL >SELECT TABLE_NAME, CHECK_OPTION, IS_ UPDATABLE, DEFINER, SECURITY_TYPE FROM information_schema.VIEWS WHERE BINARY TABLE_SCHEMA='schema_name' AND BINARY TABLE_ NAME='table_name' ORDER BY TABLE_NAME;`
ERROR 1064 (HY000): errCode = 2, detailMessage = Syntax error in line 1:
...schema.VIEWS WHERE BINARY TABLE_SCHEMA='schema_name' AND BI...
                             ^
Encountered: IDENTIFIER
Expected: ||, COMMA

**Comment by zhoyo21th** [comment]
I got the same problem.
It seems that is not 100% MySQL compatibility
