### ISSUE TITLE
[Bug] 使用SUBSTRING和RANK开窗函数后进行JOIN操作会提示Merge block not match错误

### ISSUE THREAD

**Issue by HolgerWang1999** [apache/doris#35844]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.1.3

### What's Wrong?

升级到2.1.3版本后，如果子查询中使用SUBSTRING函数，再与其他表进行JOIN操作则会提示Merge block not match错误
错误原文：
[CANCELLED]Merge block not match, self:[columns: metric_name, metric_value, stat_value, stat_date, DORIS_DELETE_SIGN, metric_name, stat_date, , Int32, VectorizedFnCall[substring](arguments=metric_name, Int32,return=Nullable(String)), types: Nullable(String), Nullable(String), Nullable(String), Nullable(DateV2), Int8, Nullable(String), Nullable(DateV2), Int64, Int32, Nullable(String)], input:[columns: metric_name, metric_value, stat_value, stat_date, DORIS_DELETE_SIGN, metric_name, stat_date, , Int32, VectorizedFnCall[substring](arguments=metric_name, Int32,return=Nullable(String)), strlen, types: Nullable(String), Nullable(String), Nullable(String), Nullable(DateV2), Int8, Nullable(String), Nullable(DateV2), Int64, Int32, Nullable(String), Int32],

比对了self和input发现是多了一个strlen

### What You Expected?

升级前是可以正常执行的，不应该引发此错误

### How to Reproduce?

复现SQL：
```sql
CREATE TABLE digital_marketing.substring_test (
    `id` INT COMMENT 'id', 
    `k1` STRING, 
    `k2` DATE
) 
UNIQUE KEY (id) 
DISTRIBUTED BY HASH(id) BUCKETS AUTO 
PROPERTIES (
    "replication_allocation" = "tag.location.default:2", 
    "enable_unique_key_merge_on_write" = "true"
);

INSERT
    OVERWRITE TABLE digital_marketing.substring_test
VALUES
    (1, 'EDM:mailId:123456789', '2024-01-01'),
    (2, 'EDM:mailId:123456789', '2024-01-02');

SELECT
    *
FROM
    (
        SELECT
            mail_id
        FROM
            (
                SELECT
                    SUBSTRING(k1, 12) AS mail_id,
                    RANK() OVER       (
                        PARTITION BY
                            k1
                        ORDER BY
                            k2 DESC
                    ) AS rk
                FROM
                    digital_marketing.substring_test
            ) tmp
        WHERE
            rk = 1
    ) a
    JOIN (
        SELECT
            mail_id
        FROM
            (
                SELECT
                    SUBSTRING(k1, 12) AS mail_id,
                    RANK() OVER       (
                        PARTITION BY
                            k1
                        ORDER BY
                            k2 DESC
                    ) AS rk
                FROM
                    digital_marketing.substring_test
            ) tmp
        WHERE
            rk = 1
    ) b ON a.mail_id = b.mail_id;
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by HolgerWang1999** [comment]
使用了SUBSTRING的子查询源表的建表语句：
CREATE TABLE digital_marketing.ods_mysql_vesync_stat_operation_data_stat_fd (
    `id` INT COMMENT 'id',
    `metric_name` STRING,
    `metric_value` STRING,
    `stat_value` STRING,
    `stat_date` DATE,
    `create_time` DATETIME COMMENT '数据创建时间',
    `update_time` DATETIME COMMENT '数据修改时间'
) 
UNIQUE KEY (id) 
COMMENT "EDM-运营指标表" 
DISTRIBUTED BY HASH(id) BUCKETS AUTO 
PROPERTIES (
    "replication_allocation" = "tag.location.default:2", 
    "enable_unique_key_merge_on_write" = "true"
);

对metric_name进行SUBSTRING并进行关联的示例SQL：
SELECT
    *
FROM
    (
        SELECT
            tmp.task_id,
            tmp.metric_value,
            tmp.stat_value
        FROM
            (
                SELECT
                    SUBSTRING(metric_name, 12) AS task_id,
                    metric_value,
                    stat_value,
                    RANK() OVER                (
                        PARTITION BY
                            metric_name
                        ORDER BY
                            stat_date DESC
                    ) AS rk
                FROM
                    digital_marketing.ods_mysql_vesync_stat_operation_data_stat_fd
                WHERE
                    INSTR(metric_name, 'EDM:mailId:') > 0
                    AND metric_value = 'relatedOrderQuantity'
            ) tmp
        WHERE
            tmp.rk = 1
    ) AS ods1
    LEFT JOIN (
        SELECT
            tmp.task_id,
            tmp.metric_value,
            tmp.stat_value
        FROM
            (
                SELECT
                    SUBSTRING(metric_name, 12) AS task_id,
                    metric_value,
                    stat_value,
                    RANK() OVER                (
                        PARTITION BY
                            metric_name
                        ORDER BY
                            stat_date DESC
                    ) AS rk
                FROM
                    digital_marketing.ods_mysql_vesync_stat_operation_data_stat_fd
                WHERE
                    INSTR(metric_name, 'EDM:mailId:') > 0
                    AND metric_value = 'relatedSales'
            ) tmp
        WHERE
            tmp.rk = 1
    ) AS ods2 ON ods1.task_id = ods2.task_id;

**Comment by HolgerWang1999** [comment]
复现SQL示例：
```sql
CREATE TABLE digital_marketing.substring_test (
    `id` INT COMMENT 'id', 
    `k1` STRING, 
    `k2` DATE
) 
UNIQUE KEY (id) 
DISTRIBUTED BY HASH(id) BUCKETS AUTO 
PROPERTIES (
    "replication_allocation" = "tag.location.default:2", 
    "enable_unique_key_merge_on_write" = "true"
);

INSERT
    OVERWRITE TABLE digital_marketing.substring_test
VALUES
    (1, 'EDM:mailId:123456789', '2024-01-01'),
    (2, 'EDM:mailId:123456789', '2024-01-02');

SELECT
    *
FROM
    (
        SELECT
            mail_id
        FROM
            (
                SELECT
                    SUBSTRING(k1, 12) AS mail_id,
                    RANK() OVER       (
                        PARTITION BY
                            k1
                        ORDER BY
                            k2 DESC
                    ) AS rk
                FROM
                    digital_marketing.substring_test
            ) tmp
        WHERE
            rk = 1
    ) a
    JOIN (
        SELECT
            mail_id
        FROM
            (
                SELECT
                    SUBSTRING(k1, 12) AS mail_id,
                    RANK() OVER       (
                        PARTITION BY
                            k1
                        ORDER BY
                            k2 DESC
                    ) AS rk
                FROM
                    digital_marketing.substring_test
            ) tmp
        WHERE
            rk = 1
    ) b ON a.mail_id = b.mail_id;
```

**Comment by lsy3993** [comment]
Let's take a look first, then we will fix it

**Comment by morrySnow** [comment]
could u give more info?
- show variables
- explain verbose

**Comment by HolgerWang1999** [comment]
I updated the [How to Reproduce?] just now, thx!

**Comment by morrySnow** [comment]
set global enable_nereids_planner=true

**Comment by HolgerWang1999** [comment]
@morrySnow Sure, thanks for your help!
