### ISSUE TITLE
[Bug] Get the table's value all null from paimon 0.8 (Doris 2.1.4)

### ISSUE THREAD

**Issue by medivh511** [apache/doris#36021]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris 2.1.4

### What's Wrong?

hadoop 3.3.6 paimon 0.8 doris 2.1.4

The table from paimon had values and it could be got from flink session, but if u get these values from doris paimon catalog, all of them showed null

### What You Expected?

I hope the doris paimon catalog could show correct values from paimon 0.8

### How to Reproduce?

1. first create doris catalog for paimon:

CREATE CATALOG `paimon_catalog` PROPERTIES (
  "type" = "paimon",
  "warehouse" = "hdfs://ns/paimon",
  "dfs.nameservices" = "ns",
  "dfs.ha.namenodes.ns" = "nn1,nn2,nn3",
  "dfs.namenode.rpc-address.ns.nn1" = "x.x.x.x:9000",
  "dfs.namenode.rpc-address.ns.nn2" = "x.x.x.x:9000",
  "dfs.namenode.rpc-address.ns.nn3" = "x.x.x.x:9000",
  "dfs.client.failover.proxy.provider.ns" = "org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider",
  "dfs.client.hedged.read.threadpool.size" = "128",
  "dfs.client.hedged.read.threshold.millis" = "500",
  "hadoop.username" = "root"
);

and doris found one table named ACT_DL which schema liked:

CREATE TABLE
  `ACT_DL` (
    `RECORDID` TEXT NULL,
    `REC_CREATOR` TEXT NULL,
    `REC_CREATE_TIME` TEXT NULL,
    `REC_REVISOR` TEXT NULL,
    `REC_REVISE_TIME` TEXT NULL,
    `AGGREGATETYPE` TEXT NULL,
    `AGGREGATENO` TINYINT NULL,
    `HEATID` TEXT NULL,
    `BOFSCHEDLEID` BIGINT NULL,
    `EXECUTESTANDARD` TEXT NULL,
    `PLANSTEELGRADE` TEXT NULL,
    `ACTSTEELGRADE` TEXT NULL,
    `TAPID` TEXT NULL,
    `IRONLADLEID` TEXT NULL,
    `IRONLADLESTATUS` TEXT NULL,
    `SHIFTNO` TEXT NULL,
    `SHIFTGROUP` TEXT NULL,
    `LADLEID` TEXT NULL,
    `LADLELIFE` TEXT NULL,
    `LADLESTATUS` TEXT NULL,
    `EMPTYLADLEWEIGHT` TEXT NULL,
    `LININGLIFE` TEXT NULL,
    `TAPPINGHOLELIFE` TEXT NULL,
    `OXYGENLANCELIFE` TEXT NULL,
    `SUBLANCELIFE` TEXT NULL,
    `BLOWINGDURATION` TEXT NULL,
    `BRICKUSEDTIMES` TEXT NULL,
    `HEATSTARTTIME` DATETIMEV2(3) NULL,
    `HEATENDTIME` DATETIMEV2(3) NULL,
    `HEATDURATION` TEXT NULL,
    `REBLOW` TEXT NULL,
    `REBLOWDURATION` TEXT NULL,
    `TAPPINGDURATION` TEXT NULL,
    `WEIGHTOFTAPPING` TEXT NULL,
    `STARTSLAGSPLASH` DATETIMEV2(3) NULL,
    `STOPSLAGSPLASH` DATETIMEV2(3) NULL,
    `O2CONSUMPTION` TEXT NULL,
    `O2CONSPEERTON` TEXT NULL,
    `CO2CONTENT` TEXT NULL,
    `COCONTENT` TEXT NULL,
    `ARCONSBOTTOM` TEXT NULL,
    `N2CONSBOTTOM` TEXT NULL,
    `N2CONSSLAGSPLASH` TEXT NULL,
    `N2CONSFORGAS` TEXT NULL,
    `N2CONSNTOTAL` TEXT NULL,
    `ENDTEMPERATURE` TEXT NULL,
    `TEMPERATURETIME` DATETIMEV2(3) NULL,
    `STEELNETWEIGHT` TEXT NULL,
    `HOTMETALPERCHARGED` TEXT NULL,
    `WEIGHTHOTMETALCHARGED` TEXT NULL,
    `WEIGHTSCRAPCHARGED` TEXT NULL,
    `WEIGHTSTEELCHARGED` TEXT NULL,
    `PATTERNBLOWING` TEXT NULL,
    `BOTTOMBLOWINGTYPE` TEXT NULL,
    `SCRAPMODE` TEXT NULL,
    `INSERT_TIME` DATETIMEV2(3) NULL,
    `EXECUTED` TEXT NULL,
    `PRODDATE` TEXT NULL,
    `OPERATEFLAG` TINYINT NULL,
    `OXYGENLANCEID` TEXT NULL,
    `SLAGSPLASH` TEXT NULL,
    `ARCLENGTH` TEXT NULL,
    `VOLTAGELEVEL` TEXT NULL,
    `CURRENTLEVEL` TEXT NULL,
    `POWERCONSUMPTION` TEXT NULL,
    `BIGFURNACETIMES` TEXT NULL,
    `SMALLFURNACETIMES` TEXT NULL,
    `ELECTRODETIMES` TEXT NULL,
    `REBLOWTIMES` TEXT NULL,
    `SUBLANCEID` TEXT NULL,
    `REMARK` TEXT NULL,
    `SUPPLYTIME` TEXT NULL,
    `PONO` TEXT NULL,
    `POWERCONSUMPTION_P` TEXT NULL,
    `POWERCONSUMPTION_V` TEXT NULL,
    `POWERCONSUMPTION_F` TEXT NULL,
    `POWER_START` TEXT NULL,
    `POWER_END` TEXT NULL,
    `OXY_START` TEXT NULL,
    `OXY_END` TEXT NULL,
    `MOLTEN_IRON` TEXT NULL,
    `FIRST_MATERIALS` TEXT NULL,
    `SECOND_MATERIALS` TEXT NULL,
    `LIME` TEXT NULL,
    `DOLOMITE` TEXT NULL,
    `MATERIALS_MANUFACTURERS` TEXT NULL,
    `SELF_OPEN` TINYINT NULL,
    `DRIANAGE` TINYINT NULL,
    `ACT_DELAY` TEXT NULL,
    `TECHNICAL_CONDITIONS` TEXT NULL,
    `TAPPINGSTARTTIME` DATETIMEV2(3) NULL,
    `TAPPINGENDTIME` DATETIMEV2(3) NULL,
    `BELLTIMES` INT NULL,
    `FURNACELIFE` INT NULL,
    `FURNACEWALLLIFE` INT NULL,
    `SLEEVETIMES` INT NULL,
    `HJ_SUM_WT` TEXT NULL,
    `WEATHER` TEXT NULL,
    `REFININGSLAG` TEXT NULL,
    `SQUADLEADER` TEXT NULL,
    `REGISTRAR` TEXT NULL,
    `MATERIALMAN` TEXT NULL,
    `SYNOPSIS` TEXT NULL,
    `IS_B_SAMPLE_OK` TEXT NULL,
    `SEND_FLAG` TEXT NULL,
    `ARGON_GAS_FLOW_RATE` TEXT NULL,
    `ALLOY_ADD_STEEL_WEIGHT` TEXT NULL,
    `SAMPLE1TIME` DATETIMEV2(3) NULL,
    `SAMPLE1TEMPERATURE` INT NULL,
    `YGYZL` TEXT NULL,
    `YJ_FLAG` TEXT NULL,
    `WEIGHTADDTIME` DATETIMEV2(3) NULL,
    `HJ_TOT_WT` TEXT NULL,
    `IS_BZ` TINYINT NULL,
    `SAMPLE2TIME` DATETIMEV2(3) NULL,
    `SAMPLE2TEMPERATURE` TEXT NULL,
    `SAMPLE3TIME` DATETIMEV2(3) NULL,
    `SAMPLE3TEMPERATURE` TEXT NULL,
    `IRON_P` TEXT NULL,
    `IRON_S` TEXT NULL,
    `IRON_SI` TEXT NULL,
    `SUPPLYTIME2` DATETIMEV2(3) NULL,
    `SUPPLYO2TIME` DATETIMEV2(3) NULL,
    `ELECTRODE_DOWN` DATETIMEV2(3) NULL,
    `WEIGHTADDTIME_END` DATETIMEV2(3) NULL,
    `WEIGHTADDTIME_DUR` TEXT NULL,
    `QUALITY_FLAG` TEXT NULL,
    `VERSION` TINYINT NULL,
    `ANA_FLAG` TINYINT NULL
  ) ENGINE = PAIMON_EXTERNAL_TABLE;

2. used the flink session to get this table's value:

CREATE CATALOG paimon_catalog WITH 
(
    'type' = 'paimon',
    'warehouse' = 'hdfs://ns/paimon'
);

USE CATALOG paimon_catalog;

USE paimon_catalog.dl_ods;

SET 'execution.checkpointing.max-concurrent-checkpoints' = '3';
SET 'table.exec.sink.upsert-materialize' = 'NONE';
SET 'execution.checkpointing.interval' = '10s';
SET 'execution.checkpointing.min-pause' = '10s';
SET 'taskmanager.numberOfTaskSlots' = '1';

select * from ACT_DL;

the result showed:

![image](https://github.com/apache/doris/assets/136689882/5517f6ec-f4c6-4611-916d-f97a2586d546)

3. back to the doris web ui and run the query like:

select * from ACT_DL

the value showed:

![image](https://github.com/apache/doris/assets/136689882/07eda74b-91e4-4774-8989-57feb695c717)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yiyong98** [comment]
Hello, we are also facing same issue. Any idea how it can work?

**Comment by medivh511** [comment]
After discussed this issue with selectdb team, they confirmed it was a bug and provided a workaround to get the correct result from paimon 0.8

use this internal setting:( Do not use it in the global env, or it will cause peformance issue)
set force_jni_scanner=true;

this issue was caused by the table names and column names whose used the upper characters, the selectdb team will fix this bug in next release
