### ISSUE TITLE
[Bug] Bug with BIGINT boundary values

### ISSUE THREAD

**Issue by malwaregarry** [apache/doris#36077]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.1.3

### What's Wrong?

From https://doris.apache.org/docs/sql-manual/sql-types/Data-Types/BIGINT/:
> BIGINT 8-byte signed integer, range [-9223372036854775808, 9223372036854775807]

Given a table with a bigint column. We have 1 row with value 1
```
CREATE TABLE t1(c0 BIGINT NOT NULL) DISTRIBUTED BY RANDOM  PROPERTIES ("replication_num" = "1");
INSERT INTO t1 (c0) VALUES (1);
``` 

This returns true:
`SELECT (NOT (9223372036854775807<= t1.c0)) from t1;`

This does not return any rows:
`SELECT t1.c0 FROM t1 WHERE (NOT (9223372036854775807<= t1.c0)) ;`

This returns true:
`SELECT (NOT (-9223372036854775808 >= t1.c0)) from t1;`

This does not return any rows:
`SELECT t1.c0 FROM t1 WHERE (NOT (9223372036854775807<= t1.c0)) ;`

### What You Expected?

The queries return rows
`SELECT t1.c0 FROM t1 WHERE (NOT (9223372036854775807<= t1.c0)) ;`
`SELECT t1.c0 FROM t1 WHERE (NOT (9223372036854775807<= t1.c0)) ;`

### How to Reproduce?

```
DROP DATABASE IF EXISTS doris0;
CREATE DATABASE doris0;
USE doris0;
CREATE TABLE t1(c0 BIGINT NOT NULL) DISTRIBUTED BY RANDOM  PROPERTIES ("replication_num" = "1");
INSERT INTO t1 (c0) VALUES (1);

SELECT (NOT (9223372036854775807<= t1.c0)) from t1;
SELECT t1.c0 FROM t1 WHERE (NOT (9223372036854775807<= t1.c0)) ;

SELECT (NOT (-9223372036854775808 >= t1.c0)) from t1;
SELECT t1.c0 FROM t1 WHERE (NOT (9223372036854775807<= t1.c0)) ;
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhiqiang-hhhh** [comment]
already fixed by https://github.com/apache/doris/pull/34832

try latest 2.1

**Comment by malwaregarry** [comment]
thanks works on 2.1.4
