### ISSUE TITLE
[Bug] doris-streamloader memory leak 

### ISSUE THREAD

**Issue by tianjiqx** [apache/doris#36119]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.0.1

### What's Wrong?

Translation: When using the [apache/doris-streamloader](https://github.com/apache/doris-streamloader) script for testing and importing, the doris-streamloader process experienced rapid memory escalation, ultimately causing the BE process to crash. It is suspected that there is a memory leak in doris-streamloader. However, using HTTP stream load functioned normally. The test data used was clickbench hits.tsv.

### What You Expected?

Successful import was achieved with minimal memory usage.

### Anything Else?

./doris-streamloader --source_file="/opt/hits_benchmark/1_2_hits.tsv" --url="http://localhost:8030" --header="group_commit:sync_mode?columns: WatchID,JavaEnable,Title,GoodEvent,EventTime,EventDate,CounterID,ClientIP,RegionID,UserID,CounterClass,OS,UserAgent,URL,Referer,IsRefresh,RefererCategoryID,RefererRegionID,URLCategoryID,URLRegionID,ResolutionWidth,ResolutionHeight,ResolutionDepth,FlashMajor,FlashMinor,FlashMinor2,NetMajor,NetMinor,UserAgentMajor,UserAgentMinor,CookieEnable,JavascriptEnable,IsMobile,MobilePhone,MobilePhoneModel,Params,IPNetworkID,TraficSourceID,SearchEngineID,SearchPhrase,AdvEngineID,IsArtifical,WindowClientWidth,WindowClientHeight,ClientTimeZone,ClientEventTime,SilverlightVersion1,SilverlightVersion2,SilverlightVersion3,SilverlightVersion4,PageCharset,CodeVersion,IsLink,IsDownload,IsNotBounce,FUniqID,OriginalURL,HID,IsOldCounter,IsEvent,IsParameter,DontCountHits,WithHash,HitColor,LocalEventTime,Age,Sex,Income,Interests,Robotness,RemoteIP,WindowName,OpenerName,HistoryLength,BrowserLanguage,BrowserCountry,SocialNetwork,SocialAction,HTTPError,SendTiming,DNSTiming,ConnectTiming,ResponseStartTiming,ResponseEndTiming,FetchTiming,SocialSourceNetworkID,SocialSourcePage,ParamPrice,ParamOrderID,ParamCurrency,ParamCurrencyID,OpenstatServiceName,OpenstatCampaignID,OpenstatAdID,OpenstatSourceID,UTMSource,UTMMedium,UTMCampaign,UTMContent,UTMTerm,FromTag,HasGCLID,RefererHash,URLHash,CLID" --db="hits" --table="hits" --workers 1 --max_byte_per_task 10485760

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by sollhui** [comment]
Thank you for your feedback. We will verify it.

**Comment by cheokkin1994** [comment]
I encountered a similar issue where writing a script to load 100 files into Doris results in memory exhaustion, causing the script to become unresponsive and stuck.
