### ISSUE TITLE
[Bug] delete with value column predicates should not work

### ISSUE THREAD

**Issue by dataroaring** [apache/doris#36153]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

1. create a aggregate table with key and value
2. delete from the table with where value = xxx
3. the delete should not work.

### What You Expected?

3. the delete should not work.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Dragonliu2018** [comment]
i want to fix it.

**Comment by Dragonliu2018** [comment]
looks like it's been fixed.
```sql
CREATE TABLE IF NOT EXISTS t1 (
    id LARGEINT NOT NULL COMMENT "id of site",
    pv BIGINT SUM DEFAULT "0" COMMENT "total page views"
)
AGGREGATE KEY(id)
DISTRIBUTED BY HASH(id) BUCKETS 3
PROPERTIES ("replication_num" = "1");

insert into t1 values(1, 1);
insert into t1 values(1, 1);
insert into t1 values(2, 1);

select * from t1;
+------+------+
| id   | pv   |
+------+------+
| 1    |    2 |
| 2    |    1 |
+------+------+
2 rows in set (0.02 sec)

delete from t1 where pv = 1;
ERROR 1105 (HY000): errCode = 2, detailMessage = delete predicate on value column only supports Unique table with merge-on-write enabled and Duplicate table, but Table[t1] is an Aggregate table.
```
