### ISSUE TITLE
[Enhancement] enhance the robustness and stability of Doris in handling semi-structure types

### ISSUE THREAD

**Issue by eldenmoon** [apache/doris#36362]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

# Background
To enhance the robustness and stability of Doris in handling semi-structure types including JSON and VARIANT type data, we aim to comprehensively test the parsing behavior of these types under various invalid JSON formats.

# Requirement
Please create test cases to validate Doris' parsing behavior under various invalid JSON formats, following the table creation methods referenced in the resources below.

# References:

[JSON Parsing Test Suite](https://github.com/nst/JSONTestSuite/tree/master/test_parsing)
[JSON Transform Test Suite](https://github.com/nst/JSONTestSuite/tree/master/test_transform)
[JSON Schema Test Suite](https://github.com/json-schema-org/JSON-Schema-Test-Suite/tree/bcf1dc81ae099ade2a9642c672c06ee1af1bb489/tests)

# Tasks
Table Creation: Create tables for [JSON](https://doris.apache.org/docs/sql-manual/sql-types/Data-Types/JSON?_highlight=json) and [VARIANT](https://doris.apache.org/docs/sql-manual/sql-types/Data-Types/VARIANT?_highlight=variant) types according to Doris' table creation specifications.
Test Cases: Write test cases covering various invalid JSON formats, including but not limited to the following scenarios:
Incorrect JSON syntax (e.g., missing commas, unclosed brackets, etc.)
Invalid character encoding
Excessively large numbers or strings
Excessive nesting levels
Mixed arrays of different types

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tech-Circle-48** [comment]
please assign to me

**Comment by eldenmoon** [comment]
> please assign to me

done
