### ISSUE TITLE
[Feature] Add system table `information_schema.mem_tracker`

### ISSUE THREAD

**Issue by xinyiZzz** [apache/doris#36373]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

## Goal
support querying MemTracker memory statistics

**`select * from information_schema.mem_tracker;`**
show the table in this web `ip:8040/mem_tracker`, return total of all BE and add a new column `Backend Host`.
![image](https://github.com/apache/doris/assets/13197424/7dc795aa-638a-468d-abb2-5b4a2756469e)

**`select * from information_schema.mem_tracker where type="global"`**
and supports query by `Type` and `Host`, like this web:
![image](https://github.com/apache/doris/assets/13197424/446ac767-110f-478d-8629-5c246f425dbf)

this document introduce MemTracker:
https://doris.apache.org/docs/admin-manual/memory-management/memory-tracker

**TODO:**
BE use an independent scanner to return result when select `information_schema.table`, so, can create a new mem_tracker_scanner to return MemTracker statistics.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xinyiZzz** [comment]
@Vallishp

**Comment by Vallishp** [comment]
will work on it.

**Comment by xinyiZzz** [comment]
https://github.com/apache/doris/pull/36679
show all memory state: `http://beip:8040/mem_tracker?type=all`, this is the result of `select * from information_schema.mem_tracker`, return by`mem_tracker_scanner`.

**Comment by xinyiZzz** [comment]
impl: https://github.com/apache/doris/pull/37348
