### ISSUE TITLE
[Feature] Support show backend config

### ISSUE THREAD

**Issue by DarvenDuan** [apache/doris#36445]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Can Doris implements a stmt to support show backend config like "admin show backend config where backendID = xxx" ? It's more convenient than BE OPEN API.

### Use case

show backend config by executing a showStmt

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by cjj2010** [comment]
You can also visit backendIP:8040 to find backend config

**Comment by DarvenDuan** [comment]
> You can also visit backendIP:8040 to find backend config

Using API can visit only one backend, sometimes we need see all backend's config for a given config key, maybe we need add a new show stmt？
