### ISSUE TITLE
[Bug] AUTO_INCREMENT doesn't seem to work, gives error.

### ISSUE THREAD

**Issue by hyler** [apache/doris#36638]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.1.3

### What's Wrong?

Create simple table:
```
mysql> CREATE TABLE sink (mykey BIGINT NOT NULL AUTO_INCREMENT, name VARCHAR(64)) UNIQUE KEY(mykey) DISTRIBUT
ED BY HASH(mykey) BUCKETS AUTO PROPERTIES("replication_num" = "1");
Query OK, 0 rows affected (0.05 sec)
```

Insert values:
```
mysql> INSERT INTO sink (name) VALUES ('mark');
Query OK, 1 row affected (0.15 sec)
{'label':'label_50ebd44d291c443d_bf696f2afe14d2cb', 'status':'VISIBLE', 'txnId':'3056'}
```

Fails when the data comes from a SELECT:
```
mysql> INSERT INTO sink (name) SELECT 'john' AS name FROM sink;
ERROR 1105 (HY000): errCode = 2, detailMessage = Insert has filtered data in strict mode. url: http://192.168.1.224:8040/api/_load_error_log?file=__shard_56/error_log_insert_stmt_f5761498513f4ab5-823316e0596a9de0_f5761498513f4ab5_823316e0596a9de0
```

This is the log:
```
Reason: column_name[mykey], null value for not null column, type=BIGINT. src line []; 
```

### What You Expected?

I expect the data to go into the table and the column to be auto-incremented.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hyler** [comment]
I wanted to provide a cleaner workflow that demonstrates the issue. I've attached a screenshot. I cannot understand what I'm doing wrong to get this error.
![image](https://github.com/apache/doris/assets/18198129/5261b580-5d2f-4f76-818f-4e09b4d2ae6a)

**Comment by ixzc** [comment]
it really does not meet expectations. we will fix this and update you if there is some thing new.
