### ISSUE TITLE
[Bug] BE crash at JEMALLOC free

### ISSUE THREAD

**Issue by lide-reed** [apache/doris#36641]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.10

### What's Wrong?

some BE nodes crash with following stack:

--------
*** Query id: 4c98019bdfa54035-ac96ed099f8f99aa ***
*** tablet id: 0 ***
*** Aborted at 1718391604 (unix time) try "date -d @1718391604" if you are using GNU date ***
*** Current BE git commitID: 2405101 ***
*** SIGSEGV address not mapped to object (@0x1c0000) received by PID 879937 (TID 28945 OR 0x7f2b8a9f1700) from PID 1835008;
 stack trace: ***
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) in /usr/local/service/doris/lib/be/d
oris_be
 1# os::Linux::chained_handler(int, siginfo*, void*) in /usr/local/jdk/jre/lib/amd64/server/libjvm.so
 2# JVM_handle_linux_signal in /usr/local/jdk/jre/lib/amd64/server/libjvm.so
 3# signalHandler(int, siginfo*, void*) in /usr/local/jdk/jre/lib/amd64/server/libjvm.so
 4# 0x00007F559ECB1400 in /lib64/libc.so.6
 5# jemalloc_usable_size in /usr/local/service/doris/lib/be/doris_be
 6# free in /usr/local/service/doris/lib/be/doris_be
 7# __GI__dl_deallocate_tls in /lib64/ld-linux-x86-64.so.2
 8# __free_stacks in /lib64/libpthread.so.0
 9# __deallocate_stack in /lib64/libpthread.so.0
10# start_thread in /lib64/libpthread.so.0
11# __clone in /lib64/libc.so.6

### What You Expected?

don't crash

### How to Reproduce?

Cannot reproduce

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lide-reed** [comment]
If compile with TCMallo, it will not crash.

**Comment by biohazard4321** [comment]
这个目前用openjdk会报； jemalloc跟openjdk的jni不太兼容，还不太好解决

**Comment by xinyiZzz** [comment]
带前缀的 jemalloc 和 动态加载 jni 不兼容，最终的解决方法是移除 jni 动态加载，3个相关pr，2.0有需要可以pick下
1. 问题分析、移除jemalloc的前缀、禁用mem hook，https://github.com/apache/doris/pull/34578
2. 移除 jni 动态加载，https://github.com/apache/doris/pull/35557
3. 恢复了 jemalloc 前缀、允许 mem hook，https://github.com/apache/doris/pull/35694
