### ISSUE TITLE
[Enhancement] supprt SELECT * REPLACE

### ISSUE THREAD

**Issue by dataroaring** [apache/doris#36777]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

When we have a table with 100 columns, and we want to save some data to another table with one column data changed. It is tedious to write out all column name. We can support SELECT * REPLACE like bigsql.

Https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xiabaike** [comment]
I want to try to complete this issue, can you assign it to me?

**Comment by macroguo-ghy** [comment]
@dataroaring can youreview my PR #38680?
