### ISSUE TITLE
[Bug] delete from table where key=xxx hangs

### ISSUE THREAD

**Issue by dataroaring** [apache/doris#36775]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

 -9999782574499444.2 is legal but doris handles it as illegal.
when an illegal decimal happens on delete, fe retries it until timeout.

### What You Expected?

Handle -9999782574499444.2  successfully.
Fail immediately for illegal data.

### How to Reproduce?

CREATE TABLE table1
(
    col1 BOOLEAN NOT NULL, col2 DECIMAL(17, 1) NOT NULL, col3 INT NOT NULL, 
)
DUPLICATE KEY(`col1`,`col2`,`col3`)
DISTRIBUTED BY HASH(`col1`,`col2`,`col3`) BUCKETS 4
PROPERTIES (
     "disable_auto_compaction"="false", 
    "replication_num" = "3"
);

delete from table1 where col1 = "false" and col2 = "-9999782574499444.2" and col3 = "-25"

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by felixwluo** [comment]
pick
