### ISSUE TITLE
[Bug] query result's column name becomes value

### ISSUE THREAD

**Issue by superdiaodiao** [apache/doris#38020]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

branch: master
latest git version: 715af6eea9f18f0aac690be4dfa5f6330a153ede

### What's Wrong?

Column name is missing and turns into value of it:
![70a8ce0a2c5700a8f2c4900d05c492f](https://github.com/user-attachments/assets/990017f2-cc94-44c1-9dbb-9b1385323258)

### What You Expected?

display normal column name like **MySQL**:
```
mysql> select now();
+-----------------------+
| now()                 |
+-----------------------+
| 2024-07-17 19:52:48   |
+-----------------------+
1 row in set (0.07 sec)

mysql> 
mysql> 
mysql> 
mysql> select current_date();
+--------------+
| current_date() |
+--------------+
| 2024-07-17   |
+--------------+
1 row in set (0.00 sec)
```

### How to Reproduce?

pull latest master code and query like: `select now();`

### Anything Else?

It has been appearing a few days before today issue reported.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zclllyybb** [comment]
that's because FE constant folding. AFAIK it's not easy or necessary to resolve it.

**Comment by morningman** [comment]
I think it should be same as MySQL

**Comment by superdiaodiao** [comment]
Yes, MySQL can display the function name in this situation.

**Comment by morrySnow** [comment]
which version do u use? cannot reproduce this. order version have this problem and have be fixed

**Comment by morrySnow** [comment]
<img width="495" alt="image" src="https://github.com/user-attachments/assets/3db83122-0428-4cc1-afe0-c7a0009ef3a1">

**Comment by superdiaodiao** [comment]
> branch: master
> latest git version: [715af6e](https://github.com/apache/doris/commit/715af6eea9f18f0aac690be4dfa5f6330a153ede)

just like the **describe** above:
branch: master
latest git version: https://github.com/apache/doris/commit/715af6eea9f18f0aac690be4dfa5f6330a153ede

**Comment by superdiaodiao** [comment]
update:
After git version 912a23887fcae26c34ff6d03ad76bd221e44c5c8 on master, this problem was solved.
