### ISSUE TITLE
[Bug] MySQL protocol cannot obtain decimal precision when SSL is enabled

### ISSUE THREAD

**Issue by cjj2010** [apache/doris#38065]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.1.0-2.1.4、master

### What's Wrong?

MySQL protocol cannot obtain decimal precision when SSL is enabled
Steps to enable SSL，https://doris.apache.org/zh-CN/docs/admin-manual/auth/certificate
Using JDBC to query data of type decimalv3 (38, 10)
e.g
```
	   String url = "jdbc:mysql://192.168.83.177:33/demo?"
					+ "useSSL=true"
					+ "&requireSSL=true";

            String user = "root";
            String password = "123456";
            System.out.println("连接数据库");
            Connection conn = DriverManager.getConnection(url, user, password);
            System.out.println("连接正常!");
            PreparedStatement preparedStatement = conn.prepareStatement("select 603B91D1989D_06a2 from dwd_1813421496594669569 where 1 = 1");
            ResultSet rs= preparedStatement.executeQuery();
            ResultSetMetaData metaData =rs.getMetaData();
            int scale = metaData.getScale(1);
            System.out.println(scale);
```
Scale will return 0

### What You Expected?

Return to normal accuracy

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zy-kkk** [comment]
Let me look at this question
