### ISSUE TITLE
表名大小写问题

### ISSUE THREAD

**Issue by hf200012** [apache/doris#3834]
information_schema表中lower_case_table_names=0，已经只不区分大小写了，但是实际使用了，这个不起作用，
怎么让表名和字段名称不区分大消息

**Comment by morningman** [comment]
Currently Doris does not support making database and table name case insensible.
The value of `lower_case_table_names` in `information_schema` is meaningless for now.

**Comment by Likes123** [comment]
我这边尝试的结果是：lower_case_table_names=1 fe拉不起来。但是lower_case_table_names=0可以。但是官方文档没有依然说可以设置成lower_case_table_names=0，没有做同步的修改

**Comment by Likes123** [comment]
参看官网，在 fe/conf/fe.conf中添加：
lower_case_table_names=1  不区分大小写

需要重新初始化实例，也就是删除meta信息重新初始化数据库
