### ISSUE TITLE
[Bug] Can not compile on M1 MacOS because malloc.h was included in allocator.h

### ISSUE THREAD

**Issue by macroguo-ghy** [apache/doris#38599]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master branch

### What's Wrong?

compile fail
```
 fatal error: 'malloc.h' file not found
#include <malloc.h>
         ^~~~~~~~~~
```

### What You Expected?

success

### How to Reproduce?

./build.sh --be --fe

### Anything Else?

Introduced by this PR https://github.com/apache/doris/pull/37234

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TangSiyang2001** [comment]
just replace it with header <cstdlib>
