### ISSUE TITLE
[Enhancement](doris-future) Support "REGR_" aggregation functions (PART II)

### ISSUE THREAD

**Issue by zclllyybb** [apache/doris#38975]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

We are going to support all regression functions in pg. You can see them in https://www.postgresql.org/docs/16/functions-aggregate.html with `regr_` prefix. And considring the difficulty of this task, it will be nice for community as "good first issue".

In this issue, you should implement function `regr_intercept` and `regr_slope`

If you'd like to work on it, please comment to let me know. I'll help you to achieve this.

### Solution

you can found an example of implementation of a aggregate function [here](https://github.com/apache/doris/pull/33265)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ShivamChavan01** [comment]
Can I work On It @zclllyybb

**Comment by zclllyybb** [comment]
> Can I work On It @zclllyybb

yes~ feel free to communicate when you meet problem.

**Comment by zclllyybb** [comment]
@ShivamChavan01 hello, any developments or problem recently?

**Comment by Yoruet** [comment]
I want to work on it plz

**Comment by Yoruet** [comment]
I want to try it plz.
