### ISSUE TITLE
[Bug] 同样的数据，排序键顺序不一样，数据量差30%

### ISSUE THREAD

**Issue by hnwkz** [apache/doris#39608]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-2.0.9-5c2fca80b0

### What's Wrong?

建表语句1：
![image](https://github.com/user-attachments/assets/9aa7faad-10dc-44ef-b5d9-739ed5999bc9)
建表语句2：
![image](https://github.com/user-attachments/assets/c136764a-88f5-4efe-a3de-8cc411931f1f)
同样使用lz4压缩方式，唯一的区别就是，主键排序字段不一样
表一使用lz4压缩，主键顺序event_name(varchar100)排在首位，show data 大小为 5.203 GB
表一使用lz4压缩，主键顺序event_time(datetime)排在首位，show data 大小为 3.815 GB
为何仅仅修改了排序键的顺序，占用磁盘空间差距近30%？

### What You Expected?

主键顺序不同，是否有索引数据占用了空间？

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hk53315** [comment]
大部分压缩算法的原理，都是基于数据特征来压缩的，往往维护一个滑动窗口，后续的数据与窗口内容匹配度越高，越容易被编码优化。对同一字段，排序后再压缩，意味着临近的数据特征更相似，往往有数倍的压缩率提升。

**Comment by HappenLee** [comment]
@hk53315 give the best answer，close the issue
