### ISSUE TITLE
[Bug] explode_map() funcation ERROR:Unknown table

### ISSUE THREAD

**Issue by SoWhat-ET** [apache/doris#39614]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.1.4

### What's Wrong?

```

select 
    a.name,
    tmp.k,
    tmp.v
from (
    select 
        'zhangsan' name,
        map(1,20,2,30) score
)a lateral view explode_map(score)  tmp as k,v;
```
Query ERROR (执行报错)：
> errCode = 2, detailMessage = Unknown table 'v'

Rewriting it in the way below works, but it's not the result I was expecting.
(改写为下面的形式可以执行成功，但是不是我预期的结果)

```sql
select 
    a.name,
    tmp.k
from (
    select 
        'zhangsan' name,
        map(1,20,2,30) score
)a lateral view explode_map(score)  tmp as k
```
![image](https://github.com/user-attachments/assets/76180e15-2bfa-410e-ad2f-8223075591e0)

### What You Expected?

| name        |   k      |     v      |
| zhangsan |   1      |    20     |
| zhangsan |   2      |    30     |

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by HappenLee** [comment]
https://github.com/apache/doris/pull/39972#event-14026257428 fix buy here，please update to 2.1.6
