### ISSUE TITLE
[Bug] conv() with float value as input parameter leads to incorrect result

### ISSUE THREAD

**Issue by yoursweetie** [apache/doris#39618]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.1

### What's Wrong?

conv() with float value as input parameter leads to incorrect result

### What You Expected?

float value or other illegal values are banned from conv() function

### How to Reproduce?

Just execute
```
create table test_tb(int_1 int, float_2 float);

insert into test_tb values(1, 1.464868);

select conv(float_2,10,2),float_2 from test_tb;
```
![图片](https://github.com/user-attachments/assets/ed8c5144-cc89-4b9d-be82-da459c18b3f9)

The result "0" is incorrect, it should be like "0 01111111 01110111000000011001011"

![图片](https://github.com/user-attachments/assets/3b8ac6ff-19a2-44c7-aab7-d9d95b50066e)

BTW, I suggest that the conv() prohibits floating-point numbers as input parameters

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yiguolei** [comment]
It will be fixed in 2.1.7
