### ISSUE TITLE
[Spark Load] Some Todo For Spark Before It can be used in Prod Env

### ISSUE THREAD

**Issue by wangbo** [apache/doris#3998]
**Goal**
* Major goal is ```stable and can be used in some user cases```  and then ```use Spark Load in Prod Env``` as quick as possible.
* More comprehensive optimization and function support which may cost more time can be slowly improved in subsequent iterations

**Function Test**
* Floating-point type correctness test
* Basic use process test
* Node failure test

**Performance Test**
* Broker load performace when source data and Doris in different regions

**Global Dict Build Function**
* Support Global Dict Write Lock(#4058)
* Support Non-Global Dict

**SparkDPP**
* Eliminate  convert between RDD and Dataframe when doing aggregation(#4303)
* Support More Type Aggregator,such as Decimal, Date, Datetime
* Use BigInteger in Integer Aggregator to complete bound check
* Use statistics to determine the concurrency in doing aggregate reduce
* Float-point bound check

**FE Scheduling framework**
* Support Job resume

**Common Function**
* Clean up temporary data including hive table and hdfs file

**Comment by morningman** [comment]
> * Support Job resume

What is "job resume"?

**Comment by wangbo** [comment]
> > * Support Job resume
> 
> What is "job resume"?

For example,If load job fails because of be downs,then we can resume the load job to load data to be when be recovers instead of submit a new load stmt which may build dict and do dpp again.
