### ISSUE TITLE
[Feature] 增加删除坏tablet的系统命令

### ISSUE THREAD

**Issue by xleoken** [apache/doris#40213]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

各位大佬，一张表的其中一个tablet坏了，其所有副本也丢失了，导致不能查询。通过设置 `skip_bad_tablet` 可以支持在单次session里面忽略掉坏tablet。希望可以支持一种命令，可以直接删除这个tablet。

尝试过 `ADMIN SET FRONTEND CONFIG ("recover_with_empty_tablet" = "true");` 这个并不是直接生效，也没起作用

![image](https://github.com/user-attachments/assets/183b2f56-6c06-482a-8254-c263d3c6f7ad)

![image](https://github.com/user-attachments/assets/05a6ece3-9c44-49ff-a644-d9b38f43342f)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by echo-hhj** [comment]
可以参考一下这个[副本修复](https://ask.selectdb.com/questions/D1Pw1/zui-jia-shi-jian-shu-ju-fu-ben-wen-ti-pai-cha-zhi-nan)文档，如果所有副本都损坏，可以通过填充空的rowset来解决

**Comment by xleoken** [comment]
好的，我试试
