### ISSUE TITLE
[Bug] doris.2.0.14版本show frontends耗时很慢 30s，其他命令都是毫秒级

### ISSUE THREAD

**Issue by baimafeima-yf** [apache/doris#40586]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.14

### What's Wrong?

show frontends耗时很慢 30s 其他命令都是毫秒级 fe日志也没有明显报错，/etc/resolv.conf也是空的，没配其他地址
![doris问题1](https://github.com/user-attachments/assets/da345a56-d700-43f6-bceb-2ec9c93e4e94)
![doris问题2](https://github.com/user-attachments/assets/959fb4a3-f56f-499d-b438-c0eff9cf1dbd)
![doris问题3](https://github.com/user-attachments/assets/e4e4a75d-8908-4a0e-9c96-5c468ec85abb)

### What You Expected?

show frontends毫秒级返回

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhanghui9700** [comment]
the issue is closed, how to fixed this?
