### ISSUE TITLE
[Bug] CPU does not support SSSE3 instruction set.

### ISSUE THREAD

**Issue by 1638540149** [apache/doris#40627]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.0

### What's Wrong?

When I started doris be，It wrong.The log is 
Instruction check fail.The CPU does not support SSSE3 instruction set.
For example, if your CPU does not support AVX2 , you need to rebuild the Doris BE with: USE_ACX2=0 sh build.sh --be
But I try to rebuild with USE_SSSE3=0 sh build.sh,it dose not work

### What You Expected?

How to resolve this question?

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zclllyybb** [comment]
try to manually undef __SSSE3__ and re-compile

**Comment by HappenLee** [comment]
if you use x86，must at least support sse4.2 or above
