### ISSUE TITLE
[Enhancement](good first issue) Reduce usage of log fatal

### ISSUE THREAD

**Issue by zclllyybb** [apache/doris#40835]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Except in storage layer exception, we should try best to avoid `LOG(FATAL)` which leads to BE crash.

### Solution

use `throw Exception` to replace them which not in `if constexpr`.
for those in `if constexpr else{...}`, use `static_assert` about template argument which used in that judgement to advance them to compile time

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tobiichi-Origam1** [comment]
I want to work on it, please assign it to me!
