### ISSUE TITLE
[Enhancement](good first issue) Support exception report in our benchmark utils

### ISSUE THREAD

**Issue by zclllyybb** [apache/doris#40834]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

now some of our benchmark utils(see in `tools/`, like clickbench, tpch...) don't report detail messages when meet error running query. it's not very convinced. we need support this.

### Solution

modify the scripts to report error if meet.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by cat-with-cat** [comment]
I want to try it, please assign it to me.
