### ISSUE TITLE
support SQL syntax  group_concat( distinct field )

### ISSUE THREAD

**Issue by yanchao891012** [apache/doris#4114]
select group_concat( distinct stage) , group_concat( distinct location ) from dwd_applications where id<10 group by id;
ERROR 1064 (HY000): errCode = 2, detailMessage = group_concat does not support DISTINCT

![group_concat](https://user-images.githubusercontent.com/16846702/87757556-6ddd4780-c83d-11ea-95f1-f0459a9db97b.png)

**Comment by dataalive** [comment]
it's been supported since 1.1.2

![img_v2_d4b94f8e-8ead-4309-b2da-6aaa7760591g](https://user-images.githubusercontent.com/99398130/191990987-5d0039e7-2711-4541-affa-700f993f4513.jpg)
