### ISSUE TITLE
[Bug] doris数据库使用left join连接mysql中的表时，mysql表中的非空字段作为查询条件报错【SQL 错误 [1105] [HY000]: errCode = 2, detailMessage = (10.201.61.186)[INTERNAL_ERROR]Function eq get failed, expr is VectorizedFnCall[eq](arguments=IS_ENABLED, Int8,return=Nullable(UInt8)) and return type is Nullable(UInt8).】

### ISSUE THREAD

**Issue by hunagjingxin** [apache/doris#41184]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.1.6

### What's Wrong?

![微信图片_20240924095054](https://github.com/user-attachments/assets/1d9f880c-c738-4479-b99c-59cd6ac23ed9)

mysql建表语句：
CREATE TABLE `iaas_host_test` (
  `ID` varchar(38) COLLATE utf8_unicode_ci NOT NULL COMMENT 'ID',
  `REGION_ID` varchar(38) COLLATE utf8_unicode_ci NOT NULL COMMENT '区域ID',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `iaas_region_test` (
  `REGION_ID` varchar(38) COLLATE utf8_unicode_ci NOT NULL COMMENT '流水号',
  `IS_ENABLED` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否启用',
  `IS_DEFAULT` tinyint(1) DEFAULT '0' COMMENT '是否为默认区域',
  PRIMARY KEY (`REGION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

在doris数据库中查询：
  select * from cmp.iaas.iaas_host_test t1
  left join cmp.iaas.iaas_region_test t2 on t1.REGION_ID = t2.REGION_ID
  where t2.is_enabled = 1
执行报错：
SQL 错误 [1105] [HY000]: errCode = 2, detailMessage = (10.201.61.186)[INTERNAL_ERROR]Function eq get failed, expr is VectorizedFnCall[eq](arguments=IS_ENABLED, Int8,return=Nullable(UInt8)) and return type is Nullable(UInt8).

### What You Expected?

doris数据库使用left join连接mysql中的表时，mysql表中的非空字段作为查询条件时，查询不报错

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zy-kkk** [comment]
https://github.com/apache/doris/pull/41014
