### ISSUE TITLE
[Bug] flink doris connector type conversion error while sink DATE type of data

### ISSUE THREAD

**Issue by SmiMi** [apache/doris#41244]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

flink-doris-connector-1.16
1.16.0
1.16.2
24.0.0

### What's Wrong?

![image](https://github.com/user-attachments/assets/f1e9fea3-10e5-44bc-b9b7-b045a03054ff)

When I run the example, I get the following error：

java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer

### What You Expected?

![image](https://github.com/user-attachments/assets/fb47944b-f1e0-4722-a68f-a3439f546d72)

Whether this should use Long type

### How to Reproduce?

No response

### Anything Else?

No response

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CloudExtreme** [comment]
It should be fixed in project doris-flink-connector, could you please assign this issue to me?

**Comment by CloudExtreme** [comment]
It may be considered as the value of epochday is much more lesser than the maximum value of int. I'm not sure that's the right thing to use getInt. Maybe you can cast long to int to avoid this issue or make an issue in project doris-flink-connector.
