### ISSUE TITLE
[Enhancement] (nereids)implement SwitchCatalogCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42525]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

SwitchCatalogCommand is supported in legacy planner but not in nereids(new doris fe planner). you need implement it in nereids.The DorisParser.g4 has the syntax definition already(see bellow). And you can check SwitchStmt.java in legacy planner to see what the command does and migrate it to nereids planner
```unsupoortedUseStatement : SWITCH catalog=identifier```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vinlee19** [comment]
i  will pick it!
