### ISSUE TITLE
[Enhancement] (nereids)implement RecoverCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42550]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

recover command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following use command in nereids:
- [x] https://github.com/apache/doris/issues/42544
- [x] https://github.com/apache/doris/issues/42545
- [x] https://github.com/apache/doris/issues/42547

This pr https://github.com/apache/doris/pull/41913 implemented Set Command in nereids. Although it's a little complex than this one, it can be a reference

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Vallishp** [comment]
@LiBinfeng-01  Pls assign all these 3 to me. thanks. also do we need to remove the legacy code for corresponding function or keep it as for now?

**Comment by starocean999** [comment]
@Vallishp Thanks, you need replay to the all 3 issues, then I can assign them to you one by one

**Comment by LiBinfeng-01** [comment]
@Vallishp thx，these issues have been assigned to you. You don't need to remove the legacy code after implement same features of new one
