### ISSUE TITLE
[Enhancement] (nereids)implement DropRoleCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42618]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

DropRoleCommand is supported in the legacy planner but needs implementation in Nereids. The syntax is defined in DorisParser.g4. For reference, examine DropRoleStmt.java in the legacy planner.

```unsupportedDropStatement : DROP ROLE (IF EXISTS)? name=identifier```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Vallishp** [comment]
i will pick it. thanks
