### ISSUE TITLE
[Enhancement] (nereids)implement DropCatalogCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42613]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

DropCatalogCommand is supported in the legacy planner but not in Nereids. Implementation is required in Nereids. See the DorisParser.g4 syntax definition and review DropCatalogStmt.java in the legacy planner for reference.

```unsupportedDropStatement : DROP CATALOG (IF EXISTS)? name=identifier```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by msridhar78** [comment]
@starocean999 @LiBinfeng-01 I will pick this up
