### ISSUE TITLE
[Enhancement] (nereids)implement DropRepositoryCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42617]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

DropRepositoryCommand is implemented in the legacy planner but unsupported in Nereids. You’ll need to migrate it. Check DorisParser.g4 for the syntax and DropRepositoryStmt.java in the legacy planner for functionality details.

```unsupportedDropStatement : DROP REPOSITORY name=identifier```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Vallishp** [comment]
I will pick it
