### ISSUE TITLE
[Enhancement] (nereids)implement DropFileCommand  in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42619]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

DropFileCommand is available in the legacy planner but requires implementation in Nereids. The syntax definition is in DorisParser.g4, and DropFileStmt.java in the legacy planner details the command’s functionality.

```unsupportedDropStatement : DROP FILE name=STRING_LITERAL ((FROM | IN) database=identifier)? properties=propertyClause
 ```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Vallishp** [comment]
i will pick it
