### ISSUE TITLE
[Enhancement] (nereids)implement dropDatabase command in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42622]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

DropWorkloadPolicyCommand is available in the legacy planner but needs implementation in Nereids. The syntax is in DorisParser.g4, and DropWorkloadSchedPolicyStmt.java in the legacy planner can be used for reference.

```unsupportedDropStatement : DROP WORKLOAD POLICY (IF EXISTS)? name=identifierOrText```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Vallishp** [comment]
i will pick it.  we need to change issue title as  dropWorkloadPolicyCommand
