### ISSUE TITLE
[Enhancement] (nereids)implement DropEncryptKeyCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42623]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

DropEncryptKeyCommand is implemented in the legacy planner but unsupported in Nereids. You’ll need to add support in Nereids based on the syntax in DorisParser.g4 and the functionality in DropEncryptKeyStmt.java.

```unsupportedDropStatement : DROP ENCRYPTKEY (IF EXISTS)? name=multipartIdentifier```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Vallishp** [comment]
i will pick this
