### ISSUE TITLE
[Enhancement] (nereids)implement DropWorkloadGroupCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42621]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

DropWorkloadGroupCommand is supported in the legacy planner but missing in Nereids. Implement it in Nereids based on the syntax in DorisParser.g4, and refer to DropWorkloadGroupStmt.java in the legacy planner for functionality.

```unsupportedDropStatement : DROP WORKLOAD GROUP (IF EXISTS)? name=identifierOrText```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Vallishp** [comment]
i will pick it
