### ISSUE TITLE
[Enhancement] (nereids)implement DropStoragePolicyCommand  in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42626]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

DropStoragePolicyCommand is supported in the legacy planner but needs implementation in Nereids. Use the syntax definition in DorisParser.g4, and refer to DropPolicyStmt.java in the legacy planner.

```unsupportedDropStatement : DROP STORAGE POLICY (IF EXISTS)? name=identifier```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by msridhar78** [comment]
@LiBinfeng-01 @starocean999 I will pick this up, thanks
