### ISSUE TITLE
[Enhancement] (nereids)implement showSqlBlockRuleCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42719]
showSqlBlockRule command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showSqlBlockRule command in nereids:
unsupportedshowSqlBlockRuleStatement
``` SHOW SQL_BLOCK_RULE (FOR ruleName=identifier)?                                ```

**Comment by Vallishp** [comment]
@starocean999 i will pick it. thanks
