### ISSUE TITLE
[Enhancement] (nereids)implement showCreateRepositoryCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42724]
showCreateRepository command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showCreateRepository command in nereids:
unsupportedshowCreateRepositoryStatement
``` SHOW CREATE REPOSITORY FOR identifier                                         ```

**Comment by GentleCold** [comment]
I can try this, txn @LiBinfeng-01

**Comment by GentleCold** [comment]
I can try this, thx @LiBinfeng-01
