### ISSUE TITLE
[Enhancement] (nereids)implement showProcessListCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42729]
showProcessList command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showProcessList command in nereids:
unsupportedshowProcessListStatement
``` SHOW FULL? PROCESSLIST                                                        ```

**Comment by msridhar78** [comment]
@starocean999 @LiBinfeng-01 Please assign this issue to me
