### ISSUE TITLE
[Enhancement] (nereids)implement showPluginsCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42733]
showPlugins command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showPlugins command in nereids:
unsupportedshowPluginsStatement
``` SHOW PLUGINS                                                                  ```

**Comment by starocean999** [comment]
@Vallishp pls add a comment, then I am able to assgin the issue to you

**Comment by Vallishp** [comment]
@LiBinfeng-01   pls assign to me
