### ISSUE TITLE
[Enhancement] (nereids)implement showMaterializedViewCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42738]
showMaterializedView command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showMaterializedView command in nereids:
unsupportedshowMaterializedViewStatement
``` SHOW CREATE MATERIALIZED VIEW name=multipartIdentifier                        ```

**Comment by msridhar78** [comment]
@starocean999 @LiBinfeng-01 @morrySnow Please assign this issue to me

**Comment by msridhar78** [comment]
@starocean999 @LiBinfeng-01 Please assign this issue to me
