### ISSUE TITLE
[Enhancement] (nereids)implement showTriggersCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42731]
showTriggers command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showTriggers command in nereids:
unsupportedshowTriggersStatement
``` SHOW FULL? TRIGGERS ((FROM | IN) database=multipartIdentifier)? wildWhere?    ```

**Comment by Vallishp** [comment]
i will pick it
