### ISSUE TITLE
[Enhancement] (nereids)implement showAuthorsCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42735]
showAuthors command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showAuthors command in nereids:
unsupportedshowAuthorsStatement
``` SHOW AUTHORS                                                                  ```

**Comment by GentleCold** [comment]
pr: #43547, move to `In review`? @LiBinfeng-01
