### ISSUE TITLE
[Enhancement] (nereids)implement showCreateTableCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42736]
showCreateTable command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showCreateTable command in nereids:
unsupportedshowCreateTableStatement
``` SHOW BRIEF? CREATE TABLE name=multipartIdentifier                             ```

**Comment by msridhar78** [comment]
@LiBinfeng-01 @starocean999 @morrySnow Please assign this issue to me
