### ISSUE TITLE
[Enhancement] (nereids)implement showStatusCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42730]
showStatus command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showStatus command in nereids:
unsupportedshowStatusStatement
``` SHOW (GLOBAL | SESSION | LOCAL)? STATUS wildWhere?                            ```

**Comment by msridhar78** [comment]
@LiBinfeng-01 will pick this
