### ISSUE TITLE
[Enhancement] (nereids)implement showCreateDatabaseCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42739]
showCreateDatabase command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showCreateDatabase command in nereids:
unsupportedshowCreateDatabaseStatement
``` SHOW CREATE (DATABASE | SCHEMA) name=multipartIdentifier                      ```

**Comment by msridhar78** [comment]
@starocean999 @LiBinfeng-01 Please assign this issue to me
