### ISSUE TITLE
[Enhancement] (nereids)implement showCreateViewCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42737]
showCreateView command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showCreateView command in nereids:
unsupportedshowCreateViewStatement
``` SHOW CREATE VIEW name=multipartIdentifier                                     ```

**Comment by msridhar78** [comment]
@starocean999 @LiBinfeng-01 @morrySnow Please assign this issue to me
