### ISSUE TITLE
[Enhancement] (nereids)implement showCharsetCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42749]
showCharset command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showCharset command in nereids:
unsupportedshowCharsetStatement
``` SHOW ((CHAR SET) | CHARSET) wildWhere?                                        ```

**Comment by msridhar78** [comment]
@starocean999 @LiBinfeng-01 pls assign this to me
