### ISSUE TITLE
[Enhancement] (nereids)implement showDynamicPartitionCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42746]
showDynamicPartition command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showDynamicPartition command in nereids:
unsupportedshowDynamicPartitionStatement
``` SHOW DYNAMIC PARTITION TABLES ((FROM | IN) database=multipartIdentifier)?     ```

**Comment by Vallishp** [comment]
i will pick it
