### ISSUE TITLE
[Enhancement] (nereids)implement showDataTypesCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42743]
showDataTypes command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showDataTypes command in nereids:
unsupportedshowDataTypesStatement
``` SHOW DATA TYPES                                                               ```

**Comment by msridhar78** [comment]
@starocean999 @LiBinfeng-01 I will pick this up. Thanks
