### ISSUE TITLE
[Enhancement] (nereids)implement showCollationCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42748]
showCollation command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showCollation command in nereids:
unsupportedshowCollationStatement
``` SHOW COLLATION wildWhere?                                                     ```

**Comment by msridhar78** [comment]
@starocean999 @LiBinfeng-01 Please assign this issue to me
