### ISSUE TITLE
[Enhancement] (nereids)implement showCreateCatalogCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42740]
showCreateCatalog command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showCreateCatalog command in nereids:
unsupportedshowCreateCatalogStatement
``` SHOW CREATE CATALOG name=identifier                                           ```

**Comment by msridhar78** [comment]
@starocean999 @LiBinfeng-01 Please assign this issue to me
