### ISSUE TITLE
[Enhancement] (nereids)implement showProcCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42750]
showProc command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showProc command in nereids:
unsupportedshowProcStatement
``` SHOW PROC path=STRING_LITERAL                                                 ```

**Comment by starocean999** [comment]
@Vallishp pls add a comment, then I am able to assgin the issue to you

**Comment by Vallishp** [comment]
pls assign to me
