### ISSUE TITLE
[Enhancement] (nereids)implement showPartitionIdCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42756]
showPartitionId command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showPartitionId command in nereids:
unsupportedshowPartitionIdStatement
``` SHOW PARTITION partitionId=INTEGER_VALUE                                      ```

**Comment by Vallishp** [comment]
i will pick it. thanks
