### ISSUE TITLE
[Enhancement] (nereids)implement showWaringErrorCountCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42751]
showWaringErrorCount command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showWaringErrorCount command in nereids:
unsupportedshowWaringErrorCountStatement
``` SHOW COUNT LEFT_PAREN ASTERISK RIGHT_PAREN (WARNINGS | ERRORS)                ```

**Comment by msridhar78** [comment]
@LiBinfeng-01 will pick this up
