### ISSUE TITLE
[Enhancement] (nereids)implement showWaringErrorsCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42752]
showWaringErrors command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showWaringErrors command in nereids:
unsupportedshowWaringErrorsStatement
``` SHOW (WARNINGS | ERRORS) limitClause?                                         ```

**Comment by msridhar78** [comment]
@LiBinfeng-01 @starocean999 I will pick this up
