### ISSUE TITLE
[Enhancement] (nereids)implement showTrashCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42763]
showTrash command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showTrash command in nereids:
unsupportedshowTrashStatement
``` SHOW TRASH (ON backend=STRING_LITERAL)?                                       ```

**Comment by echo-hhj** [comment]
https://github.com/apache/doris/pull/44352
