### ISSUE TITLE
[Enhancement] (nereids)implement showGrantsForUserCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42767]
showGrantsForUser command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showGrantsForUser command in nereids:
unsupportedshowGrantsForUserStatement
``` SHOW GRANTS FOR userIdentify                                                  ```

**Comment by Vallishp** [comment]
i will pick it. thanks
