### ISSUE TITLE
[Enhancement] (nereids)implement showPrivilegesCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42769]
showPrivileges command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showPrivileges command in nereids:
unsupportedshowPrivilegesStatement
``` SHOW PRIVILEGES                                                               ```

**Comment by starocean999** [comment]
@Vallishp pls add a comment, then I am able to assgin the issue to you

**Comment by Vallishp** [comment]
pls assign to me
