### ISSUE TITLE
[Enhancement] (nereids)implement showBackendsCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42762]
showBackends command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showBackends command in nereids:
unsupportedshowBackendsStatement
``` SHOW BACKENDS                                                                 ```

**Comment by starocean999** [comment]
@Vallishp pls add a comment, then I am able to assgin the issue to you

**Comment by Vallishp** [comment]
@LiBinfeng-01   pls assign to me
