### ISSUE TITLE
[Enhancement] (nereids)implement showFrontendsCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42764]
showFrontends command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showFrontends command in nereids:
unsupportedshowFrontendsStatement
``` SHOW FRONTENDS name=identifier?                                               ```

**Comment by starocean999** [comment]
@Vallishp pls add a comment, then I am able to assgin the issue to you

**Comment by Vallishp** [comment]
@LiBinfeng-01   pls assign to me
