### ISSUE TITLE
[Enhancement] (nereids)implement showSyncJobCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42775]
showSyncJob command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showSyncJob command in nereids:
unsupportedshowSyncJobStatement
``` SHOW SYNC JOB ((FROM | IN) database=multipartIdentifier)?                     ```

**Comment by msridhar78** [comment]
@starocean999 @LiBinfeng-01 I will pick this up
