### ISSUE TITLE
[Enhancement] (nereids)implement showSmallFilesCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42770]
showSmallFiles command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showSmallFiles command in nereids:
unsupportedshowSmallFilesStatement
``` SHOW FILE ((FROM | IN) database=multipartIdentifier)?                         ```

**Comment by Vallishp** [comment]
i will pick it
