### ISSUE TITLE
[Enhancement] (nereids)implement showLoadProfileCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42773]
showLoadProfile command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showLoadProfile command in nereids:
unsupportedshowLoadProfileStatement
``` SHOW LOAD PROFILE loadIdPath=STRING_LITERAL                                   ```

**Comment by Vallishp** [comment]
i will pick it
