### ISSUE TITLE
[Enhancement] (nereids)implement showQueryProfileCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42772]
showQueryProfile command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showQueryProfile command in nereids:
unsupportedshowQueryProfileStatement
``` SHOW QUERY PROFILE queryIdPath=STRING_LITERAL                                 ```

**Comment by Vallishp** [comment]
This Command is deprecated. is it needed in nereids?

**Comment by rijeshkp** [comment]
@starocean999 can you please assign this Issue to me. Thanks.
