### ISSUE TITLE
[Enhancement] (nereids)implement showLastInsertCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42777]
showLastInsert command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showLastInsert command in nereids:
unsupportedshowLastInsertStatement
``` SHOW LAST INSERT                                                              ```

**Comment by starocean999** [comment]
@Vallishp pls add a comment, then I am able to assgin the issue to you

**Comment by Vallishp** [comment]
@LiBinfeng-01   pls assign to me
