### ISSUE TITLE
[Enhancement] (nereids)implement alterWorkloadGroupCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42793]
alterWorkloadGroup command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following alterWorkloadGroup command in nereids:
unsupportedalterWorkloadGroupStatement
``` ALTER WORKLOAD GROUP name=identifierOrText
    properties=propertyClause?                                                  ```

**Comment by Vallishp** [comment]
i will pick it
