### ISSUE TITLE
[Enhancement] (nereids)implement alterSqlBlockRuleCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42796]
alterSqlBlockRule command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following alterSqlBlockRule command in nereids:
unsupportedalterSqlBlockRuleStatement
``` ALTER SQL_BLOCK_RULE name=identifier properties=propertyClause?               ```

**Comment by Vallishp** [comment]
i will pick it
