### ISSUE TITLE
[Enhancement] (nereids)implement alterWorkloadPolicyCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42794]
alterWorkloadPolicy command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following alterWorkloadPolicy command in nereids:
unsupportedalterWorkloadPolicyStatement
``` ALTER WORKLOAD POLICY name=identifierOrText
    properties=propertyClause?                                                  ```

**Comment by Vallishp** [comment]
i will pick it.
