### ISSUE TITLE
[Enhancement] (nereids)implement syncCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42814]
sync command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following sync command in nereids:
unsupportedsyncStatement
``` SYNC                                                                          ```

**Comment by msridhar78** [comment]
@starocean999 @LiBinfeng-01 Please assign this issue to me

**Comment by Vallishp** [comment]
i will pick it
