### ISSUE TITLE
[Enhancement] (nereids)implement adminShowReplicaDistributionCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42837]
adminShowReplicaDistribution command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following adminShowReplicaDistribution command in nereids:
unsupportedadminShowReplicaDistributionStatement
``` ADMIN SHOW REPLICA DISTRIBUTION FROM baseTableRef                             ```

**Comment by Vallishp** [comment]
i will pick it
