### ISSUE TITLE
[Enhancement] (nereids)implement adminCheckTabletsCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42843]
adminCheckTablets command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following adminCheckTablets command in nereids:
unsupportedadminCheckTabletsStatement
``` ADMIN CHECK tabletList properties=propertyClause?                             ```

**Comment by rijeshkp** [comment]
@starocean999 can you please assign the issue to me. Thanks
