### ISSUE TITLE
[Enhancement] (nereids)implement adminCleanTrashCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42846]
adminCleanTrash command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following adminCleanTrash command in nereids:
unsupportedadminCleanTrashStatement
``` ADMIN CLEAN TRASH (ON LEFT_PAREN backends+=STRING_LITERAL
        (COMMA backends+=STRING_LITERAL) RIGHT_PAREN)?                              ```

**Comment by DongLiang-0** [comment]
hi, can i pick this and assign it to me

**Comment by rijeshkp** [comment]
@starocean999 can you please assign the issue to me. Thanks.
