### ISSUE TITLE
[Enhancement] (nereids)implement adminShowTabletStorageFormatCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42849]
adminShowTabletStorageFormat command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following adminShowTabletStorageFormat command in nereids:
unsupportedadminShowTabletStorageFormatStatement
``` ADMIN SHOW TABLET STORAGE FORMAT VERBOSE?                                     ```

**Comment by GentleCold** [comment]
hi, may I pick this?

**Comment by GentleCold** [comment]
I think the work of this issue is almost the same as #42783, so maybe you can assign it to him  directly? I'll pick another issue :) @LiBinfeng-01

**Comment by LiBinfeng-01** [comment]
> I think the work of this issue is almost the same as #42783, so maybe you can assign it to him directly? I'll pick another issue :) @LiBinfeng-01

sure
