### ISSUE TITLE
[Enhancement] (nereids)implement adminDiagnoseTabletCommand in nereids

### ISSUE THREAD

**Issue by LiBinfeng-01** [apache/doris#42848]
adminDiagnoseTablet command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following adminDiagnoseTablet command in nereids:
unsupportedadminDiagnoseTabletStatement
``` ADMIN DIAGNOSE TABLET tabletId=INTEGER_VALUE                                  ```

**Comment by Vallishp** [comment]
i will pick it

**Comment by Vallishp** [comment]
@msridhar78 its similar to https://github.com/apache/doris/pull/43159

**Comment by msridhar78** [comment]
@LiBinfeng-01 I will pick it up
