### ISSUE TITLE
[Bug] enable_fold_constant_by_be设置为true和false的时候sql结果不一致

### ISSUE THREAD

**Issue by hebust-fengyu** [apache/doris#43061]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.1.7

### What's Wrong?

mysql> set enable_fold_constant_by_be = true;
Query OK, 0 rows affected (0.00 sec)

mysql> select hex(s) from ( select from_base64('wr2JEDVXzL9+2XtRhgIloA==') as s )t;
+--------------------------------------------------+
| hex(s)                                                                   |
+--------------------------------------------------+
| C2BDEFBFBD103557CCBF7EEFBFBD7B51EFBFBD0225EFBFBD |
+--------------------------------------------------+
1 row in set (0.02 sec)

mysql> set enable_fold_constant_by_be = false;
Query OK, 0 rows affected (0.00 sec)

mysql> select hex(s) from ( select from_base64('wr2JEDVXzL9+2XtRhgIloA==') as s )t;
+----------------------------------+
| hex(s)                           |
+----------------------------------+
| C2BD89103557CCBF7ED97B51860225A0 |
+----------------------------------+
1 row in set (0.01 sec)

### What You Expected?

设置set enable_fold_constant_by_be前后结果查询应该一致

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by felixwluo** [comment]
Let me see
