### ISSUE TITLE
[Enhancement] add db sync test case for test_ts_col_drop test_ts_col_drop test_ts_col_alter_type test_ts_col_order_by

### ISSUE THREAD

**Issue by dataroaring** [apache/doris#43560]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Above cases had been added for table sync, db sync need them too.

### Solution

add cases to db sync.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wyxxxcat** [comment]
pick
