### ISSUE TITLE
[Enhancement] add alter comment support to ccr

### ISSUE THREAD

**Issue by dataroaring** [apache/doris#43563]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Solution

1. generate bin log in fe 
2. handle binlog in ccr-syncer
3. add cases for db and table sync
4. update documents.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wyxxxcat** [comment]
pick

**Comment by dataroaring** [comment]
https://github.com/apache/doris/pull/39783
