### ISSUE TITLE
[Enhancement] add column rename cases to db sync and table sync

### ISSUE THREAD

**Issue by dataroaring** [apache/doris#43562]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Solution

basic case 1:

1. create ccr job on db or table
2. create table and insert data
3. rename a column
4. insert data
5. check data in upstream and downstream are same
6. check columns name in upstream and downstream are same.

base case 2:

add materialized view and rename column used by materialized view.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wyxxxcat** [comment]
pick
