### ISSUE TITLE
[Bug] Monthly active contributors and Contributors over time in README are not working

### ISSUE THREAD

**Issue by yzeng25** [apache/doris#44197]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Current version

### What's Wrong?

Monthly active contributors and Contributors over time in README are not working
https://github.com/apache/doris?tab=readme-ov-file#-contributors

### What You Expected?

Remove or use an alternative

### How to Reproduce?

1. click https://github.com/blitz-js/blitz/blob/main/CONTRIBUTOR_STATS.md
2. click https://www.apiseven.com/en/contributor-graph?chart=contributorOverTime&repo=blitz-js/blitz
3. get error message on the service provider, which is api7.ai's side, upper right corner shows 'Request Error', and returns no info.

### Anything Else?

Also see

- https://github.com/api7/contributor-graph/issues/231 first brought up the issue
- https://github.com/api7/contributor-graph/issues/232 validates the issue
- https://github.com/pingcap/docs-cn/issues/19086 & https://github.com/pingcap/docs-dm/issues/933 how the other repos deal with the issue, one chooses to use an alternative, and the other deletes the section.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by morningman** [comment]
thanks for your report.
