### ISSUE TITLE
[Bug] The result of the nested query with "NOT IN" is not correct

### ISSUE THREAD

**Issue by Jianing-Xu** [apache/doris#44340]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-2.0.5-rc02

### What's Wrong?

When the subquery returns a large amount of data (approximately 350,000), a nested query with "NOT IN" can lead to errors, while the statement with "IN" works correctly.

### What You Expected?

The query statement using not in returns the correct result

### How to Reproduce?

select count(*) from t1 where id not in (select t1id from t2);

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wwbbcjeyc** [comment]
老哥，你怎么关闭了这个问题。是找到问了嘛。我这表有个类似的

**Comment by Jianing-Xu** [comment]
> 老哥，你怎么关闭这个问题。找到了问了嘛。我这表有类似的

Sorry，最近比较忙没看github。关闭的原因是我自己造的数据难以复现。我碰到的场景是 **select 大表a not in 大表b**，not in语句应该是doris有bug，后面测试了in语句是正常的。如果你的场景允许的话，可以考虑转化语义，用in来实现；或者缩小子查询数据量，最后求并集

**Comment by wwwxxxhhh** [comment]
> 老哥，你怎么关闭了这个问题。是找到问了嘛。我这表有个类似的
你那doris版本是多少的呀，我用的2.1.7，还是有这个问题

**Comment by wwwxxxhhh** [comment]
> 老哥，你怎么关闭了这个问题。是找到问了嘛。我这表有个类似的

你那doris版本是多少的呀，我用的2.1.7，还是有这个问题
