### ISSUE TITLE
[Bug] runtime filter reports 'sync filter size meet error' when enable_pipeline_x_exec is off.

### ISSUE THREAD

**Issue by dh-cloud** [apache/doris#44730]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.1.6

### What's Wrong?

When `enable_pipeline_exec` is on but `enable_pipeline_x_exec` is off, two table join with `in_or_bloom`  runtime filter will report error e.g.:

```
ERROR 1105（HY000）：errCode = 2， detailMessage = (cdb-doris-benode-2.cdb-doris-benode.cloudspace.svc.cluster.local)[CANCELLED]sync filter size meet error,filter:RuntimeFilter:(id = 1,type = in_or_bloomfilter, need_local_merge: false, is_broadcast:false, build_bf_cardinality:true)
```

### What You Expected?

no error report

### When `enable_pipeline_exec` is on but `enable_pipeline_x_exec` is on:

HashJoinBuildSinkOperatorX::sink() calls **send_filter_size**() when eos is on.

### When `enable_pipeline_exec` is on but `enable_pipeline_x_exec` is off:

HashJoinNode::sink() does not call **send_filter_size**() when eos is on.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ixzc** [comment]
you can avoid this by setting this
`set global runtime_filter_type = 'IN,MIN_MAX';`
or upgrade your doris to 2.1.7 version

**Comment by dh-cloud** [comment]
> or upgrade your doris to 2.1.7 version

@ixzc I see doris 2.17 has been forcibly set `enable_pipeline_x_engine` to true. Does that mean those code `of pipeline on, pipeline_x off` will not be maintained?

**Comment by ixzc** [comment]
> > or upgrade your doris to 2.1.7 version
> 
> @ixzc I see doris 2.17 has been forcibly set `enable_pipeline_x_engine` to true. Does that mean those code `of pipeline on, pipeline_x off` will not be maintained?

yes

**Comment by heshc** [comment]
I'm using Apache Doris 2.1.8, and I occasionally encounter the following error during query execution:
errCode = 2, detailMessage = ()[CANCELLED]sync filter size meet error, filter: RuntimeFilter: (id = 1, type = bloomfilter, is_broadcast: false, ignored: true, disabled: false, build_bf_cardinality: true, dependency: HASH_JOIN_SINK_OPERATOR_FINISH_DEPENDENCY: id=4, block task = 0, ready=true, _always_ready=false, count=0, synced_size: -1, has_local_target: false, has_remote_target: true, error_msg: []

**Comment by BiteTheDDDDt** [comment]
> Hi, [@BiteTheDDDDt](https://github.com/BiteTheDDDDt)
> 
> On **Doris 2.1.6 with enable_pipeline_exec=true and enable_pipeline_x_exec=false,** running TPC-DS 1GB query 14 triggers the same error: `sync filter size meet error.`
> 
> PipelineX path: `HashJoinBuildSinkOperatorX::sink()` calls `send_filter_size()` at EOS. See code:
> 
> [doris/be/src/pipeline/exec/hashjoin_build_sink.cpp](https://github.com/apache/doris/blob/fcc4635d0832740d88dd43bf68930e44e058b8a1/be/src/pipeline/exec/hashjoin_build_sink.cpp#L643-L647)
> 
> Lines 643 to 647 in [fcc4635](/apache/doris/commit/fcc4635d0832740d88dd43bf68930e44e058b8a1)
>  if (!local_state._runtime_filters_disabled) { 
>      RETURN_IF_ERROR(local_state._runtime_filter_slots->send_filter_size( 
>              state, local_state._shared_state->build_block->rows(), 
>              local_state._finish_dependency)); 
>  } 
> 
> Non-PipelineX path: `HashJoinNode::sink()` does not call it at EOS.
> 
> On the receiver side, whether `need_sync_filter_size()` is required is gated by the `enable_pipeline_exec `setting. However, the non-PipelineX pipeline engine doesn’t send the filter size, which leads to the mismatch and the error. See code:
> 
> [doris/be/src/exprs/runtime_filter.cpp](https://github.com/apache/doris/blob/fcc4635d0832740d88dd43bf68930e44e058b8a1/be/src/exprs/runtime_filter.cpp#L1985-L1989)
> 
> Lines 1985 to 1989 in [fcc4635](/apache/doris/commit/fcc4635d0832740d88dd43bf68930e44e058b8a1)
>  bool IRuntimeFilter::need_sync_filter_size() { 
>      return (type() == RuntimeFilterType::IN_OR_BLOOM_FILTER || 
>              type() == RuntimeFilterType::BLOOM_FILTER) && 
>             _wrapper->get_build_bf_cardinality() && !_is_broadcast_join && _enable_pipeline_exec; 
>  } 
> 
> Is there an LTS 2.x branch where this should be fixed? If so, I’m happy to submit a patch.

Hi, the related issues have been fixed in the latest version 2.1. Please upgrade directly.

**Comment by AntiTopQuark** [comment]
> Hi, the related issues have been fixed in the latest version 2.1. Please upgrade directly.

@BiteTheDDDDt Could you share how this was fixed? Is there a PR with the fix that I can study? Thanks!

**Comment by BiteTheDDDDt** [comment]
> > Hi, the related issues have been fixed in the latest version 2.1. Please upgrade directly.
> 
> [@BiteTheDDDDt](https://github.com/BiteTheDDDDt) Could you share how this was fixed? Is there a PR with the fix that I can study? Thanks!

Many changes have been made in this regard. For specifics, you can directly refer to the git history of the RuntimeFilter and RuntimeFilterSlots classes.

**Comment by BiteTheDDDDt** [comment]
@AntiTopQuark For 2.1-latest, the pipeline_engine is no longer maintained, only the pipeline_x_engine is currently being maintained.

**Comment by AntiTopQuark** [comment]
> [@AntiTopQuark](https://github.com/AntiTopQuark) For 2.1-latest, the pipeline_engine is no longer maintained, only the pipeline_x_engine is currently being maintained.

All right， thank you very much.
