### ISSUE TITLE
增加flink connector doris功能开发

### ISSUE THREAD

**Issue by sober-weifeng** [apache/doris#4478]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by morningman** [comment]
Hi @sober-weifeng , are you willing to help Doris implement this feature?

**Comment by Hackeruncle** [comment]
when?

**Comment by caoliang-web** [comment]
After version 0.15, flink-doris-connector has been supported
