### ISSUE TITLE
[Bug] 使用 where 1=1 作为条件执行 delete 语句后，相同主键的数据就再也无法更新和查询了

### ISSUE THREAD

**Issue by Helltab** [apache/doris#44856]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

 2.0.9

### What's Wrong?

使用 where 1=1 作为条件执行 delete 语句后，相同主键的数据就再也无法更新和查询了

### What You Expected?

使用 where 1=1 作为条件执行 delete 语句后，期望得到两种结果：
1. 直接得到报错，不允许执行
2. 正常执行，但是相同主键的数据可以重复插入或者更新

### How to Reproduce?

 1. create table
 3. insert one record
 4. delete with where 1=1
 5. insert before record

```
DROP TABLE IF EXISTS `test_delete_tb`;
CREATE TABLE `test_delete_tb`
(
    `user_id`   bigint(20) NOT NULL COMMENT '主键ID',
    `user_no`   bigint(20) NOT NULL COMMENT '主键ID2',
    `user_name` varchar(255)    NOT NULL COMMENT '名称'

)ENGINE = OLAP UNIQUE KEY(`user_id`, `user_no`)
COMMENT '测试where1=1'
DISTRIBUTED BY HASH(`user_no`) BUCKETS AUTO
PROPERTIES (
"enable_unique_key_merge_on_write" = "true",
"light_schema_change" = "true",
"disable_auto_compaction" = "false",
"enable_single_replica_compaction" = "false"
);;


insert into test_delete_tb (`user_id`, `user_no`, `user_name`)
values (1,1,'AB');
select * from test_delete_tb;

# It is ok
#delete from test_delete_tb where  `user_id`>0;

# Crash
delete from test_delete_tb where 1=1 and `user_id`>0;
insert into test_delete_tb (`user_id`, `user_no`, `user_name`)
values (1,1,'AB');
select * from test_delete_tb;
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ixzc** [comment]
you can upgrade your doris to 2.0.15 version. it's ok
<img width="834" alt="image" src="https://github.com/user-attachments/assets/6c03464f-19c0-418e-ae25-ffc8abc545a8">
