### ISSUE TITLE
[Bug] Be crash because of variant type

### ISSUE THREAD

**Issue by cambyzju** [apache/doris#44882]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.1.7

### What's Wrong?

be crash

### What You Expected?

do not crash

### How to Reproduce?

1. create table with `variant type` and `c.d column name`:
```
CREATE TABLE `test` (
  `a` int,
  `b` varchar(50),
  `c.d` variant
) ENGINE=OLAP
DUPLICATE KEY(a)
DISTRIBUTED BY HASH(a) BUCKETS 1
PROPERTIES (
"replication_num" = "1"
);
```

2. add some data
```
insert into test values(1,"2",'{"key":"3"}');
```

3. after simple query, then be crashed:
```
> select * from test;
ERROR 1105 (HY000): errCode = 2, detailMessage = Backend Backend [id=10016, host=127.0.0.1, heartbeatPort=9050, alive=false, lastStartTime=2024-12-02 20:24:10, process epoch=1733142250469, tags: {location=default}] not exists or dead, query e91c1d29dd614e8a-adf80c3d25a66a91 should be cancelled
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ixzc** [comment]
we will fix this
