### ISSUE TITLE
[Bug] Can't list S3 objects if the root path of S3 resource has a leading slash

### ISSUE THREAD

**Issue by DarvenDuan** [apache/doris#44902]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0

### What's Wrong?

If we create a S3 resource and whe `s3.root.path` has a leading slash(/), such as: `/root`, the `S3Client:ListObjectsV2` will not work in `s3_file_system.cpp`.
See more in : https://stackoverflow.com/questions/52443839/s3-what-exactly-is-a-prefix-and-what-ratelimits-apply and https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-prefixes.html

### What You Expected?

`S3Client:ListObjectsV2` gets work even though `s3.root.path` has a leading slash

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ixzc** [comment]
we will fix this
