### ISSUE TITLE
[Bug] task_group_inl.h:91] _rq is full, capacity=4096

### ISSUE THREAD

**Issue by luo985** [apache/doris#45419]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.1.6

### What's Wrong?

通过http方式（StreamLoad）实时导入在线日志数据到doris，不定时出现导入很慢（持续几十秒）。这段时间对应的be节点/metrics接口也没反应。
be的WARNING日志中有持续出现 task_group_inl.h:91] _rq is full, capacity=4096 错误，不确定有没有关联关系

### What You Expected?

解决不定时导入慢的问题

### Anything Else?
![企业微信截图_20241214170647](https://github.com/user-attachments/assets/19e252ec-83ab-4040-ab3d-e586612b839c)
![企业微信截图_20241214171812](https://github.com/user-attachments/assets/5f26c5b6-38d5-4280-99de-5f7c928e51fd)
![企业微信截图_20241214124446](https://github.com/user-attachments/assets/5763f30e-4031-4fed-880b-6f8516aee408)
![企业微信截图_20241214124510](https://github.com/user-attachments/assets/258c2926-2f08-4107-ba45-a266e49eb13f)

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by arstercz** [comment]
I had the same issue , `version-2.1.5`.
