### ISSUE TITLE
[Bug] overwrite分区表时，查询无结果会报错SQL 错误 [1105] [HY000]: errCode = 2, detailMessage = Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by jalousiex** [apache/doris#45944]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

3.0.2

### What's Wrong?

insert overwrite分区表时，查询无结果会报错
SQL 错误 [1105] [HY000]: errCode = 2, detailMessage = Index 0 out of bounds for length 0

### What You Expected?

查询无数据时无写入，也不应该报错

### How to Reproduce?

insert overwrite table tab1 partition(*)
select *
  from tab1_T t
 where 1=2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zclllyybb** [comment]
It's already fixed by https://github.com/apache/doris/pull/40657 in 3.0.3
