### ISSUE TITLE
[Bug] Stream Load http接口偶尔报乱码问题

### ISSUE THREAD

**Issue by helxm** [apache/doris#45969]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.1.7

### What's Wrong?

使用Stream Load批量写数据，雷同的数据，偶尔报： Reason: Parse json data for JsonDoc failed. code: 10, error info: The input is not valid UTF-8. 

请求头已加上utf-8

HttpPut put = new HttpPut(loadUrl);
put.removeHeaders(HttpHeaders.CONTENT_LENGTH);
put.removeHeaders(HttpHeaders.TRANSFER_ENCODING);
put.setHeader(HttpHeaders.EXPECT, "100-continue");
put.setHeader(HttpHeaders.AUTHORIZATION, basicAuthHeader(user, password));

put.setHeader("Content-Type", "application/json; charset=utf-8");//不加全报编码错误，加了偶尔报

// You can set stream load related properties in the Header, here we set label and column_separator.
put.setHeader("label", UUID.randomUUID().toString());
put.setHeader("column_separator", ",");
put.setHeader("format", "json");
put.setHeader("strip_outer_array", "true");
put.setHeader("jsonpaths", "[\"$.id\""
...

### What You Expected?

怎么解决

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by helxm** [comment]
已解决

**Comment by pengpuxin2015** [comment]
hello，how to fix it?thanks
