### ISSUE TITLE
flex 版本问题

### ISSUE THREAD

**Issue by darionyaphet** [apache/doris#5580]
docker  中编译 doris `Error: flex version (2.5.37) must be greater than or equal to 2.6.0` 

docker 中需要升级 flex 吗？

**Comment by HappenLee** [comment]
If compile the master branch， please use 1.3 version of docker image.

**Comment by darionyaphet** [comment]
No I am building `Apache Doris 0.13.0`

**Comment by stdpain** [comment]
@darionyaphet 
try to use apachedoris/doris-dev:build-env-1.2 
http://doris.incubator.apache.org/master/zh-CN/installing/compilation.html#%E4%BD%BF%E7%94%A8-docker-%E5%BC%80%E5%8F%91%E9%95%9C%E5%83%8F%E7%BC%96%E8%AF%91%EF%BC%88%E6%8E%A8%E8%8D%90%EF%BC%89
