### ISSUE TITLE
[Config] Add config to limit the num of history load job num or history transaction under db to avoid too much memory usage

### ISSUE THREAD

**Issue by caiconghui** [apache/doris#5680]
Now, we use time expire to control the history trasaction num and load job under db, but it is hard to make a balance between informaction viewing and memory usage, for some user may execute many load jobs such as insert job in a short time, which may cause heavy memory pressure which other user may execute only some load jobs for one day. 
So we need to add config to limit the num of history load job num or history transaction under db to avoid too much memory usage.

**Comment by francisoliverlee** [comment]
@caiconghui insert-job, broker load job and transaction jobs could be checked by coders anytime . 
how about make them persistence, such as store in itself, make it a write audit log

**Comment by caiconghui** [comment]
> @caiconghui insert-job, broker load job and transaction jobs could be checked by coders anytime .
> how about make them persistence, such as store in itself, make it a write audit log

this PR is mainly to control memory usage, and I think we can implement it in next PR

**Comment by francisoliverlee** [comment]
> > @caiconghui insert-job, broker load job and transaction jobs could be checked by coders anytime .
> > how about make them persistence, such as store in itself, make it a write audit log
> 
> this PR is mainly to control memory usage, and I think we can implement it in next PR

high memory usage cause of lots of history jobs in it , persistence such as store it in Doris or write it in audit log can 
- reduce memory usage.
- be read any time by developpers for hisitory jobs.

how do u like it ?

**Comment by caiconghui** [comment]
what is the format for audit log ? file or table data? I think if job writed in file, it is hard to managed, if stored in table, the steps may be some A bit cumbersome and data may be lost because we need to stream load it. In my option, we can do audit log by fe plugin as a addtiional way to record it while you can set expire time short

**Comment by caiconghui** [comment]
> > > @caiconghui insert-job, broker load job and transaction jobs could be checked by coders anytime .
> > > how about make them persistence, such as store in itself, make it a write audit log
> > 
> > 
> > this PR is mainly to control memory usage, and I think we can implement it in next PR
> 
> high memory usage cause of lots of history jobs in it , persistence such as store it in Doris or write it in audit log can
> 
> * reduce memory usage.
> * be read any time by developpers for hisitory jobs.
> 
> how do u like it ?
what is the format for audit log ? file or table data? I think if job writed in file, it is hard to managed, if stored in table, the steps may be some A bit cumbersome and data may be lost because we need to stream load it. In my option, we can do audit log by fe plugin as a addtiional way to record it while you can set expire time short
