### ISSUE TITLE
[Bug] doris 0.14 backup/restore问题

### ISSUE THREAD

**Issue by 345362231** [apache/doris#6574]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

0.14.0-release-4c1e52261

### What's Wrong?

使用minio作为s3的存储源，按照官方的备份恢复步骤进行操作。
第一步，创建s3的仓库，仓库名为s3_repo，创建成功。
第二步，创建备份，通过命令BACKUP SNAPSHOT kimi112.b1 TO s3_repo on (hash_k1_replace5_bak)；创建备份成成功。
这里有个问题就是生成了2个__palo_repository_s3_repo文件件并在不同的目录中，这里有点怪。
![image](https://user-images.githubusercontent.com/45547524/132194607-3ab5e081-eb55-4d5d-a7a6-2a9106f115f4.png)

第三步，查看备份信息，show snapshot on s3_repo可查看到
![image](https://user-images.githubusercontent.com/45547524/132193684-7a5637ba-fd84-43de-9f2d-a2d17cbbb814.png)
第四步，恢复快照，通过命令restore SNAPSHOT kimi112.b1 from s3_repo on (`hash_k1_replace5_bak`) PROPERTIES ("backup_timestamp"="2021-09-06-17-18-32" );执行命令成功。
第五步，查看恢复状态，进入到目标库，show restore;
![image](https://user-images.githubusercontent.com/45547524/132194954-fc5f86ef-6d7c-434c-a9da-7331b05e0929.png)
这里downloading卡住，这里应该算是报错：get nothing from remote path: s3://velero/velero/__palo_repository_s3_repo/__ss_b1/__ss_content/__db_664542/__tbl_941686/__part_941685/__idx_941687/__941688
无法表恢复。
这里应该是备份路径不统一，应该是个bug。
在进行恢复的时候，不能获取到远程路径的数据，也应该是个bug。

### What You Expected?

按照help cmd中的操作帮助，我不认为我操作有问题，那怎么解决这个备份还原问题，希望能得到帮助。谢谢

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by morningman** [comment]
what is your `create repository` statement?

**Comment by 345362231** [comment]
CREATE REPOSITORY `s3_repo` WITH S3 ON LOCATION "s3://velero/velero" PROPERTIES ("AWS_ENDPOINT" = "http://test-minio.XXX.XX:30542","AWS_ACCESS_KEY"="XXXX","AWS_SE[DCRET_KEY"="XXXX","AWS_REGION"="velero");

**Comment by xinghuayu007** [comment]
除了s3，其他存储能浮现吗？

**Comment by 345362231** [comment]
目前只用了s3，没有其他存储方式

**Comment by morningman** [comment]
感觉可能是minio 对s3的兼容语义和其他对象存储不太一样。。

**Comment by 345362231** [comment]
就是说这个问题 没有其他解决方法？只能用云厂商的s3存储？

**Comment by morningman** [comment]
> 就是说这个问题 没有其他解决方法？只能用云厂商的s3存储？

我们没有测试过minio，先确认下：s3://velero/velero/__palo_repository_s3_repo/__ss_b1/__ss_content/__db_664542/__tbl_941686/__part_941685/__idx_941687/__941688  这路径下有文件么？如果没有的话，实际文件是到哪个路径下了？

**Comment by 345362231** [comment]
s3://velero/velero/__palo_repository_s3_repo/__ss_b1/__ss_content/__db_664542/__tbl_941686/__part_941685/__idx_941687/__941688 这个路径下是没有的
实际路径是s3://velero/__palo_repository_s3_repo/__ss_b1/__ss_content/__db_664542/__tbl_941686/__part_941685/__idx_941687/__941688
前面少了个velero

**Comment by morningman** [comment]
s3://velero/velero/__palo_repository_s3_repo/  这个目录有么？

**Comment by 345362231** [comment]
也有这个目录

**Comment by morningman** [comment]
你重新创建一个 repo，使用这个路径：s3://velero/velero/   最后加个 / ，先试试，不是很确定

**Comment by 345362231** [comment]
这个尝试过，没有任何变化

**Comment by morningman** [comment]
> 这个尝试过，没有任何变化

这个只能等我们有时间找个minio的环境试试了，不同系统似乎对s3协议中路径的解析规则不太一样

**Comment by ChPi** [comment]
这个问题是因为client参数不兼容。be代码s3_util.cpp改为下面就可以了，把useVirtualAdressing改为false。
new Aws::S3::S3Client(aws_cred, aws_config, Aws::Client::AWSAuthV4Signer::PayloadSigningPolicy::Never, false)

be配置可以加一个useVirtualAdressing参数控制这个

**Comment by yangzhg** [comment]
> 这个问题是因为client参数链接你的s3存储有问题, s3路径有两种，默认的解析可能有问题。
> be代码s3_util.cpp改为下面另外一种，把useVirtualAdressing改为false。
> new Aws::S3::S3Client(aws_cred, aws_config, Aws::Client::AWSAuthV4Signer::PayloadSigningPolicy::Never, false)
> 
> be配置可以加一个useVirtualAdressing参数控制这个

增加参数是不行的，一个be 接收的请求是多个，可能有的支持useVirtualAdressing 有的不支持，目前绝大部分支持s3 协议的对象存储都支持VirtualHost style， path style 支持的越来越少了，所以现在统一成了 VirtualHost style

**Comment by 345362231** [comment]
> 这个问题是因为client参数链接你的s3存储有问题, s3路径有两种，默认的解析可能有问题。
> be代码s3_util.cpp改为下面另外一种，把useVirtualAdressing改为false。
> new Aws::S3::S3Client(aws_cred, aws_config, Aws::Client::AWSAuthV4Signer::PayloadSigningPolicy::Never, false)
> 
> be配置可以加一个useVirtualAdressing参数控制这个

使用他这个方法，build新的palo_be，替换后，测试备份还原是可以使用的

**Comment by yangzhg** [comment]
> 使用他这个方法，build新的palo_be，替换后，测试备份还原是可以使用的

你可以通过 export MINIO_DOMAIN=mydomain.com 使minio  支持VirtualHost style， path style 因为安全问题 已经被大多数云储存厂商逐渐废弃了

**Comment by ChPi** [comment]
resolved #6962
