### ISSUE TITLE
[Bug] compile error

### ISSUE THREAD

**Issue by englefly** [apache/doris#7191]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

commit ce7fa5d6d9454d3b89e75859690fb216ca68167b (HEAD -> master, origin/master, origin/HEAD)
Author: renzhimin7 <1240388654@qq.com>
Date:   Mon Nov 22 14:47:00 2021 +0800

    [typo] Update multi-tenant.md (#7162)
    
    A double quote is missing

### What's Wrong?

compilation using docker image failed.
docker image: apache/incubator-doris:build-env-1.4.1

``` sh build.sh --clean --be --fe --ui ```
we got error:
```
ninja: error: '/var/local/thirdparty/installed/lib64/libbreakpad_client.a', needed by 'src/service/palo_be', missing and no known rule to make it
```

### What You Expected?

compilation success

### How to Reproduce?

docker pull apache/incubator-doris:build-env-1.4.1
git clone git@github.com:minghong/talent-plan.git
docker run -it -v ~/.m2:/root/.m2 -v ~/work/incubator-doris/:/root/incubator-doris-DORIS-x.x.x-release/ apache/incubator-doris:build-env-1.4.1

inside docker container:
[root@7eec959b89ab incubator-doris-DORIS-x.x.x-release]# sh build.sh --clean --be --fe --ui 

We got following error message

-- The ASM compiler identification is GNU
-- Found assembler: /opt/rh/devtoolset-10/root/usr/bin/gcc
-- Looking for sys/random.h
-- Looking for sys/random.h - not found
-- Some symbols from glibc will be replaced for compatibility
-- Configuring done
-- Generating done
-- Build files have been written to: /root/incubator-doris-DORIS-x.x.x-release/be/build_Release
[0/2] Re-checking globbed directories...
ninja: error: '/var/local/thirdparty/installed/lib64/libbreakpad_client.a', needed by 'src/service/palo_be', missing and no known rule to make it

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jackwener** [comment]
Remove `thirdparty/installed/` and create a empty dir `thirdparty/installed/`.

**Comment by jackwener** [comment]
It may caused by image. 
`apache/incubator-doris:***`  -> `apache/doris:***`

**Comment by m1iktea** [comment]
> If you compile by docker, It may caused by image. `apache/incubator-doris:***` -> `apache/doris:***`

Which image can I use to build, `apache/doris:build-env-for-1.0.0` or other tags?
