### ISSUE TITLE
[Enhancement] add date_trunc() function

### ISSUE THREAD

**Issue by whutpencil** [apache/doris#7298]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

date_trunc() is a very useful function in hive, MySQL and presto. We should add it to Doris.

The use effect is as follows. Here, it is assumed that the date is **2021-12-04 03:04:05.016**

Unit | Example Truncated Value
-- | --
second | 2021-12-04 03:04:05.000
minute | 2021-12-04 03:04:00.000
hour | 2021-12-04 03:00:00.000
day | 2021-12-04 00:00:00.000
week | 2021-11-29 00:00:00.000
month | 2021-12-01 00:00:00.000
quarter | 2021-10-01 00:00:00.000
year | 2021-01-01 00:00:00.000

### Solution

I am very willing to provide documentation and Fe implementation, but because of my poor C + + ability, I hope some friends can improve it.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by morningman** [comment]
https://doris.apache.org/docs/dev/sql-manual/sql-functions/date-time-functions/date-trunc
