### ISSUE TITLE
Doris Roadmap 2022

### ISSUE THREAD

**Issue by morningman** [apache/doris#7502]

**Comment by morningman** [comment]
For English Version(To be added)

**Comment by yiguolei** [comment]
For regression test and performance test, we could follow clickhouse's test method. If it is allowed, I could do this.

**Comment by yiguolei** [comment]
Clang compile is already on process, see https://github.com/apache/incubator-doris/pull/7451

**Comment by EmmyMiao87** [comment]
Could you please open an email to discuss Roadmap 2022 of Doris ?

**Comment by yangzhg** [comment]
支持parquet 文件存储格式也应该加进去吧

**Comment by wangshuo128** [comment]
希望考虑跨版本升级功能。

**Comment by Henry2SS** [comment]
What about supporting AVRO format in LOAD function?

**Comment by zbtzbtzbt** [comment]
Looking forward to push based pipeline engine @yiguolei yi

**Comment by hf200012** [comment]
外部数据源联邦查询能力：
1.kudu support

Doris Manager：
1.Follow-up Doris Manager upgrade
2.User UI interaction improvement
3.Doris Manager supports Doris automated upgrade

**Comment by 924060929** [comment]
我们公司已经有一个回归测试框架。大体是用groovy的dsl去完成测试sql、stream load、安装tpch等功能，大概使用方式如下图。
后续可以提给社区
![image](https://user-images.githubusercontent.com/8806055/147537342-fd5e9a33-6c89-4e00-85ac-06be6bc403d0.png)

**Comment by jackwener** [comment]
既然后续有这么多内容，关于社区部分建一个 RFC 目录挺有必要的，大型的 PR 的 design doc 放进去，一方面是为了社区新人的快速融入，另外也减小PR review的压力

**Comment by morningman** [comment]
> 既然后续有这么多内容，关于社区部分建一个 RFC 目录挺有必要的，大型的 PR 的 design doc 放进去，一方面是为了社区新人的快速融入，另外也减小PR review的压力

好主意，你是否有一些RFC 模板可供参考？

**Comment by jackwener** [comment]
这是 cockroach 的 [实践](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/README.md)

**Comment by caiconghui** [comment]
> What about supporting AVRO format in LOAD function?

#7650

**Comment by Henry2SS** [comment]
> > What about supporting AVRO format in LOAD function?
> 
> #7650

Thx for opening an issue.

**Comment by morningman** [comment]
> > > What about supporting AVRO format in LOAD function?
> > 
> > 
> > #7650
> 
> Thx for opening an issue.

Add to the roadmap

**Comment by hf200012** [comment]
#7680 Data export function supports exporting to db, kafka, etc.

**Comment by hf200012** [comment]
#7678 max_by, min_by aggregate function support

**Comment by huligong1234** [comment]
looking forward to support decimal data type for create table as select statement.  (detailMessage = Unsupported type 'DECIMAL(9,0)' in create table as select statement)

**Comment by morningman** [comment]
> #7680 Data export function supports exporting to db, kafka, etc.
> #7678 max_by, min_by aggregate function support
Added to the Roadmap

**Comment by morningman** [comment]
> support decimal data type for create table as select statement. (detailMessage = Unsupported type 'DECIMAL(9,0)' in create table as select statement)

Added to the roadmap

**Comment by yiguolei** [comment]
Could use vectorized method to optimize load process??

**Comment by i7xh** [comment]
Why Doris need push based query engine?

**Comment by yiguolei** [comment]
@i7xh 
Two example:
1.  Currently doris‘s concurrency control is based on tablet, one tablet ---> exec fragment， there is only one thread to deal with the data at query engine. If use pushed engine, could expand the computing thread num at run time.
2. In pull engine, if one fragment contains 3 or more node, like  scan--> filter--> agg there is only one node is executing, but in  push based engine, node executing could be async, for example scan and agg could execute at same time.

**Comment by i7xh** [comment]
> Provides Schemaless semantics for fast analysis of semi-structured data

> Json Parsing Optimization

There are a lot of user cases schema-less or semi-structured that lead to support json optimization especially，mainly with decouple change of the schema?

**Comment by i7xh** [comment]
<img width="524" alt="企业微信截图_a18eb192-6b6a-4615-a6a5-eeae4d0430d2" src="https://user-images.githubusercontent.com/635169/150123300-5dc4c6d5-71ad-4a5f-a0d8-ba272d2ee316.png">


look forward imperatively

**Comment by lordk911** [comment]
want to know when will vectorized query engine could be released.

**Comment by kuncle** [comment]
When will support data type Decimal(38,18) ?

**Comment by kpfly** [comment]
> When will support data type Decimal(38,18) ?

This feature will be released as an experimental feature in version 1.2.0，which will be released at the end of this month.

**Comment by kuncle** [comment]
> > When will support data type Decimal(38,18) ?
> 
> This feature will be released as an experimental feature in version 1.2.0，which will be released at the end of this month.

cool, thanks.

**Comment by mengzhisy** [comment]
请教一下“Pipeline execution engine”是否可以更方便地实现多线程执行算法，然后大幅提升多核利用率？
拿doris测试过tpc-ds，目前对多核心的利用率貌似比较低
