### ISSUE TITLE
Release note 1.0.0

### ISSUE THREAD

**Issue by morningman** [apache/doris#8549]
1.0.0 has been released now!

### 1. Support vectorized execution engine (Experimental)

Enabled by `set enable_vectorized_engine=true`. In most cases, this can significantly improve query performance.

### 2. Support for [Lateral View](http://doris.incubator.apache.org/sql-reference/sql-statements/Data%20Manipulation/lateral-view.html) syntax (Exprimental)

With this syntax, we can expand a bitmap, String or Json Array from one column into multiple rows so that the expanded data can be further processed later (e.g. Filter, Join, etc.).

### 3. Support for [Hive Outer Table](http://doris.incubator.apache.org/extending-doris/hive-of-doris.html) (Exprimental)

Support for users to create Hive outer tables and perform queries. This feature will extend Doris' federated query capabilities. You can use this feature to access and analyze data stored in hive directly or import hive data into Doris with `insert into select` statements.
        
### 4. Support for the [Apache SeaTunnel(Incubating)](http://doris.incubator.apache.org/extending-doris/seatunnel.html) plugin

Users can contact SeaTunnel for pass-through and ETL between multiple data sources.
        
### 5. Supports [Z-Order](https://en.wikipedia.org/wiki/Z-order) data sorting format.

Storing data in Z-Order order speeds up filtering performance for non-prefixed column conditions.
        
### 6. Support for more bitmap functions

* `bitmap_max`
* `bitmap_and_not`
* `bitmap_and_not_count`
* `bitmap_has_all`
* `bitmap_and_count`
* `bitmap_or_count`
* `bitmap_xor_count`
* `bitmap_subset_limit`
* `sub_bitmap`

Check the function manual for details.
        
## Important bug fixes

* Fix some memory issue.
* Fix some query errors.
* Fix some scheduling logic problems of broker load.
* Fix the problem that metadata cannot be loaded due to STREAM keyword.
* Fix the problem that Decommission cannot be executed correctly.

## Optimization

* Reduce the number of Segment files generated during bulk import to reduce Compaction pressure.
* Transfer data via attachment function of BRPC to reduce serialization and deserialization overhead during query.
* Support direct return of HLL/BITMAP type binary data for business parsing on the outside.
* Optimize and reduce the probability of OVERCROWDED and NOT_CONNECTED errors in BRPC to enhance system stability.
* Enhance the fault tolerance of import.
* Support synchronous update and deletion of data via Flink CDC.
* Support adaptive Runtime Filter.

## Ease of use

* Routine Load supports displaying the status of the current offset, delay number, etc.
* Add statistics of peak memory usage in FE audit log.
* Add missing version information in Compaction URL results to facilitate troubleshooting.
* Support marking BE as **unqueryable** or **unimportable** to quickly block problem nodes.

## Others

* Add the function of [Minidump](http://doris.incubator.apache.org/developer-guide/minidump.html).

## Thanks

Thanks to everyone who has contributed to this release:

@924060929
@adonis0147
@Aiden-Dong
@aihai
@airborne12
@Alibaba-HZY
@amosbird
@arthuryangcs
@awakeljw
@bingzxy
@BiteTheDDDDt
@blackstar-baba
@caiconghui
@CalvinKirs
@cambyzju
@caoliang-web
@ccoffline
@chaplinthink
@chovy-3012
@ChPi
@DarvenDuan
@dataalive
@dataroaring
@dh-cloud
@dohongdayi
@dongweizhao
@drgnchan
@e0c9
@EmmyMiao87
@englefly
@eyesmoons
@freemandealer
@Gabriel39
@gaodayue
@GoGoWen
@Gongruixiao
@gwdgithubnom
@HappenLee
@Henry2SS
@hf200012
@htyoung
@jacktengg
@jackwener
@JNSimba
@Keysluomo
@kezhenxu94
@killxdcj
@lihuigang
@littleeleventhwolf
@liutang123
@liuzhuang2017
@lonre
@lovingfeel
@luozenglin
@luzhijing
@MeiontheTop
@mh-boy
@morningman
@mrhhsg
@Myasuka
@nimuyuhan
@obobj
@pengxiangyu
@qidaye
@qzsee
@renzhimin7
@Royce33
@SleepyBear96
@smallhibiscus
@sodamnsure
@spaces-X
@sparklezzz
@stalary
@steadyBoy
@tarepanda1024
@THUMarkLau
@tianhui5
@tinkerrrr
@ucasfl
@Userwhite
@vinson0526
@wangbo
@wangshuo128
@wangyf0555
@weajun
@weizuo93
@whutpencil
@WindyGao
@wunan1210
@xiaokang
@xiaokangguo
@xiedeyantu
@xinghuayu007
@xingtanzjr
@xinyiZzz
@xtr1993
@xu20160924
@xuliuzhe
@xuzifu666
@xy720
@yangzhg
@yiguolei
@yinzhijian
@yjant 
@zbtzbtzbt 
@zenoyang
@zh0122
@zhangstar333
@zhannngchen
@zhengshengjun
@zhengshiJ
@ZhikaiZuo
@ztgoto
@zuochunwei

**Comment by maninhill** [comment]
Can Doris v1.0.0 be released within April, right?

**Comment by liu391447823** [comment]
Can Doris v1.0.0 be released within April, right?
