### ISSUE TITLE
[Enhancement] Remove some unused include

### ISSUE THREAD

**Issue by jackwener** [apache/doris#8721]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

There are many redundant Header file included.

We can remove them.

### Solution

This is a good related tools--[IWYU](https://github.com/include-what-you-use/include-what-you-use)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ritikBhandari** [comment]
Hi,
Can I solve this issue if you dont mind?

**Comment by jackwener** [comment]
Yes, you can take it up.❤

**Comment by ritikBhandari** [comment]
So is this issue present in the whole repository or some of the files?

**Comment by jackwener** [comment]
> So is this issue present in the whole repository or some of the files?

Let me give a example.

In the `be/src/env`, other `.h` file include `.env.h` . `.cpp` file include corresponding `.h` file.

So, all file include `.env.h`. We can remove all `include` in  `.env.h`  in the other file.

For example,
```
#include <memory>
#include <string>
```
is in `env.h`.  Other file can remove them.

We can remove other redundant included header like above.

**Comment by ritikBhandari** [comment]
Sure.
Thank you :)

**Comment by BiteTheDDDDt** [comment]
clangd also has functions about this, I describe in the [documentation](https://doris.apache.org/zh-CN/developer-guide/cpp-diagnostic-code.html) how to configure clangd for doris, maybe we can do some exploration.

https://discourse.llvm.org/t/rfc-lifting-include-cleaner-missing-unused-include-detection-out-of-clangd/61228

**Comment by BiteTheDDDDt** [comment]
> hi! are there any more header files that need to be removed?

There are still many redundant includes in doris, you can use clangd or other tools to find and try to remove them.

**Comment by akd3070** [comment]
hey 
i can help it out.You an can assign me the task.

**Comment by sai-praveenkumar** [comment]
hey is this issue still open???
You can assign me the task.

**Comment by AnvarAslam** [comment]
i like to solve these issue & you can guide me to solve these issue?

**Comment by BiteTheDDDDt** [comment]
There are some method more specifictly (just a advice):
1. Firstly you should build doris https://doris.apache.org/zh-CN/docs/dev/install/source-install/compilation-with-ldb-toolchain
2. config clangd well https://doris.apache.org/community/developer-guide/cpp-diagnostic-code/
3. find some unused include and remove it.
<img width="593" alt="图片" src="https://user-images.githubusercontent.com/7939630/194703705-77eb84a9-99bb-44c8-96cf-fd1e8a05fb72.png">
4. start a pull request and waiting for review https://doris.apache.org/community/how-to-contribute/pull-request/

**Comment by SankarshanMishra** [comment]
hello! I want to work on this issue, kindly assign me this issue and guide me a little because this is going to be my first open-source contribution.
