### ISSUE TITLE
[Proposal] Make date/decimal read and evaluation faster

### ISSUE THREAD

**Issue by wangbo** [apache/doris#8796]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Currently date/decimal may cost too many times when evaluating predicate.
Because they are customized class and can not be evaluated in vectorized way.
For decimal, I think we can convert it to int128, then evaluating it in vectorized way. The ```convert```  may be slow in current insert method, but I think we can try to vectorized it.
For date, currently implemented using a 24-byte array, I think maybe we can convert it to a integer and then evaluate it in vectorized way.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kpfly** [comment]
@liaoxin01

**Comment by liaoxin01** [comment]
I'm planning to implement decimalv3. The storage layer and computing layer will use a unified data type. Select the data type according to the precision, which can be int32, Int64 or int128. It will improve the precision of decimal and support up to 38 significant digits. It also can avoid the conversion between computing layer and storage layer, and make reading and evaluation faster.
