### ISSUE TITLE
[Enhancement] Enhancement the FE java code

### ISSUE THREAD

**Issue by jackwener** [apache/doris#9126]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

There is a lot of old code in FE, we can do some enhancement.

There are
- replace for(Type thing: things) with things.foreach()
```java
for (String sessionId : sessionIds) {
    XXX
}
->
sessionIds.foreach(sessionId -> {
    XXX
})
```
- `IDEA` will remind some typo in annotation, we can fix it.
- ....

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Toms1999** [comment]
Hi,
Can I try to do it if you dont mind?

**Comment by jackwener** [comment]
> Hi, Can I try to do it if you dont mind?

It's OK😃

**Comment by Toms1999** [comment]
hi,i&nbsp; found an annotation problem and submit A pr,thinks





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月24日(星期天) 晚上6:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/incubator-doris] [Enhancement] Enhancement the FE java code (Issue #9126)





  
Hi, Can I try to do it if you dont mind?
  
It's OK😃
