### ISSUE TITLE
[Feature] Support protobuf format for routine load

### ISSUE THREAD

**Issue by xy720** [apache/doris#9302]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Currently, we only support csv/json format for kafka routine load, but don't support protobuf data.
I will submit a feature that support load protobuf data for kafka routine load, and make canal format as an example.
So that user can use canal -> kafka -> doris way to load canal data.

The submission of this feature consists of two steps：
1、support protobuf scanner and deserializer to consume protobuf data from kafka load pipe.
2、support canal format for routine load.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xy720** [comment]
I am still working on it.

**Comment by Authorlove** [comment]
@xy720 Has this feature been completed? Is there any user documentation?
