### ISSUE TITLE
[Feature] Cancel-Load support State condition

### ISSUE THREAD

**Issue by dataalive** [apache/doris#9477]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

when we have so many loading tasks, doris now support cancel load with label and lable-* regex match. 

```sql
CANCEL LOAD
[FROM db_name]
WHERE [LABEL = "load_label" | LABEL like "label_pattern"];
```

but sometimes we need to cancel dedicated state tasks like  all ```PENDING``` tasks 

so i suggest to support syntax like the following
```sql
CANCEL LOAD
[FROM db_name]
WHERE [LABEL = "load_label" | LABEL like "label_pattern"] [AND/OR] [STATE = "PENDING"]; 
```

### Use case

we could cancel load with dedicated state.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
If you're not working on this feature, you can assign to me.
