### ISSUE TITLE
[Feature] Improve Doris observability

### ISSUE THREAD

**Issue by stalary** [apache/doris#9577]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

I’d like to improve Doris observability. This is achieved by introducing SkyWalking and OpenTelemetry. Parameters allow users to decide which monitoring tool to use.

Currently OpenTelemetry is very convincing in terms of protocol specifications, skyWalking is more convincing in terms of overall APM, so I'm going to implement both by switching them on and off.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by luozenglin** [comment]
The idea sounds cool. In fact, I'm already working on introducing OpenTelemetry for doris to improve observability. I have built a code framework to collect and send query trace data, it still has a lot of refinement work to do. I'll commit the code to a branch later for discussion. You are very welcome to participate in the work of doris observability and look forward to developing with you.
