### ISSUE TITLE
[Bug] PAUSE SYNC JOB   卡死

### ISSUE THREAD

**Issue by yiyulinfeng** [apache/doris#9594]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.0

### What's Wrong?

PAUSE SYNC JOB   卡死，
包括 STOP 操作

### What You Expected?

看看是不是bug 

### How to Reproduce?

PAUSE SYNC JOB job1_hrtds002
> 2013 - Lost connection to MySQL server during query
> 时间: 352.744s

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yiyulinfeng** [comment]
重启了fe，就恢复正常

**Comment by morningman** [comment]
> 要是如你说，这么简单的问题，我还有必要来这里提issues?

请注意你的言辞！开源社区没有任何人有义务解决你的问题！

**Comment by fangzheng0518** [comment]
我也遇到了同样的问题，SYNC JOB里只有2张表（数据量才实时同步了2天，几万条数据而已）
