### ISSUE TITLE
[Enhancement](Nereids)Fragment translator rules

### ISSUE THREAD

**Issue by morrySnow** [apache/doris#9622]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

In Nereids, we use physical plan to describe query plan. But in original Doris, we use Fragment to do that.
So, we need to translate physical plan into Fragment.

### Solution

Maybe we should implement this in two phase.
First, some rules that translate each type physical plan node to PlanNode in Fragment
Second, a node type independent framework that assemble PlanNodes to Fragments according to physical plan node structure.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Kikyou1997** [comment]
I could do it
