### ISSUE TITLE
[Bug] time_round function calculated wrong timestamp

### ISSUE THREAD

**Issue by zhengshengjun** [apache/doris#9711]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.0.0

### What's Wrong?

I'm trying to replace Apache Druid with Doris in our business, but failed in time_around functions documented in 
https://doris.apache.org/zh-CN/sql-manual/sql-functions/date-time-functions/time_round.html#time-round

Seems there are some bugs

1. select day_floor('2022-05-03 13:09:20', 1) from test.flink_doris_druid limit 1;  
         expect:            2022-05-04 00:00:00   
         turn out to be:  2022-05-03 00:00:00 
2.  select day_ceil('2022-05-03 00:00:00', -1) from test.flink_doris_druid limit 1;
         expect:            2022-05-02 00:00:00   
         turn out to be:  NULL

2.  select day_ceil('2022-05-03 13:09:20', 1) from test.flink_doris_druid limit 1;
         expect:            2022-05-05 00:00:00   
         turn out to be:  2022-05-04 00:00:00 

3. select day_ceil('2022-05-03 13:09:20', 4) from test.flink_doris_druid limit 1;  
        expect:              2022-05-08 00:00:00
        turn out to be     2022-05-04 00:00:00

### What You Expected?

as described above

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhengshengjun** [comment]
PR:   https://github.com/apache/incubator-doris/pull/9712

**Comment by BiteTheDDDDt** [comment]
why q1 expect result is `2022-05-04 00:00:00`?

**Comment by dataalive** [comment]
> why q1 expect result is `2022-05-04 00:00:00`?

In accordance with rounding, divided by 12 o'clock ?

**Comment by BiteTheDDDDt** [comment]
> 

Isn't the floor rounded down? like floor(0.6)=0

**Comment by zhengshengjun** [comment]
> > 
> 
> Isn't the floor rounded down? like floor(0.6)=0

@BiteTheDDDDt Yes, floor meas rounded down, and the second parameter in `day_floor('2022-05-03 13:09:20', 1)` meas add 1 more day

**Comment by BiteTheDDDDt** [comment]
> > > 
> > 
> > 
> > Isn't the floor rounded down? like floor(0.6)=0
> 
> @BiteTheDDDDt Yes, floor meas rounded down, and the second parameter in `day_floor('2022-05-03 13:09:20', 1)` meas add 1 more day

why we should add the second param `period`? period looks like it's just the unit. formulately, `floor(x,period)=floor(x/period)*period`

**Comment by zhengshengjun** [comment]
@BiteTheDDDDt 
Thanks for pointing out this mistake, I'd thought the second parameter was something like "time shift". 
So the above cases are all right. And I looked though the code, there is a trivial error in Hour case. 

SQL:    `select hour_ceil('1970-01-01 01:01:10', 1, '1970-01-01 00:01:10') from test.flink_doris_sink limit 1`
Apache Druid's result:  1970-01-01 01:01:10
Apache Doris's result:  1970-01-01 02:01:10 

the query means  time are divided into pieces by hour started from  `1970-01-01 00:01:10`
( `1970-01-01 00:01:10`, `1970-01-01 01:01:10`, `1970-01-01 02:01:10`)

and 1970-01-01 01:01:10 belongs to  [`1970-01-01 01:01:10`, `1970-01-01 02:01:10`],  its rounded ceil will be 1970-01-01 01:01:10

**Comment by zhengshengjun** [comment]
Other error cases:

select hour_ceil('1970-01-01 01:00:10', 1, '1970-01-01 00:00:30')
expect: '1970-01-01T01:00:30' 

select hour_floor('1970-01-01 01:00:10', 1, '1970-01-01 00:00:30')"
expect: '1970-01-01T00:00:30'

select day_ceil('2022-05-25')"
expect: '2022-05-25'
 
select month_ceil('2022-05-01')"
expect: '2022-05-01'

**Comment by dataalive** [comment]
这个关联的PR： https://github.com/apache/doris/pull/9712 已经合入，这个Issue可以关闭了。
