### ISSUE TITLE
[Enhancement] group_concat support order by

### ISSUE THREAD

**Issue by stalary** [apache/doris#9744]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

group_concat support order by, such as `group_concat(k order by k)` like mysql.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment]
@BiteTheDDDDt Could you help to implement this function? There are a lot of changes in this function that I cannot complete.

**Comment by BiteTheDDDDt** [comment]
Hi, I will try to do some implementation, before we can do some communication
