### ISSUE TITLE
[Enhancement] Elasticsearch extrenal table generate dsl move to fe from be

### ISSUE THREAD

**Issue by stalary** [apache/doris#9835]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Elasticsearch extrenal table generate dsl move to fe from be. This makes it consistent with other external structures and makes it easier to view query plans.

### Solution

It is divided into the following steps
1. Generate a DSL in the EsScanNode of fe
2. Modify be's es_http_scan_node, use the generated DSL directly, and clean up the useless code.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Userwhite** [comment]
"clean up the useless code.", I think generat DSL by fe should be configurable(session variables)，if DSL is too large，query may be affected by rpc

**Comment by stalary** [comment]
https://github.com/apache/doris/pull/11894
